export const IPC_EVENT_showItemInFolder = 'IPC_EVENT_showItemInFolder'
export const IPC_EVENT_showOpenFileDialog = 'IPC_EVENT_showOpenFileDialog'
export const IPC_EVENT_showSaveDialog = 'IPC_EVENT_showSaveDialog'
export const IPC_EVENT_copyToClipboard = 'IPC_EVENT_copyToClipboard'
export const IPC_EVENT_pathExists = 'IPC_EVENT_pathExists'
export const IPC_EVENT_openInBrowser = 'IPC_EVENT_openInBrowser'
