modules/smil-utils/.test modules/smil-utils/.install modules/smil-utils/.install-doc $(TARGET_DIR)/state/modules/smil-utils/modified-since-release_ : \
	modules/smil-utils/src/main/resources/META-INF/catalog.xml \
	modules/smil-utils/src/main/resources/xml/resolve-relative-uris.xsl \
	modules/smil-utils/src/main/resources/xml/smil3-to-smil1.xsl \
	modules/smil-utils/src/main/resources/xml/prepare-mo-for-join.xsl \
	modules/smil-utils/src/main/resources/xml/smil-update-links.xpl \
	modules/smil-utils/src/main/resources/xml/smil-to-audio-clips.xsl \
	modules/smil-utils/src/main/resources/xml/clock-functions.xsl \
	modules/smil-utils/src/main/resources/xml/smil-update-links.xsl \
	modules/smil-utils/src/main/resources/xml/smil-to-audio-clips.xpl \
	modules/smil-utils/src/main/resources/xml/smil2-to-smil1.xsl \
	modules/smil-utils/src/main/resources/xml/generate-ids.xsl \
	modules/smil-utils/src/main/resources/xml/upgrade-smil-daisy202.xsl \
	modules/smil-utils/src/main/resources/xml/get-audioclip-by-href.xsl \
	modules/smil-utils/src/main/resources/xml/audio-clips-to-fileset.xpl \
	modules/smil-utils/src/main/resources/xml/audio-clips-to-fileset.xsl \
	modules/smil-utils/src/main/resources/xml/dtd/dtbsmil-2005-1.dtd \
	modules/smil-utils/src/main/resources/xml/dtd/dtbsmil110.dtd \
	modules/smil-utils/src/main/resources/xml/dtd/dtbsmil-2005-2.dtd \
	modules/smil-utils/src/main/resources/xml/dtd/SMIL10.dtd \
	modules/smil-utils/src/main/resources/xml/smil-to-audio-fileset.xsl \
	modules/smil-utils/src/main/resources/xml/join.xpl \
	modules/smil-utils/src/main/resources/xml/conditionally-join-toplevel-seq-with-body.xsl \
	modules/smil-utils/src/main/resources/xml/smil-to-audio-fileset.xpl \
	modules/smil-utils/src/main/resources/xml/rearrange.prepare.xsl \
	modules/smil-utils/src/main/resources/xml/join.xsl \
	modules/smil-utils/src/main/resources/xml/upgrade-smil.xpl \
	modules/smil-utils/src/main/resources/xml/smil-to-text-fileset.xpl \
	modules/smil-utils/src/main/resources/xml/rearrange.xsl \
	modules/smil-utils/src/main/resources/xml/audio-clips-update-files.xpl \
	modules/smil-utils/src/main/resources/xml/smil-to-text-fileset.xsl \
	modules/smil-utils/src/main/resources/xml/audio-clips-update-files.xsl \
	modules/smil-utils/src/main/resources/xml/rearrange.xpl \
	modules/smil-utils/src/main/resources/xml/upgrade-smil-dtbook.xsl \
	modules/smil-utils/src/main/resources/xml/downgrade-smil.xpl \
	modules/smil-utils/src/main/resources/xml/library.xpl
modules/smil-utils/.test modules/smil-utils/.install-doc : \
	modules/smil-utils/src/test/xspec/upgrade-smil-daisy202_test.xspec \
	modules/smil-utils/src/test/resources/logback.xml \
	modules/smil-utils/src/test/resources/docs/test20.smil \
	modules/smil-utils/src/test/resources/docs/test-doc-1.xml \
	modules/smil-utils/src/test/resources/docs/test-doc-3.xml \
	modules/smil-utils/src/test/resources/docs/test-doc-2.xml \
	modules/smil-utils/src/test/resources/docs/test-mo1.smil \
	modules/smil-utils/src/test/resources/docs/test-mo2.smil \
	modules/smil-utils/src/test/resources/docs/test-content.xml \
	modules/smil-utils/src/test/resources/docs/test.smil \
	modules/smil-utils/src/test/java/XProcSpecTest.java \
	modules/smil-utils/src/test/xprocspec/downgrade.xprocspec \
	modules/smil-utils/src/test/xprocspec/resources/mediaoverlay-joined.medium_1.smil \
	modules/smil-utils/src/test/xprocspec/resources/expected_5.xml \
	modules/smil-utils/src/test/xprocspec/resources/expected_4.xml \
	modules/smil-utils/src/test/xprocspec/resources/mediaoverlay-joined.small_1.smil \
	modules/smil-utils/src/test/xprocspec/resources/expected_1.xml \
	modules/smil-utils/src/test/xprocspec/resources/expected_3.xml \
	modules/smil-utils/src/test/xprocspec/resources/expected_2.xml \
	modules/smil-utils/src/test/xprocspec/resources/content_3.xhtml \
	modules/smil-utils/src/test/xprocspec/resources/content_1.xhtml \
	modules/smil-utils/src/test/xprocspec/resources/content_5.xhtml \
	modules/smil-utils/src/test/xprocspec/resources/content_2.xhtml \
	modules/smil-utils/src/test/xprocspec/resources/content_6.xhtml \
	modules/smil-utils/src/test/xprocspec/resources/content_47.xhtml \
	modules/smil-utils/src/test/xprocspec/resources/content_4.xhtml \
	modules/smil-utils/src/test/xprocspec/resources/mediaoverlay-joined.smil \
	modules/smil-utils/src/test/xprocspec/update-links.xprocspec \
	modules/smil-utils/src/test/xprocspec/rearrange.xprocspec \
	modules/smil-utils/src/test/xprocspec/audio-clips-update-files.xprocspec \
	modules/smil-utils/src/test/xprocspec/audio-clips-to-fileset.xprocspec \
	modules/smil-utils/src/test/xprocspec/join.xprocspec
.make/mk/modules/smil-utils/sources.mk : \
	modules/smil-utils/src \
	modules/smil-utils/src/test \
	modules/smil-utils/src/test/xspec \
	modules/smil-utils/src/test/resources \
	modules/smil-utils/src/test/resources/docs \
	modules/smil-utils/src/test/java \
	modules/smil-utils/src/test/xprocspec \
	modules/smil-utils/src/test/xprocspec/resources \
	modules/smil-utils/src/main \
	modules/smil-utils/src/main/resources \
	modules/smil-utils/src/main/resources/META-INF \
	modules/smil-utils/src/main/resources/xml \
	modules/smil-utils/src/main/resources/xml/dtd
