libs/com.xmlcalabash/.test : \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/unzip-002.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/compress-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/namespace-delete-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/unzip-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/delta-xml-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/exf-cwd-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/compare-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/rdf-load-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/invoke-module-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/info-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/set-cookies-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/message-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/sparql-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/collection.xsl \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/java-properties-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/pipe.xpl \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/test-suite.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/collection-manager-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/pretty-print-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/eval-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/sample-tests.zip \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/head-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/insert-document-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/java.properties \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/metadata-extractor-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/get-cookies-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/pipe2.xpl \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/copy-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/data/book.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/data/chapter.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/data/nwn.rdf \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/data/nwalsh.com.html \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/css-formatter-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/delete-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/uri-info-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/rdfa-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/xinclude-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/adhoc-query-001.xml \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/pxp-set-base-uri-001.xml \
	libs/com.xmlcalabash/test/testsuite/extension/test-suite.xml \
	libs/com.xmlcalabash/test/testsuite/extension/unimpl-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/normalization-form-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/normalization-form-002.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/normalization-form-003.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/cdata-section-elements-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/cdata-section-elements-002.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/undeclare-prefixes-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/indent-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/indent-002.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/standalone-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/omit-xml-declaration-002.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/standalone-002.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/omit-xml-declaration-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/test-suite.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/standalone-003.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/results/normalization-form-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/results/normalization-form-002.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/results/normalization-form-003.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/results/escape-uri-attributes-002.html \
	libs/com.xmlcalabash/test/testsuite/serialization/results/cdata-section-elements-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/results/cdata-section-elements-002.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/results/undeclare-prefixes-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/results/indent-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/results/indent-002.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/results/standalone-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/results/omit-xml-declaration-002.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/results/standalone-002.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/results/include-content-type-002.html \
	libs/com.xmlcalabash/test/testsuite/serialization/results/omit-xml-declaration-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/results/standalone-003.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/results/include-content-type-001.html \
	libs/com.xmlcalabash/test/testsuite/serialization/results/version-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/results/doctype-public-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/results/encoding-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/results/escape-uri-attributes-001.html \
	libs/com.xmlcalabash/test/testsuite/serialization/results/byte-order-mark-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/results/media-type-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/results/byte-order-mark-002.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/results/doctype-system-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/results/.htaccess \
	libs/com.xmlcalabash/test/testsuite/serialization/version-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/include-content-type-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/doctype-public-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/escape-uri-002.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/include-content-type-002.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/encoding-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/escape-uri-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/byte-order-mark-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/media-type-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/err-d0020-001.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/byte-order-mark-002.xml \
	libs/com.xmlcalabash/test/testsuite/serialization/doctype-system-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespace-rename-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespace-rename-017.xml \
	libs/com.xmlcalabash/test/testsuite/required/for-each-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0006-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/filter-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/string-replace-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0020-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/version-available-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/evaluation-order-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0034-007.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0034-013.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0004-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0022-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0005-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0015-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/xslt-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0013-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0003-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0052-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0029-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0039-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/param-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0058-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0048-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0034-012.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0034-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/evaluation-order-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0001-008.xml \
	libs/com.xmlcalabash/test/testsuite/required/split-sequence-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/multipart-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/string-replace-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/unwrap-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0051-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/filter-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespace-rename-016.xml \
	libs/com.xmlcalabash/test/testsuite/required/for-each-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespace-rename-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/for-each-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespace-rename-014.xml \
	libs/com.xmlcalabash/test/testsuite/required/viewport-009.xml \
	libs/com.xmlcalabash/test/testsuite/required/multipart-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/split-sequence-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/string-replace-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/compare-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/version-available-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0034-010.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0034-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0022-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/param-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0005-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0025-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/xslt-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/xslt-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0013-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0033-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0005-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0052-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0029-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/param-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0022-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0034-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0034-011.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0061-001.xpl \
	libs/com.xmlcalabash/test/testsuite/required/evaluation-order-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/compare-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0030-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/unwrap-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/multipart-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0020-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0007-004.xml~ \
	libs/com.xmlcalabash/test/testsuite/required/split-sequence-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0041-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0051-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/filter-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/viewport-008.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespace-rename-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespace-rename-015.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespace-rename-011.xml \
	libs/com.xmlcalabash/test/testsuite/required/for-each-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/for-each-010.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespace-rename-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/split-sequence-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0020-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/string-replace-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/store-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/library-v2.xpl \
	libs/com.xmlcalabash/test/testsuite/required/err-d0012-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0034-015.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0004-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0034-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0005-013.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0005-007.xml \
	libs/com.xmlcalabash/test/testsuite/required/xslt-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/document-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0005-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0005-012.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0034-014.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0004-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0032-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0012-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0022-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0040-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/compare-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/iteration-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/try-001.xpl \
	libs/com.xmlcalabash/test/testsuite/required/string-replace-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/split-sequence-007.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0020-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/for-each-011.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespace-rename-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespace-rename-010.xml \
	libs/com.xmlcalabash/test/testsuite/required/for-each-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespace-rename-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/for-each-007.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespace-rename-012.xml \
	libs/com.xmlcalabash/test/testsuite/required/multipart-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0020-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/split-sequence-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/compare-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/replace-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0017-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0022-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0014-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0034-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/make-sequence.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0004-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0034-016.xml \
	libs/com.xmlcalabash/test/testsuite/required/variable-008.xml \
	libs/com.xmlcalabash/test/testsuite/required/param-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0005-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0005-010.xml \
	libs/com.xmlcalabash/test/testsuite/required/xslt-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0059-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0028-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/xslt-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0005-011.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0005-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/param-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0034-017.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0034-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0022-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0012-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/compare-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/iteration-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0020-007.xml \
	libs/com.xmlcalabash/test/testsuite/required/multipart-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/split-sequence-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/for-each-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespace-rename-013.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespace-rename-007.xml \
	libs/com.xmlcalabash/test/testsuite/required/for-each-012.xml \
	libs/com.xmlcalabash/test/testsuite/required/set-attributes-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/group-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/insert-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0026-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/load-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespaces-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/add-attribute-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/choose-008.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0005-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/data-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/value-available-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/exclude-inline-prefixes-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/input-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/input-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/value-available-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/versioning-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0023-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0042-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/data-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0052-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/step-available-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0009-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0039-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0019-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/system-property-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0020-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0030-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/load-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0051-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/set-attributes-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/pipeline-imported.xpl \
	libs/com.xmlcalabash/test/testsuite/required/group-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0006-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0026-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/insert-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0020-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespaces-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/library-imported.xpl \
	libs/com.xmlcalabash/test/testsuite/required/identity-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/add-attribute-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/data-007.xml \
	libs/com.xmlcalabash/test/testsuite/required/step-available-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0005-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/value-available-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0023-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/versioning-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/exclude-inline-prefixes-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/input-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/exclude-inline-prefixes-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0023-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/versioning-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/step-available-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0052-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/data-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0019-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0039-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/add-attribute-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0009-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0029-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0058-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/identity-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/system-property-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespaces-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0010-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/load-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0020-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/insert-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0026-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/group-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/xml-id-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/import-009.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespaces-007.xml \
	libs/com.xmlcalabash/test/testsuite/required/insert-007.xml \
	libs/com.xmlcalabash/test/testsuite/required/ebv-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/wrap-009.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0017-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0007-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0004-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0014-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/add-attribute-007.xml \
	libs/com.xmlcalabash/test/testsuite/required/value-available-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/versioning-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0023-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/data-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/step-available-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/input-011.xml \
	libs/com.xmlcalabash/test/testsuite/required/exclude-inline-prefixes-007.xml \
	libs/com.xmlcalabash/test/testsuite/required/input-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0059-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/input-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/exclude-inline-prefixes-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0028-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0038-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/xpath-version-available-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/input-010.xml \
	libs/com.xmlcalabash/test/testsuite/required/data-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/versioning-007.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0023-007.xml \
	libs/com.xmlcalabash/test/testsuite/required/value-available-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/log-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/add-attribute-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/escape-markup-001.xpl \
	libs/com.xmlcalabash/test/testsuite/required/identity-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/wrap-008.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0001-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0031-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0011-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/insert-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/load-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespaces-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/import-008.xml \
	libs/com.xmlcalabash/test/testsuite/required/xml-id-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespaces-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespaces-010.xml \
	libs/com.xmlcalabash/test/testsuite/required/insert-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0026-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/insert-010.xml \
	libs/com.xmlcalabash/test/testsuite/required/ebv-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0011-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0007-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0027-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/identity-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0014-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/add-attribute-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/http-request-009.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0023-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/versioning-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/step-available-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/data-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/labelelements-009.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0023-009.xml \
	libs/com.xmlcalabash/test/testsuite/required/exclude-inline-prefixes-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/input-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/input-012.xml \
	libs/com.xmlcalabash/test/testsuite/required/declare-step-009.xml \
	libs/com.xmlcalabash/test/testsuite/required/exclude-inline-prefixes-010.xml \
	libs/com.xmlcalabash/test/testsuite/required/library-missing-version.xpl \
	libs/com.xmlcalabash/test/testsuite/required/err-c0059-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0018-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0038-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/declare-step-008.xml \
	libs/com.xmlcalabash/test/testsuite/required/xpath-version-available-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0023-008.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0008-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0028-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/input-007.xml \
	libs/com.xmlcalabash/test/testsuite/required/exclude-inline-prefixes-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/labelelements-008.xml \
	libs/com.xmlcalabash/test/testsuite/required/step-available-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/value-available-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0023-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/versioning-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/log-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/http-request-008.xml \
	libs/com.xmlcalabash/test/testsuite/required/test-suite.xml \
	libs/com.xmlcalabash/test/testsuite/required/add-attribute-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0053-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0022-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/identity-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0040-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0050-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0007-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0011-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0031-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0001-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0026-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/insert-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespaces-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/import-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/count-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespaces-008.xml \
	libs/com.xmlcalabash/test/testsuite/required/insert-008.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0027-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/try-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/wrap-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/wrap-sequence-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/choose-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0024-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/http-request-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/http-request-011.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0014-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0034-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0023-009.xml \
	libs/com.xmlcalabash/test/testsuite/required/labelelements-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/labelelements-011.xml \
	libs/com.xmlcalabash/test/testsuite/required/declare-step-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0023-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/declare-step-011.xml \
	libs/com.xmlcalabash/test/testsuite/required/exclude-inline-prefixes-008.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0025-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0023-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/exclude-inline-prefixes-009.xml \
	libs/com.xmlcalabash/test/testsuite/required/declare-step-010.xml \
	libs/com.xmlcalabash/test/testsuite/required/declare-step-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/labelelements-010.xml \
	libs/com.xmlcalabash/test/testsuite/required/labelelements-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0023-008.xml \
	libs/com.xmlcalabash/test/testsuite/required/http-request-010.xml \
	libs/com.xmlcalabash/test/testsuite/required/http-request-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0002-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0022-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/parameters-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/wrap-sequence-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/wrap-007.xml \
	libs/com.xmlcalabash/test/testsuite/required/try-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/insert-009.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespaces-009.xml \
	libs/com.xmlcalabash/test/testsuite/required/count-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/import-007.xml \
	libs/com.xmlcalabash/test/testsuite/required/import-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/import-011.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0027-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-primary-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/wrap-011.xml \
	libs/com.xmlcalabash/test/testsuite/required/wrap-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/atomic-imported.xpl \
	libs/com.xmlcalabash/test/testsuite/required/parameters-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/choose-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0034-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0014-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/http-request-012.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0024-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0004-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/http-request-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/labelelements-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/input-009.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0023-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/declare-step-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/declare-step-007.xml \
	libs/com.xmlcalabash/test/testsuite/required/pipeline-no-type.xpl \
	libs/com.xmlcalabash/test/testsuite/required/input-008.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0003-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0023-007.xml \
	libs/com.xmlcalabash/test/testsuite/required/labelelements-007.xml \
	libs/com.xmlcalabash/test/testsuite/required/http-request-007.xml \
	libs/com.xmlcalabash/test/testsuite/required/fibonacci.xml \
	libs/com.xmlcalabash/test/testsuite/required/pipeinfo-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/http-request-013.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0002-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/choose-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/parameters-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/wrap-sequence-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/wrap-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/wrap-010.xml \
	libs/com.xmlcalabash/test/testsuite/required/try-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0027-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/import-010.xml \
	libs/com.xmlcalabash/test/testsuite/required/count-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/import-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0057-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/try-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/sink-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/wrap-sequence-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/http-request-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/choose-007.xml \
	libs/com.xmlcalabash/test/testsuite/required/resolve-uri-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/labelelements-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0005-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0025-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0015-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0035-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0023-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/declare-step-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/declare-step-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0033-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0003-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0023-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0062-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0025-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/labelelements-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/choose-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/http-request-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/preserve-base-uri-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/wrap-sequence-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/wrap-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/try-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/nested-pipeline-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0010-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0061-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/import-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/count-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/import-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0057-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/try-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/sink-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/wrap-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/http-request-014.xml \
	libs/com.xmlcalabash/test/testsuite/required/resolve-uri-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/choose-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/data-008.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0035-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0025-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0023-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0003-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/declare-step-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0033-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/labelelements-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/choose-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/http-request-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/preserve-base-uri-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0019-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/wrap-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/sink-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0010-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/import-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/viewport-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/unescapemarkup-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0056-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/insert-004.xpl \
	libs/com.xmlcalabash/test/testsuite/required/make-absolute-uris-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0037-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0007-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/xinclude-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0055-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/variable-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/option-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0018-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0005-008.xml \
	libs/com.xmlcalabash/test/testsuite/required/rename-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/add-xml-base-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/rename-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0005-009.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0028-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0018-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0063-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0012-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/variable-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0002-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/xinclude-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0037-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0001-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0021-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/make-absolute-uris-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/pack-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0011-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0031-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/unescapemarkup-007.xml \
	libs/com.xmlcalabash/test/testsuite/required/viewport-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespace-rename-009.xml \
	libs/com.xmlcalabash/test/testsuite/required/for-each-008.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0036-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0056-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0001-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/unescapemarkup-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0011-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/pack-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0027-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0007-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0037-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0009-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/variable-007.xml \
	libs/com.xmlcalabash/test/testsuite/required/option-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0055-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0028-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/delete-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/rename-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/add-xml-base-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/escape-markup-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/add-xml-base-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/rename-007.xml \
	libs/com.xmlcalabash/test/testsuite/required/use-when-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0018-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/delete-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0028-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0008-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/variable-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0034-018.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0009-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0007-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/pack-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0031-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0011-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/unescapemarkup-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/make-absolute-uris-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0021-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0001-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0036-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/for-each-009.xml \
	libs/com.xmlcalabash/test/testsuite/required/viewport-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/namespace-rename-008.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0016-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0036-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0026-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0010-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/viewport-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/viewport-011.xml \
	libs/com.xmlcalabash/test/testsuite/required/directory-list-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/insert-002.xpl \
	libs/com.xmlcalabash/test/testsuite/required/err-s0001-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/pack-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/xinclude-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0034-008.xml \
	libs/com.xmlcalabash/test/testsuite/required/error-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/variable-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/base-uri-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0025-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/add-xml-base-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/rename-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0044-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/rename-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/output-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0003-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0062-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/delete-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/use-when-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/variable-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/error-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0009-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0029-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0019-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0034-009.xml \
	libs/com.xmlcalabash/test/testsuite/required/xinclude-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/unescapemarkup-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0001-007.xml \
	libs/com.xmlcalabash/test/testsuite/required/insert-003.xpl \
	libs/com.xmlcalabash/test/testsuite/required/err-d0020-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/viewport-010.xml \
	libs/com.xmlcalabash/test/testsuite/required/viewport-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/library.xpl \
	libs/com.xmlcalabash/test/testsuite/required/err-s0010-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0030-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0026-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0006-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0036-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0016-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/directory-list-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/viewport-006.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0007-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0001-011.xml \
	libs/com.xmlcalabash/test/testsuite/required/unescapemarkup-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/pack-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/insert-001.xpl \
	libs/com.xmlcalabash/test/testsuite/required/err-s0001-005.xml \
	libs/com.xmlcalabash/test/testsuite/required/xinclude-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/error-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/variable-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/option-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/use-when-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/base-uri-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/delete-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0025-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/add-xml-base-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0044-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0003-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/output-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-c0013-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0044-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/rename-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/add-xml-base-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0062-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0028-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/delete-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/base-uri-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/use-when-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0029-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0009-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0001-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0001-010.xml \
	libs/com.xmlcalabash/test/testsuite/required/pack-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0011-004.xml \
	libs/com.xmlcalabash/test/testsuite/required/unescapemarkup-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/viewport-007.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0030-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0010-001.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-d0020-002.xml \
	libs/com.xmlcalabash/test/testsuite/required/err-s0036-003.xml \
	libs/com.xmlcalabash/test/testsuite/required/pipe-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/validrng-008.xml \
	libs/com.xmlcalabash/test/testsuite/optional/exec-016.xml \
	libs/com.xmlcalabash/test/testsuite/optional/exec-002.xml \
	libs/com.xmlcalabash/test/testsuite/optional/err-c0064-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/exec-003.xml \
	libs/com.xmlcalabash/test/testsuite/optional/exec-017.xml \
	libs/com.xmlcalabash/test/testsuite/optional/validrng-009.xml \
	libs/com.xmlcalabash/test/testsuite/optional/xslt2-002.xpl \
	libs/com.xmlcalabash/test/testsuite/optional/exec-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/exec-015.xml \
	libs/com.xmlcalabash/test/testsuite/optional/exec-014.xml \
	libs/com.xmlcalabash/test/testsuite/optional/uuid-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/err-c0053-004.xml \
	libs/com.xmlcalabash/test/testsuite/optional/exec-004.xml \
	libs/com.xmlcalabash/test/testsuite/optional/exec-010.xml \
	libs/com.xmlcalabash/test/testsuite/optional/exec-011.xml \
	libs/com.xmlcalabash/test/testsuite/optional/exec-005.xml \
	libs/com.xmlcalabash/test/testsuite/optional/err-c0053-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/err-c0053-003.xml \
	libs/com.xmlcalabash/test/testsuite/optional/exec-013.xml \
	libs/com.xmlcalabash/test/testsuite/optional/exec-007.xml \
	libs/com.xmlcalabash/test/testsuite/optional/exec-006.xml \
	libs/com.xmlcalabash/test/testsuite/optional/exec-012.xml \
	libs/com.xmlcalabash/test/testsuite/optional/err-c0053-002.xml \
	libs/com.xmlcalabash/test/testsuite/optional/template-017.xml \
	libs/com.xmlcalabash/test/testsuite/optional/template-003.xml \
	libs/com.xmlcalabash/test/testsuite/optional/validxsd-013.xml \
	libs/com.xmlcalabash/test/testsuite/optional/validxsd-007.xml \
	libs/com.xmlcalabash/test/testsuite/optional/err-c0033-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/validxsd-006.xml \
	libs/com.xmlcalabash/test/testsuite/optional/validxsd-012.xml \
	libs/com.xmlcalabash/test/testsuite/optional/template-002.xml \
	libs/com.xmlcalabash/test/testsuite/optional/template-016.xml \
	libs/com.xmlcalabash/test/testsuite/optional/validsch-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/validsch-003.xml \
	libs/com.xmlcalabash/test/testsuite/optional/template-014.xml \
	libs/com.xmlcalabash/test/testsuite/optional/validxsd-004.xml \
	libs/com.xmlcalabash/test/testsuite/optional/validxsd-010.xml \
	libs/com.xmlcalabash/test/testsuite/optional/validxsd-011.xml \
	libs/com.xmlcalabash/test/testsuite/optional/validxsd-005.xml \
	libs/com.xmlcalabash/test/testsuite/optional/template-015.xml \
	libs/com.xmlcalabash/test/testsuite/optional/template-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/www-form-urldecode-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/validsch-002.xml \
	libs/com.xmlcalabash/test/testsuite/optional/err-c0066-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/template-005.xml \
	libs/com.xmlcalabash/test/testsuite/optional/template-011.xml \
	libs/com.xmlcalabash/test/testsuite/optional/validxsd-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/in-scope-names-002.xml \
	libs/com.xmlcalabash/test/testsuite/optional/template-010.xml \
	libs/com.xmlcalabash/test/testsuite/optional/psvi-required-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/template-004.xml \
	libs/com.xmlcalabash/test/testsuite/optional/validsch-005.xml \
	libs/com.xmlcalabash/test/testsuite/optional/err-c0066-002.xml \
	libs/com.xmlcalabash/test/testsuite/optional/template-012.xml \
	libs/com.xmlcalabash/test/testsuite/optional/template-006.xml \
	libs/com.xmlcalabash/test/testsuite/optional/validxsd-002.xml \
	libs/com.xmlcalabash/test/testsuite/optional/in-scope-names-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/test-suite.xml \
	libs/com.xmlcalabash/test/testsuite/optional/validxsd-003.xml \
	libs/com.xmlcalabash/test/testsuite/optional/template-007.xml \
	libs/com.xmlcalabash/test/testsuite/optional/template-013.xml \
	libs/com.xmlcalabash/test/testsuite/optional/validsch-004.xml \
	libs/com.xmlcalabash/test/testsuite/optional/err-c0036-004.xml \
	libs/com.xmlcalabash/test/testsuite/optional/hash-004.xml \
	libs/com.xmlcalabash/test/testsuite/optional/err-c0037-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/err-c0063-002.xml \
	libs/com.xmlcalabash/test/testsuite/optional/xsl-formatter-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/hash-005.xml \
	libs/com.xmlcalabash/test/testsuite/optional/err-c0036-005.xml \
	libs/com.xmlcalabash/test/testsuite/optional/err-c0037-002.xml \
	libs/com.xmlcalabash/test/testsuite/optional/template-009.xml \
	libs/com.xmlcalabash/test/testsuite/optional/err-c0063-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/template-008.xml \
	libs/com.xmlcalabash/test/testsuite/optional/err-c0037-003.xml \
	libs/com.xmlcalabash/test/testsuite/optional/hash-006.xml \
	libs/com.xmlcalabash/test/testsuite/optional/err-c0036-002.xml \
	libs/com.xmlcalabash/test/testsuite/optional/hash-002.xml \
	libs/com.xmlcalabash/test/testsuite/optional/template-018.xml \
	libs/com.xmlcalabash/test/testsuite/optional/www-form-urlencode-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/validxsd-008.xml \
	libs/com.xmlcalabash/test/testsuite/optional/xslt2-002.xml \
	libs/com.xmlcalabash/test/testsuite/optional/xslt2-003.xml \
	libs/com.xmlcalabash/test/testsuite/optional/validxsd-009.xml \
	libs/com.xmlcalabash/test/testsuite/optional/hash-003.xml \
	libs/com.xmlcalabash/test/testsuite/optional/err-c0036-003.xml \
	libs/com.xmlcalabash/test/testsuite/optional/err-c0036-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/hash-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/xslt2-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/err-c0054-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/xquery.xq \
	libs/com.xmlcalabash/test/testsuite/optional/xquery-006.xml \
	libs/com.xmlcalabash/test/testsuite/optional/xinclude-004.xml \
	libs/com.xmlcalabash/test/testsuite/optional/validrng-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/xinclude-005.xml \
	libs/com.xmlcalabash/test/testsuite/optional/err-c0060-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/xquery-005.xml \
	libs/com.xmlcalabash/test/testsuite/optional/validrng-002.xml \
	libs/com.xmlcalabash/test/testsuite/optional/exec-008.xml \
	libs/com.xmlcalabash/test/testsuite/optional/err-c0034-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/exec-009.xml \
	libs/com.xmlcalabash/test/testsuite/optional/validrng-003.xml \
	libs/com.xmlcalabash/test/testsuite/optional/xinclude-006.xml \
	libs/com.xmlcalabash/test/testsuite/optional/xquery-004.xml \
	libs/com.xmlcalabash/test/testsuite/optional/err-c0057-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/xinclude-002.xml \
	libs/com.xmlcalabash/test/testsuite/optional/err-c0035-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/validrng-006.xml \
	libs/com.xmlcalabash/test/testsuite/optional/xinclude-003.xml \
	libs/com.xmlcalabash/test/testsuite/optional/xquery-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/xquery-003.xml \
	libs/com.xmlcalabash/test/testsuite/optional/xinclude-001.xml \
	libs/com.xmlcalabash/test/testsuite/optional/validrng-004.xml \
	libs/com.xmlcalabash/test/testsuite/optional/err-c0035-002.xml \
	libs/com.xmlcalabash/test/testsuite/optional/validrng-005.xml \
	libs/com.xmlcalabash/test/testsuite/optional/xquery-002.xml \
	libs/com.xmlcalabash/test/testsuite/optional/err-c0061-001.xml \
	libs/com.xmlcalabash/test/testsuite/lib/pipeline.xpl \
	libs/com.xmlcalabash/test/testsuite/lib/pipeline2.xpl \
	libs/com.xmlcalabash/test/testsuite/lib/l2.xpl \
	libs/com.xmlcalabash/test/testsuite/lib/externalxml.xpl \
	libs/com.xmlcalabash/test/testsuite/lib/l3.xpl \
	libs/com.xmlcalabash/test/testsuite/lib/l1.xpl \
	libs/com.xmlcalabash/test/testsuite/lib/l4.xpl \
	libs/com.xmlcalabash/test/testsuite/lib/l5.xpl \
	libs/com.xmlcalabash/test/testsuite/lib/l6.xpl \
	libs/com.xmlcalabash/test/testsuite/lib/exclude-inline-prefixes.xpl \
	libs/com.xmlcalabash/test/testsuite/lib/l1a.xpl \
	libs/com.xmlcalabash/test/testsuite/doc/pqhref.xsd \
	libs/com.xmlcalabash/test/testsuite/doc/xhtml-ct.html \
	libs/com.xmlcalabash/test/testsuite/doc/non-well-formed.xml \
	libs/com.xmlcalabash/test/testsuite/doc/xinclude/input-xinclude-recursive-2.xml \
	libs/com.xmlcalabash/test/testsuite/doc/xinclude/para.xml \
	libs/com.xmlcalabash/test/testsuite/doc/document.xml \
	libs/com.xmlcalabash/test/testsuite/doc/document.rnc \
	libs/com.xmlcalabash/test/testsuite/doc/xml-base-test.xml \
	libs/com.xmlcalabash/test/testsuite/doc/xpath-xinclude-doc.xml \
	libs/com.xmlcalabash/test/testsuite/doc/compoundEntity.xml \
	libs/com.xmlcalabash/test/testsuite/doc/document-attr.xsd \
	libs/com.xmlcalabash/test/testsuite/doc/envelope.xml \
	libs/com.xmlcalabash/test/testsuite/doc/input-xinclude.xml \
	libs/com.xmlcalabash/test/testsuite/doc/document-ns.xml \
	libs/com.xmlcalabash/test/testsuite/doc/directory-list-test/adir/cfile \
	libs/com.xmlcalabash/test/testsuite/doc/directory-list-test/bfile \
	libs/com.xmlcalabash/test/testsuite/doc/directory-list-test/afile \
	libs/com.xmlcalabash/test/testsuite/doc/envelope.fo \
	libs/com.xmlcalabash/test/testsuite/doc/xml-base-chap.xml \
	libs/com.xmlcalabash/test/testsuite/doc/html-utf8.data \
	libs/com.xmlcalabash/test/testsuite/doc/input-xinclude-loop-source.xml \
	libs/com.xmlcalabash/test/testsuite/doc/address-valid-sample.xml \
	libs/com.xmlcalabash/test/testsuite/doc/nfc-input.xml \
	libs/com.xmlcalabash/test/testsuite/doc/s-input.dtd \
	libs/com.xmlcalabash/test/testsuite/doc/compoundDoc.xml \
	libs/com.xmlcalabash/test/testsuite/doc/input-cs.xml \
	libs/com.xmlcalabash/test/testsuite/doc/document-ns.xsd \
	libs/com.xmlcalabash/test/testsuite/doc/s-input.xml \
	libs/com.xmlcalabash/test/testsuite/doc/input-xinclude-recursive-1.xml \
	libs/com.xmlcalabash/test/testsuite/doc/document2.xml \
	libs/com.xmlcalabash/test/testsuite/doc/envelope.xsl \
	libs/com.xmlcalabash/test/testsuite/doc/invalid.xml \
	libs/com.xmlcalabash/test/testsuite/doc/s-input2.xml \
	libs/com.xmlcalabash/test/testsuite/doc/xidoc.xml \
	libs/com.xmlcalabash/test/testsuite/doc/textdata-utf8.txt \
	libs/com.xmlcalabash/test/testsuite/doc/address-nonexistent-dtd.xml \
	libs/com.xmlcalabash/test/testsuite/doc/docbook-valid.xml \
	libs/com.xmlcalabash/test/testsuite/doc/xml11.xml \
	libs/com.xmlcalabash/test/testsuite/doc/address.dtd \
	libs/com.xmlcalabash/test/testsuite/doc/pqhref.rnc \
	libs/com.xmlcalabash/test/testsuite/doc/chaps/div.xml \
	libs/com.xmlcalabash/test/testsuite/doc/chaps/div2.xml \
	libs/com.xmlcalabash/test/testsuite/doc/windows-1252.txt \
	libs/com.xmlcalabash/test/testsuite/doc/divs/div.xml \
	libs/com.xmlcalabash/test/testsuite/doc/divs/p.xml \
	libs/com.xmlcalabash/test/testsuite/doc/document.xsd \
	libs/com.xmlcalabash/test/testsuite/doc/nfkc-input.xml \
	libs/com.xmlcalabash/test/testsuite/doc/address-invalid-sample.xml \
	libs/com.xmlcalabash/test/testsuite/doc/input.xml \
	libs/com.xmlcalabash/test/testsuite/doc/xmldata.xml \
	libs/com.xmlcalabash/test/testsuite/doc/input-en-cs.xml \
	libs/com.xmlcalabash/test/testsuite/doc/docbook-phases.sch \
	libs/com.xmlcalabash/test/testsuite/doc/nfkd-input.xml \
	libs/com.xmlcalabash/test/testsuite/doc/xhtml.html \
	libs/com.xmlcalabash/test/testsuite/doc/textdata-utf8.data \
	libs/com.xmlcalabash/test/testsuite/doc/docbook-invalid.xml \
	libs/com.xmlcalabash/test/testsuite/doc/input-xinclude-loop-target.xml \
	libs/com.xmlcalabash/test/testsuite/doc/input-en.xml \
	libs/com.xmlcalabash/test/testsuite/doc/docbook.sch
.make/mk/libs/com.xmlcalabash/sources.mk : \
	libs/com.xmlcalabash/test \
	libs/com.xmlcalabash/test/testsuite \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash \
	libs/com.xmlcalabash/test/testsuite/xmlcalabash/data \
	libs/com.xmlcalabash/test/testsuite/extension \
	libs/com.xmlcalabash/test/testsuite/serialization \
	libs/com.xmlcalabash/test/testsuite/serialization/results \
	libs/com.xmlcalabash/test/testsuite/required \
	libs/com.xmlcalabash/test/testsuite/optional \
	libs/com.xmlcalabash/test/testsuite/lib \
	libs/com.xmlcalabash/test/testsuite/doc \
	libs/com.xmlcalabash/test/testsuite/doc/xinclude \
	libs/com.xmlcalabash/test/testsuite/doc/directory-list-test \
	libs/com.xmlcalabash/test/testsuite/doc/directory-list-test/adir \
	libs/com.xmlcalabash/test/testsuite/doc/chaps \
	libs/com.xmlcalabash/test/testsuite/doc/divs
