modules/liblouis-utils/.test modules/liblouis-utils/.install modules/liblouis-utils/.install-doc $(TARGET_DIR)/state/modules/liblouis-utils/modified-since-release_ : \
	modules/liblouis-utils/src/main/resources/tables/spaces.cti \
	modules/liblouis-utils/src/main/resources/tables/spaces.dis \
	modules/liblouis-utils/src/main/resources/tables/unicode.dis \
	modules/liblouis-utils/src/main/resources/META-INF/catalog.xml \
	modules/liblouis-utils/src/main/resources/xml/translate-mathml.xpl \
	modules/liblouis-utils/src/main/resources/xml/translate-file.xpl \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/litdigits6Dots.uti \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/latinUppercaseComp6.uti \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/loweredDigits6Dots.uti \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/spaces.uti \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/ukmaths.cfg \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/ukmaths.sem \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/ukmaths_unicode_defs.cti \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/ukmaths_single_cell_defs.cti \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/ukmaths_edit.ctb \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/marburg.cfg \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/latinLetterDef6Dots.uti \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/marburg_unicode_defs.cti \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/marburg.sem \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/nemeth.ctb \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/wiskunde.sem \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/wiskunde-chardefs.cti \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/liblouisutdml.ini \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/nl-chardefs.uti \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/nemeth_edit.ctb \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/nemethdefs.cti \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/namespace.sem \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/digits6Dots.uti \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/exactdots \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/ukmaths.ctb \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/en-chardefs.cti \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/woluwe.cfg \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/nemeth.cfg \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/latinLetterDef8Dots.uti \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/digits6DotsPlusDot6.uti \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/marburg_single_cell_defs.cti \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/braille-patterns.cti \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/wiskunde_edit.ctb \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/marburg_edit.ctb \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/unicode.dis \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/marburg.ctb \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/wiskunde.ctb \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml/nemeth.sem \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/impl/LiblouisMathMLTransform.java \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/impl/LiblouisutdmlConfigRegistry.java \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/impl/LiblouisExternalNativePath.java \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/impl/LiblouisTableDatatypeService.java \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/impl/LiblouisMathMLConfigPath.java \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/impl/mac/LiblouisNativePathForMacOS.java \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/impl/LiblouisTableRegistry.java \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/impl/linux/LiblouisNativePathForLinux.java \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/impl/LiblouisTranslatorJnaImplProvider.java \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/impl/windows/LiblouisNativePathForWindows.java \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/impl/LiblouisTableJnaImplProvider.java \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/impl/LiblouisutdmlProcessBuilderImpl.java \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/calabash/impl/LiblouisResultReader.java \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/calabash/impl/TranslateFileStep.java \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/LiblouisTable.java \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/LiblouisutdmlConfigPath.java \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/LiblouisTableResolver.java \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/pef/impl/LiblouisDisplayTableProvider.java \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/pef/LiblouisDisplayTableBrailleConverter.java \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/LiblouisTablePath.java \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/Liblouisutdml.java \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/package-info.java \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/LiblouisTranslator.java \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/LiblouisutdmlConfigResolver.java \
	modules/liblouis-utils/src/main/README.md
modules/liblouis-utils/.test modules/liblouis-utils/.install-doc : \
	modules/liblouis-utils/src/test/resources/logback.xml \
	modules/liblouis-utils/src/test/resources/tables/foobar.utb \
	modules/liblouis-utils/src/test/resources/tables/ital.cti \
	modules/liblouis-utils/src/test/resources/tables/foobar.ctb \
	modules/liblouis-utils/src/test/resources/tables/squash-ws.utb \
	modules/liblouis-utils/src/test/resources/tables/stateful.utb \
	modules/liblouis-utils/src/test/resources/tables/foobar.dis \
	modules/liblouis-utils/src/test/resources/tables/digits.cti \
	modules/liblouis-utils/src/test/resources/tables/uplows.cti \
	modules/liblouis-utils/src/test/resources/tables/delete-ws.utb \
	modules/liblouis-utils/src/test/resources/tables/signs.cti \
	modules/liblouis-utils/src/test/resources/tables/foobar.uti \
	modules/liblouis-utils/src/test/resources/tables/braille-patterns.cti \
	modules/liblouis-utils/src/test/resources/mathml/test_013.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_007.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_006.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_012.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_004.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_010.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_038.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_039.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_011.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_005.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_029.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_001.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_015.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_014.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_028.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_016.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_002.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_003.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_017.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_070.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_064.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_058.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_104.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_110.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_111.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_105.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_059.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_065.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_071.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_067.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_073.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_098.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_113.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_107.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_106.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_112.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_099.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_072.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_066.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_062.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_076.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_089.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_116.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_102.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_103.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_117.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_088.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_077.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_063.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_049.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_075.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_061.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_101.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_115.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_114.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_100.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_060.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_074.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_048.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_051.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_045.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_079.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_092.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_086.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_119.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_118.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_087.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_093.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_078.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_044.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_050.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_046.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_052.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_085.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_091.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_090.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_084.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_053.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_047.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_043.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_057.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_080.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_094.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_095.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_081.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_056.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_042.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_068.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_054.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_040.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_097.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_083.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_108.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_109.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_082.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_096.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_041.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_055.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_069.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_032.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_026.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_027.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_033.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_025.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_031.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_019.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_018.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_030.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_024.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_008.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_020.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_034.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_035.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_021.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_009.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_037.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_023.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_022.xml \
	modules/liblouis-utils/src/test/resources/mathml/test_036.xml \
	modules/liblouis-utils/src/test/resources/META-INF/catalog.xml \
	modules/liblouis-utils/src/test/resources/phony.xsl \
	modules/liblouis-utils/src/test/java/TablePath.java \
	modules/liblouis-utils/src/test/java/ignore \
	modules/liblouis-utils/src/test/java/org/daisy/pipeline/braille/liblouis/impl/LiblouisTranslatorJnaImplTest.java \
	modules/liblouis-utils/src/test/java/XSpecAndXProcSpecTest.java \
	modules/liblouis-utils/src/test/java/LiblouisCoreTest.java \
	modules/liblouis-utils/src/test/java/LiblouisTablesTest.java \
	modules/liblouis-utils/src/test/java/MockHyphenator.java \
	modules/liblouis-utils/src/test/xprocspec/test_transform_mathml.xprocspec \
	modules/liblouis-utils/src/test/xprocspec/test_transform.xprocspec \
	modules/liblouis-utils/src/test/xprocspec/test_translate-mathml_woluwe.xprocspec
modules/liblouis-utils/.install-doc : \
	modules/liblouis-utils/doc/index.md
.make/mk/modules/liblouis-utils/sources.mk : \
	modules/liblouis-utils/src \
	modules/liblouis-utils/src/test \
	modules/liblouis-utils/src/test/resources \
	modules/liblouis-utils/src/test/resources/tables \
	modules/liblouis-utils/src/test/resources/mathml \
	modules/liblouis-utils/src/test/resources/META-INF \
	modules/liblouis-utils/src/test/java \
	modules/liblouis-utils/src/test/java/org \
	modules/liblouis-utils/src/test/java/org/daisy \
	modules/liblouis-utils/src/test/java/org/daisy/pipeline \
	modules/liblouis-utils/src/test/java/org/daisy/pipeline/braille \
	modules/liblouis-utils/src/test/java/org/daisy/pipeline/braille/liblouis \
	modules/liblouis-utils/src/test/java/org/daisy/pipeline/braille/liblouis/impl \
	modules/liblouis-utils/src/test/xprocspec \
	modules/liblouis-utils/src/main \
	modules/liblouis-utils/src/main/resources \
	modules/liblouis-utils/src/main/resources/tables \
	modules/liblouis-utils/src/main/resources/META-INF \
	modules/liblouis-utils/src/main/resources/xml \
	modules/liblouis-utils/src/main/resources/lbu_files \
	modules/liblouis-utils/src/main/resources/lbu_files/mathml \
	modules/liblouis-utils/src/main/java \
	modules/liblouis-utils/src/main/java/org \
	modules/liblouis-utils/src/main/java/org/daisy \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/impl \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/impl/mac \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/impl/linux \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/impl/windows \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/calabash \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/calabash/impl \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/pef \
	modules/liblouis-utils/src/main/java/org/daisy/pipeline/braille/liblouis/pef/impl \
	modules/liblouis-utils/doc
