modules/css-utils/.test modules/css-utils/.install modules/css-utils/.install-doc $(TARGET_DIR)/state/modules/css-utils/modified-since-release_ : \
	modules/css-utils/src/main/resources/META-INF/catalog.xml \
	modules/css-utils/src/main/resources/rnc/stylesheetParametersRequest.rnc \
	modules/css-utils/src/main/resources/xml/css-detach.xpl \
	modules/css-utils/src/main/resources/xml/css-detach.xsl \
	modules/css-utils/src/main/resources/xml/clean-up-namespaces.xpl \
	modules/css-utils/src/main/resources/xml/css-speech-clean.xpl \
	modules/css-utils/src/main/resources/xml/css-speech-cascade.xpl \
	modules/css-utils/src/main/resources/xml/css-to-fileset.xpl \
	modules/css-utils/src/main/resources/xml/css-to-fileset.xsl \
	modules/css-utils/src/main/resources/xml/css-cascade.xpl \
	modules/css-utils/src/main/resources/xml/library.xpl \
	modules/css-utils/src/main/resources/xml/library.xsl \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/impl/MediumParser.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/impl/StylesheetParametersWebServiceExtension.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/impl/StylesheetParametersResource.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/impl/StylesheetParametersRequest.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/impl/UnmodifiableTerm.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/impl/MediumDatatypeService.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/impl/StylesheetParametersDatatypeService.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/impl/DefaultCssCascader.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/impl/StylesheetParametersParser.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/MediumProvider.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/UserAgentStylesheetRegistry.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/SourceMapReader.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/MediaQueryParser.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/CssPreProcessor.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/calabash/impl/CssCascadeStep.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/calabash/impl/CssAnalyzeStep.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/calabash/impl/InMemoryURIResolver.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/CssSerializer.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/CounterEvaluator.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/CssCascader.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/speech/SpeechDeclarationTransformer.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/speech/impl/SpeechCssCascader.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/speech/VoiceFamilyList.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/StyleAccessor.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/saxon/impl/CssParseParamSetFunctionProvider.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/saxon/impl/CssMediaFunctionProvider.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/Medium.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/Dimension.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/JStyleParserCssCascader.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/XsltProcessor.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/CssAnalyzer.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/UserAgentStylesheet.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/sass/impl/SassVariable.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/sass/impl/SassMapParser.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/sass/impl/DoxygenComment.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/sass/impl/SassAnalyzer.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/sass/impl/Comment.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/sass/impl/SassMapDatatypeService.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/sass/SassCompiler.java \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/CounterStyle.java \
	modules/css-utils/src/main/antlr3/org/daisy/pipeline/css/sass/impl/SassDocumentation.g \
	modules/css-utils/src/main/antlr3/org/daisy/pipeline/css/sass/impl/SassPostProcess.g \
	modules/css-utils/src/main/antlr3/org/daisy/pipeline/css/sass/impl/Doxygen.g \
	modules/css-utils/src/main/README.md
modules/css-utils/.test modules/css-utils/.install-doc : \
	modules/css-utils/src/test/xspec/test_css-parse-param-set.xspec \
	modules/css-utils/src/test/resources/logback.xml \
	modules/css-utils/src/test/resources/nested_properties.css \
	modules/css-utils/src/test/resources/default-dtbook-speech.scss \
	modules/css-utils/src/test/resources/speech-and-print.css \
	modules/css-utils/src/test/resources/font.ttf \
	modules/css-utils/src/test/resources/import.css \
	modules/css-utils/src/test/resources/META-INF/catalog.xml \
	modules/css-utils/src/test/resources/imports/4.scss \
	modules/css-utils/src/test/resources/imports/6/_index.scss \
	modules/css-utils/src/test/resources/imports/3.scss \
	modules/css-utils/src/test/resources/imports/2.css \
	modules/css-utils/src/test/resources/imports/1.css \
	modules/css-utils/src/test/resources/imports/_5.scss \
	modules/css-utils/src/test/resources/charset.scss \
	modules/css-utils/src/test/resources/charset.css \
	modules/css-utils/src/test/resources/misc.scss \
	modules/css-utils/src/test/resources/import.scss \
	modules/css-utils/src/test/resources/misc.css \
	modules/css-utils/src/test/resources/speech.css \
	modules/css-utils/src/test/resources/references.css \
	modules/css-utils/src/test/resources/nested_properties.scss \
	modules/css-utils/src/test/resources/bg.png \
	modules/css-utils/src/test/java/XProcSpecTest.java \
	modules/css-utils/src/test/java/ignore \
	modules/css-utils/src/test/java/org/daisy/pipeline/css/speech/impl/SpeechCssCascaderTest.java \
	modules/css-utils/src/test/java/org/daisy/pipeline/css/speech/VoiceFamilyListTest.java \
	modules/css-utils/src/test/java/org/daisy/pipeline/css/CssAnalyzerTest.java \
	modules/css-utils/src/test/java/org/daisy/pipeline/css/CounterStyleTest.java \
	modules/css-utils/src/test/java/SassTest.java \
	modules/css-utils/src/test/xprocspec/test_css-analyze.xprocspec \
	modules/css-utils/src/test/xprocspec/test_format-lists.xprocspec \
	modules/css-utils/src/test/xprocspec/test_css-speech-cascade.xprocspec \
	modules/css-utils/src/test/xprocspec/test_css-to-fileset.xprocspec
.make/mk/modules/css-utils/sources.mk : \
	modules/css-utils/src \
	modules/css-utils/src/test \
	modules/css-utils/src/test/xspec \
	modules/css-utils/src/test/resources \
	modules/css-utils/src/test/resources/META-INF \
	modules/css-utils/src/test/resources/imports \
	modules/css-utils/src/test/resources/imports/6 \
	modules/css-utils/src/test/java \
	modules/css-utils/src/test/java/org \
	modules/css-utils/src/test/java/org/daisy \
	modules/css-utils/src/test/java/org/daisy/pipeline \
	modules/css-utils/src/test/java/org/daisy/pipeline/css \
	modules/css-utils/src/test/java/org/daisy/pipeline/css/speech \
	modules/css-utils/src/test/java/org/daisy/pipeline/css/speech/impl \
	modules/css-utils/src/test/xprocspec \
	modules/css-utils/src/main \
	modules/css-utils/src/main/resources \
	modules/css-utils/src/main/resources/META-INF \
	modules/css-utils/src/main/resources/rnc \
	modules/css-utils/src/main/resources/xml \
	modules/css-utils/src/main/java \
	modules/css-utils/src/main/java/org \
	modules/css-utils/src/main/java/org/daisy \
	modules/css-utils/src/main/java/org/daisy/pipeline \
	modules/css-utils/src/main/java/org/daisy/pipeline/css \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/impl \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/calabash \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/calabash/impl \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/speech \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/speech/impl \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/saxon \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/saxon/impl \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/sass \
	modules/css-utils/src/main/java/org/daisy/pipeline/css/sass/impl \
	modules/css-utils/src/main/antlr3 \
	modules/css-utils/src/main/antlr3/org \
	modules/css-utils/src/main/antlr3/org/daisy \
	modules/css-utils/src/main/antlr3/org/daisy/pipeline \
	modules/css-utils/src/main/antlr3/org/daisy/pipeline/css \
	modules/css-utils/src/main/antlr3/org/daisy/pipeline/css/sass \
	modules/css-utils/src/main/antlr3/org/daisy/pipeline/css/sass/impl
