modules/nlp-common/.test modules/nlp-common/.install modules/nlp-common/.install-doc $(TARGET_DIR)/state/modules/nlp-common/modified-since-release_ : \
	modules/nlp-common/src/main/resources/META-INF/catalog.xml \
	modules/nlp-common/src/main/resources/xml/break-detect.xpl \
	modules/nlp-common/src/main/resources/xml/distribute-sentences.xsl \
	modules/nlp-common/src/main/resources/xml/reshape.xpl \
	modules/nlp-common/src/main/resources/xml/break-and-reshape.xpl \
	modules/nlp-common/src/main/resources/xml/create-valid-breaks.xsl \
	modules/nlp-common/src/main/resources/xml/library.xpl \
	modules/nlp-common/src/main/resources/dictionaries/dot_abbr_fr.txt \
	modules/nlp-common/src/main/resources/dictionaries/compact_abbr_fr.txt \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/impl/matchrules/WordListMatchRule.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/impl/matchrules/NumberRangeMatchRule.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/impl/matchrules/AbbrMatchRule.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/impl/matchrules/CompactAbbrMatchRule.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/impl/matchrules/RegexAheadMatchRule.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/impl/matchrules/RegexMatchRule.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/impl/matchrules/WordFileMatchRule.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/impl/PrefixMatchStringFinder.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/impl/FullMatchStringFinder.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/impl/IStringFinder.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/impl/ResourceUtils.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/impl/MatchRule.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/ruledcategorizers/RuledMultilangCategorizer.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/ruledcategorizers/RuledFrenchCategorizer.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/calabash/impl/BreakDetectProvider.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/calabash/impl/XmlBreakRebuilder.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/calabash/impl/InlineSectionFinder.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/calabash/impl/InlineSectionProcessor.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/calabash/impl/BreakDetectStep.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/calabash/impl/DuplicationManager.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/calabash/impl/FormatSpecifications.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/calabash/impl/StringComposer.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/calabash/impl/TreeWriterFactory.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/TextCategorizer.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/LangDetector.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/DummyLangDetector.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/LanguageUtils.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/RuleBasedTextCategorizer.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/lexing/LexResultPrettyPrinter.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/lexing/ruled/impl/EuroSentenceDetector.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/lexing/ruled/impl/ISentenceDetector.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/lexing/ruled/impl/RuleBasedLexer.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/lexing/ruled/impl/BasicSentenceDetector.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/lexing/LexServiceRegistry.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/lexing/LexService.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/lexing/light/impl/LightLexer.java \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/lexing/omni/impl/OmnilangLexer.java
modules/nlp-common/.test modules/nlp-common/.install-doc : \
	modules/nlp-common/src/test/resources/epub3_test.html \
	modules/nlp-common/src/test/resources/zedai_test.xml \
	modules/nlp-common/src/test/resources/dtbook_test.xml \
	modules/nlp-common/src/test/java/org/daisy/pipeline/nlp/FrenchCategorizerTest.java \
	modules/nlp-common/src/test/java/org/daisy/pipeline/nlp/RuledCategorizerTest.java \
	modules/nlp-common/src/test/java/org/daisy/pipeline/nlp/calabash/impl/ActualFilesTest.java \
	modules/nlp-common/src/test/java/org/daisy/pipeline/nlp/calabash/impl/SegmentsPrettyPrinter.java \
	modules/nlp-common/src/test/java/org/daisy/pipeline/nlp/calabash/impl/DummyLexer.java \
	modules/nlp-common/src/test/java/org/daisy/pipeline/nlp/calabash/impl/BreakDetectTest.java \
	modules/nlp-common/src/test/java/org/daisy/pipeline/nlp/calabash/impl/StringComposerTest.java \
	modules/nlp-common/src/test/java/org/daisy/pipeline/nlp/PrefixMatchTest.java \
	modules/nlp-common/src/test/java/org/daisy/pipeline/nlp/lexing/ruled/impl/LexingTest.java \
	modules/nlp-common/src/test/java/org/daisy/pipeline/nlp/lexing/ruled/impl/FrenchLexingTest.java \
	modules/nlp-common/src/test/java/org/daisy/pipeline/nlp/lexing/light/impl/LightLexingTest.java \
	modules/nlp-common/src/test/java/org/daisy/pipeline/nlp/lexing/omni/impl/OmnilangTest.java \
	modules/nlp-common/src/test/xprocspec/reshape.xprocspec
.make/mk/modules/nlp-common/sources.mk : \
	modules/nlp-common/src \
	modules/nlp-common/src/test \
	modules/nlp-common/src/test/resources \
	modules/nlp-common/src/test/java \
	modules/nlp-common/src/test/java/org \
	modules/nlp-common/src/test/java/org/daisy \
	modules/nlp-common/src/test/java/org/daisy/pipeline \
	modules/nlp-common/src/test/java/org/daisy/pipeline/nlp \
	modules/nlp-common/src/test/java/org/daisy/pipeline/nlp/calabash \
	modules/nlp-common/src/test/java/org/daisy/pipeline/nlp/calabash/impl \
	modules/nlp-common/src/test/java/org/daisy/pipeline/nlp/lexing \
	modules/nlp-common/src/test/java/org/daisy/pipeline/nlp/lexing/ruled \
	modules/nlp-common/src/test/java/org/daisy/pipeline/nlp/lexing/ruled/impl \
	modules/nlp-common/src/test/java/org/daisy/pipeline/nlp/lexing/light \
	modules/nlp-common/src/test/java/org/daisy/pipeline/nlp/lexing/light/impl \
	modules/nlp-common/src/test/java/org/daisy/pipeline/nlp/lexing/omni \
	modules/nlp-common/src/test/java/org/daisy/pipeline/nlp/lexing/omni/impl \
	modules/nlp-common/src/test/xprocspec \
	modules/nlp-common/src/main \
	modules/nlp-common/src/main/resources \
	modules/nlp-common/src/main/resources/META-INF \
	modules/nlp-common/src/main/resources/xml \
	modules/nlp-common/src/main/resources/dictionaries \
	modules/nlp-common/src/main/java \
	modules/nlp-common/src/main/java/org \
	modules/nlp-common/src/main/java/org/daisy \
	modules/nlp-common/src/main/java/org/daisy/pipeline \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/impl \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/impl/matchrules \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/ruledcategorizers \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/calabash \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/calabash/impl \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/lexing \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/lexing/ruled \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/lexing/ruled/impl \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/lexing/light \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/lexing/light/impl \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/lexing/omni \
	modules/nlp-common/src/main/java/org/daisy/pipeline/nlp/lexing/omni/impl
