/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_daisy_pipeline_tts_attnative_ATTLib */

#ifndef _Included_org_daisy_pipeline_tts_attnative_ATTLib
#define _Included_org_daisy_pipeline_tts_attnative_ATTLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_daisy_pipeline_tts_attnative_ATTLib
 * Method:    openConnection
 * Signature: (Ljava/lang/String;III)J
 */
JNIEXPORT jlong JNICALL Java_org_daisy_pipeline_tts_attnative_ATTLib_openConnection
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     org_daisy_pipeline_tts_attnative_ATTLib
 * Method:    closeConnection
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_daisy_pipeline_tts_attnative_ATTLib_closeConnection
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_daisy_pipeline_tts_attnative_ATTLib
 * Method:    synthesizeRequest
 * Signature: (Ljava/lang/Object;JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_daisy_pipeline_tts_attnative_ATTLib_synthesizeRequest
  (JNIEnv *, jclass, jobject, jlong, jstring);

/*
 * Class:     org_daisy_pipeline_tts_attnative_ATTLib
 * Method:    speak
 * Signature: (Ljava/lang/Object;J[B)I
 */
JNIEXPORT jint JNICALL Java_org_daisy_pipeline_tts_attnative_ATTLib_speak
  (JNIEnv *, jclass, jobject, jlong, jbyteArray);

/*
 * Class:     org_daisy_pipeline_tts_attnative_ATTLib
 * Method:    getVoiceNames
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_daisy_pipeline_tts_attnative_ATTLib_getVoiceNames
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
