name: DAISY Pipeline 2
collections:
  wiki:
    output: true
    permalink: /:path/
    alternative_base: "https://github.com/daisy/pipeline/wiki"
  wiki_ui:
    output: true
    permalink: /Get-Help/User-Guide/Desktop-Application/:path/
    alternative_base: "https://github.com/daisy/pipeline-ui/wiki"
  wiki_webui:
    output: true
    permalink: /Get-Help/User-Guide/Web-Application/:path/
    alternative_base: "https://github.com/daisy/pipeline-webui/wiki"
defaults:
  - scope: {path: "", type: wiki}
    values:
      layout: wiki
      spine: sitemap
      edit_button: wiki
  - scope: {path: "", type: wiki_ui}
    values:
      layout: wiki
      spine: sitemap
      edit_button: wiki-ui
  - scope: {path: "", type: wiki_webui}
    values:
      layout: wiki
      spine: sitemap
      edit_button: wiki-webui
markdown: kramdown
kramdown:
  parse_block_html: true
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: false
    css: class
sass:
  sass_dir: css
baseurl: "/pipeline"
site_base: "http://daisy.github.io"
meta_file: _meta.ttl
include:
  - modules/braille/dtbook-to-pef/src/main/resources/css/_tables.scss/index.md
  - modules/braille/html-to-pef/src/main/resources/css/_tables.scss/index.md
  - modules/braille/dtbook-to-pef/src/main/resources/css/_definition-lists.scss/index.md
  - modules/braille/html-to-pef/src/main/resources/css/_definition-lists.scss/index.md
  - modules/braille/dtbook-to-pef/src/main/resources/css/_legacy.scss/index.md
  - modules/braille/html-to-pef/src/main/resources/css/_legacy.scss/index.md
  - modules/braille/dtbook-to-pef/src/main/resources/css/_generate-toc.scss/index.md
  - modules/braille/html-to-pef/src/main/resources/css/_generate-toc.scss/index.md
  - modules/braille/dtbook-to-pef/src/main/resources/css/_notes.scss/index.md
  - modules/braille/html-to-pef/src/main/resources/css/_notes.scss/index.md
  - modules/braille/dtbook-to-pef/src/main/resources/css/_page-breaking.scss/index.md
  - modules/braille/html-to-pef/src/main/resources/css/_page-breaking.scss/index.md
  - modules/braille/dtbook-to-pef/src/main/resources/css/_volume-breaking.scss/index.md
  - modules/braille/html-to-pef/src/main/resources/css/_volume-breaking.scss/index.md
