package org.daisy.pipeline.tts.acapela.impl;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : nscube_forjna.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class NSC_SOUND_DATA extends Structure {
	public int uiSize;
	/** C type : unsigned char* */
	public Pointer pSoundBuffer;
	public NSC_SOUND_DATA() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("uiSize", "pSoundBuffer");
	}
	/** @param pSoundBuffer C type : unsigned char* */
	public NSC_SOUND_DATA(int uiSize, Pointer pSoundBuffer) {
		super();
		this.uiSize = uiSize;
		this.pSoundBuffer = pSoundBuffer;
	}
	public NSC_SOUND_DATA(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends NSC_SOUND_DATA implements Structure.ByReference {
		
	};
	public static class ByValue extends NSC_SOUND_DATA implements Structure.ByValue {
		
	};
}
