modules/scripts/nimas-fileset-validator/.test modules/scripts/nimas-fileset-validator/.install modules/scripts/nimas-fileset-validator/.install-doc $(TARGET_DIR)/state/modules/scripts/nimas-fileset-validator/modified-since-release_ : \
	modules/scripts/nimas-fileset-validator/src/main/resources/META-INF/catalog.xml \
	modules/scripts/nimas-fileset-validator/src/main/resources/xml/nimas-fileset-validator.xpl \
	modules/scripts/nimas-fileset-validator/src/main/resources/xml/schema/sch/package-doc-with-mathml.sch \
	modules/scripts/nimas-fileset-validator/src/main/resources/xml/schema/sch/package-doc-without-mathml.sch \
	modules/scripts/nimas-fileset-validator/src/main/resources/xml/schema/sch/mod/package-doc-common.sch \
	modules/scripts/nimas-fileset-validator/src/main/resources/xml/schema/sch/mod/package-doc-without-mathml-mod.sch \
	modules/scripts/nimas-fileset-validator/src/main/resources/xml/schema/sch/mod/package-doc-with-mathml-mod.sch \
	modules/scripts/nimas-fileset-validator/src/main/resources/xml/schema/rng/package-doc-1.2.rng \
	modules/scripts/nimas-fileset-validator/src/main/resources/xml/schema/rng/mod/datatypes.rng \
	modules/scripts/nimas-fileset-validator/src/main/resources/xml/schema/rng/mod/attributes.rng \
	modules/scripts/nimas-fileset-validator/src/main/resources/xml/nimas-fileset-validator.validate.xpl \
	modules/scripts/nimas-fileset-validator/src/main/resources/xml/nimas-fileset-validator.validate-package-doc.xpl \
	modules/scripts/nimas-fileset-validator/src/main/resources/xml/nimas-fileset-validator.fileset-filter.xpl \
	modules/scripts/nimas-fileset-validator/src/main/resources/xml/nimas-fileset-validator.store.xpl
modules/scripts/nimas-fileset-validator/.test modules/scripts/nimas-fileset-validator/.install-doc : \
	modules/scripts/nimas-fileset-validator/src/test/resources/logback.xml \
	modules/scripts/nimas-fileset-validator/src/test/resources/9781122334455NIMAS/9781122334455NIMAS.pdf \
	modules/scripts/nimas-fileset-validator/src/test/resources/9781122334455NIMAS/9781122334455NIMAS.xml \
	modules/scripts/nimas-fileset-validator/src/test/resources/9781122334455NIMAS/images/U00/cover.jpg \
	modules/scripts/nimas-fileset-validator/src/test/resources/9781122334455NIMAS/images/U01C01/icon.jpg \
	modules/scripts/nimas-fileset-validator/src/test/resources/9781122334455NIMAS/images/U01C01/p006-001.jpg \
	modules/scripts/nimas-fileset-validator/src/test/resources/9781122334455NIMAS/images/U01C01/p002-001.jpg \
	modules/scripts/nimas-fileset-validator/src/test/resources/9781122334455NIMAS/images/U01C01/p010-001.jpg \
	modules/scripts/nimas-fileset-validator/src/test/resources/9781122334455NIMAS/images/U01C01/p008-001.jpg \
	modules/scripts/nimas-fileset-validator/src/test/resources/9781122334455NIMAS/9781122334455NIMAS.opf \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/MathML_Sample2.xml-report.xml \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/MathML_Sample2.xml \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-027.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-011.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-005.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-033.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-036.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-022.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-014.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-023.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/check.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-015.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-001.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-037.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-004.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-032.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-026.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-010.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-018.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-030.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-006.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-012.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-024.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-009.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-017.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-021.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-035.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-003.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-034.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-002.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-016.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-020.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-008.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-013.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-025.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-031.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-007.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-019.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-003.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-035.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-021.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-017.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-009.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-024.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-012.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-006.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-030.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-018.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-019.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-007.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-031.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-025.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-013.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-008.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-020.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-016.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-002.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-034.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-014.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-022.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-036.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-033.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-005.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-011.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-027.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-010.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-026.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-032.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-004.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-037.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-001.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-015.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-023.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-044.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-050.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-051.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-045.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-053.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-047.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-046.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-052.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/sglobe.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-056.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-042.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-043.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-057.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-041.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-055.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-054.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-040.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-059.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-065.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/test.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-064.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-058.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-004b.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/go.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-004c.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/bglobe.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-063.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-062.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-060.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-048.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-049.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-061.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-002b.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-018.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-006.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-012.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-009.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-021.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-017.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-003.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-014b.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-014c.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-002.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-020.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-016.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-008.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-013.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-007.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-019.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-039.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-011.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-005.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-028.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-014.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-022.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-015.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-023.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-001.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-029.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/goon.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-004.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-010.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-038.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/mathml.txt \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-014.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-028.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-005.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-011.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-010.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-004.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-029.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-001.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-015.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-003.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-017.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-009.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-012.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-006.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-018.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-019.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-007.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-013.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-008.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-016.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-002.png \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/MathML_Sample2-copy.xml \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/MathML_Sample2-copy.xml-report.xml \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/MathML_Sample2.ncx \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/MathML_Sample2.smil \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/resources.res \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/mathml-fallback-transform.xslt \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/MathML_Sample2.opf \
	modules/scripts/nimas-fileset-validator/src/test/resources/greatpainters-text-files-only/greatpainters-spring.jpg \
	modules/scripts/nimas-fileset-validator/src/test/resources/greatpainters-text-files-only/greatpainters-the_adoration_of_the_lamb.jpg \
	modules/scripts/nimas-fileset-validator/src/test/resources/greatpainters-text-files-only/speechgen.opf \
	modules/scripts/nimas-fileset-validator/src/test/resources/greatpainters-text-files-only/greatpainters-last_judgement.jpg \
	modules/scripts/nimas-fileset-validator/src/test/resources/greatpainters-text-files-only/dtbook.xml \
	modules/scripts/nimas-fileset-validator/src/test/resources/greatpainters-text-files-only/dtbookbasic.css \
	modules/scripts/nimas-fileset-validator/src/test/resources/greatpainters-text-files-only/speechgen.ncx \
	modules/scripts/nimas-fileset-validator/src/test/resources/greatpainters-text-files-only/greatpainters-the_fighting_temeraire.jpg \
	modules/scripts/nimas-fileset-validator/src/test/resources/greatpainters-text-files-only/greatpainters-portrait_of_georg_gisze.jpg \
	modules/scripts/nimas-fileset-validator/src/test/java/XProcSpecTest.java \
	modules/scripts/nimas-fileset-validator/src/test/xprocspec/test_nimas-fileset-validator.xprocspec \
	modules/scripts/nimas-fileset-validator/src/test/xprocspec/test_nimas-fileset-validator.script.xprocspec
modules/scripts/nimas-fileset-validator/.install-doc : \
	modules/scripts/nimas-fileset-validator/doc/dev-notes.md \
	modules/scripts/nimas-fileset-validator/doc/index.md
.make/mk/modules/scripts/nimas-fileset-validator/sources.mk : \
	modules/scripts/nimas-fileset-validator/src \
	modules/scripts/nimas-fileset-validator/src/test \
	modules/scripts/nimas-fileset-validator/src/test/resources \
	modules/scripts/nimas-fileset-validator/src/test/resources/9781122334455NIMAS \
	modules/scripts/nimas-fileset-validator/src/test/resources/9781122334455NIMAS/images \
	modules/scripts/nimas-fileset-validator/src/test/resources/9781122334455NIMAS/images/U00 \
	modules/scripts/nimas-fileset-validator/src/test/resources/9781122334455NIMAS/images/U01C01 \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2 \
	modules/scripts/nimas-fileset-validator/src/test/resources/MathML_Modular_Extension_Example_2/images \
	modules/scripts/nimas-fileset-validator/src/test/resources/greatpainters-text-files-only \
	modules/scripts/nimas-fileset-validator/src/test/java \
	modules/scripts/nimas-fileset-validator/src/test/xprocspec \
	modules/scripts/nimas-fileset-validator/src/main \
	modules/scripts/nimas-fileset-validator/src/main/resources \
	modules/scripts/nimas-fileset-validator/src/main/resources/META-INF \
	modules/scripts/nimas-fileset-validator/src/main/resources/xml \
	modules/scripts/nimas-fileset-validator/src/main/resources/xml/schema \
	modules/scripts/nimas-fileset-validator/src/main/resources/xml/schema/sch \
	modules/scripts/nimas-fileset-validator/src/main/resources/xml/schema/sch/mod \
	modules/scripts/nimas-fileset-validator/src/main/resources/xml/schema/rng \
	modules/scripts/nimas-fileset-validator/src/main/resources/xml/schema/rng/mod \
	modules/scripts/nimas-fileset-validator/doc
