clientlib/java/clientlib-java/.test : \
	clientlib/java/clientlib-java/src/test/resources/responses/jobRequest.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/alive.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/scripts.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/datatypes/braille-translator.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/datatypes/test-regex.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/datatypes.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/scripts/zedai-to-epub3.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/scripts/dtbook-to-zedai.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/scripts/zedai-to-pef.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/scripts/dtbook-to-epub3.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/scripts/dtbook-validator.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/scripts/daisy202-to-epub3.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/scripts/job2.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job6.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job5.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job4.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job1.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job3.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job2.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/63.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/77.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/76.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/62.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/48.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/74.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/60.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/61.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/75.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/49.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/71.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/65.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/59.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/58.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/64.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/70.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/66.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/72.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/8.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/9.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/73.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/67.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/28.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/14.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/15.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/29.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/17.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/16.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/12.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/13.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/11.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/39.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/38.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/10.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/21.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/35.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/34.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/20.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/36.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/22.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/23.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/37.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/33.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/27.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/26.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/32.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/24.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/30.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/18.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/19.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/31.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/25.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/81.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/42.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/56.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/4.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/57.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/5.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/43.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/80.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/82.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/69.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/7.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/55.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/41.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/40.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/6.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/54.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/68.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/83.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/50.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/2.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/44.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/78.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/79.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/45.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/51.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/3.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/84.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/47.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/1.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/53.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/52.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7/46.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job1/result/option/output-dir/idx/output/zedai.xml \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job1/result/F00000\ -\ Don't\ Worry,\ Be\ Happy\ Lyrics.epub.xml \
	clientlib/java/clientlib-java/src/test/resources/scripts/zedai-to-epub3.xml \
	clientlib/java/clientlib-java/src/test/resources/scripts/dtbook-to-zedai.xml \
	clientlib/java/clientlib-java/src/test/resources/scripts/zedai-to-pef.xml \
	clientlib/java/clientlib-java/src/test/resources/scripts/dtbook-to-epub3.xml \
	clientlib/java/clientlib-java/src/test/resources/scripts/dtbook-validator.xml \
	clientlib/java/clientlib-java/src/test/resources/scripts/test.xml \
	clientlib/java/clientlib-java/src/test/resources/scripts/daisy202-to-epub3.xml \
	clientlib/java/clientlib-java/src/test/resources/jobs/job2/context/hauy_valid.xml \
	clientlib/java/clientlib-java/src/test/resources/jobs/job2/job.xml \
	clientlib/java/clientlib-java/src/test/resources/jobs/job1/context/dtbook.2005.basic.css \
	clientlib/java/clientlib-java/src/test/resources/jobs/job1/context/valentin.jpg \
	clientlib/java/clientlib-java/src/test/resources/jobs/job1/context/hauy_valid.xml \
	clientlib/java/clientlib-java/src/test/resources/jobs/job1/job.xml \
	clientlib/java/clientlib-java/src/test/java/org/daisy/pipeline/jobs/test/JobCreationTest.java \
	clientlib/java/clientlib-java/src/test/java/org/daisy/pipeline/jobs/test/JobStorageTest.java \
	clientlib/java/clientlib-java/src/test/java/org/daisy/pipeline/jobs/test/ParsingTest.java \
	clientlib/java/clientlib-java/src/test/java/org/daisy/pipeline/client/models/ProgressTest.java \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/Pipeline2Logger.java \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/filestorage/JobStorage.java \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/filestorage/JobValidator.java \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/utils/XPath.java \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/utils/NamespaceContextMap.java \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/utils/Files.java \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/utils/XML.java \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/models/Message.java \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/models/Client.java \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/models/Argument.java \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/models/Property.java \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/models/Alive.java \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/models/DataType.java \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/models/JobSizes.java \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/models/datatypes/RegexType.java \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/models/datatypes/EnumType.java \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/models/Job.java \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/models/JobQueue.java \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/models/Callback.java \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/models/JobMessages.java \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/models/Result.java \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/models/Script.java \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/Pipeline2Exception.java
.make/mk/clientlib/java/clientlib-java/sources.mk : \
	clientlib/java/clientlib-java/src \
	clientlib/java/clientlib-java/src/test \
	clientlib/java/clientlib-java/src/test/resources \
	clientlib/java/clientlib-java/src/test/resources/responses \
	clientlib/java/clientlib-java/src/test/resources/responses/datatypes \
	clientlib/java/clientlib-java/src/test/resources/responses/scripts \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job7 \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job1 \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job1/result \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job1/result/option \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job1/result/option/output-dir \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job1/result/option/output-dir/idx \
	clientlib/java/clientlib-java/src/test/resources/responses/jobs/job1/result/option/output-dir/idx/output \
	clientlib/java/clientlib-java/src/test/resources/scripts \
	clientlib/java/clientlib-java/src/test/resources/jobs \
	clientlib/java/clientlib-java/src/test/resources/jobs/job2 \
	clientlib/java/clientlib-java/src/test/resources/jobs/job2/context \
	clientlib/java/clientlib-java/src/test/resources/jobs/job1 \
	clientlib/java/clientlib-java/src/test/resources/jobs/job1/context \
	clientlib/java/clientlib-java/src/test/java \
	clientlib/java/clientlib-java/src/test/java/org \
	clientlib/java/clientlib-java/src/test/java/org/daisy \
	clientlib/java/clientlib-java/src/test/java/org/daisy/pipeline \
	clientlib/java/clientlib-java/src/test/java/org/daisy/pipeline/jobs \
	clientlib/java/clientlib-java/src/test/java/org/daisy/pipeline/jobs/test \
	clientlib/java/clientlib-java/src/test/java/org/daisy/pipeline/client \
	clientlib/java/clientlib-java/src/test/java/org/daisy/pipeline/client/models \
	clientlib/java/clientlib-java/src/main \
	clientlib/java/clientlib-java/src/main/java \
	clientlib/java/clientlib-java/src/main/java/org \
	clientlib/java/clientlib-java/src/main/java/org/daisy \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/filestorage \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/utils \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/models \
	clientlib/java/clientlib-java/src/main/java/org/daisy/pipeline/client/models/datatypes
