libs/jsass/.test libs/jsass/.install : \
	libs/jsass/src/test/resources/darwin-aarch64/libjsass_test.dylib \
	libs/jsass/src/test/resources/windows-x64/libjsass_test.dll \
	libs/jsass/src/test/resources/linux-aarch64/libjsass_test.so \
	libs/jsass/src/test/resources/scss/inc/mixins.scss \
	libs/jsass/src/test/resources/scss/test/functions.scss \
	libs/jsass/src/test/resources/scss/input.scss \
	libs/jsass/src/test/resources/scss/compressed/output-with-map.css \
	libs/jsass/src/test/resources/scss/compressed/output-without-map.css \
	libs/jsass/src/test/resources/scss/nested/output-with-map.css \
	libs/jsass/src/test/resources/scss/nested/output-without-map.css \
	libs/jsass/src/test/resources/scss/error.scss \
	libs/jsass/src/test/resources/scss/src/include.scss \
	libs/jsass/src/test/resources/linux-armhf32/libjsass_test.so \
	libs/jsass/src/test/resources/linux-x64/libjsass_test.so \
	libs/jsass/src/test/resources/sass/input.sass \
	libs/jsass/src/test/resources/sass/inc/mixins.sass \
	libs/jsass/src/test/resources/sass/test/functions.sass \
	libs/jsass/src/test/resources/sass/error.sass \
	libs/jsass/src/test/resources/sass/compressed/output-with-map.css \
	libs/jsass/src/test/resources/sass/compressed/output-without-map.css \
	libs/jsass/src/test/resources/sass/nested/output-with-map.css \
	libs/jsass/src/test/resources/sass/nested/output-without-map.css \
	libs/jsass/src/test/resources/sass/src/include.sass \
	libs/jsass/src/test/resources/darwin-x86_64/libjsass_test.dylib \
	libs/jsass/src/test/java/io/bit3/jsass/PrecisionTest.java \
	libs/jsass/src/test/java/io/bit3/jsass/ArgumentConverterTest.java \
	libs/jsass/src/test/java/io/bit3/jsass/Utils.java \
	libs/jsass/src/test/java/io/bit3/jsass/adapter/NativeSassToJavaTest.java \
	libs/jsass/src/test/java/io/bit3/jsass/adapter/NativeTestLoader.java \
	libs/jsass/src/test/java/io/bit3/jsass/adapter/NativeTestAdapter.java \
	libs/jsass/src/test/java/io/bit3/jsass/adapter/NativeAdapterTest.java \
	libs/jsass/src/test/java/io/bit3/jsass/Sass2ScssTest.java \
	libs/jsass/src/test/java/io/bit3/jsass/CompileStringTest.java \
	libs/jsass/src/test/java/io/bit3/jsass/CompileFileTest.java \
	libs/jsass/src/test/java/io/bit3/jsass/ExceptionTest.java \
	libs/jsass/src/test/java/io/bit3/jsass/TestFunctions.java \
	libs/jsass/src/test/java/io/bit3/jsass/AbstractCompileTest.java \
	libs/jsass/src/test/java/io/bit3/jsass/ImporterTest.java \
	libs/jsass/src/test/java/io/bit3/jsass/CleanSourceMapTest.java \
	libs/jsass/src/test/java/io/bit3/jsass/TestImporter.java \
	libs/jsass/src/test/c/CMakeLists.txt \
	libs/jsass/src/test/c/io_bit3_jsass_adapter_NativeTestAdapter.c \
	libs/jsass/src/test/c/io_bit3_jsass_adapter_NativeTestAdapter.h \
	libs/jsass/src/main/resources/darwin-aarch64/libjsass.dylib \
	libs/jsass/src/main/resources/windows-x64/libjsass.dll \
	libs/jsass/src/main/resources/windows-x64/libsass.dll \
	libs/jsass/src/main/resources/linux-aarch64/libjsass.so \
	libs/jsass/src/main/resources/linux-armhf32/libjsass.so \
	libs/jsass/src/main/resources/linux-x64/libjsass.so \
	libs/jsass/src/main/resources/darwin-x86_64/libjsass.dylib \
	libs/jsass/src/main/java/io/bit3/jsass/Separator.java \
	libs/jsass/src/main/java/io/bit3/jsass/importer/Importer.java \
	libs/jsass/src/main/java/io/bit3/jsass/importer/JsassCustomHeaderImporter.java \
	libs/jsass/src/main/java/io/bit3/jsass/importer/ImportException.java \
	libs/jsass/src/main/java/io/bit3/jsass/importer/Import.java \
	libs/jsass/src/main/java/io/bit3/jsass/context/ImportStack.java \
	libs/jsass/src/main/java/io/bit3/jsass/context/Context.java \
	libs/jsass/src/main/java/io/bit3/jsass/context/AbstractContext.java \
	libs/jsass/src/main/java/io/bit3/jsass/context/StringContext.java \
	libs/jsass/src/main/java/io/bit3/jsass/context/FileContext.java \
	libs/jsass/src/main/java/io/bit3/jsass/annotation/DefaultFloatValue.java \
	libs/jsass/src/main/java/io/bit3/jsass/annotation/ErrorFunction.java \
	libs/jsass/src/main/java/io/bit3/jsass/annotation/DefaultStringValue.java \
	libs/jsass/src/main/java/io/bit3/jsass/annotation/DefaultLongValue.java \
	libs/jsass/src/main/java/io/bit3/jsass/annotation/DefaultCharacterValue.java \
	libs/jsass/src/main/java/io/bit3/jsass/annotation/DefaultIntegerValue.java \
	libs/jsass/src/main/java/io/bit3/jsass/annotation/DefaultByteValue.java \
	libs/jsass/src/main/java/io/bit3/jsass/annotation/DefaultBooleanValue.java \
	libs/jsass/src/main/java/io/bit3/jsass/annotation/Name.java \
	libs/jsass/src/main/java/io/bit3/jsass/annotation/DebugFunction.java \
	libs/jsass/src/main/java/io/bit3/jsass/annotation/DefaultShortValue.java \
	libs/jsass/src/main/java/io/bit3/jsass/annotation/DefaultDoubleValue.java \
	libs/jsass/src/main/java/io/bit3/jsass/annotation/WarnFunction.java \
	libs/jsass/src/main/java/io/bit3/jsass/Sass2ScssOptions.java \
	libs/jsass/src/main/java/io/bit3/jsass/adapter/NativeContext.java \
	libs/jsass/src/main/java/io/bit3/jsass/adapter/NativeFileContext.java \
	libs/jsass/src/main/java/io/bit3/jsass/adapter/NativeLoader.java \
	libs/jsass/src/main/java/io/bit3/jsass/adapter/NativeStringContext.java \
	libs/jsass/src/main/java/io/bit3/jsass/adapter/AbstractNativeContext.java \
	libs/jsass/src/main/java/io/bit3/jsass/adapter/NativeImporterWrapper.java \
	libs/jsass/src/main/java/io/bit3/jsass/adapter/NativeOptions.java \
	libs/jsass/src/main/java/io/bit3/jsass/adapter/LoaderException.java \
	libs/jsass/src/main/java/io/bit3/jsass/adapter/NativeImport.java \
	libs/jsass/src/main/java/io/bit3/jsass/adapter/NativeAdapter.java \
	libs/jsass/src/main/java/io/bit3/jsass/Compiler.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/FunctionWrapperFactory.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/FunctionArgumentSignature.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/FunctionArgumentSignatureFactory.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/JsassCustomFunctions.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/FunctionWrapper.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/converter/CharacterArgumentConverter.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/converter/BooleanArgumentConverter.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/converter/StringArgumentConverter.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/converter/IntegerArgumentConverter.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/converter/ObjectArgumentConverter.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/converter/ContextArgumentConverter.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/converter/LastImportArgumentConverter.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/converter/ConversionException.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/converter/FloatArgumentConverter.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/converter/DoubleArgumentConverter.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/converter/ShortArgumentConverter.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/converter/LongArgumentConverter.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/converter/ByteArgumentConverter.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/converter/ArgumentConverter.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/factory/ByteArgumentConverterFactory.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/factory/DoubleArgumentConverterFactory.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/factory/IntegerArgumentConverterFactory.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/factory/StringArgumentConverterFactory.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/factory/FloatArgumentConverterFactory.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/factory/LastImportArgumentConverterFactory.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/factory/ShortArgumentConverterFactory.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/factory/CharacterArgumentConverterFactory.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/factory/ContextArgumentConverterFactory.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/factory/LongArgumentConverterFactory.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/factory/BooleanArgumentConverterFactory.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/factory/ArgumentConverterFactory.java \
	libs/jsass/src/main/java/io/bit3/jsass/function/FunctionDeclaration.java \
	libs/jsass/src/main/java/io/bit3/jsass/UnsupportedContextException.java \
	libs/jsass/src/main/java/io/bit3/jsass/OutputStyle.java \
	libs/jsass/src/main/java/io/bit3/jsass/CompilationException.java \
	libs/jsass/src/main/java/io/bit3/jsass/type/TypeUtils.java \
	libs/jsass/src/main/java/io/bit3/jsass/type/SassNumber.java \
	libs/jsass/src/main/java/io/bit3/jsass/type/SassBoolean.java \
	libs/jsass/src/main/java/io/bit3/jsass/type/SassValue.java \
	libs/jsass/src/main/java/io/bit3/jsass/type/SassColor.java \
	libs/jsass/src/main/java/io/bit3/jsass/type/SassError.java \
	libs/jsass/src/main/java/io/bit3/jsass/type/SassMap.java \
	libs/jsass/src/main/java/io/bit3/jsass/type/SassList.java \
	libs/jsass/src/main/java/io/bit3/jsass/type/SassNull.java \
	libs/jsass/src/main/java/io/bit3/jsass/type/SassWarning.java \
	libs/jsass/src/main/java/io/bit3/jsass/type/SassString.java \
	libs/jsass/src/main/java/io/bit3/jsass/Output.java \
	libs/jsass/src/main/java/io/bit3/jsass/Options.java \
	libs/jsass/src/main/java/io/bit3/jsass/package-info.java \
	libs/jsass/src/main/c/jni_helper.c \
	libs/jsass/src/main/c/CMakeLists.txt \
	libs/jsass/src/main/c/io_bit3_jsass_adapter_NativeAdapter.h \
	libs/jsass/src/main/c/Toolchain-mingw64-amd64.cmake \
	libs/jsass/src/main/c/io_bit3_jsass_adapter_NativeAdapter.c \
	libs/jsass/src/main/c/version_script.map \
	libs/jsass/src/main/c/Toolchain-linux-armhf32.cmake \
	libs/jsass/src/main/c/Toolchain-darwin-aarch64.cmake \
	libs/jsass/src/main/c/exported_symbols_list.txt \
	libs/jsass/src/main/c/Toolchain-darwin-amd64.cmake \
	libs/jsass/src/main/c/Toolchain-linux-aarch64.cmake
.make/mk/libs/jsass/sources.mk : \
	libs/jsass/src \
	libs/jsass/src/test \
	libs/jsass/src/test/resources \
	libs/jsass/src/test/resources/darwin-aarch64 \
	libs/jsass/src/test/resources/windows-x64 \
	libs/jsass/src/test/resources/linux-aarch64 \
	libs/jsass/src/test/resources/scss \
	libs/jsass/src/test/resources/scss/inc \
	libs/jsass/src/test/resources/scss/test \
	libs/jsass/src/test/resources/scss/compressed \
	libs/jsass/src/test/resources/scss/nested \
	libs/jsass/src/test/resources/scss/src \
	libs/jsass/src/test/resources/linux-armhf32 \
	libs/jsass/src/test/resources/linux-x64 \
	libs/jsass/src/test/resources/sass \
	libs/jsass/src/test/resources/sass/inc \
	libs/jsass/src/test/resources/sass/test \
	libs/jsass/src/test/resources/sass/compressed \
	libs/jsass/src/test/resources/sass/nested \
	libs/jsass/src/test/resources/sass/src \
	libs/jsass/src/test/resources/darwin-x86_64 \
	libs/jsass/src/test/java \
	libs/jsass/src/test/java/io \
	libs/jsass/src/test/java/io/bit3 \
	libs/jsass/src/test/java/io/bit3/jsass \
	libs/jsass/src/test/java/io/bit3/jsass/adapter \
	libs/jsass/src/test/c \
	libs/jsass/src/main \
	libs/jsass/src/main/libsass \
	libs/jsass/src/main/resources \
	libs/jsass/src/main/resources/darwin-aarch64 \
	libs/jsass/src/main/resources/windows-x64 \
	libs/jsass/src/main/resources/linux-aarch64 \
	libs/jsass/src/main/resources/linux-armhf32 \
	libs/jsass/src/main/resources/linux-x64 \
	libs/jsass/src/main/resources/darwin-x86_64 \
	libs/jsass/src/main/java \
	libs/jsass/src/main/java/io \
	libs/jsass/src/main/java/io/bit3 \
	libs/jsass/src/main/java/io/bit3/jsass \
	libs/jsass/src/main/java/io/bit3/jsass/importer \
	libs/jsass/src/main/java/io/bit3/jsass/context \
	libs/jsass/src/main/java/io/bit3/jsass/annotation \
	libs/jsass/src/main/java/io/bit3/jsass/adapter \
	libs/jsass/src/main/java/io/bit3/jsass/function \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/converter \
	libs/jsass/src/main/java/io/bit3/jsass/function/arguments/factory \
	libs/jsass/src/main/java/io/bit3/jsass/type \
	libs/jsass/src/main/c
