#pragma once

/// <summary>
/// List of return code. <br/>
/// This list should match the one defined in org/daisy/pipeline/tts/onecore/SAPIResult.java
/// </summary>
enum SAPIResult {
    SAPI_OK = 0,
    UNSUPPORTED_FORMAT,
    TOO_LONG_VOICE_NAME,
    TOO_LONG_VOICE_VENDOR,
    TOO_LONG_TEXT,
    UNSUPPORTED_AUDIO_FORMAT,
    VOICE_NOT_FOUND,
    COULD_NOT_SET_VOICE,
    COULD_NOT_SET_EVENT_INTERESTS,
    COULD_NOT_LISTEN_TO_EVENTS,
    COULD_NOT_INIT_COM,
    COULD_NOT_CREATE_CATEGORY,
    COULD_NOT_ENUM_CATEGORY,
    COULD_NOT_COUNT_ENUM,
    COULD_NOT_SPEAK_INVALIDARG,
    COULD_NOT_SPEAK_E_POINTER,
    COULD_NOT_SPEAK_OUTOFMEMORY,
    COULD_NOT_SPEAK_INVALIDFLAGS,
    COULD_NOT_SPEAK_BUSY,
    COULD_NOT_SPEAK_THIS_FORMAT,
    COULD_NOT_SPEAK,
    COULD_NOT_SET_STREAM_FORMAT,
    COULD_NOT_BIND_STREAM,
    COULD_NOT_INIT_STREAM,
    COULD_NOT_BIND_OUTPUT
};