/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_daisy_pipeline_tts_onecore_SAPI */

#ifndef _Included_org_daisy_pipeline_tts_onecore_SAPI
#define _Included_org_daisy_pipeline_tts_onecore_SAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_daisy_pipeline_tts_onecore_SAPI
 * Method:    openConnection
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_daisy_pipeline_tts_onecore_SAPI_openConnection
  (JNIEnv *, jclass);

/*
 * Class:     org_daisy_pipeline_tts_onecore_SAPI
 * Method:    closeConnection
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_daisy_pipeline_tts_onecore_SAPI_closeConnection
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_daisy_pipeline_tts_onecore_SAPI
 * Method:    speak
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_daisy_pipeline_tts_onecore_SAPI_speak
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring);

/*
 * Class:     org_daisy_pipeline_tts_onecore_SAPI
 * Method:    getStreamSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_daisy_pipeline_tts_onecore_SAPI_getStreamSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_daisy_pipeline_tts_onecore_SAPI
 * Method:    readStream
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_org_daisy_pipeline_tts_onecore_SAPI_readStream
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     org_daisy_pipeline_tts_onecore_SAPI
 * Method:    getVoiceVendors
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_daisy_pipeline_tts_onecore_SAPI_getVoiceVendors
  (JNIEnv *, jclass);

/*
 * Class:     org_daisy_pipeline_tts_onecore_SAPI
 * Method:    getVoiceNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_daisy_pipeline_tts_onecore_SAPI_getVoiceNames
  (JNIEnv *, jclass);

/*
 * Class:     org_daisy_pipeline_tts_onecore_SAPI
 * Method:    getVoiceLocales
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_daisy_pipeline_tts_onecore_SAPI_getVoiceLocales
  (JNIEnv *, jclass);

/*
 * Class:     org_daisy_pipeline_tts_onecore_SAPI
 * Method:    getVoiceGenders
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_daisy_pipeline_tts_onecore_SAPI_getVoiceGenders
  (JNIEnv *, jclass);

/*
 * Class:     org_daisy_pipeline_tts_onecore_SAPI
 * Method:    getVoiceAges
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_daisy_pipeline_tts_onecore_SAPI_getVoiceAges
  (JNIEnv *, jclass);

/*
 * Class:     org_daisy_pipeline_tts_onecore_SAPI
 * Method:    getBookmarkNames
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_daisy_pipeline_tts_onecore_SAPI_getBookmarkNames
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_daisy_pipeline_tts_onecore_SAPI
 * Method:    getBookmarkPositions
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_daisy_pipeline_tts_onecore_SAPI_getBookmarkPositions
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_daisy_pipeline_tts_onecore_SAPI
 * Method:    initialize
 * Signature: (IS)I
 */
JNIEXPORT jint JNICALL Java_org_daisy_pipeline_tts_onecore_SAPI_initialize
  (JNIEnv *, jclass, jint, jshort);

/*
 * Class:     org_daisy_pipeline_tts_onecore_SAPI
 * Method:    dispose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_daisy_pipeline_tts_onecore_SAPI_dispose
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
