modules/common/common-utils/.test modules/common/common-utils/.install modules/common/common-utils/.install-doc $(TARGET_DIR)/state/modules/common/common-utils/modified-since-release_ : \
	modules/common/common-utils/src/main/resources/META-INF/catalog.xml \
	modules/common/common-utils/src/main/resources/xml/xproc/i18n-translate.xpl \
	modules/common/common-utils/src/main/resources/xml/xproc/error.xpl \
	modules/common/common-utils/src/main/resources/xml/xproc/assert.xpl \
	modules/common/common-utils/src/main/resources/xml/xproc/add-ids.xpl \
	modules/common/common-utils/src/main/resources/xml/xproc/tokenize.xpl \
	modules/common/common-utils/src/main/resources/xml/xproc/message.xpl \
	modules/common/common-utils/src/main/resources/xml/xproc/add-ids.xsl \
	modules/common/common-utils/src/main/resources/xml/xproc/log-error.xpl \
	modules/common/common-utils/src/main/resources/xml/xproc/parse-xml-stylesheet-instructions.xpl \
	modules/common/common-utils/src/main/resources/xml/xproc/xml-chunker.xpl \
	modules/common/common-utils/src/main/resources/xml/xproc/library.xpl \
	modules/common/common-utils/src/main/resources/xml/xslt/i18n.xsl \
	modules/common/common-utils/src/main/resources/xml/xslt/fileset-from-xml-stylesheet-instructions.xsl \
	modules/common/common-utils/src/main/resources/xml/xslt/generate-id.xsl \
	modules/common/common-utils/src/main/resources/xml/xslt/parse-xml-stylesheet-instructions.xsl \
	modules/common/common-utils/src/main/resources/xml/xslt/numeral-conversion.xsl \
	modules/common/common-utils/src/main/resources/xml/xslt/library.xsl \
	modules/common/common-utils/src/main/java/org/daisy/pipeline/common/calabash/impl/Chunker.java \
	modules/common/common-utils/src/main/java/org/daisy/pipeline/common/calabash/impl/ErrorReporter.java \
	modules/common/common-utils/src/main/java/org/daisy/pipeline/common/calabash/impl/LogError.java \
	modules/common/common-utils/src/main/java/org/daisy/pipeline/common/calabash/impl/ChunkerStep.java \
	modules/common/common-utils/src/main/java/org/daisy/pipeline/common/calabash/impl/Error.java \
	modules/common/common-utils/src/main/java/org/daisy/pipeline/common/saxon/impl/NormalizeLangDefinition.java \
	modules/common/common-utils/src/main/java/org/daisy/pipeline/common/saxon/impl/ErrorDefinition.java \
	modules/common/common-utils/src/main/java/org/daisy/pipeline/common/saxon/impl/DateTimeParser.java \
	modules/common/common-utils/src/main/java/org/daisy/pipeline/common/saxon/impl/ProgressDefinition.java \
	modules/common/common-utils/src/main/java/org/daisy/pipeline/common/saxon/impl/MessageDefinition.java \
	modules/common/common-utils/src/main/java/org/daisy/pipeline/common/rest/Response.java \
	modules/common/common-utils/src/main/java/org/daisy/pipeline/common/rest/scheduler/RecoverableError.java \
	modules/common/common-utils/src/main/java/org/daisy/pipeline/common/rest/scheduler/Scheduler.java \
	modules/common/common-utils/src/main/java/org/daisy/pipeline/common/rest/scheduler/ExponentialBackoffScheduler.java \
	modules/common/common-utils/src/main/java/org/daisy/pipeline/common/rest/scheduler/Schedulable.java \
	modules/common/common-utils/src/main/java/org/daisy/pipeline/common/rest/scheduler/FatalError.java \
	modules/common/common-utils/src/main/java/org/daisy/pipeline/common/rest/package-info.java \
	modules/common/common-utils/src/main/java/org/daisy/pipeline/common/rest/Request.java \
	modules/common/common-utils/src/main/java/org/daisy/pipeline/common/NormalizeLang.java
modules/common/common-utils/.test modules/common/common-utils/.install-doc : \
	modules/common/common-utils/src/test/xspec/i18n.xspec \
	modules/common/common-utils/src/test/xspec/parse-xml-stylesheet-instructions.xspec \
	modules/common/common-utils/src/test/xspec/numeral-conversion.xspec \
	modules/common/common-utils/src/test/resources/logback.xml \
	modules/common/common-utils/src/test/resources/test_parse-xml-stylesheet-instructions.xml \
	modules/common/common-utils/src/test/java/XProcSpecTest.java \
	modules/common/common-utils/src/test/java/org/daisy/pipeline/common/calabash/impl/ChunkerTest.java \
	modules/common/common-utils/src/test/xprocspec/test_parse-xml-stylesheet-instructions.xprocspec \
	modules/common/common-utils/src/test/xprocspec/assert.xprocspec \
	modules/common/common-utils/src/test/xprocspec/error.xprocspec \
	modules/common/common-utils/src/test/xprocspec/i18n-translate.xprocspec
.make/mk/modules/common/common-utils/sources.mk : \
	modules/common/common-utils/src \
	modules/common/common-utils/src/test \
	modules/common/common-utils/src/test/xspec \
	modules/common/common-utils/src/test/resources \
	modules/common/common-utils/src/test/java \
	modules/common/common-utils/src/test/java/org \
	modules/common/common-utils/src/test/java/org/daisy \
	modules/common/common-utils/src/test/java/org/daisy/pipeline \
	modules/common/common-utils/src/test/java/org/daisy/pipeline/common \
	modules/common/common-utils/src/test/java/org/daisy/pipeline/common/calabash \
	modules/common/common-utils/src/test/java/org/daisy/pipeline/common/calabash/impl \
	modules/common/common-utils/src/test/xprocspec \
	modules/common/common-utils/src/main \
	modules/common/common-utils/src/main/resources \
	modules/common/common-utils/src/main/resources/META-INF \
	modules/common/common-utils/src/main/resources/xml \
	modules/common/common-utils/src/main/resources/xml/xproc \
	modules/common/common-utils/src/main/resources/xml/xslt \
	modules/common/common-utils/src/main/java \
	modules/common/common-utils/src/main/java/org \
	modules/common/common-utils/src/main/java/org/daisy \
	modules/common/common-utils/src/main/java/org/daisy/pipeline \
	modules/common/common-utils/src/main/java/org/daisy/pipeline/common \
	modules/common/common-utils/src/main/java/org/daisy/pipeline/common/calabash \
	modules/common/common-utils/src/main/java/org/daisy/pipeline/common/calabash/impl \
	modules/common/common-utils/src/main/java/org/daisy/pipeline/common/saxon \
	modules/common/common-utils/src/main/java/org/daisy/pipeline/common/saxon/impl \
	modules/common/common-utils/src/main/java/org/daisy/pipeline/common/rest \
	modules/common/common-utils/src/main/java/org/daisy/pipeline/common/rest/scheduler
