framework/webservice/.test framework/webservice/.install framework/webservice/.install-doc $(TARGET_DIR)/state/framework/webservice/modified-since-release_ : \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/script/scripts.rnc \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/script/script.rnc \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/script/scriptElement.rnc \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/properties/properties.rnc \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/properties/property.rnc \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/properties/propertyElement.rnc \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/datatypes.rnc \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/job/sizeElem.rnc \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/job/jobElement.rnc \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/job/jobs.rnc \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/job/job.rnc \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/job/sizes.rnc \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/queue/queue.rnc \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/request/jobRequest.rnc \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/client/clientElement.rnc \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/client/clients.rnc \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/client/client.rnc \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/base/alive.rnc \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/base/priority.rnc \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/base/error.rnc \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/base/common.rnc \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/impl/VolatileClientStorage.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/impl/SimpleRequestLogEntry.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/impl/JobsWebSocketEndpoint.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/impl/VolatileClient.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/impl/WebSocketCallback.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/impl/PosterCallback.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/impl/VolatileWebserviceStorage.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/impl/PushNotifier.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/impl/VolatileRequestLog.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/impl/VolatileJobConfigurationStorage.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/impl/AuthenticationFilter.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/Routes.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/jetty/impl/WebSocketServer.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/xml/PropertyXmlWriter.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/xml/JobXmlWriter.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/xml/QueueXmlWriter.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/xml/JobsXmlWriter.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/xml/JobSizeXmlWriter.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/xml/ClientsXmlWriter.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/xml/XmlUtils.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/xml/PropertiesXmlWriter.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/xml/ErrorWriter.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/xml/JobsSizeXmlWriter.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/xml/ClientXmlWriter.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/xml/DatatypesXmlWriter.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/xml/AliveXmlWriter.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/xml/ScriptXmlWriter.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/xml/ScriptsXmlWriter.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/xml/XmlValidator.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/SizesResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/PortResultResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/JobBatchResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/OptionResultResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/QueueResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/JobsResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/JobResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/PropertyResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/QueueDownResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/QueueMoveResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/JobConfigurationResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/LogResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/ClientResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/DatatypeResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/PropertiesResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/ScriptsResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/ClientsResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/NamedResultResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/ScriptResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/HaltResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/AliveResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/QueueUpResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/PipelineStatusService.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/ResultResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/package-info.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/PipelineWebService.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl/DatatypesResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/WebServiceExtension.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/AdminResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/MultipartRequestData.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/GenericResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/AuthenticatedResource.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/Callback.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/Properties.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/Authenticator.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/request/PropertyRequest.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/request/ClientRequest.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/request/JsonRequired.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/request/JobRequest.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/request/Request.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/CallbackHandler.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/PipelineWebServiceConfiguration.java \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/package-info.java
framework/webservice/.test framework/webservice/.install-doc : \
	framework/webservice/src/test/resources/logback.xml \
	framework/webservice/src/test/resources/data.zip \
	framework/webservice/src/test/resources/data2.zip \
	framework/webservice/src/test/resources/cover\ image.jpg \
	framework/webservice/src/test/resources/META-INF/catalog.xml \
	framework/webservice/src/test/resources/hello.xml \
	framework/webservice/src/test/resources/mock-module/script.xpl \
	framework/webservice/src/test/resources/mock-module/foo.xsl \
	framework/webservice/src/test/resources/mock-module/messages-script.xpl \
	framework/webservice/src/test/resources/mock-module/error-script.xpl \
	framework/webservice/src/test/java/TestMultipleJobs.java \
	framework/webservice/src/test/java/TestClients.java \
	framework/webservice/src/test/java/Base.java \
	framework/webservice/src/test/java/TestMessages.java \
	framework/webservice/src/test/java/ignore \
	framework/webservice/src/test/java/org/daisy/pipeline/webservice/impl/VolatileClientStorageTest.java \
	framework/webservice/src/test/java/TestAdmin.java \
	framework/webservice/src/test/java/TestNonLocalJobs.java \
	framework/webservice/src/test/java/SleepStep.java \
	framework/webservice/src/test/java/SampleXmlFormatsTest.java \
	framework/webservice/src/test/java/TestAuthenticationErrors.java \
	framework/webservice/src/test/java/TestPushNotifications.java \
	framework/webservice/src/test/java/TestMessagesWithDerby.java \
	framework/webservice/src/test/java/JobWrapper.java \
	framework/webservice/src/test/java/TestLocalJobs.java \
	framework/webservice/src/test/java/TestClientJobs.java
framework/webservice/.install-doc : \
	framework/webservice/doc/xml-formats/alive.xml \
	framework/webservice/doc/xml-formats/scripts.xml \
	framework/webservice/doc/xml-formats/queue.xml \
	framework/webservice/doc/xml-formats/jobRequest1.xml \
	framework/webservice/doc/xml-formats/jobRequest2.xml \
	framework/webservice/doc/xml-formats/script.xml \
	framework/webservice/doc/xml-formats/error.xml \
	framework/webservice/doc/xml-formats/jobs.xml \
	framework/webservice/doc/xml-formats/job.xml \
	framework/webservice/doc/xml-formats/sizes.xml \
	framework/webservice/doc/xml-formats/client.xml \
	framework/webservice/doc/xml-formats/clients.xml \
	framework/webservice/doc/xml-formats/jobRequest1.localmode.xml
.make/mk/framework/webservice/sources.mk : \
	framework/webservice/src \
	framework/webservice/src/test \
	framework/webservice/src/test/resources \
	framework/webservice/src/test/resources/META-INF \
	framework/webservice/src/test/resources/mock-module \
	framework/webservice/src/test/java \
	framework/webservice/src/test/java/org \
	framework/webservice/src/test/java/org/daisy \
	framework/webservice/src/test/java/org/daisy/pipeline \
	framework/webservice/src/test/java/org/daisy/pipeline/webservice \
	framework/webservice/src/test/java/org/daisy/pipeline/webservice/impl \
	framework/webservice/src/main \
	framework/webservice/src/main/resources \
	framework/webservice/src/main/resources/org \
	framework/webservice/src/main/resources/org/daisy \
	framework/webservice/src/main/resources/org/daisy/pipeline \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/script \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/properties \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/job \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/queue \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/request \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/client \
	framework/webservice/src/main/resources/org/daisy/pipeline/webservice/resources/base \
	framework/webservice/src/main/java \
	framework/webservice/src/main/java/org \
	framework/webservice/src/main/java/org/daisy \
	framework/webservice/src/main/java/org/daisy/pipeline \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/impl \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/jetty \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/jetty/impl \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/xml \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/restlet/impl \
	framework/webservice/src/main/java/org/daisy/pipeline/webservice/request \
	framework/webservice/doc \
	framework/webservice/doc/xml-formats
