package org.daisy.dotify.translator.impl.liblouis;

import org.daisy.dotify.api.translator.TranslatorMode;
import org.daisy.dotify.api.translator.TranslatorMode.DotsPerCell;
import org.daisy.dotify.api.translator.TranslatorSpecification;
import org.daisy.dotify.api.translator.TranslatorType;

import java.util.HashMap;
import java.util.Map;

enum LiblouisSpecifications {
    INSTANCE;
    private final Map<TranslatorSpecification, String> specs;

    /**
     * This file is generated so we will suppress the warning of LineLength for this function.
     */
    @SuppressWarnings("checkstyle:LineLength")
    private LiblouisSpecifications() {
        specs = new HashMap<>();

        //Generated by ListTables
        specs.put(new TranslatorSpecification("af", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "afr-za-g1.ctb");
        specs.put(new TranslatorSpecification("af", TranslatorMode.Builder.withGrade(1.0).build()), "afr-za-g1.ctb");
        specs.put(new TranslatorSpecification("ar", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "ar.tbl");
        specs.put(new TranslatorSpecification("ar", TranslatorMode.Builder.withGrade(1.0).build()), "ar.tbl");
        specs.put(new TranslatorSpecification("ar", TranslatorMode.Builder.withType(TranslatorType.CONTRACTED).build()), "ar-ar-g2.ctb");
        specs.put(new TranslatorSpecification("ar", TranslatorMode.Builder.withGrade(2.0).build()), "ar-ar-g2.ctb");
        specs.put(new TranslatorSpecification("as", TranslatorMode.Builder.withGrade(1.0).build()), "as.tbl");
        specs.put(new TranslatorSpecification("awa", TranslatorMode.Builder.withGrade(1.0).build()), "awa.tbl");
        specs.put(new TranslatorSpecification("bn", TranslatorMode.Builder.withGrade(1.0).build()), "bn.tbl");
        specs.put(new TranslatorSpecification("bra", TranslatorMode.Builder.withGrade(1.0).build()), "bra.tbl");
        specs.put(new TranslatorSpecification("ca", TranslatorMode.Builder.withGrade(1.0).build()), "ca.tbl");
        specs.put(new TranslatorSpecification("chr", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "chr-us-g1.ctb");
        specs.put(new TranslatorSpecification("chr", TranslatorMode.Builder.withGrade(1.0).build()), "chr-us-g1.ctb");
        specs.put(new TranslatorSpecification("ckb", TranslatorMode.Builder.withGrade(1.0).build()), "ckb.tbl");
        specs.put(new TranslatorSpecification("cs", TranslatorMode.Builder.withGrade(1.0).build()), "cs.tbl");
        specs.put(new TranslatorSpecification("cy", TranslatorMode.Builder.withType(TranslatorType.CONTRACTED).build()), "cy.tbl");
        specs.put(new TranslatorSpecification("cy", TranslatorMode.Builder.withGrade(2.0).build()), "cy.tbl");
        specs.put(new TranslatorSpecification("cy", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "cy-cy-g1.utb");
        specs.put(new TranslatorSpecification("cy", TranslatorMode.Builder.withGrade(1.0).build()), "cy-cy-g1.utb");
        specs.put(new TranslatorSpecification("da", TranslatorMode.Builder.withType(TranslatorType.CONTRACTED).build()), "da-dk-g26-lit.ctb");
        specs.put(new TranslatorSpecification("da", TranslatorMode.Builder.withGrade(2.0).build()), "da-dk-g26-lit.ctb");
        specs.put(new TranslatorSpecification("da", TranslatorMode.Builder.withGrade(1.5).build()), "da-dk-g26l-lit.ctb");
        specs.put(new TranslatorSpecification("da", TranslatorMode.Builder.withType(TranslatorType.CONTRACTED).dotsPerCell(DotsPerCell.EIGHT).build()), "da-dk-g28.ctb");
        specs.put(new TranslatorSpecification("da", TranslatorMode.Builder.withGrade(2.0).dotsPerCell(DotsPerCell.EIGHT).build()), "da-dk-g28.ctb");
        specs.put(new TranslatorSpecification("da", TranslatorMode.Builder.withType(TranslatorType.CONTRACTED).build()), "da-dk-g26.ctb");
        specs.put(new TranslatorSpecification("da", TranslatorMode.Builder.withGrade(2.0).build()), "da-dk-g26.ctb");
        specs.put(new TranslatorSpecification("da", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "da-dk-g16-lit.ctb");
        specs.put(new TranslatorSpecification("da", TranslatorMode.Builder.withGrade(1.0).build()), "da-dk-g16-lit.ctb");
        specs.put(new TranslatorSpecification("da", TranslatorMode.Builder.withGrade(1.5).dotsPerCell(DotsPerCell.EIGHT).build()), "da-dk-g28l.ctb");
        specs.put(new TranslatorSpecification("da", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "da-dk-g16.ctb");
        specs.put(new TranslatorSpecification("da", TranslatorMode.Builder.withGrade(1.0).build()), "da-dk-g16.ctb");
        specs.put(new TranslatorSpecification("da", TranslatorMode.Builder.withGrade(1.5).build()), "da-dk-g26l.ctb");
        specs.put(new TranslatorSpecification("da", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).dotsPerCell(DotsPerCell.EIGHT).build()), "da-dk-g18.ctb");
        specs.put(new TranslatorSpecification("da", TranslatorMode.Builder.withGrade(1.0).dotsPerCell(DotsPerCell.EIGHT).build()), "da-dk-g18.ctb");
        specs.put(new TranslatorSpecification("de", TranslatorMode.Builder.withGrade(1.0).build()), "de-g1.ctb");
        specs.put(new TranslatorSpecification("de", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "de-g0.utb");
        specs.put(new TranslatorSpecification("de", TranslatorMode.Builder.withGrade(0.0).build()), "de-g0.utb");
        specs.put(new TranslatorSpecification("de", TranslatorMode.Builder.withType(TranslatorType.CONTRACTED).build()), "de-g2.ctb");
        specs.put(new TranslatorSpecification("de", TranslatorMode.Builder.withGrade(2.0).build()), "de-g2.ctb");
        specs.put(new TranslatorSpecification("el", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "el.tbl");
        specs.put(new TranslatorSpecification("en", TranslatorMode.Builder.withType(TranslatorType.CONTRACTED).build()), "en-ueb-g2.ctb");
        specs.put(new TranslatorSpecification("en", TranslatorMode.Builder.withGrade(2.0).build()), "en-ueb-g2.ctb");
        specs.put(new TranslatorSpecification("en", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "en-ueb-g1.ctb");
        specs.put(new TranslatorSpecification("en", TranslatorMode.Builder.withGrade(1.0).build()), "en-ueb-g1.ctb");
        specs.put(new TranslatorSpecification("en-GB", TranslatorMode.Builder.withType(TranslatorType.CONTRACTED).build()), "en_GB.tbl");
        specs.put(new TranslatorSpecification("en-GB", TranslatorMode.Builder.withGrade(2.0).build()), "en_GB.tbl");
        specs.put(new TranslatorSpecification("en-GB", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "en-gb-g1.utb");
        specs.put(new TranslatorSpecification("en-GB", TranslatorMode.Builder.withGrade(1.0).build()), "en-gb-g1.utb");
        specs.put(new TranslatorSpecification("en-US", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "en-us-g1.ctb");
        specs.put(new TranslatorSpecification("en-US", TranslatorMode.Builder.withGrade(1.0).build()), "en-us-g1.ctb");
        specs.put(new TranslatorSpecification("en-US", TranslatorMode.Builder.withType(TranslatorType.CONTRACTED).build()), "en_US.tbl");
        specs.put(new TranslatorSpecification("en-US", TranslatorMode.Builder.withGrade(2.0).build()), "en_US.tbl");
        specs.put(new TranslatorSpecification("eo", TranslatorMode.Builder.withGrade(1.0).build()), "eo.tbl");
        specs.put(new TranslatorSpecification("eo-xsistemo", TranslatorMode.Builder.withGrade(1.0).build()), "eo-g1-x-system.ctb");
        specs.put(new TranslatorSpecification("es", TranslatorMode.Builder.withType(TranslatorType.CONTRACTED).build()), "es-g2.ctb");
        specs.put(new TranslatorSpecification("es", TranslatorMode.Builder.withGrade(2.0).build()), "es-g2.ctb");
        specs.put(new TranslatorSpecification("es", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "es.tbl");
        specs.put(new TranslatorSpecification("es", TranslatorMode.Builder.withGrade(1.0).build()), "es.tbl");
        specs.put(new TranslatorSpecification("fa", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "fa-ir-g1.utb");
        specs.put(new TranslatorSpecification("fa", TranslatorMode.Builder.withGrade(1.0).build()), "fa-ir-g1.utb");
        specs.put(new TranslatorSpecification("fi", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "fi.utb");
        specs.put(new TranslatorSpecification("fr", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "fr-bfu-comp6.utb");
        specs.put(new TranslatorSpecification("fr", TranslatorMode.Builder.withType(TranslatorType.CONTRACTED).build()), "fr-bfu-g2.ctb");
        specs.put(new TranslatorSpecification("fr", TranslatorMode.Builder.withGrade(2.0).build()), "fr-bfu-g2.ctb");
        specs.put(new TranslatorSpecification("ga", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "ga-g1.utb");
        specs.put(new TranslatorSpecification("ga", TranslatorMode.Builder.withGrade(1.0).build()), "ga-g1.utb");
        specs.put(new TranslatorSpecification("ga", TranslatorMode.Builder.withType(TranslatorType.CONTRACTED).build()), "ga.tbl");
        specs.put(new TranslatorSpecification("ga", TranslatorMode.Builder.withGrade(2.0).build()), "ga.tbl");
        specs.put(new TranslatorSpecification("gez", TranslatorMode.Builder.withGrade(1.0).build()), "gez.tbl");
        specs.put(new TranslatorSpecification("gu", TranslatorMode.Builder.withGrade(1.0).build()), "gu.tbl");
        specs.put(new TranslatorSpecification("haw", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "haw-us-g1.ctb");
        specs.put(new TranslatorSpecification("haw", TranslatorMode.Builder.withGrade(1.0).build()), "haw-us-g1.ctb");
        specs.put(new TranslatorSpecification("hi", TranslatorMode.Builder.withGrade(1.0).build()), "hi.tbl");
        specs.put(new TranslatorSpecification("hr", TranslatorMode.Builder.withGrade(1.0).build()), "hr-g1.tbl");
        specs.put(new TranslatorSpecification("hu", TranslatorMode.Builder.withType(TranslatorType.CONTRACTED).build()), "hu-hu-g2.ctb");
        specs.put(new TranslatorSpecification("hu", TranslatorMode.Builder.withGrade(2.0).build()), "hu-hu-g2.ctb");
        specs.put(new TranslatorSpecification("hu", TranslatorMode.Builder.withGrade(1.0).build()), "hu.tbl");
        specs.put(new TranslatorSpecification("iu", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "iu-ca-g1.ctb");
        specs.put(new TranslatorSpecification("iu", TranslatorMode.Builder.withGrade(1.0).build()), "iu-ca-g1.ctb");
        specs.put(new TranslatorSpecification("kha", TranslatorMode.Builder.withGrade(1.0).build()), "kha.tbl");
        specs.put(new TranslatorSpecification("kn", TranslatorMode.Builder.withGrade(1.0).build()), "kn.tbl");
        specs.put(new TranslatorSpecification("ko", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "ko-g1.ctb");
        specs.put(new TranslatorSpecification("ko", TranslatorMode.Builder.withGrade(1.0).build()), "ko-g1.ctb");
        specs.put(new TranslatorSpecification("ko", TranslatorMode.Builder.withType(TranslatorType.CONTRACTED).build()), "ko-2006-g2.ctb");
        specs.put(new TranslatorSpecification("ko", TranslatorMode.Builder.withGrade(2.0).build()), "ko-2006-g2.ctb");
        specs.put(new TranslatorSpecification("ko", TranslatorMode.Builder.withType(TranslatorType.CONTRACTED).build()), "ko-g2.ctb");
        specs.put(new TranslatorSpecification("ko", TranslatorMode.Builder.withGrade(2.0).build()), "ko-g2.ctb");
        specs.put(new TranslatorSpecification("ko", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "ko-2006-g1.ctb");
        specs.put(new TranslatorSpecification("ko", TranslatorMode.Builder.withGrade(1.0).build()), "ko-2006-g1.ctb");
        specs.put(new TranslatorSpecification("lt", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "lt-6dot.tbl");
        specs.put(new TranslatorSpecification("lv", TranslatorMode.Builder.withGrade(1.0).build()), "lv.tbl");
        specs.put(new TranslatorSpecification("mi", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "mao-nz-g1.ctb");
        specs.put(new TranslatorSpecification("mi", TranslatorMode.Builder.withGrade(1.0).build()), "mao-nz-g1.ctb");
        specs.put(new TranslatorSpecification("ml", TranslatorMode.Builder.withGrade(1.0).build()), "ml.tbl");
        specs.put(new TranslatorSpecification("mn", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).dotsPerCell(DotsPerCell.EIGHT).build()), "mn-MN-g1.utb");
        specs.put(new TranslatorSpecification("mn", TranslatorMode.Builder.withType(TranslatorType.CONTRACTED).dotsPerCell(DotsPerCell.EIGHT).build()), "mn-MN-g2.ctb");
        specs.put(new TranslatorSpecification("mni", TranslatorMode.Builder.withGrade(1.0).build()), "mni.tbl");
        specs.put(new TranslatorSpecification("mr", TranslatorMode.Builder.withGrade(1.0).build()), "mr.tbl");
        specs.put(new TranslatorSpecification("ne", TranslatorMode.Builder.withGrade(1.0).build()), "ne.tbl");
        specs.put(new TranslatorSpecification("nl", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "nl.tbl");
        specs.put(new TranslatorSpecification("nl", TranslatorMode.Builder.withGrade(0.0).build()), "nl.tbl");
        specs.put(new TranslatorSpecification("nl-BE", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "nl_BE.tbl");
        specs.put(new TranslatorSpecification("nl-BE", TranslatorMode.Builder.withGrade(0.0).build()), "nl_BE.tbl");
        specs.put(new TranslatorSpecification("no", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).dotsPerCell(DotsPerCell.EIGHT).build()), "no-no-8dot-fallback-6dot-g0.utb");
        specs.put(new TranslatorSpecification("no", TranslatorMode.Builder.withGrade(0.0).dotsPerCell(DotsPerCell.EIGHT).build()), "no-no-8dot-fallback-6dot-g0.utb");
        specs.put(new TranslatorSpecification("no", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "no-no-g0.utb");
        specs.put(new TranslatorSpecification("no", TranslatorMode.Builder.withGrade(0.0).build()), "no-no-g0.utb");
        specs.put(new TranslatorSpecification("no", TranslatorMode.Builder.withGrade(1.0).build()), "no-no-g1.ctb");
        specs.put(new TranslatorSpecification("no", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).dotsPerCell(DotsPerCell.EIGHT).build()), "no-no-8dot.utb");
        specs.put(new TranslatorSpecification("no", TranslatorMode.Builder.withGrade(0.0).dotsPerCell(DotsPerCell.EIGHT).build()), "no-no-8dot.utb");
        specs.put(new TranslatorSpecification("no", TranslatorMode.Builder.withType(TranslatorType.CONTRACTED).build()), "no.tbl");
        specs.put(new TranslatorSpecification("no", TranslatorMode.Builder.withGrade(3.0).build()), "no.tbl");
        specs.put(new TranslatorSpecification("no", TranslatorMode.Builder.withGrade(2.0).build()), "no-no-g2.ctb");
        specs.put(new TranslatorSpecification("or", TranslatorMode.Builder.withGrade(1.0).build()), "or.tbl");
        specs.put(new TranslatorSpecification("pa", TranslatorMode.Builder.withGrade(1.0).build()), "pa.tbl");
        specs.put(new TranslatorSpecification("pl", TranslatorMode.Builder.withGrade(1.0).build()), "pl.tbl");
        specs.put(new TranslatorSpecification("pt", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "pt-pt-g1.utb");
        specs.put(new TranslatorSpecification("pt", TranslatorMode.Builder.withGrade(1.0).build()), "pt-pt-g1.utb");
        specs.put(new TranslatorSpecification("pt", TranslatorMode.Builder.withType(TranslatorType.CONTRACTED).build()), "pt.tbl");
        specs.put(new TranslatorSpecification("pt", TranslatorMode.Builder.withGrade(2.0).build()), "pt.tbl");
        specs.put(new TranslatorSpecification("ru", TranslatorMode.Builder.withGrade(1.0).build()), "ru.tbl");
        specs.put(new TranslatorSpecification("sa", TranslatorMode.Builder.withGrade(1.0).build()), "sa.tbl");
        specs.put(new TranslatorSpecification("sd", TranslatorMode.Builder.withGrade(1.0).build()), "sd.tbl");
        specs.put(new TranslatorSpecification("sk", TranslatorMode.Builder.withGrade(1.0).build()), "sk.tbl");
        specs.put(new TranslatorSpecification("sl", TranslatorMode.Builder.withGrade(1.0).build()), "sl.tbl");
        specs.put(new TranslatorSpecification("sr", TranslatorMode.Builder.withGrade(1.0).build()), "sr.tbl");
        specs.put(new TranslatorSpecification("ta", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "ta-ta-g1.ctb");
        specs.put(new TranslatorSpecification("ta", TranslatorMode.Builder.withGrade(1.0).build()), "ta-ta-g1.ctb");
        specs.put(new TranslatorSpecification("te", TranslatorMode.Builder.withGrade(1.0).build()), "te.tbl");
        specs.put(new TranslatorSpecification("tr", TranslatorMode.Builder.withType(TranslatorType.CONTRACTED).dotsPerCell(DotsPerCell.EIGHT).build()), "tr-g2.tbl");
        specs.put(new TranslatorSpecification("tr", TranslatorMode.Builder.withGrade(2.0).dotsPerCell(DotsPerCell.EIGHT).build()), "tr-g2.tbl");
        specs.put(new TranslatorSpecification("ur", TranslatorMode.Builder.withType(TranslatorType.UNCONTRACTED).build()), "ur-pk-g1.utb");
        specs.put(new TranslatorSpecification("ur", TranslatorMode.Builder.withGrade(1.0).build()), "ur-pk-g1.utb");
        specs.put(new TranslatorSpecification("ur", TranslatorMode.Builder.withType(TranslatorType.CONTRACTED).build()), "ur-pk-g2.ctb");
        specs.put(new TranslatorSpecification("ur", TranslatorMode.Builder.withGrade(2.0).build()), "ur-pk-g2.ctb");
        specs.put(new TranslatorSpecification("vi", TranslatorMode.Builder.withGrade(1.0).build()), "vi.tbl");
    }

    static Map<TranslatorSpecification, String> getMap() {
        return INSTANCE.specs;
    }

}
