assembly/.test assembly/.install $(TARGET_DIR)/state/assembly/modified-since-release_ : \
	assembly/src/main/docker/logback.xml \
	assembly/src/main/docker/Dockerfile \
	assembly/src/main/assembly/dist-mac.properties \
	assembly/src/main/assembly/dist-win.properties \
	assembly/src/main/assembly/dist-linux.xml \
	assembly/src/main/assembly/dist-mac.xml \
	assembly/src/main/assembly/components/jars-mac.xml \
	assembly/src/main/assembly/components/jars-win.xml \
	assembly/src/main/assembly/components/cli-linux.xml \
	assembly/src/main/assembly/components/jre-win64.xml \
	assembly/src/main/assembly/components/simple-api.xml \
	assembly/src/main/assembly/components/bin-win.xml \
	assembly/src/main/assembly/components/cli-win.xml \
	assembly/src/main/assembly/components/bin-linux.xml \
	assembly/src/main/assembly/components/base.xml \
	assembly/src/main/assembly/components/bin-mac.xml \
	assembly/src/main/assembly/components/jars-linux.xml \
	assembly/src/main/assembly/components/cli-mac.xml \
	assembly/src/main/assembly/components/jre-win32.xml \
	assembly/src/main/assembly/components/jre-mac.xml \
	assembly/src/main/assembly/components/jars.xml \
	assembly/src/main/assembly/components/jre-win.xml \
	assembly/src/main/assembly/dist-deb.properties \
	assembly/src/main/assembly/dist-win.xml \
	assembly/src/main/assembly/dist.properties \
	assembly/src/main/assembly/dist-linux.properties \
	assembly/src/main/resources/bin/pipeline2.bat \
	assembly/src/main/resources/bin/checkJavaVersion.bat \
	assembly/src/main/resources/bin/pipeline2 \
	assembly/src/main/resources/etc/logback.xml \
	assembly/src/main/resources/etc/logging.properties \
	assembly/src/main/resources/etc/felix.properties \
	assembly/src/main/resources/etc/pipeline.properties \
	assembly/src/main/resources/etc/org.apache.felix.fileinstall-modules.cfg \
	assembly/src/main/resources/cli/config.yml \
	assembly/src/main/resources/NOTICE.txt \
	assembly/src/main/resources/README.txt \
	assembly/src/main/java/SimpleAPI.java \
	assembly/src/main/deb/DEBIAN/prerm \
	assembly/src/main/deb/DEBIAN/conffiles \
	assembly/src/main/deb/DEBIAN/preinst \
	assembly/src/main/deb/DEBIAN/postinst \
	assembly/src/main/deb/DEBIAN/templates \
	assembly/src/main/deb/DEBIAN/copyright \
	assembly/src/main/deb/DEBIAN/postrm \
	assembly/src/main/deb/DEBIAN/control \
	assembly/src/main/deb/etc/init.d/daisy-pipeline2 \
	assembly/src/main/deb/etc/default/daisy-pipeline2 \
	assembly/src/main/deb/DEBIAN.cli/prerm \
	assembly/src/main/deb/DEBIAN.cli/preinst \
	assembly/src/main/deb/DEBIAN.cli/postinst \
	assembly/src/main/deb/DEBIAN.cli/templates \
	assembly/src/main/deb/DEBIAN.cli/postrm \
	assembly/src/main/deb/DEBIAN.cli/control \
	assembly/src/main/deb/opt/daisy-pipeline2/bin/debian.cfg \
	assembly/src/main/xslt/pom-to-release.xslt
assembly/.test : \
	assembly/src/test/xspec/pom-to-release.xspec \
	assembly/src/test/resources/test-docker-image.sh \
	assembly/src/test/resources/test-checkJavaVersion.sh \
	assembly/src/test/resources/effective-pom.xml \
	assembly/src/test/resources/test-checkJavaVersion.bat \
	assembly/src/test/resources/descriptor.xml
.make/mk/assembly/sources.mk : \
	assembly/src \
	assembly/src/test \
	assembly/src/test/xspec \
	assembly/src/test/resources \
	assembly/src/main \
	assembly/src/main/docker \
	assembly/src/main/assembly \
	assembly/src/main/assembly/components \
	assembly/src/main/resources \
	assembly/src/main/resources/bin \
	assembly/src/main/resources/etc \
	assembly/src/main/resources/cli \
	assembly/src/main/java \
	assembly/src/main/deb \
	assembly/src/main/deb/DEBIAN \
	assembly/src/main/deb/etc \
	assembly/src/main/deb/etc/init.d \
	assembly/src/main/deb/etc/default \
	assembly/src/main/deb/DEBIAN.cli \
	assembly/src/main/deb/opt \
	assembly/src/main/deb/opt/daisy-pipeline2 \
	assembly/src/main/deb/opt/daisy-pipeline2/bin \
	assembly/src/main/xslt
