modules/common/mediatype-utils/.test modules/common/mediatype-utils/.install modules/common/mediatype-utils/.install-doc $(TARGET_DIR)/state/modules/common/mediatype-utils/modified-since-release_ : \
	modules/common/mediatype-utils/src/main/resources/META-INF/catalog.xml \
	modules/common/mediatype-utils/src/main/resources/xml/maps/ns-to-mediatype.xml \
	modules/common/mediatype-utils/src/main/resources/xml/maps/ext-to-mediatype.xml \
	modules/common/mediatype-utils/src/main/resources/xml/xproc/mediatype.xpl \
	modules/common/mediatype-utils/src/main/resources/xml/xproc/library.xpl \
	modules/common/mediatype-utils/src/main/resources/xml/xslt/mediatype-functions.xsl
modules/common/mediatype-utils/.test modules/common/mediatype-utils/.install-doc : \
	modules/common/mediatype-utils/src/test/xspec/mediatype-functions.xspec \
	modules/common/mediatype-utils/src/test/resources/test-mediatype-detect.xpl \
	modules/common/mediatype-utils/src/test/resources/test.xpl \
	modules/common/mediatype-utils/src/test/resources/compare.xpl \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/porrasturvat-1.0.3.tar.gz \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/plaintext \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/magic.mime \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/a.zip \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/mime-types.properties \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/wrong-extensions/txt.xml \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/wrong-extensions/opf.txt \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/wrong-extensions/png.xml \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/wrong-extensions/html.bin \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/f.tar.gz \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/c.gif \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/b-jpg.img \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/afpfile.afp \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/META-INF/MANIFEST.MF \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/a/MimeDetector.class \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/a/MimeDetector.java \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/a/f.tar.gz \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/a/resources/mime.cache \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/a/resources/eu/medsea/mimeutil/magic.mime \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/a/resources/eu/medsea/mimeutil/mime-types.properties \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/a/e.svg \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/a/e[xml] \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/a/c-gif.img \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/a/a.html \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/xml/ncx.xml \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/xml/container.xml \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/xml/package.xml \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/xml/XSLT.xml \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/xml/mqia0001.xml \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/xml/XProc.xml \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/xml/noFileExtension \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/xml/package.xml~ \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/xml/navigation.xml \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/epub.epub \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/e.svg \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/textfiles/western \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/textfiles/unicode \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/e[xml] \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/e-svg.img \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/test.bin \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/b.jpg \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/eu/medsea/mimeutil/MimeTypeTest.java \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/eu/medsea/mimeutil/util/EncodingGuesserTest.java \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/eu/medsea/mimeutil/MimeUtil2Test.java \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/eu/medsea/mimeutil/MimeUtilTest.java \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/eu/medsea/mimeutil/MimeTypeHashSetTest.java \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/eu/medsea/mimeutil/detector/MagicMimeMimeDetectorTest.java \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/eu/medsea/mimeutil/detector/OpendesktopMimeDetectorTest.java \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/eu/medsea/mimeutil/detector/TextMimeDetectorTest.java \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/eu/medsea/mimeutil/detector/WindowsRegistryMimeDetectorTest.java \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/d.png \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/plaintext.txt \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/d-png.img \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/c-gif.img \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/e.xml \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/epub/Publication/ncx.xml \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/epub/Publication/Content/mqia0001.xhtml \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/epub/Publication/Content/tjcs0000.jpg \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/epub/Publication/Content/mqia0001.smil \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/epub/Publication/Content/1_Jamen__Benny.mp3 \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/epub/Publication/Content/41077stor.jpg \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/epub/Publication/navigation.xhtml \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/epub/Publication/package.opf \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/epub/META-INF/container.xml \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/epub/mimetype \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/log4j.properties \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/a.html
.make/mk/modules/common/mediatype-utils/sources.mk : \
	modules/common/mediatype-utils/src \
	modules/common/mediatype-utils/src/test \
	modules/common/mediatype-utils/src/test/xspec \
	modules/common/mediatype-utils/src/test/resources \
	modules/common/mediatype-utils/src/test/resources/samples \
	modules/common/mediatype-utils/src/test/resources/samples/fileset \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/wrong-extensions \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/META-INF \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/a \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/a/resources \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/a/resources/eu \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/a/resources/eu/medsea \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/a/resources/eu/medsea/mimeutil \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/xml \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/textfiles \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/eu \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/eu/medsea \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/eu/medsea/mimeutil \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/eu/medsea/mimeutil/util \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/eu/medsea/mimeutil/detector \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/epub \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/epub/Publication \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/epub/Publication/Content \
	modules/common/mediatype-utils/src/test/resources/samples/fileset/epub/META-INF \
	modules/common/mediatype-utils/src/main \
	modules/common/mediatype-utils/src/main/resources \
	modules/common/mediatype-utils/src/main/resources/META-INF \
	modules/common/mediatype-utils/src/main/resources/xml \
	modules/common/mediatype-utils/src/main/resources/xml/maps \
	modules/common/mediatype-utils/src/main/resources/xml/xproc \
	modules/common/mediatype-utils/src/main/resources/xml/xslt
