utils/xprocspec/.test utils/xprocspec/.install utils/xprocspec/.install-doc $(TARGET_DIR)/state/utils/xprocspec/modified-since-release_ : \
	utils/xprocspec/src/main/resources/expath-pkg.xml \
	utils/xprocspec/src/main/resources/content/xml/xproc/preprocess/explicit-type-namespace.xsl \
	utils/xprocspec/src/main/resources/content/xml/xproc/preprocess/infer-scenarios.xsl \
	utils/xprocspec/src/main/resources/content/xml/xproc/preprocess/infer-primary-ports.xsl \
	utils/xprocspec/src/main/resources/content/xml/xproc/preprocess/xprocTestSuite-to-xprocspec.xsl \
	utils/xprocspec/src/main/resources/content/xml/xproc/preprocess/preprocess.xpl \
	utils/xprocspec/src/main/resources/content/xml/xproc/utils/validate-with-relax-ng.xpl \
	utils/xprocspec/src/main/resources/content/xml/xproc/utils/error.xpl \
	utils/xprocspec/src/main/resources/content/xml/xproc/utils/assert.xpl \
	utils/xprocspec/src/main/resources/content/xml/xproc/utils/recursive-directory-list.xpl \
	utils/xprocspec/src/main/resources/content/xml/xproc/utils/document-to-select-xslt.xsl \
	utils/xprocspec/src/main/resources/content/xml/xproc/utils/message.xpl \
	utils/xprocspec/src/main/resources/content/xml/xproc/utils/namespace-fixup.xsl \
	utils/xprocspec/src/main/resources/content/xml/xproc/utils/logging-library.xpl \
	utils/xprocspec/src/main/resources/content/xml/xproc/utils/log.xpl \
	utils/xprocspec/src/main/resources/content/xml/xproc/utils/load.xpl \
	utils/xprocspec/src/main/resources/content/xml/xproc/utils/sort-zip-entries.xsl \
	utils/xprocspec/src/main/resources/content/xml/xproc/utils/document.xpl \
	utils/xprocspec/src/main/resources/content/xml/xproc/utils/html-load.xpl \
	utils/xprocspec/src/main/resources/content/xml/xproc/evaluate/group-assertions-with-context.xsl \
	utils/xprocspec/src/main/resources/content/xml/xproc/evaluate/compare.xpl \
	utils/xprocspec/src/main/resources/content/xml/xproc/evaluate/assertion-to-xslt.xsl \
	utils/xprocspec/src/main/resources/content/xml/xproc/evaluate/expect-to-custom-invocation.xsl \
	utils/xprocspec/src/main/resources/content/xml/xproc/evaluate/format-test-result.xsl \
	utils/xprocspec/src/main/resources/content/xml/xproc/evaluate/evaluate.xpl \
	utils/xprocspec/src/main/resources/content/xml/xproc/evaluate/test-result.re-add-attributes.xsl \
	utils/xprocspec/src/main/resources/content/xml/xproc/compile/description-to-invocation.xsl \
	utils/xprocspec/src/main/resources/content/xml/xproc/compile/compile.xpl \
	utils/xprocspec/src/main/resources/content/xml/xproc/report/report-template.xhtml \
	utils/xprocspec/src/main/resources/content/xml/xproc/report/report-to-html.xsl \
	utils/xprocspec/src/main/resources/content/xml/xproc/report/report.xpl \
	utils/xprocspec/src/main/resources/content/xml/xproc/report/report-to-junit.xsl \
	utils/xprocspec/src/main/resources/content/xml/xproc/report/pretty-print.xsl \
	utils/xprocspec/src/main/resources/content/xml/xproc/xprocspec.xpl \
	utils/xprocspec/src/main/resources/content/xml/xproc/run/invocation-to-option-evaluation.xsl \
	utils/xprocspec/src/main/resources/content/xml/xproc/run/run.xpl \
	utils/xprocspec/src/main/resources/content/xml/schema/xprocspec.compile.rng \
	utils/xprocspec/src/main/resources/content/xml/schema/xprocspec.preprocess.rng \
	utils/xprocspec/src/main/resources/content/xml/schema/xprocspec.run.rng \
	utils/xprocspec/src/main/resources/content/xml/schema/xprocspec.results.rng \
	utils/xprocspec/src/main/resources/content/xml/schema/xprocspec.evaluate.rng \
	utils/xprocspec/src/main/resources/content/xml/schema/xprocspec.rng \
	utils/xprocspec/src/main/resources/META-INF/catalog.xml \
	utils/xprocspec/src/main/resources/cxan.xml
utils/xprocspec/.test utils/xprocspec/.install-doc : \
	utils/xprocspec/src/test/resources/logback.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/extension.xprocspec.pending \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization.xprocspec.pending \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/extension/unimpl-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/normalization-form-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/normalization-form-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/normalization-form-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/cdata-section-elements-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/cdata-section-elements-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/undeclare-prefixes-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/indent-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/indent-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/standalone-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/omit-xml-declaration-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/standalone-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/omit-xml-declaration-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/standalone-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/results/normalization-form-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/results/normalization-form-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/results/normalization-form-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/results/escape-uri-attributes-002.html \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/results/cdata-section-elements-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/results/cdata-section-elements-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/results/undeclare-prefixes-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/results/indent-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/results/indent-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/results/standalone-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/results/omit-xml-declaration-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/results/standalone-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/results/include-content-type-002.html \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/results/omit-xml-declaration-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/results/standalone-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/results/include-content-type-001.html \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/results/version-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/results/doctype-public-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/results/encoding-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/results/escape-uri-attributes-001.html \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/results/byte-order-mark-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/results/media-type-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/results/byte-order-mark-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/results/doctype-system-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/results/.htaccess \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/version-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/include-content-type-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/doctype-public-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/escape-uri-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/include-content-type-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/encoding-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/escape-uri-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/byte-order-mark-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/media-type-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/err-d0020-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/byte-order-mark-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/doctype-system-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespace-rename-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespace-rename-017.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/for-each-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0006-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/filter-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/string-replace-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0020-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/version-available-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/evaluation-order-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0034-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0034-013.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0004-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0022-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0005-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0015-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/xslt-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0013-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0003-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0052-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0029-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0039-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/param-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0058-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0048-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0034-012.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0034-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/evaluation-order-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0001-008.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/split-sequence-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/multipart-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/string-replace-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/unwrap-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0051-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/filter-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespace-rename-016.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/for-each-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespace-rename-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/for-each-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespace-rename-014.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/viewport-009.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/multipart-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/split-sequence-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/string-replace-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/compare-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/version-available-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0034-010.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0034-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0022-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/param-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0005-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0025-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/xslt-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/xslt-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0013-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0033-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0005-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0052-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0029-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/param-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0022-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0034-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0034-011.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0061-001.xpl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/evaluation-order-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/compare-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0030-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/unwrap-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/multipart-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0020-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/split-sequence-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0041-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0051-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/filter-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/viewport-008.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespace-rename-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespace-rename-015.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespace-rename-011.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/for-each-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/for-each-010.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespace-rename-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/split-sequence-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0020-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/string-replace-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/store-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/library-v2.xpl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0012-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0034-015.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0004-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0034-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0005-013.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0005-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/xslt-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/document-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0005-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0005-012.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0034-014.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0004-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0032-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0012-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0022-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0040-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/compare-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/iteration-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/try-001.xpl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/string-replace-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/split-sequence-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0020-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/for-each-011.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespace-rename-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespace-rename-010.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/for-each-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespace-rename-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/for-each-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespace-rename-012.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/multipart-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0020-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/split-sequence-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/compare-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/replace-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0017-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0022-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0014-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0034-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/make-sequence.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0004-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0034-016.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/variable-008.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/param-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0005-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0005-010.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/xslt-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0059-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0028-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/xslt-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0005-011.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0005-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/param-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0034-017.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0034-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0022-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0012-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/compare-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/iteration-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0020-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/multipart-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/split-sequence-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/for-each-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespace-rename-013.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespace-rename-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/for-each-012.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/set-attributes-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/group-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/insert-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0026-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/load-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespaces-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/add-attribute-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/choose-008.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0005-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/data-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/value-available-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/exclude-inline-prefixes-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/input-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/input-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/value-available-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/versioning-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0023-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0042-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/data-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0052-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/step-available-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0009-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0039-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0019-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/system-property-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0020-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0030-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/load-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0051-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/set-attributes-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/pipeline-imported.xpl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/group-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0006-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0026-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/insert-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0020-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespaces-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/library-imported.xpl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/identity-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/add-attribute-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/data-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/step-available-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0005-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/value-available-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0023-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/versioning-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/exclude-inline-prefixes-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/input-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/exclude-inline-prefixes-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0023-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/versioning-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/step-available-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0052-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/data-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0019-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0039-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/add-attribute-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0009-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0029-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0058-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/identity-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/system-property-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespaces-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0010-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/load-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0020-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/insert-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0026-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/group-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/xml-id-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/import-009.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespaces-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/insert-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/ebv-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/wrap-009.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0017-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0007-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0004-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0014-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/add-attribute-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/value-available-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/versioning-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0023-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/data-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/step-available-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/input-011.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/exclude-inline-prefixes-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/input-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0059-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/input-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/exclude-inline-prefixes-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0028-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0038-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/xpath-version-available-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/input-010.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/data-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/versioning-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0023-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/value-available-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/log-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/add-attribute-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/escape-markup-001.xpl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/identity-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/wrap-008.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0001-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0031-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0011-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/insert-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/load-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespaces-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/import-008.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/xml-id-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespaces-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespaces-010.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/insert-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0026-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/insert-010.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/ebv-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0011-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0007-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0027-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/identity-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0014-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/add-attribute-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/http-request-009.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0023-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/versioning-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/step-available-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/data-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/labelelements-009.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0023-009.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/exclude-inline-prefixes-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/input-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/input-012.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/declare-step-009.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/exclude-inline-prefixes-010.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/library-missing-version.xpl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0059-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0018-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0038-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/declare-step-008.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/xpath-version-available-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0023-008.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0008-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0028-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/input-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/exclude-inline-prefixes-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/labelelements-008.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/step-available-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/value-available-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0023-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/versioning-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/log-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/http-request-008.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/add-attribute-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0053-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0022-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/identity-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0040-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0050-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0007-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0011-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0031-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0001-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0026-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/insert-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespaces-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/import-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/count-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespaces-008.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/insert-008.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0027-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/try-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/wrap-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/wrap-sequence-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/choose-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0024-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/http-request-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/http-request-011.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0014-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0034-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0023-009.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/labelelements-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/labelelements-011.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/declare-step-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0023-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/declare-step-011.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/exclude-inline-prefixes-008.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0025-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0023-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/exclude-inline-prefixes-009.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/declare-step-010.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/declare-step-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/labelelements-010.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/labelelements-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0023-008.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/http-request-010.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/http-request-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0002-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0022-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/parameters-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/wrap-sequence-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/wrap-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/try-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/insert-009.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespaces-009.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/count-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/import-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/import-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/import-011.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0027-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-primary-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/wrap-011.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/wrap-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/atomic-imported.xpl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/parameters-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/choose-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0034-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0014-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/http-request-012.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0024-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0004-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/http-request-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/labelelements-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/input-009.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0023-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/declare-step-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/declare-step-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/pipeline-no-type.xpl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/input-008.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0003-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0023-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/labelelements-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/http-request-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/fibonacci.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/pipeinfo-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/http-request-013.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0002-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/choose-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/parameters-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/wrap-sequence-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/wrap-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/wrap-010.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/try-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0027-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/import-010.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/count-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/import-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0057-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/try-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/sink-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/wrap-sequence-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/http-request-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/choose-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/resolve-uri-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/labelelements-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0005-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0025-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0015-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0035-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0023-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/declare-step-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/declare-step-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0033-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0003-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0023-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0062-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0025-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/labelelements-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/choose-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/http-request-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/preserve-base-uri-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/wrap-sequence-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/wrap-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/try-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/nested-pipeline-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0010-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0061-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/import-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/count-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/import-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0057-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/try-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/sink-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/wrap-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/http-request-014.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/resolve-uri-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/choose-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/data-008.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0035-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0025-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0023-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0003-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/declare-step-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0033-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/labelelements-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/choose-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/http-request-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/preserve-base-uri-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0019-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/wrap-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/sink-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0010-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/import-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/viewport-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/unescapemarkup-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0056-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/insert-004.xpl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/make-absolute-uris-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0037-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0007-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/xinclude-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0055-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/variable-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/option-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0018-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0005-008.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/rename-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/add-xml-base-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/rename-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0005-009.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0028-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0018-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0063-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0012-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/variable-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0002-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/xinclude-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0037-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0001-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0021-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/make-absolute-uris-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/pack-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0011-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0031-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/unescapemarkup-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/viewport-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespace-rename-009.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/for-each-008.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0036-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0056-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0001-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/unescapemarkup-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0011-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/pack-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0027-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0007-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0037-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0009-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/variable-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/option-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0055-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0028-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/delete-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/rename-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/add-xml-base-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/escape-markup-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/add-xml-base-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/rename-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/use-when-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0018-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/delete-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0028-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0008-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/variable-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0034-018.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0009-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0007-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/pack-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0031-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0011-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/unescapemarkup-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/make-absolute-uris-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0021-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0001-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0036-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/for-each-009.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/viewport-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/namespace-rename-008.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0016-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0036-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0026-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0010-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/viewport-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/viewport-011.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/directory-list-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/insert-002.xpl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0001-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/pack-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/xinclude-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0034-008.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/error-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/variable-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/base-uri-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0025-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/add-xml-base-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/rename-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0044-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/rename-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/output-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0003-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0062-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/delete-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/use-when-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/variable-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/error-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0009-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0029-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0019-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0034-009.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/xinclude-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/unescapemarkup-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0001-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/insert-003.xpl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0020-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/viewport-010.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/viewport-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/library.xpl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0010-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0030-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0026-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0006-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0036-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0016-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/directory-list-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/viewport-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0007-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0001-011.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/unescapemarkup-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/pack-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/insert-001.xpl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0001-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/xinclude-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/error-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/variable-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/option-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/use-when-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/base-uri-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/delete-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0025-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/add-xml-base-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0044-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0003-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/output-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-c0013-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0044-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/rename-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/add-xml-base-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0062-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0028-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/delete-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/base-uri-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/use-when-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0029-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0009-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0001-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0001-010.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/pack-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0011-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/unescapemarkup-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/viewport-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0030-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0010-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-d0020-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/err-s0036-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required/pipe-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/validrng-008.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/exec-016.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/exec-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/err-c0064-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/exec-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/exec-017.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/validrng-009.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/xslt2-002.xpl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/exec-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/exec-015.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/exec-014.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/uuid-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/err-c0053-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/exec-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/exec-010.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/exec-011.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/exec-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/err-c0053-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/err-c0053-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/exec-013.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/exec-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/exec-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/exec-012.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/err-c0053-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/template-017.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/template-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/validxsd-013.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/validxsd-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/err-c0033-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/validxsd-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/validxsd-012.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/template-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/template-016.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/validsch-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/validsch-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/template-014.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/validxsd-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/validxsd-010.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/validxsd-011.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/validxsd-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/template-015.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/template-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/www-form-urldecode-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/validsch-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/err-c0066-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/template-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/template-011.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/validxsd-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/in-scope-names-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/template-010.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/psvi-required-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/template-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/validsch-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/err-c0066-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/template-012.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/template-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/validxsd-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/in-scope-names-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/validxsd-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/template-007.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/template-013.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/validsch-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/err-c0036-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/hash-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/err-c0037-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/err-c0063-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/xsl-formatter-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/hash-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/err-c0036-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/err-c0037-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/template-009.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/err-c0063-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/template-008.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/err-c0037-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/hash-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/err-c0036-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/hash-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/template-018.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/www-form-urlencode-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/validxsd-008.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/xslt2-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/xslt2-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/validxsd-009.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/hash-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/err-c0036-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/err-c0036-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/hash-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/xslt2-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/err-c0054-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/xquery.xq \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/xquery-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/xinclude-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/validrng-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/xinclude-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/err-c0060-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/xquery-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/validrng-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/exec-008.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/err-c0034-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/exec-009.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/validrng-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/xinclude-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/xquery-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/err-c0057-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/xinclude-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/err-c0035-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/validrng-006.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/xinclude-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/xquery-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/xquery-003.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/xinclude-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/validrng-004.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/err-c0035-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/validrng-005.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/xquery-002.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional/err-c0061-001.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc.xprocspec.pending \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/lib/pipeline.xpl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/lib/pipeline2.xpl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/lib/l2.xpl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/lib/externalxml.xpl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/lib/l3.xpl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/lib/l1.xpl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/lib/l4.xpl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/lib/l5.xpl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/lib/l6.xpl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/lib/exclude-inline-prefixes.xpl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/lib/l1a.xpl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/lib/.htaccess \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/pqhref.xsd \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/xhtml-ct.html \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/non-well-formed.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/xinclude/input-xinclude-recursive-2.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/xinclude/para.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/document.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/document.rnc \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/xml-base-test.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/xpath-xinclude-doc.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/compoundEntity.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/document-attr.xsd \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/envelope.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/input-xinclude.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/document-ns.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/directory-list-test/adir/cfile \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/directory-list-test/bfile \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/directory-list-test/afile \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/envelope.fo \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/xml-base-chap.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/html-utf8.data \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/input-xinclude-loop-source.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/address-valid-sample.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/nfc-input.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/s-input.dtd \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/compoundDoc.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/input-cs.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/document-ns.xsd \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/s-input.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/input-xinclude-recursive-1.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/document2.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/envelope.xsl \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/invalid.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/s-input2.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/xidoc.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/textdata-utf8.txt \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/address-nonexistent-dtd.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/docbook-valid.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/xml11.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/address.dtd \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/pqhref.rnc \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/chaps/div.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/chaps/div2.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/windows-1252.txt \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/divs/div.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/divs/p.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/document.xsd \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/nfkc-input.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/address-invalid-sample.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/input.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/xmldata.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/input-en-cs.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/docbook-phases.sch \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/nfkd-input.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/xhtml.html \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/textdata-utf8.data \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/docbook-invalid.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/input-xinclude-loop-target.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/input-en.xml \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/docbook.sch \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/.htaccess \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional.xprocspec.pending \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required.xprocspec.pending \
	utils/xprocspec/src/test/xprocspec/tests/expect-1.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/document-3.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/import-1.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/call-3.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/input-1.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/call-4.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/scenario-2.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/param-1.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/import-1b.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/description-1.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/document-2.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/call-2.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/document-1.resources/html5.html \
	utils/xprocspec/src/test/xprocspec/tests/document-1.resources/recursive2/file21 \
	utils/xprocspec/src/test/xprocspec/tests/document-1.resources/xml.xml \
	utils/xprocspec/src/test/xprocspec/tests/document-1.resources/xhtml5.html \
	utils/xprocspec/src/test/xprocspec/tests/document-1.resources/recursive1/file2 \
	utils/xprocspec/src/test/xprocspec/tests/document-1.resources/recursive1/recursive11/file11 \
	utils/xprocspec/src/test/xprocspec/tests/document-1.resources/recursive1/recursive11/file12 \
	utils/xprocspec/src/test/xprocspec/tests/document-1.resources/recursive1/recursive11/file13 \
	utils/xprocspec/src/test/xprocspec/tests/document-1.resources/recursive1/file1 \
	utils/xprocspec/src/test/xprocspec/tests/document-1.resources/recursive1/recursive12/file21 \
	utils/xprocspec/src/test/xprocspec/tests/document-1.resources/text.txt \
	utils/xprocspec/src/test/xprocspec/tests/document-1.resources/image.png \
	utils/xprocspec/src/test/xprocspec/tests/import-2a.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/script-2.resources/script-2.xprocspec.skip-ci \
	utils/xprocspec/src/test/xprocspec/tests/script-1.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/import-1a.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/scenario-1.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/import-2b.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/regression-tests/regression-2.resources/invalid-xproc-script.xpl \
	utils/xprocspec/src/test/xprocspec/tests/regression-tests/regression-2.resources/invalid-xprocspec.xprocspec.skip-ci \
	utils/xprocspec/src/test/xprocspec/tests/regression-tests/regression-2.resources/valid-test-referring-to-invalid-XProc.xprocspec.skip-ci \
	utils/xprocspec/src/test/xprocspec/tests/regression-tests/regression-1_attributes-on-inline-document-should-not-be-deleted.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/regression-tests/regression-2_invalid-documents.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/regression-tests/issue-9_specifying-primary-parameter-port-generates-duplicate-ports.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/regression-tests/issue-4_temp-dir-option.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/regression-tests/issue-31_ports-with-no-results-give-a-port-not-found-warning.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/regression-tests/regression-1_attributes-from-foreign-namespaces-on-xproc-elements.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/call-1.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/document-1.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/import-3.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/script-2.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/documentation-1.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/pending-1.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/import-3a.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/context-1.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/document-3.resources/document-3.xprocspec.skip-ci \
	utils/xprocspec/src/test/xprocspec/tests/import-2.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/option-1.xprocspec \
	utils/xprocspec/src/test/xprocspec/tests/input-2.xprocspec \
	utils/xprocspec/src/test/xprocspec/steps/identity.xpl \
	utils/xprocspec/src/test/xprocspec/steps/identity-library-import.xpl \
	utils/xprocspec/src/test/xprocspec/steps/identity-library.xpl \
	utils/xprocspec/src/test/xprocspec/steps/error.xpl \
	utils/xprocspec/src/test/xprocspec/steps/identity-with-foreign-namespace.xpl \
	utils/xprocspec/src/test/xprocspec/steps/temp-dir-option.xpl \
	utils/xprocspec/src/test/xprocspec/steps/pipx.xpl \
	utils/xprocspec/src/test/xprocspec/steps/custom-count.xpl
.make/mk/utils/xprocspec/sources.mk : \
	utils/xprocspec/src \
	utils/xprocspec/src/test \
	utils/xprocspec/src/test/resources \
	utils/xprocspec/src/test/xprocspec \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/extension \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/serialization/results \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/required \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/optional \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/lib \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/xinclude \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/directory-list-test \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/directory-list-test/adir \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/chaps \
	utils/xprocspec/src/test/xprocspec/xproc-test-suite/doc/divs \
	utils/xprocspec/src/test/xprocspec/tests \
	utils/xprocspec/src/test/xprocspec/tests/document-1.resources \
	utils/xprocspec/src/test/xprocspec/tests/document-1.resources/recursive2 \
	utils/xprocspec/src/test/xprocspec/tests/document-1.resources/recursive1 \
	utils/xprocspec/src/test/xprocspec/tests/document-1.resources/recursive1/recursive11 \
	utils/xprocspec/src/test/xprocspec/tests/document-1.resources/recursive1/recursive12 \
	utils/xprocspec/src/test/xprocspec/tests/script-2.resources \
	utils/xprocspec/src/test/xprocspec/tests/regression-tests \
	utils/xprocspec/src/test/xprocspec/tests/regression-tests/regression-2.resources \
	utils/xprocspec/src/test/xprocspec/tests/document-3.resources \
	utils/xprocspec/src/test/xprocspec/steps \
	utils/xprocspec/src/main \
	utils/xprocspec/src/main/resources \
	utils/xprocspec/src/main/resources/content \
	utils/xprocspec/src/main/resources/content/xml \
	utils/xprocspec/src/main/resources/content/xml/xproc \
	utils/xprocspec/src/main/resources/content/xml/xproc/preprocess \
	utils/xprocspec/src/main/resources/content/xml/xproc/utils \
	utils/xprocspec/src/main/resources/content/xml/xproc/evaluate \
	utils/xprocspec/src/main/resources/content/xml/xproc/compile \
	utils/xprocspec/src/main/resources/content/xml/xproc/report \
	utils/xprocspec/src/main/resources/content/xml/xproc/run \
	utils/xprocspec/src/main/resources/content/xml/schema \
	utils/xprocspec/src/main/resources/META-INF
