modules/scripts-utils/dtbook-utils/.test modules/scripts-utils/dtbook-utils/.install modules/scripts-utils/dtbook-utils/.install-doc $(TARGET_DIR)/state/modules/scripts-utils/dtbook-utils/modified-since-release_ : \
	modules/scripts-utils/dtbook-utils/src/main/resources/css/default-speech.scss \
	modules/scripts-utils/dtbook-utils/src/main/resources/META-INF/catalog.xml \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/validate-dtbook/dtbook-validator.store.xpl \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/validate-dtbook/schema/sch/dtbook.mathml.nimas.sch \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/validate-dtbook/schema/sch/dtbook.mathml.sch \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/validate-dtbook/schema/sch/mod/mathml-content-elements.sch \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/validate-dtbook/schema/rng/dtbook-2005-2.mathml-3.integration.rng \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/validate-dtbook/schema/rng/dtbook-2005-3.mathml-2.integration.rng \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/validate-dtbook/schema/rng/dtbook/dtbook-1.1.0.rng \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/validate-dtbook/schema/rng/dtbook/dtbook-2005-1.rng \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/validate-dtbook/schema/rng/dtbook/dtbook-2005-3.rng \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/validate-dtbook/schema/rng/dtbook/dtbook-2005-2.rng \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/validate-dtbook/schema/rng/dtbook-2005-2.mathml-2.integration.rng \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/validate-dtbook/schema/rng/dtbook-2005-3.mathml-3.integration.rng \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/validate-dtbook/schema/rng/mod/smilref-attr.rng \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/validate-dtbook/validate-dtbook.xpl \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/validate-dtbook/dtbook-validator.select-schema.xpl \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/validate-dtbook/dtbook-validator.check-images.xpl \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/validate-dtbook/dtbook-validator.script.xpl \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/break-detect/add-ids.xsl \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/break-detect/library.xpl \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/dtbook-update-links.xpl \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/dtbook-to-mods-meta.xpl \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/dtbook-update-links.xsl \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/dtbook-to-mods-meta.xsl \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/upgrade-dtbook/dtbook2005-2to3.xsl \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/upgrade-dtbook/dtbook2005-1to2.xsl \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/upgrade-dtbook/upgrade-dtbook.xpl \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/upgrade-dtbook/dtbook110to2005-1.xsl \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/dtbook-fileset.xsl \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/dtbook-load.xpl \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/dtd/dtbook-2005-1.dtd \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/dtd/dtbook-2005-2.dtd \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/dtd/dtbook-2005-3.dtd \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/dtd/dtbook110.dtd \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/merge-dtbook/merge-dtbook.xsl \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/merge-dtbook/merge-dtbook.xpl \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/dtbook-utils-library.xpl
modules/scripts-utils/dtbook-utils/.test modules/scripts-utils/dtbook-utils/.install-doc : \
	modules/scripts-utils/dtbook-utils/src/test/resources/logback.xml \
	modules/scripts-utils/dtbook-utils/src/test/resources/test6.css \
	modules/scripts-utils/dtbook-utils/src/test/resources/test7.css \
	modules/scripts-utils/dtbook-utils/src/test/resources/invalid-doctype.xml \
	modules/scripts-utils/dtbook-utils/src/test/resources/test5.css \
	modules/scripts-utils/dtbook-utils/src/test/resources/dtbook.2005.basic.css \
	modules/scripts-utils/dtbook-utils/src/test/resources/test4.css \
	modules/scripts-utils/dtbook-utils/src/test/resources/test1.css \
	modules/scripts-utils/dtbook-utils/src/test/resources/MathML_Sample2.xml \
	modules/scripts-utils/dtbook-utils/src/test/resources/dtbook110.xml \
	modules/scripts-utils/dtbook-utils/src/test/resources/test3.css \
	modules/scripts-utils/dtbook-utils/src/test/resources/test2.css \
	modules/scripts-utils/dtbook-utils/src/test/resources/lexicon.pls \
	modules/scripts-utils/dtbook-utils/src/test/resources/font.ttf \
	modules/scripts-utils/dtbook-utils/src/test/resources/test10.css \
	modules/scripts-utils/dtbook-utils/src/test/resources/nativemathml.xml \
	modules/scripts-utils/dtbook-utils/src/test/resources/test11.css \
	modules/scripts-utils/dtbook-utils/src/test/resources/style.css \
	modules/scripts-utils/dtbook-utils/src/test/resources/dtbook_valid_2005-3.xml \
	modules/scripts-utils/dtbook-utils/src/test/resources/valentin.jpg \
	modules/scripts-utils/dtbook-utils/src/test/resources/dtbook_valid_2005-2.xml \
	modules/scripts-utils/dtbook-utils/src/test/resources/dtbook_not_well_formed.xml \
	modules/scripts-utils/dtbook-utils/src/test/resources/hauy_valid.xml \
	modules/scripts-utils/dtbook-utils/src/test/resources/test9.css \
	modules/scripts-utils/dtbook-utils/src/test/resources/dtbook-with-stylesheets.xml \
	modules/scripts-utils/dtbook-utils/src/test/resources/test8.css \
	modules/scripts-utils/dtbook-utils/src/test/resources/image.png \
	modules/scripts-utils/dtbook-utils/src/test/java/XProcSpecTest.java \
	modules/scripts-utils/dtbook-utils/src/test/xprocspec/test_dtd_catalog.xprocspec \
	modules/scripts-utils/dtbook-utils/src/test/xprocspec/test_validate.xprocspec \
	modules/scripts-utils/dtbook-utils/src/test/xprocspec/test_dtbook-validator.script.xprocspec \
	modules/scripts-utils/dtbook-utils/src/test/xprocspec/test_dtbook-to-mods-meta.xprocspec \
	modules/scripts-utils/dtbook-utils/src/test/xprocspec/test_load.xprocspec \
	modules/scripts-utils/dtbook-utils/src/test/xprocspec/test_upgrade.xprocspec
modules/scripts-utils/dtbook-utils/.install-doc : \
	modules/scripts-utils/dtbook-utils/doc/dtbook-validator.md \
	modules/scripts-utils/dtbook-utils/doc/routines.md \
	modules/scripts-utils/dtbook-utils/doc/dtbook-validator-dev-notes.md \
	modules/scripts-utils/dtbook-utils/doc/index.md \
	modules/scripts-utils/dtbook-utils/doc/dtbook-cleaner.md
.make/mk/modules/scripts-utils/dtbook-utils/sources.mk : \
	modules/scripts-utils/dtbook-utils/src \
	modules/scripts-utils/dtbook-utils/src/test \
	modules/scripts-utils/dtbook-utils/src/test/resources \
	modules/scripts-utils/dtbook-utils/src/test/java \
	modules/scripts-utils/dtbook-utils/src/test/xprocspec \
	modules/scripts-utils/dtbook-utils/src/main \
	modules/scripts-utils/dtbook-utils/src/main/resources \
	modules/scripts-utils/dtbook-utils/src/main/resources/css \
	modules/scripts-utils/dtbook-utils/src/main/resources/META-INF \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/validate-dtbook \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/validate-dtbook/schema \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/validate-dtbook/schema/sch \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/validate-dtbook/schema/sch/mod \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/validate-dtbook/schema/rng \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/validate-dtbook/schema/rng/dtbook \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/validate-dtbook/schema/rng/mod \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/break-detect \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/upgrade-dtbook \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/dtd \
	modules/scripts-utils/dtbook-utils/src/main/resources/xml/merge-dtbook \
	modules/scripts-utils/dtbook-utils/doc
