modules/scripts-utils/daisy3-utils/.test modules/scripts-utils/daisy3-utils/.install modules/scripts-utils/daisy3-utils/.install-doc $(TARGET_DIR)/state/modules/scripts-utils/daisy3-utils/modified-since-release_ : \
	modules/scripts-utils/daisy3-utils/src/main/resources/META-INF/catalog.xml \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/daisy3-library.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/daisy3-upgrader.script.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/ncx/1.1.0-to-2005-1.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/ncx/create-ncx.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/ncx/create-ncx.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/ncx/update-links.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/ncx/update-links.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/upgrade.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/audio-transcode-update-opf.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/resources/create-res-file.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/resources/resources.res \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/resources/update-links.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/resources/update-links.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/dtbook/fix-dtbook-structure.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/dtbook/prepare-dtbook.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils/fill-end-attrs.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils/add-elapsed-time.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils/add-smilrefs.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils/1.1.0-to-2005-1.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils/add-smilrefs.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils/add-ids.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils/create-daisy3-smils.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils/add-smilrefs-audio-only.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils/audio-order.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils/add-smilrefs-from-smils.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils/copy-smilrefs.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils/create-smils.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils/compute-elapsed-time.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/load/opf-to-fileset.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/load/load.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/audio-transcode.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/tts/dtbook-semantic-transform.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/tts/dtbook-annotating.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/tts/dtbook-to-ssml.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/tts/tts-for-dtbook.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/opf/compute-total-time.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/opf/create-opf.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/opf/1.0.1-to-1.2.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/opf/create-daisy3-opf.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/opf/update-links.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/opf/update-links.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/update-links.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/dtd/ncx110.dtd \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/dtd/resource110.dtd \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/dtd/oeb12.ent \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/dtd/oebpkg12.dtd \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/dtd/oebpkg101.dtd \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/dtd/ncx-2005-1.dtd \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/dtd/resource-2005-1.dtd \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/dtd/oeb1.ent \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/daisy3-upgrader.xpl
modules/scripts-utils/daisy3-utils/.test modules/scripts-utils/daisy3-utils/.install-doc : \
	modules/scripts-utils/daisy3-utils/src/test/resources/logback.xml \
	modules/scripts-utils/daisy3-utils/src/test/resources/1.1.0/ncx110.dtd \
	modules/scripts-utils/daisy3-utils/src/test/resources/1.1.0/mo.smil \
	modules/scripts-utils/daisy3-utils/src/test/resources/1.1.0/content.xml \
	modules/scripts-utils/daisy3-utils/src/test/resources/1.1.0/oebpkg101.dtd \
	modules/scripts-utils/daisy3-utils/src/test/resources/1.1.0/navigation.ncx \
	modules/scripts-utils/daisy3-utils/src/test/resources/1.1.0/dtbook110.dtd \
	modules/scripts-utils/daisy3-utils/src/test/resources/1.1.0/book.opf \
	modules/scripts-utils/daisy3-utils/src/test/resources/1.1.0/dtbsmil110.dtd \
	modules/scripts-utils/daisy3-utils/src/test/resources/1.1.0/oeb1.ent \
	modules/scripts-utils/daisy3-utils/src/test/resources/1.1.0/audio.wav \
	modules/scripts-utils/daisy3-utils/src/test/java/XProcSpecTest.java \
	modules/scripts-utils/daisy3-utils/src/test/xprocspec/create-smils.xprocspec \
	modules/scripts-utils/daisy3-utils/src/test/xprocspec/semantic-transformations.xprocspec \
	modules/scripts-utils/daisy3-utils/src/test/xprocspec/upgrade.xprocspec \
	modules/scripts-utils/daisy3-utils/src/test/xprocspec/add-smilrefs.xprocspec \
	modules/scripts-utils/daisy3-utils/src/test/xprocspec/ncx.xprocspec \
	modules/scripts-utils/daisy3-utils/src/test/xprocspec/create-opf.xprocspec \
	modules/scripts-utils/daisy3-utils/src/test/xprocspec/load.xprocspec \
	modules/scripts-utils/daisy3-utils/src/test/xprocspec/audio-transcode.xprocspec \
	modules/scripts-utils/daisy3-utils/src/test/xprocspec/upgrade.script.xprocspec
modules/scripts-utils/daisy3-utils/.install-doc : \
	modules/scripts-utils/daisy3-utils/doc/index.md
.make/mk/modules/scripts-utils/daisy3-utils/sources.mk : \
	modules/scripts-utils/daisy3-utils/src \
	modules/scripts-utils/daisy3-utils/src/test \
	modules/scripts-utils/daisy3-utils/src/test/resources \
	modules/scripts-utils/daisy3-utils/src/test/resources/1.1.0 \
	modules/scripts-utils/daisy3-utils/src/test/java \
	modules/scripts-utils/daisy3-utils/src/test/xprocspec \
	modules/scripts-utils/daisy3-utils/src/main \
	modules/scripts-utils/daisy3-utils/src/main/resources \
	modules/scripts-utils/daisy3-utils/src/main/resources/META-INF \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/ncx \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/resources \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/dtbook \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/load \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/tts \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/opf \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/dtd \
	modules/scripts-utils/daisy3-utils/doc
