modules/scripts-utils/daisy3-utils/.test modules/scripts-utils/daisy3-utils/.install modules/scripts-utils/daisy3-utils/.install-doc $(TARGET_DIR)/state/modules/scripts-utils/daisy3-utils/modified-since-release_ : \
	modules/scripts-utils/daisy3-utils/src/main/resources/META-INF/catalog.xml \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/daisy3-library.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/validate/nimas-fileset-validator.script.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/validate/schema/sch/package-doc-with-mathml.sch \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/validate/schema/sch/package-doc-without-mathml.sch \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/validate/schema/sch/mod/package-doc-common.sch \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/validate/schema/sch/mod/package-doc-without-mathml-mod.sch \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/validate/schema/sch/mod/package-doc-with-mathml-mod.sch \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/validate/schema/rng/package-doc-1.2.rng \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/validate/schema/rng/mod/datatypes.rng \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/validate/schema/rng/mod/attributes.rng \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/validate/nimas-fileset-validator.validate.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/validate/nimas-fileset-validator.validate-package-doc.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/validate/nimas-fileset-validator.fileset-filter.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/validate/nimas-fileset-validator.store.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/daisy3-upgrader.script.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/ncx/1.1.0-to-2005-1.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/ncx/create-ncx.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/ncx/create-ncx.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/ncx/update-links.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/ncx/update-links.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/upgrade.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/audio-transcode-update-opf.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/resources/create-res-file.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/resources/resources.res \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/resources/update-links.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/resources/update-links.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/dtbook/fix-dtbook-structure.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/dtbook/prepare-dtbook.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils/fill-end-attrs.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils/add-elapsed-time.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils/add-smilrefs.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils/1.1.0-to-2005-1.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils/add-smilrefs.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils/add-ids.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils/create-daisy3-smils.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils/add-smilrefs-audio-only.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils/audio-order.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils/add-smilrefs-from-smils.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils/copy-smilrefs.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils/create-smils.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils/compute-elapsed-time.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/load/opf-to-fileset.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/load/load.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/audio-transcode.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/tts/dtbook-semantic-transform.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/tts/dtbook-annotating.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/tts/dtbook-to-ssml.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/tts/tts-for-dtbook.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/opf/compute-total-time.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/opf/create-opf.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/opf/1.0.1-to-1.2.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/opf/create-daisy3-opf.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/opf/update-links.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/opf/update-links.xsl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/update-links.xpl \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/dtd/ncx110.dtd \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/dtd/resource110.dtd \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/dtd/oeb12.ent \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/dtd/oebpkg12.dtd \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/dtd/oebpkg101.dtd \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/dtd/ncx-2005-1.dtd \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/dtd/resource-2005-1.dtd \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/dtd/oeb1.ent \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/daisy3-upgrader.xpl
modules/scripts-utils/daisy3-utils/.test modules/scripts-utils/daisy3-utils/.install-doc : \
	modules/scripts-utils/daisy3-utils/src/test/resources/logback.xml \
	modules/scripts-utils/daisy3-utils/src/test/resources/9781122334455NIMAS/9781122334455NIMAS.pdf \
	modules/scripts-utils/daisy3-utils/src/test/resources/9781122334455NIMAS/9781122334455NIMAS.xml \
	modules/scripts-utils/daisy3-utils/src/test/resources/9781122334455NIMAS/images/U00/cover.jpg \
	modules/scripts-utils/daisy3-utils/src/test/resources/9781122334455NIMAS/images/U01C01/icon.jpg \
	modules/scripts-utils/daisy3-utils/src/test/resources/9781122334455NIMAS/images/U01C01/p006-001.jpg \
	modules/scripts-utils/daisy3-utils/src/test/resources/9781122334455NIMAS/images/U01C01/p002-001.jpg \
	modules/scripts-utils/daisy3-utils/src/test/resources/9781122334455NIMAS/images/U01C01/p010-001.jpg \
	modules/scripts-utils/daisy3-utils/src/test/resources/9781122334455NIMAS/images/U01C01/p008-001.jpg \
	modules/scripts-utils/daisy3-utils/src/test/resources/9781122334455NIMAS/9781122334455NIMAS.opf \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/MathML_Sample2.xml-report.xml \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/MathML_Sample2.xml \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-027.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-011.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-005.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-033.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-036.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-022.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-014.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-023.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/check.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-015.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-001.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-037.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-004.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-032.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-026.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-010.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-018.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-030.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-006.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-012.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-024.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-009.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-017.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-021.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-035.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-003.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-034.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-002.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-016.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-020.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-008.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-013.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-025.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-031.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-007.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-019.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-003.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-035.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-021.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-017.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-009.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-024.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-012.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-006.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-030.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-018.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-019.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-007.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-031.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-025.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-013.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-008.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-020.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-016.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-002.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-034.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-014.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-022.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-036.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-033.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-005.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-011.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-027.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-010.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-026.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-032.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-004.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-037.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-001.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-015.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-023.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-044.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-050.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-051.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-045.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-053.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-047.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-046.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-052.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/sglobe.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-056.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-042.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-043.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-057.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-041.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-055.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-054.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-040.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-059.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-065.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/test.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-064.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-058.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-004b.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/go.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-004c.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/bglobe.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-063.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-062.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-060.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-048.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-049.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-061.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-002b.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-018.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-006.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-012.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-009.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-021.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-017.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-003.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-014b.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-014c.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-002.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-020.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-016.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-008.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-013.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-007.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-019.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-039.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-011.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-005.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-028.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-014.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-022.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-015.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-023.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-001.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-029.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/goon.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-004.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-010.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-038.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/mathml.txt \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-014.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-028.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-005.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-011.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-010.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-004.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-029.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-001.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-015.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-003.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-017.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-009.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-012.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-006.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-018.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p278-019.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-007.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p281-013.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p279-008.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-016.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images/p280-002.png \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/MathML_Sample2-copy.xml \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/MathML_Sample2-copy.xml-report.xml \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/MathML_Sample2.ncx \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/MathML_Sample2.smil \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/resources.res \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/mathml-fallback-transform.xslt \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/MathML_Sample2.opf \
	modules/scripts-utils/daisy3-utils/src/test/resources/1.1.0/ncx110.dtd \
	modules/scripts-utils/daisy3-utils/src/test/resources/1.1.0/mo.smil \
	modules/scripts-utils/daisy3-utils/src/test/resources/1.1.0/content.xml \
	modules/scripts-utils/daisy3-utils/src/test/resources/1.1.0/oebpkg101.dtd \
	modules/scripts-utils/daisy3-utils/src/test/resources/1.1.0/navigation.ncx \
	modules/scripts-utils/daisy3-utils/src/test/resources/1.1.0/dtbook110.dtd \
	modules/scripts-utils/daisy3-utils/src/test/resources/1.1.0/book.opf \
	modules/scripts-utils/daisy3-utils/src/test/resources/1.1.0/dtbsmil110.dtd \
	modules/scripts-utils/daisy3-utils/src/test/resources/1.1.0/oeb1.ent \
	modules/scripts-utils/daisy3-utils/src/test/resources/1.1.0/audio.wav \
	modules/scripts-utils/daisy3-utils/src/test/resources/greatpainters-text-files-only/greatpainters-spring.jpg \
	modules/scripts-utils/daisy3-utils/src/test/resources/greatpainters-text-files-only/greatpainters-the_adoration_of_the_lamb.jpg \
	modules/scripts-utils/daisy3-utils/src/test/resources/greatpainters-text-files-only/speechgen.opf \
	modules/scripts-utils/daisy3-utils/src/test/resources/greatpainters-text-files-only/greatpainters-last_judgement.jpg \
	modules/scripts-utils/daisy3-utils/src/test/resources/greatpainters-text-files-only/dtbook.xml \
	modules/scripts-utils/daisy3-utils/src/test/resources/greatpainters-text-files-only/dtbookbasic.css \
	modules/scripts-utils/daisy3-utils/src/test/resources/greatpainters-text-files-only/speechgen.ncx \
	modules/scripts-utils/daisy3-utils/src/test/resources/greatpainters-text-files-only/greatpainters-the_fighting_temeraire.jpg \
	modules/scripts-utils/daisy3-utils/src/test/resources/greatpainters-text-files-only/greatpainters-portrait_of_georg_gisze.jpg \
	modules/scripts-utils/daisy3-utils/src/test/java/XProcSpecTest.java \
	modules/scripts-utils/daisy3-utils/src/test/xprocspec/create-smils.xprocspec \
	modules/scripts-utils/daisy3-utils/src/test/xprocspec/semantic-transformations.xprocspec \
	modules/scripts-utils/daisy3-utils/src/test/xprocspec/upgrade.xprocspec \
	modules/scripts-utils/daisy3-utils/src/test/xprocspec/add-smilrefs.xprocspec \
	modules/scripts-utils/daisy3-utils/src/test/xprocspec/ncx.xprocspec \
	modules/scripts-utils/daisy3-utils/src/test/xprocspec/create-opf.xprocspec \
	modules/scripts-utils/daisy3-utils/src/test/xprocspec/load.xprocspec \
	modules/scripts-utils/daisy3-utils/src/test/xprocspec/audio-transcode.xprocspec \
	modules/scripts-utils/daisy3-utils/src/test/xprocspec/nimas-fileset-validator.xprocspec \
	modules/scripts-utils/daisy3-utils/src/test/xprocspec/nimas-fileset-validator.script.xprocspec \
	modules/scripts-utils/daisy3-utils/src/test/xprocspec/upgrade.script.xprocspec
modules/scripts-utils/daisy3-utils/.install-doc : \
	modules/scripts-utils/daisy3-utils/doc/index.md \
	modules/scripts-utils/daisy3-utils/doc/nimas-fileset-validator.md \
	modules/scripts-utils/daisy3-utils/doc/nimas-fileset-validator-dev-notes.md
.make/mk/modules/scripts-utils/daisy3-utils/sources.mk : \
	modules/scripts-utils/daisy3-utils/src \
	modules/scripts-utils/daisy3-utils/src/test \
	modules/scripts-utils/daisy3-utils/src/test/resources \
	modules/scripts-utils/daisy3-utils/src/test/resources/9781122334455NIMAS \
	modules/scripts-utils/daisy3-utils/src/test/resources/9781122334455NIMAS/images \
	modules/scripts-utils/daisy3-utils/src/test/resources/9781122334455NIMAS/images/U00 \
	modules/scripts-utils/daisy3-utils/src/test/resources/9781122334455NIMAS/images/U01C01 \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2 \
	modules/scripts-utils/daisy3-utils/src/test/resources/MathML_Modular_Extension_Example_2/images \
	modules/scripts-utils/daisy3-utils/src/test/resources/1.1.0 \
	modules/scripts-utils/daisy3-utils/src/test/resources/greatpainters-text-files-only \
	modules/scripts-utils/daisy3-utils/src/test/java \
	modules/scripts-utils/daisy3-utils/src/test/xprocspec \
	modules/scripts-utils/daisy3-utils/src/main \
	modules/scripts-utils/daisy3-utils/src/main/resources \
	modules/scripts-utils/daisy3-utils/src/main/resources/META-INF \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/validate \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/validate/schema \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/validate/schema/sch \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/validate/schema/sch/mod \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/validate/schema/rng \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/validate/schema/rng/mod \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/ncx \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/resources \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/dtbook \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/smils \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/load \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/tts \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/internal/opf \
	modules/scripts-utils/daisy3-utils/src/main/resources/xml/dtd \
	modules/scripts-utils/daisy3-utils/doc
