package org.daisy.pipeline.tts.acapela.impl;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : nscube_forjna.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class NSC_EVENT_DATA_TextStarted extends Structure {
	public int uiSize;
	/** C type : void* */
	public Pointer pUserData;
	public NSC_EVENT_DATA_TextStarted() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("uiSize", "pUserData");
	}
	/** @param pUserData C type : void* */
	public NSC_EVENT_DATA_TextStarted(int uiSize, Pointer pUserData) {
		super();
		this.uiSize = uiSize;
		this.pUserData = pUserData;
	}
	public NSC_EVENT_DATA_TextStarted(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends NSC_EVENT_DATA_TextStarted implements Structure.ByReference {
		
	};
	public static class ByValue extends NSC_EVENT_DATA_TextStarted implements Structure.ByValue {
		
	};
}
