framework/persistence-derby/.test framework/persistence-derby/.install framework/persistence-derby/.install-doc $(TARGET_DIR)/state/framework/persistence-derby/modified-since-release_ : \
	framework/persistence-derby/src/main/java/org/daisy/pipeline/persistence/impl/derby/DerbyEntityManagerFactory.java
framework/persistence-derby/.test framework/persistence-derby/.install-doc : \
	framework/persistence-derby/src/test/resources/logback.xml \
	framework/persistence-derby/src/test/resources/script.xpl \
	framework/persistence-derby/src/test/resources/META-INF/catalog.xml \
	framework/persistence-derby/src/test/resources/data/db/dbex.lck \
	framework/persistence-derby/src/test/resources/data/db/db.lck \
	framework/persistence-derby/src/test/resources/data/db/seg0/c6d1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c430.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c550.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c2e1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c20.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c380.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c3c0.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c141.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c631.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c1c0.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c180.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c4d0.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c221.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c5b0.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c590.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/ce1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c340.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c1b1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c620.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c191.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c4e1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c5c1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/cd1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c230.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c581.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c741.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c351.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c421.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c2d0.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c31.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c541.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c391.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c3b1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c150.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c651.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c1e0.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c321.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c4b0.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c490.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/cc0.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c241.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c5d0.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/d711.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c730.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c81.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c6b1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c691.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c3e1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c530.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c2c1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c281.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c41.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c451.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c121.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c441.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c51.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c521.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c290.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c2b1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c3d1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c681.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c130.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c6c1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c1d1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c640.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c4c1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c481.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/cb1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/d701.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c90.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c251.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c5e0.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c331.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c300.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/ca1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c260.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c5f1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c671.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c101.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c60.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c2a1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c510.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c470.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c6a1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c3f1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c501.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c71.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c461.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c111.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c311.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c271.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/d721.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c4a1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c660.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c1f1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c161.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c411.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c570.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c3a1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c6f1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c1a1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c200.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c4f0.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c361.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c611.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c371.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/cf0.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c211.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c5a1.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c600.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c400.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c10.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c561.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c2f0.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/c171.dat \
	framework/persistence-derby/src/test/resources/data/db/seg0/d6e1.dat \
	framework/persistence-derby/src/test/resources/data/db/log/log1.dat \
	framework/persistence-derby/src/test/resources/data/db/log/logmirror.ctrl \
	framework/persistence-derby/src/test/resources/data/db/log/log.ctrl \
	framework/persistence-derby/src/test/resources/data/db/service.properties \
	framework/persistence-derby/src/test/java/MockXProcEngine.java \
	framework/persistence-derby/src/test/java/NewDatabaseTest.java \
	framework/persistence-derby/src/test/java/ExistingDatabaseTest.java \
	framework/persistence-derby/src/test/java/TestBase.java
.make/mk/framework/persistence-derby/sources.mk : \
	framework/persistence-derby/src \
	framework/persistence-derby/src/test \
	framework/persistence-derby/src/test/resources \
	framework/persistence-derby/src/test/resources/META-INF \
	framework/persistence-derby/src/test/resources/data \
	framework/persistence-derby/src/test/resources/data/db \
	framework/persistence-derby/src/test/resources/data/db/seg0 \
	framework/persistence-derby/src/test/resources/data/db/log \
	framework/persistence-derby/src/test/java \
	framework/persistence-derby/src/main \
	framework/persistence-derby/src/main/java \
	framework/persistence-derby/src/main/java/org \
	framework/persistence-derby/src/main/java/org/daisy \
	framework/persistence-derby/src/main/java/org/daisy/pipeline \
	framework/persistence-derby/src/main/java/org/daisy/pipeline/persistence \
	framework/persistence-derby/src/main/java/org/daisy/pipeline/persistence/impl \
	framework/persistence-derby/src/main/java/org/daisy/pipeline/persistence/impl/derby
