modules/scripts-utils/html-utils/.test modules/scripts-utils/html-utils/.install modules/scripts-utils/html-utils/.install-doc $(TARGET_DIR)/state/modules/scripts-utils/html-utils/modified-since-release_ : \
	modules/scripts-utils/html-utils/src/main/resources/css/default-speech.scss \
	modules/scripts-utils/html-utils/src/main/resources/META-INF/catalog.xml \
	modules/scripts-utils/html-utils/src/main/resources/xml/xproc/html-downgrade.xpl \
	modules/scripts-utils/html-utils/src/main/resources/xml/xproc/break-detect/library.xpl \
	modules/scripts-utils/html-utils/src/main/resources/xml/xproc/html-chunker.xpl \
	modules/scripts-utils/html-utils/src/main/resources/xml/xproc/html-library.xpl \
	modules/scripts-utils/html-utils/src/main/resources/xml/xproc/html-update-links.xpl \
	modules/scripts-utils/html-utils/src/main/resources/xml/xproc/html-outline.xpl \
	modules/scripts-utils/html-utils/src/main/resources/xml/xproc/html-merge.xpl \
	modules/scripts-utils/html-utils/src/main/resources/xml/xproc/html-upgrade.xpl \
	modules/scripts-utils/html-utils/src/main/resources/xml/xproc/html-fixer.xpl \
	modules/scripts-utils/html-utils/src/main/resources/xml/xproc/html-add-ids.xpl \
	modules/scripts-utils/html-utils/src/main/resources/xml/xproc/html-load.xpl \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml-rdfa-2.dtd \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml1-frameset.dtd \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml-lat1.ent \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml1-strict.dtd \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml-rdfa-model-2.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml1-transitional.dtd \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml-datatypes-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml-metaAttributes-2.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/rdfa11/xhtml-rdfa-2.dtd \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/rdfa11/xhtml-rdfa-model-2.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/rdfa11/xhtml-metaAttributes-2.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml-special.ent \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-legacy-redecl-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-inlstyle-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-inlphras-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-hypertext-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-nameident-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-arch-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-inlpres-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-lat1.ent \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml11.dtd \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-inlstruct-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-meta-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml11-model-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-link-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-legacy-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-target-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-basic-table-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-table-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-param-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-image-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-datatypes-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-ruby-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-qname-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-text-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-events-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/VERSION \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-basic-form-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-blkstruct-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-csismap-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-style-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-frames-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-script-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-pres-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-edit-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-form-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-base-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-special.ent \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-bdo-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-attribs-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-notations-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-iframe-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-object-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-charent-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-blkpres-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-applet-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-blkphras-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-symbol.ent \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-struct-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-ssismap-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-framework-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11/xhtml-list-1.mod \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml-symbol.ent \
	modules/scripts-utils/html-utils/src/main/resources/xml/xslt/html5-outline.xsl \
	modules/scripts-utils/html-utils/src/main/resources/xml/xslt/html-to-fileset.xsl \
	modules/scripts-utils/html-utils/src/main/resources/xml/xslt/remove-duplicate-ids.xsl \
	modules/scripts-utils/html-utils/src/main/resources/xml/xslt/html5-upgrade.xsl \
	modules/scripts-utils/html-utils/src/main/resources/xml/xslt/untitled-section-titles.xsl \
	modules/scripts-utils/html-utils/src/main/resources/xml/xslt/namespace-fixup.xsl \
	modules/scripts-utils/html-utils/src/main/resources/xml/xslt/html-chunker-finalize.xsl \
	modules/scripts-utils/html-utils/src/main/resources/xml/xslt/add-link-fragments.xsl \
	modules/scripts-utils/html-utils/src/main/resources/xml/xslt/html-update-links.xsl \
	modules/scripts-utils/html-utils/src/main/resources/xml/xslt/html5-normalize-sections-headings.xsl \
	modules/scripts-utils/html-utils/src/main/resources/xml/xslt/html-merge.xsl \
	modules/scripts-utils/html-utils/src/main/resources/xml/xslt/html-fixer.xsl \
	modules/scripts-utils/html-utils/src/main/resources/xml/xslt/html5-to-html4.xsl \
	modules/scripts-utils/html-utils/src/main/resources/xml/xslt/untitled-section-titles.xml \
	modules/scripts-utils/html-utils/src/main/resources/xml/xslt/library.xsl \
	modules/scripts-utils/html-utils/src/main/java/org/daisy/pipeline/html/impl/HtmlDocumentBuilder.java
modules/scripts-utils/html-utils/.test modules/scripts-utils/html-utils/.install-doc : \
	modules/scripts-utils/html-utils/src/test/xspec/namespace-fixup.xspec \
	modules/scripts-utils/html-utils/src/test/xspec/html5-outline.xspec \
	modules/scripts-utils/html-utils/src/test/xspec/html5-upgrade.xspec \
	modules/scripts-utils/html-utils/src/test/xspec/html5-to-html4.xspec \
	modules/scripts-utils/html-utils/src/test/resources/logback.xml \
	modules/scripts-utils/html-utils/src/test/resources/config-calabash.xml \
	modules/scripts-utils/html-utils/src/test/resources/non-xml.html \
	modules/scripts-utils/html-utils/src/test/resources/html-with-xml-stylesheet-processing-instruction.xml \
	modules/scripts-utils/html-utils/src/test/java/XProcSpecTest.java \
	modules/scripts-utils/html-utils/src/test/xprocspec/test_load-html.xprocspec \
	modules/scripts-utils/html-utils/src/test/xprocspec/html-update-links.xprocspec \
	modules/scripts-utils/html-utils/src/test/xprocspec/test_html-outline.xprocspec \
	modules/scripts-utils/html-utils/src/test/xprocspec/uri-functions.xprocspec \
	modules/scripts-utils/html-utils/src/test/xprocspec/test_html-break-detect.xprocspec \
	modules/scripts-utils/html-utils/src/test/xprocspec/test_fileset-load-html.xprocspec \
	modules/scripts-utils/html-utils/src/test/xprocspec/test_html-load.xprocspec \
	modules/scripts-utils/html-utils/src/test/xprocspec/html-merge.xprocspec \
	modules/scripts-utils/html-utils/src/test/xprocspec/html-downgrade.xprocspec \
	modules/scripts-utils/html-utils/src/test/xprocspec/html-id-fixer.xprocspec \
	modules/scripts-utils/html-utils/src/test/xprocspec/html-chunker.xprocspec
.make/mk/modules/scripts-utils/html-utils/sources.mk : \
	modules/scripts-utils/html-utils/src \
	modules/scripts-utils/html-utils/src/test \
	modules/scripts-utils/html-utils/src/test/xspec \
	modules/scripts-utils/html-utils/src/test/resources \
	modules/scripts-utils/html-utils/src/test/java \
	modules/scripts-utils/html-utils/src/test/xprocspec \
	modules/scripts-utils/html-utils/src/main \
	modules/scripts-utils/html-utils/src/main/resources \
	modules/scripts-utils/html-utils/src/main/resources/css \
	modules/scripts-utils/html-utils/src/main/resources/META-INF \
	modules/scripts-utils/html-utils/src/main/resources/xml \
	modules/scripts-utils/html-utils/src/main/resources/xml/xproc \
	modules/scripts-utils/html-utils/src/main/resources/xml/xproc/break-detect \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/rdfa11 \
	modules/scripts-utils/html-utils/src/main/resources/xml/dtd/xhtml11 \
	modules/scripts-utils/html-utils/src/main/resources/xml/xslt \
	modules/scripts-utils/html-utils/src/main/java \
	modules/scripts-utils/html-utils/src/main/java/org \
	modules/scripts-utils/html-utils/src/main/java/org/daisy \
	modules/scripts-utils/html-utils/src/main/java/org/daisy/pipeline \
	modules/scripts-utils/html-utils/src/main/java/org/daisy/pipeline/html \
	modules/scripts-utils/html-utils/src/main/java/org/daisy/pipeline/html/impl
