modules/scripts-utils/epub-utils/.test modules/scripts-utils/epub-utils/.install modules/scripts-utils/epub-utils/.install-doc $(TARGET_DIR)/state/modules/scripts-utils/epub-utils/modified-since-release_ : \
	modules/scripts-utils/epub-utils/src/main/resources/META-INF/catalog.xml \
	modules/scripts-utils/epub-utils/src/main/resources/xml/validate/epub-validate.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/validate/epubcheck-report-to-pipeline-report.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/validate/epubcheck-pipeline-report-to-html-report.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/epub-rename-files.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/mo/create-mediaoverlay.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/mo/clean-mediaoverlay.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/mo/tts/epub3-to-ssml.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/mo/tts/prepare-html.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/mo/tts/tts-for-epub3.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/mo/create-mediaoverlays.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/ocf/epub3-safe-uris.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/ocf/epub3-safe-uris.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/ocf/ocf-finalize.create-container-descriptor.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/ocf/ocf-zip.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/ocf/ocf-finalize.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/ocf/opf-manifest-to-fileset.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/ocf/store.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/ocf/opf-manifest-to-fileset.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/ocf/load.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/epub-update-links.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/create-package-doc.estimate-mediaoverlay-duration.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/ensure-core-media.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/package-doc-update-links.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/create-package-doc.fileset-to-manifest.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/package-doc-update-links.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/create-package-doc.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/compare-package-doc.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/create-package-doc.generate-identifier.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/assign-media-overlays.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/create-package-doc.idref-fileset-to-spine.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/add-mediaoverlays.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/add-prefix.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/html-clean-resources.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/add-prefix.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/create-package-doc.sum-mediaoverlay-durations.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/create-metadata.merge.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/merge-metadata.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/epub3-vocab.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/merge-prefix.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/opf-spine-to-fileset.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/opf2-to-opf3-metadata.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/upgrade-package-doc.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/merge-prefix.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/opf2-to-opf3-metadata.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/opf-spine-to-fileset.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/add-nav.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/upgrade-package-doc.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/add-metadata.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/opf3-to-opf2-metadata.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/detect-properties.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/create-package-doc.generate-dcterms-modified.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/opf3-to-opf2-metadata.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/detect-properties.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/create-package-doc.handler-fileset-to-bindings.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub/clean-package-doc.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/nav/epub3-nav-create-toc.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/nav/epub3-nav-from-ncx.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/nav/ncx-to-nav.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/nav/nav-to-ncx.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/nav/landmarks-to-guide.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/nav/label-pagebreaks-from-nav.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/nav/landmarks-to-guide.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/nav/label-pagebreaks-from-nav.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/nav/epub3-nav-aggregate.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/nav/epub3-nav-create-page-list.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/nav/html5-to-page-list.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/nav/i18n.xml \
	modules/scripts-utils/epub-utils/src/main/resources/xml/nav/epub3-nav-to-ncx.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/nav/epub3-nav-create-navigation-doc.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/nav/guide-to-landmarks.xpl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/nav/list-pagebreaks-from-nav.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/nav/guide-to-landmarks.xsl \
	modules/scripts-utils/epub-utils/src/main/resources/xml/library.xpl
modules/scripts-utils/epub-utils/.test modules/scripts-utils/epub-utils/.install-doc : \
	modules/scripts-utils/epub-utils/src/test/xspec/pub/opf-manifest-to-fileset.xspec \
	modules/scripts-utils/epub-utils/src/test/xspec/pub/create-metadata.merge.xspec \
	modules/scripts-utils/epub-utils/src/test/xspec/pub/merge-prefix.xspec \
	modules/scripts-utils/epub-utils/src/test/xspec/nav/nav-to-ncx.xspec \
	modules/scripts-utils/epub-utils/src/test/resources/logback.xml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/META-INF/container.xml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/mimetype \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_099.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_021.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_064.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_059.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_101.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_080.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_038.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_125.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_118.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_005.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_040.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_007.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_042.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_082.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_127.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_103.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_023.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_066.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/preface_001.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_107.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_027.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_062.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/toc-short.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_003.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_046.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_123.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_086.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_121.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_079.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_084.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_001.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_044.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_025.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_060.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/css/stylesheet.css \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_105.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_018.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/images/Moby-Dick_FE_title_page.jpg \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/images/9780316000000.jpg \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_126.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_083.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_043.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_006.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_067.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_022.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_102.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_100.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_058.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_098.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_065.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_020.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_041.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_004.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_119.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_124.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_081.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/titlepage.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_039.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_045.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_078.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_085.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_120.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_019.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_104.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_001_overlay.smil \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_061.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_024.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_063.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_026.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_106.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_087.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/toc.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_122.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_047.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_002.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_113.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_033.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_076.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/introduction_001.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_017.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_052.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_092.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_135.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_028.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/audio/mobydick_001_002_melville.mp4 \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_090.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_015.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_050.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_108.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_031.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_074.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_089.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_111.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_049.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_128.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_035.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_070.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_008.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/cover.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_002_overlay.smil \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_115.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_094.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_069.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_131.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_011.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_054.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_013.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_056.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_096.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_133.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_117.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_037.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_072.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_109.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/epigraph_001.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_051.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_014.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_029.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_091.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_134.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_048.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_110.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_075.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_030.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_088.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_077.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_032.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_112.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_093.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_136.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/fonts/STIXGeneralItalic.otf \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/fonts/STIXGeneral.otf \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/fonts/STIXGeneralBolIta.otf \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/fonts/STIXGeneralBol.otf \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_053.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_016.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_132.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_097.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_057.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_012.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_073.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_036.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_116.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_114.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_009.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_071.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_034.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_129.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_055.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/copyright.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_010.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/package.opf \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_130.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_095.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/chapter_068.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/valentin.epub \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214.OK.epub \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/META-INF/container.xml \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/mimetype \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/EPUB/C00000-4-chapter.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/EPUB/nav.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/EPUB/C00000-7-chapter.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/EPUB/C00000-3-chapter.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/EPUB/css/accessibility.css \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/EPUB/css/fonts/opendyslexic/OpenDyslexicMono-Regular.otf \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/EPUB/css/fonts/opendyslexic/OpenDyslexic-Italic.otf \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/EPUB/css/fonts/opendyslexic/OpenDyslexic-BoldItalic.otf \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/EPUB/css/fonts/opendyslexic/OpenDyslexic-Bold.otf \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/EPUB/css/fonts/opendyslexic/LICENSE.txt \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/EPUB/css/fonts/opendyslexic/OpenDyslexic-Regular.otf \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/EPUB/images/valentin.jpg \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/EPUB/C00000-1-cover.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/EPUB/C00000-2-frontmatter.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/EPUB/C00000-6-rearnotes.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/EPUB/nav.ncx \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/EPUB/C00000-9-footnotes.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/EPUB/C00000-8-conclusion.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/EPUB/C00000-5-chapter.xhtml \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/EPUB/package.opf \
	modules/scripts-utils/epub-utils/src/test/java/XSpecAndXProcSpecTest.java \
	modules/scripts-utils/epub-utils/src/test/xprocspec/mo/part_1.mp3 \
	modules/scripts-utils/epub-utils/src/test/xprocspec/mo/part_3.mp3 \
	modules/scripts-utils/epub-utils/src/test/xprocspec/mo/part_2.mp3 \
	modules/scripts-utils/epub-utils/src/test/xprocspec/mo/test_epub3-create-mediaoverlays.xprocspec \
	modules/scripts-utils/epub-utils/src/test/xprocspec/epub3-vocab.xprocspec \
	modules/scripts-utils/epub-utils/src/test/xprocspec/test_validate.xprocspec \
	modules/scripts-utils/epub-utils/src/test/xprocspec/ocf/test_ocf-finalize.xprocspec \
	modules/scripts-utils/epub-utils/src/test/xprocspec/ocf/test_load.xprocspec \
	modules/scripts-utils/epub-utils/src/test/xprocspec/pub/test_epub3-pub-merge-prefix.xprocspec \
	modules/scripts-utils/epub-utils/src/test/xprocspec/pub/test_epub3-pub-create-package-doc.xprocspec \
	modules/scripts-utils/epub-utils/src/test/xprocspec/pub/test_opf-spine-to-fileset.xprocspec \
	modules/scripts-utils/epub-utils/src/test/xprocspec/pub/test_html-clean-resources.xprocspec \
	modules/scripts-utils/epub-utils/src/test/xprocspec/nav/test_epub3-nav-from-ncx.xprocspec \
	modules/scripts-utils/epub-utils/src/test/xprocspec/nav/test_epub3-nav-create-page-list.xprocspec \
	modules/scripts-utils/epub-utils/src/test/xprocspec/nav/test_epub3-nav-create-toc.xprocspec \
	modules/scripts-utils/epub-utils/src/test/xprocspec/epub3-safe-uris.xprocspec
.make/mk/modules/scripts-utils/epub-utils/sources.mk : \
	modules/scripts-utils/epub-utils/src \
	modules/scripts-utils/epub-utils/src/test \
	modules/scripts-utils/epub-utils/src/test/xspec \
	modules/scripts-utils/epub-utils/src/test/xspec/pub \
	modules/scripts-utils/epub-utils/src/test/xspec/nav \
	modules/scripts-utils/epub-utils/src/test/resources \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214 \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/META-INF \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/css \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/images \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/audio \
	modules/scripts-utils/epub-utils/src/test/resources/moby-dick-mo-20120214/OPS/fonts \
	modules/scripts-utils/epub-utils/src/test/resources/valentin \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/META-INF \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/EPUB \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/EPUB/css \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/EPUB/css/fonts \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/EPUB/css/fonts/opendyslexic \
	modules/scripts-utils/epub-utils/src/test/resources/valentin/EPUB/images \
	modules/scripts-utils/epub-utils/src/test/java \
	modules/scripts-utils/epub-utils/src/test/xprocspec \
	modules/scripts-utils/epub-utils/src/test/xprocspec/mo \
	modules/scripts-utils/epub-utils/src/test/xprocspec/ocf \
	modules/scripts-utils/epub-utils/src/test/xprocspec/pub \
	modules/scripts-utils/epub-utils/src/test/xprocspec/nav \
	modules/scripts-utils/epub-utils/src/main \
	modules/scripts-utils/epub-utils/src/main/resources \
	modules/scripts-utils/epub-utils/src/main/resources/META-INF \
	modules/scripts-utils/epub-utils/src/main/resources/xml \
	modules/scripts-utils/epub-utils/src/main/resources/xml/validate \
	modules/scripts-utils/epub-utils/src/main/resources/xml/mo \
	modules/scripts-utils/epub-utils/src/main/resources/xml/mo/tts \
	modules/scripts-utils/epub-utils/src/main/resources/xml/ocf \
	modules/scripts-utils/epub-utils/src/main/resources/xml/pub \
	modules/scripts-utils/epub-utils/src/main/resources/xml/nav
