framework/framework-persistence/.test framework/framework-persistence/.install framework/framework-persistence/.install-doc $(TARGET_DIR)/state/framework/framework-persistence/modified-since-release_ : \
	framework/framework-persistence/src/main/resources/META-INF/persistence.xml \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/Database.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/webservice/PersistentRequestLog.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/webservice/PersistentJobConfiguration.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/webservice/PersistentClient.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/webservice/PersistentClientStorage.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/webservice/PersistentJobConfigurationStorage.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/webservice/PersistentRequestLogEntry.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/webservice/PersistentWebserviceStorage.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/job/PersistentOptionResult.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/job/PersistentOption.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/job/PersistentJob.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/job/BatchFilter.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/job/IdFilter.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/job/PersistentPortResult.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/job/PersistentMapper.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/job/ClientFilter.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/job/ContextHydrator.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/job/QueryDecorator.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/job/PersistentJobContext.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/job/PersistentInputPort.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/job/PersistentParameter.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/job/PersistentSource.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/job/PersistentJobStorage.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/messaging/PersistenceMessagePK.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/messaging/PersistentMessage.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/messaging/PersistentMessageStorage.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/ForwardingEntityManagerFactory.java \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/logging/Slf4jSessionLogger.java
framework/framework-persistence/.test framework/framework-persistence/.install-doc : \
	framework/framework-persistence/src/test/resources/META-INF/persistence.xml \
	framework/framework-persistence/src/test/java/org/daisy/pipeline/persistence/impl/webservice/PersistentClientStorageTest.java \
	framework/framework-persistence/src/test/java/org/daisy/pipeline/persistence/impl/webservice/PersistentJobConfigurationTest.java \
	framework/framework-persistence/src/test/java/org/daisy/pipeline/persistence/impl/job/PersistentSourceTest.java \
	framework/framework-persistence/src/test/java/org/daisy/pipeline/persistence/impl/job/PersistentJobStorageTest.java \
	framework/framework-persistence/src/test/java/org/daisy/pipeline/persistence/impl/job/PersistentParameterTest.java \
	framework/framework-persistence/src/test/java/org/daisy/pipeline/persistence/impl/job/PersistentOptionResultTest.java \
	framework/framework-persistence/src/test/java/org/daisy/pipeline/persistence/impl/job/PersistentPortResultTest.java \
	framework/framework-persistence/src/test/java/org/daisy/pipeline/persistence/impl/job/IdFilterTest.java \
	framework/framework-persistence/src/test/java/org/daisy/pipeline/persistence/impl/job/PersistentJobContextTest.java \
	framework/framework-persistence/src/test/java/org/daisy/pipeline/persistence/impl/job/PersistentOptionTest.java \
	framework/framework-persistence/src/test/java/org/daisy/pipeline/persistence/impl/job/PersistentInputPortTest.java \
	framework/framework-persistence/src/test/java/org/daisy/pipeline/persistence/impl/job/Mocks.java \
	framework/framework-persistence/src/test/java/org/daisy/pipeline/persistence/impl/job/QueryDecoratorTest.java \
	framework/framework-persistence/src/test/java/org/daisy/pipeline/persistence/impl/job/DatabaseProvider.java \
	framework/framework-persistence/src/test/java/org/daisy/pipeline/persistence/impl/job/ClientFilterTest.java \
	framework/framework-persistence/src/test/java/org/daisy/pipeline/persistence/impl/job/PersistentJobTest.java
.make/mk/framework/framework-persistence/sources.mk : \
	framework/framework-persistence/src \
	framework/framework-persistence/src/test \
	framework/framework-persistence/src/test/resources \
	framework/framework-persistence/src/test/resources/META-INF \
	framework/framework-persistence/src/test/java \
	framework/framework-persistence/src/test/java/org \
	framework/framework-persistence/src/test/java/org/daisy \
	framework/framework-persistence/src/test/java/org/daisy/pipeline \
	framework/framework-persistence/src/test/java/org/daisy/pipeline/persistence \
	framework/framework-persistence/src/test/java/org/daisy/pipeline/persistence/impl \
	framework/framework-persistence/src/test/java/org/daisy/pipeline/persistence/impl/webservice \
	framework/framework-persistence/src/test/java/org/daisy/pipeline/persistence/impl/job \
	framework/framework-persistence/src/main \
	framework/framework-persistence/src/main/resources \
	framework/framework-persistence/src/main/resources/META-INF \
	framework/framework-persistence/src/main/java \
	framework/framework-persistence/src/main/java/org \
	framework/framework-persistence/src/main/java/org/daisy \
	framework/framework-persistence/src/main/java/org/daisy/pipeline \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/webservice \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/job \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/impl/messaging \
	framework/framework-persistence/src/main/java/org/daisy/pipeline/persistence/logging
