modules/tts/tts-common/.test modules/tts/tts-common/.install modules/tts/tts-common/.install-doc $(TARGET_DIR)/state/modules/tts/tts-common/modified-since-release_ : \
	modules/tts/tts-common/src/main/resources/META-INF/catalog.xml \
	modules/tts/tts-common/src/main/resources/xml/xproc/flatten-structure.xsl \
	modules/tts/tts-common/src/main/resources/xml/xproc/normalize.xsl \
	modules/tts/tts-common/src/main/resources/xml/xproc/filter-chars.xsl \
	modules/tts/tts-common/src/main/resources/xml/xproc/ssml-to-audio.xpl \
	modules/tts/tts-common/src/main/resources/xml/xproc/generate-annotating-stylesheet.xsl \
	modules/tts/tts-common/src/main/resources/xml/xproc/reorder-sentences.xpl \
	modules/tts/tts-common/src/main/resources/xml/xproc/reorder-sentences.xsl \
	modules/tts/tts-common/src/main/resources/xml/xproc/flatten-css.xsl \
	modules/tts/tts-common/src/main/resources/xml/xproc/apply-lexicons.xpl \
	modules/tts/tts-common/src/main/resources/xml/xproc/get-lookahead.xsl \
	modules/tts/tts-common/src/main/resources/xml/xproc/skippable-to-ssml.xsl \
	modules/tts/tts-common/src/main/resources/xml/xproc/annotate.xpl \
	modules/tts/tts-common/src/main/resources/xml/xproc/pls-to-ssml.xsl \
	modules/tts/tts-common/src/main/resources/xml/xproc/isolate-skippable.xsl \
	modules/tts/tts-common/src/main/resources/xml/xproc/identify-sections.xsl \
	modules/tts/tts-common/src/main/resources/xml/xproc/text-to-ssml.xpl \
	modules/tts/tts-common/src/main/resources/xml/xproc/isolate-skippable.xpl \
	modules/tts/tts-common/src/main/resources/xml/xproc/extract-skippable.xsl \
	modules/tts/tts-common/src/main/resources/xml/xproc/get-tts-annotations.xpl \
	modules/tts/tts-common/src/main/resources/xml/xproc/extract-skippable.xpl \
	modules/tts/tts-common/src/main/resources/xml/xproc/css-to-ssml.xpl \
	modules/tts/tts-common/src/main/resources/xml/xproc/css-to-ssml.xsl \
	modules/tts/tts-common/src/main/resources/xml/xproc/regex-pls-to-ssml.xsl \
	modules/tts/tts-common/src/main/resources/xml/xproc/library.xpl \
	modules/tts/tts-common/src/main/resources/xml/xproc/reorganize-lexicons.xsl \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/DefaultSSMLMarkSplitter.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/impl/TTSEnginesWebServiceExtension.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/impl/VoicesResource.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/impl/TTSEnginesResource.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/impl/VoicesWebServiceExtension.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/impl/DefaultLexiconProperty.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/impl/VoicePreviewResource.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/impl/VoiceResource.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/AudioFootprintMonitor.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/Voice.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/TimedTTSExecutor.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/StructuredSSMLSplitter.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/config/AnnotationsConfigExtension.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/config/VoiceConfigExtension.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/config/ConfigReader.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/config/DynamicPropertiesExtension.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/TTSTimeout.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/LoadBalancer.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/calabash/impl/TextToPcmThread.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/calabash/impl/SSMLtoAudio.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/calabash/impl/EncodingThread.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/calabash/impl/SoundFileLink.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/calabash/impl/SynthesizeProvider.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/calabash/impl/ContiguousPCM.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/calabash/impl/ContiguousText.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/calabash/impl/GetAnnotationsProvider.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/calabash/impl/FormatSpecifications.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/calabash/impl/SynthesizeStep.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/Sentence.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/TTSLog.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/TTSService.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/SSMLMarkSplitter.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/TTSRegistry.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/VoiceManager.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/SpeechRateProperty.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/RoundRobinLoadBalancer.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/TTSInputProcessor.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/VoiceInfo.java \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/TTSEngine.java
modules/tts/tts-common/.test modules/tts/tts-common/.install-doc : \
	modules/tts/tts-common/src/test/resources/logback.xml \
	modules/tts/tts-common/src/test/resources/lexicon-test-en.pls \
	modules/tts/tts-common/src/test/resources/lexicon-test-fr.pls \
	modules/tts/tts-common/src/test/resources/tts-default-config.xml \
	modules/tts/tts-common/src/test/resources/mock-tts/mock_short.wav \
	modules/tts/tts-common/src/test/resources/mock-tts/transform-ssml.xsl \
	modules/tts/tts-common/src/test/resources/mock-tts/mock_long.wav \
	modules/tts/tts-common/src/test/resources/mock-encoder/mock_short.mp3 \
	modules/tts/tts-common/src/test/resources/valid-sheet.xsl \
	modules/tts/tts-common/src/test/java/XProcSpecTest.java \
	modules/tts/tts-common/src/test/java/ignore \
	modules/tts/tts-common/src/test/java/org/daisy/pipeline/tts/TimeoutTest.java \
	modules/tts/tts-common/src/test/java/org/daisy/pipeline/tts/config/URITest.java \
	modules/tts/tts-common/src/test/java/org/daisy/pipeline/tts/config/ConfigReaderTest.java \
	modules/tts/tts-common/src/test/java/org/daisy/pipeline/tts/GenericMarkSplitterTest.java \
	modules/tts/tts-common/src/test/java/org/daisy/pipeline/tts/calabash/impl/ConfigReaderTest.java \
	modules/tts/tts-common/src/test/java/org/daisy/pipeline/tts/calabash/impl/SSMLtoAudioTest.java \
	modules/tts/tts-common/src/test/java/org/daisy/pipeline/tts/TTSRegistryTest.java \
	modules/tts/tts-common/src/test/java/org/daisy/pipeline/tts/StructuredMarkSplitterTest.java \
	modules/tts/tts-common/src/test/java/MockEncoder.java \
	modules/tts/tts-common/src/test/java/MockTTS.java \
	modules/tts/tts-common/src/test/xprocspec/text-to-ssml.xprocspec \
	modules/tts/tts-common/src/test/xprocspec/pls-to-ssml.xprocspec \
	modules/tts/tts-common/src/test/xprocspec/extract-skippable.xprocspec \
	modules/tts/tts-common/src/test/xprocspec/normalize.xprocspec \
	modules/tts/tts-common/src/test/xprocspec/clean-text.xpl \
	modules/tts/tts-common/src/test/xprocspec/test_ssml-to-audio.xprocspec \
	modules/tts/tts-common/src/test/xprocspec/annotations.xprocspec \
	modules/tts/tts-common/src/test/xprocspec/punctuation.xprocspec \
	modules/tts/tts-common/src/test/xprocspec/skippable-to-ssml.xprocspec \
	modules/tts/tts-common/src/test/xprocspec/ordering.xprocspec \
	modules/tts/tts-common/src/test/xprocspec/annotations-in-config.xprocspec \
	modules/tts/tts-common/src/test/xprocspec/isolate-skippable.xprocspec
modules/tts/tts-common/.install-doc : \
	modules/tts/tts-common/doc/index.md
.make/mk/modules/tts/tts-common/sources.mk : \
	modules/tts/tts-common/src \
	modules/tts/tts-common/src/test \
	modules/tts/tts-common/src/test/resources \
	modules/tts/tts-common/src/test/resources/mock-tts \
	modules/tts/tts-common/src/test/resources/mock-encoder \
	modules/tts/tts-common/src/test/java \
	modules/tts/tts-common/src/test/java/org \
	modules/tts/tts-common/src/test/java/org/daisy \
	modules/tts/tts-common/src/test/java/org/daisy/pipeline \
	modules/tts/tts-common/src/test/java/org/daisy/pipeline/tts \
	modules/tts/tts-common/src/test/java/org/daisy/pipeline/tts/config \
	modules/tts/tts-common/src/test/java/org/daisy/pipeline/tts/calabash \
	modules/tts/tts-common/src/test/java/org/daisy/pipeline/tts/calabash/impl \
	modules/tts/tts-common/src/test/xprocspec \
	modules/tts/tts-common/src/main \
	modules/tts/tts-common/src/main/resources \
	modules/tts/tts-common/src/main/resources/META-INF \
	modules/tts/tts-common/src/main/resources/xml \
	modules/tts/tts-common/src/main/resources/xml/xproc \
	modules/tts/tts-common/src/main/java \
	modules/tts/tts-common/src/main/java/org \
	modules/tts/tts-common/src/main/java/org/daisy \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/impl \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/config \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/calabash \
	modules/tts/tts-common/src/main/java/org/daisy/pipeline/tts/calabash/impl \
	modules/tts/tts-common/doc
