modules/scripts-utils/zedai-utils/.test modules/scripts-utils/zedai-utils/.install modules/scripts-utils/zedai-utils/.install-doc $(TARGET_DIR)/state/modules/scripts-utils/zedai-utils/modified-since-release_ : \
	modules/scripts-utils/zedai-utils/src/main/resources/META-INF/catalog.xml \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/xproc/break-detect/library.xpl \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/xproc/zedai-load.xpl \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/xproc/zedai-validate.xpl \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/xproc/library.xpl \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/z3998-book-noselect.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/z3998-book-nodescription.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-grad01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-curl01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-otherwise03.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-quotient01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-break01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-scalarproduct01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-semantics01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-arcsinh01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-toc01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-mmultiscripts01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-section03.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-msubsup01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-head01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-simplifiedImage01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-bvar01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-secret01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-transition01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/attributes.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-entry03.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-merror01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-mroot01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-lexicon01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-ln01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-cbytes01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-tan01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-sup01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-mtd01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-imaginaryi01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-meta01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-msub01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-submission01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-thead01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-value02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-rem01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-lambda01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-aside01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-sinh01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-int01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-arccsc01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-frontcover01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-say-as01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-none01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-summary01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-mglyph01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_ssml-say-as.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_span.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-copy01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-select101.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-sec01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-spine01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-address02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-mprescripts01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-coth01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-implies01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-token01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-frontmatter01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-plus01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-divergence01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-conjugate01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-rp01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-list01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_address.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-mtr01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-col01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-math01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-description04.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-outerproduct01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-entry02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-divide01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-tfoot01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-log01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-arccoth01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-lt01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-factorial01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-pagebreak01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-instance01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-or01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_m-semantics.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-lngroup01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-union01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-section02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-mstack01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_code.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-choices01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-mrow01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_xforms-value.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-approx01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-mn01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-cot01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_emph.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-prosody02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-bodymatter01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-otherwise02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-transpose01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-citation01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-piece01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-vector01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-p01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-rt01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-block01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-sub01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-msup01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-card01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-gt01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-textarea01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-matrix01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-condition01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-bind02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_annotation.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-not01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-object03.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-code01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-infinity01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-sdev01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-d01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-cover01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_ssml-prosody.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-leq01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-h01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-cs01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-backmatter01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_object.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-msqrt01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_toc.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-power01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-span02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-exp01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-mtext01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-quote01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-select02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-note02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-hpart01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-annotation03.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-section05.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-sin01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-glossary02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-vectorproduct01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_sel-otherwise.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-lowlimit01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-integers01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-geq01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-equivalent01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-range01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_ssml-sub.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-mpadded01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-partialdiff01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-description03.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-description02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-uplimit01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-when02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-notin01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-num01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-domainofapplication01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-entry04.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_sel-when.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-limit01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-arg01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-gcd01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-annotation02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-section04.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-naturalnumbers01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-select03.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-intersect01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_note.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-root01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-min01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-body01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-arccos01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-notsubset01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-msline01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-phoneme01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-msrow01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-mlabeledtr01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-mtable01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-annoref01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-factorof01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-lnum01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-char01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-item02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-index01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-ci01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-reals01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-annotation-xml01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-object02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-max01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-name02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-emph01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-interval01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-longdesc01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-piecewise01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-maction01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_lngroup.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-rb01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-ident01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-primes01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-tbody01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_quote.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-table01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-w01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-domain01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-bibliography01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-lcm01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-arctan01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-set01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-item01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-exists01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-mlongdiv01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-object01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-mscarry01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-name01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-emph02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-td01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-csc01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-share01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-backcover01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_ssml-phoneme.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-xor01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-true01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-diff01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-sub03.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-th01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-rationals01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-complexes01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-variance01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-description01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-when01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-abs01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-selector01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-mode01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-logbase01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-determinant01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-colgroup01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-laplacian01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-hd01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-annotation01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-malignmark01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-times01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-munder01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-body02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-phoneme02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-input01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-tour01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-span01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-select01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-note01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-quote02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-notprsubset01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-section06.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-mo01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-product01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-minus01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-glossary01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-arcsech01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-model01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-floor01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-simplifiedLanguageDescription01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-munderover01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-arccot01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_ssml-token.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-arccosh01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-mspace01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-mover01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-label01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-block02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-imaginary01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-flaps01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-sub02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-sech01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-expansion01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-mphantom01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-cosh01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-tr01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-noteref01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-cn01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-arcsec01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-group01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-bind01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_description.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-rbc01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-code02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-notanumber01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-inverse01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-csymbol01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-false01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-time01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-mean01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-definition01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-abbr01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-subset01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-compose01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-csch01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-ln03.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-entry01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-repeat01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-ruby01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-menclose01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-header01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-itemset01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-arcsin01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-apply01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-ms01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-eulergamma01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-mfenced01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-lngroup02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-section01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-document01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-median01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-arctanh01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-semantics03.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-momentabout01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-otherwise01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-prosody01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_sel-select.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-tendsto01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-citation02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-verse01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-tanh01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-matrixrow01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-ref01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-setdiff01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-caption01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-mscarries01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-tactile01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-eq01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-address01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-token02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-and01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-aside03.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-linebreak01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-arccsch01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-msgroup01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-list02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-pi01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_citation.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-term01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-value01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-aside02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_entry.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-moment01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-mfrac01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_ln.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-cartesianproduct01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-sum01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-say-as02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-emptyset01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-rtc01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-codomain01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-prsubset01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-cerror01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-mstyle01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_glossary.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-s01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_section.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-sep01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-ceiling01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-resource01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-degree01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-method01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-semantics02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-maligngroup01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-toc02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-image01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-exponentiale01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-in01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-head02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_aside.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/_block.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-forall01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-cos01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-wpart01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-neq01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-mi01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-real01.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles/e-ln02.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/index.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/schemadoc.css \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/.htaccess \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/z3998-book-noruby.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/resources/z3998-base.css \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/resources/mathml3-common.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/resources/mathml.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/resources/book-template.xml \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/resources/z3998-book.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/resources/d.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/resources/z3998-book-single.rnc \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/resources/select.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/resources/xlink.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/resources/xforms.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/resources/mathml3-content.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/resources/z3998-book.nvdl \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/resources/z3998-book.sch \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/resources/rend.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/resources/xml.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/resources/its.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/resources/z3998-book-single.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/resources/synthesis.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/resources/mathml3-strict-content.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/resources/mathml3-presentation.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/z3998-book-norend.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/z3998-book-nossml.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/z3998-book.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/z3998-book-nosvg-cdr.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/z3998-book-nomath.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/z3998-book-noforms.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/z3998-book-nofeatures.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/z3998-book-history.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/xforms-nons-11.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/rdfa-attrib.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-meta.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-core-attrib.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-sub-sup.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-document.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-feature-mathml.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-list.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-description.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-global-classes.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-feature-ssml.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-feature-svg-cdr.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-table.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-term.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-feature-rend.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-note.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-time.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-s.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-d.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-address.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-quote.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-citation.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-definition.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-feature-forms.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-span.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-p.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/ssml-datatypes.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-block.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-aside.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-cover.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-by-attrib.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-feature-select.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-partitions.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-code.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-w.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-section.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/ssml-11.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-pagebreak.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-feature-description.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-linking.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-char.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-annotation.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-datatypes.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-num.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-role-attrib.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-feature-its-ruby.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/xlink.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-name.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-abbr.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-line.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-vocab-contrib-structure.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-glossary.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-object.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-headings.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/ssml-phoneme-attrib.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-transition.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-i18n-attrib.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-depth-attrib.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-caption.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-bibliography.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-emph.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-index.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-verse.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod/z3998-toc.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/z3998-book.html \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/z3998-book-noselect.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/z3998-book-nodescription.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/z3998-book-noruby.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/resources/z3998-base.css \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/resources/mathml3-common.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/resources/mathml.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/resources/book-template.xml \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/resources/z3998-book.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/resources/d.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/resources/z3998-book-single.rnc \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/resources/select.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/resources/xlink.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/resources/xforms.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/resources/mathml3-content.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/resources/z3998-book.nvdl \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/resources/z3998-book.sch \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/resources/rend.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/resources/xml.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/resources/its.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/resources/z3998-book-single.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/resources/synthesis.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/resources/mathml3-strict-content.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/resources/mathml3-presentation.xsd \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/z3998-book-norend.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/z3998-book-nossml.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/z3998-book.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/z3998-book-nosvg-cdr.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/z3998-book-nomath.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/z3998-book-noforms.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/z3998-book-nofeatures.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/xforms-nons-11.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/rdfa-attrib.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-meta.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-core-attrib.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-sub-sup.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-document.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-feature-mathml.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-list.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-description.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-global-classes.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-feature-ssml.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-feature-svg-cdr.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-table.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-term.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-feature-rend.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-note.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-time.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-s.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-d.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-address.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-quote.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-citation.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-definition.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-feature-forms.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-span.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-p.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/ssml-datatypes.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-block.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-aside.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-cover.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-by-attrib.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-feature-select.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-partitions.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-code.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-w.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-section.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/ssml-11.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-pagebreak.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-feature-description.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-linking.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-char.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-annotation.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-datatypes.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-num.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-role-attrib.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-feature-its-ruby.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/xlink.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-name.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-abbr.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-line.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-vocab-contrib-structure.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-glossary.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-object.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-headings.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/ssml-phoneme-attrib.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-transition.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-i18n-attrib.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-depth-attrib.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-caption.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-bibliography.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-emph.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-index.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-verse.rng \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod/z3998-toc.rng
.make/mk/modules/scripts-utils/zedai-utils/sources.mk : \
	modules/scripts-utils/zedai-utils/src \
	modules/scripts-utils/zedai-utils/src/main \
	modules/scripts-utils/zedai-utils/src/main/resources \
	modules/scripts-utils/zedai-utils/src/main/resources/META-INF \
	modules/scripts-utils/zedai-utils/src/main/resources/xml \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/xproc \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/xproc/break-detect \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/schemadoc/subfiles \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/resources \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0-latest/mod \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0 \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/resources \
	modules/scripts-utils/zedai-utils/src/main/resources/xml/schema/z3998-book-1.0/mod
