modules/braille/braille-css-utils/.test modules/braille/braille-css-utils/.install modules/braille/braille-css-utils/.install-doc $(TARGET_DIR)/state/modules/braille/braille-css-utils/modified-since-release_ : \
	modules/braille/braille-css-utils/src/main/resources/META-INF/catalog.xml \
	modules/braille/braille-css-utils/src/main/resources/xml/parse-content.xpl \
	modules/braille/braille-css-utils/src/main/resources/xml/parse-content.xsl \
	modules/braille/braille-css-utils/src/main/resources/xml/parse-stylesheet.xsl \
	modules/braille/braille-css-utils/src/main/resources/xml/parse-stylesheet.xpl \
	modules/braille/braille-css-utils/src/main/resources/xml/extract.xsl \
	modules/braille/braille-css-utils/src/main/resources/xml/extract.xpl \
	modules/braille/braille-css-utils/src/main/resources/xml/parse-properties.xpl \
	modules/braille/braille-css-utils/src/main/resources/xml/parse-properties.xsl \
	modules/braille/braille-css-utils/src/main/resources/xml/library.xpl \
	modules/braille/braille-css-utils/src/main/resources/xml/library.xsl \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/impl/BrailleCssParser.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/impl/UnmodifiableTermIdent.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/impl/StyleTransformerImpl.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/impl/ContentList.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/impl/CounterSetList.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/impl/StringSetList.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/impl/BrailleCssSerializer.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/impl/TextTransformList.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/impl/UnmodifiableTermString.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/impl/UnmodifiableTerm.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/impl/BrailleCssStyle.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/impl/BrailleCssCascader.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/impl/UnmodifiableTermURI.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/StyleTransformer.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/xpath/impl/Declaration.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/xpath/impl/Stylesheet.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/xpath/impl/Value.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/xpath/impl/CounterStyle.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/xpath/impl/Rule.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/xpath/StyledText.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/xpath/Style.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/SupportedPrintCSS.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/TextStyleParser.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/CounterSet.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/EmbossedMedium.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/saxon/impl/InvalidTableException.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/saxon/impl/StyledTextFunctionProvider.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/saxon/impl/RenderTableByDefinition.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/saxon/impl/StyleFunctionProvider.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/saxon/impl/TableAsList.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/CSSStyledText.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/CounterFunction.java \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/package-info.java \
	modules/braille/braille-css-utils/src/main/README.md
modules/braille/braille-css-utils/.test modules/braille/braille-css-utils/.install-doc : \
	modules/braille/braille-css-utils/src/test/xspec/test_braille-css.xspec \
	modules/braille/braille-css-utils/src/test/xspec/test_render-table-by.xspec \
	modules/braille/braille-css-utils/src/test/xspec/test_parse-stylesheet.xspec \
	modules/braille/braille-css-utils/src/test/xspec/test_parse-properties.xspec \
	modules/braille/braille-css-utils/src/test/xspec/test_parse-content.xspec \
	modules/braille/braille-css-utils/src/test/resources/logback.xml \
	modules/braille/braille-css-utils/src/test/resources/dir\ with\ spaces/sass_1.scss \
	modules/braille/braille-css-utils/src/test/resources/dir\ with\ spaces/css_1.css \
	modules/braille/braille-css-utils/src/test/resources/css/css_4_with_charset.css \
	modules/braille/braille-css-utils/src/test/resources/css/css_5_without_charset.css \
	modules/braille/braille-css-utils/src/test/resources/css/css_2_resets_css_1.css \
	modules/braille/braille-css-utils/src/test/resources/css/css_3_with_bom.css \
	modules/braille/braille-css-utils/src/test/resources/css/css_1.css \
	modules/braille/braille-css-utils/src/test/resources/META-INF/catalog.xml \
	modules/braille/braille-css-utils/src/test/resources/phony.xsl \
	modules/braille/braille-css-utils/src/test/resources/sass/sass_5_imports_module_sass_2.scss \
	modules/braille/braille-css-utils/src/test/resources/sass/sass_4_imports_sass_1.scss \
	modules/braille/braille-css-utils/src/test/resources/sass/sass_3_imports_module_css_1.scss \
	modules/braille/braille-css-utils/src/test/resources/sass/sass_8.scss \
	modules/braille/braille-css-utils/src/test/resources/sass/sass_2_imports_css_1.scss \
	modules/braille/braille-css-utils/src/test/resources/sass/sass_1.scss \
	modules/braille/braille-css-utils/src/test/resources/sass/sass_7.scss \
	modules/braille/braille-css-utils/src/test/resources/sass/sass_6.scss \
	modules/braille/braille-css-utils/src/test/resources/css-module/css/css_3_private.css \
	modules/braille/braille-css-utils/src/test/resources/css-module/css/css_2_imports_css_3.css \
	modules/braille/braille-css-utils/src/test/resources/css-module/css/css_1.css \
	modules/braille/braille-css-utils/src/test/resources/css-module/sass/sass_3_imports_css_3.scss \
	modules/braille/braille-css-utils/src/test/resources/css-module/sass/sass_2.scss \
	modules/braille/braille-css-utils/src/test/resources/css-module/sass/sass_1.scss \
	modules/braille/braille-css-utils/src/test/resources/css-module/sass/sass_4_imports_sass_5.scss \
	modules/braille/braille-css-utils/src/test/resources/css-module/sass/sass_5_private.scss \
	modules/braille/braille-css-utils/src/test/java/XProcSpecTest.java \
	modules/braille/braille-css-utils/src/test/java/ignore \
	modules/braille/braille-css-utils/src/test/java/MockCSSExtension.java \
	modules/braille/braille-css-utils/src/test/java/GenericEmbossedMediumProvider.java \
	modules/braille/braille-css-utils/src/test/xprocspec/test_extract.xprocspec \
	modules/braille/braille-css-utils/src/test/xprocspec/test_css-cascade/stylesheet_1.scss \
	modules/braille/braille-css-utils/src/test/xprocspec/test_css-cascade/stylesheet_1.xsl \
	modules/braille/braille-css-utils/src/test/xprocspec/test_css-cascade/stylesheet_4.scss \
	modules/braille/braille-css-utils/src/test/xprocspec/test_css-cascade/test_css-cascade.xprocspec \
	modules/braille/braille-css-utils/src/test/xprocspec/test_css-cascade/stylesheet_3.css \
	modules/braille/braille-css-utils/src/test/xprocspec/test_css-cascade/stylesheet_5.scss \
	modules/braille/braille-css-utils/src/test/xprocspec/test_css-cascade/stylesheet_2.scss \
	modules/braille/braille-css-utils/src/test/xprocspec/test_css-cascade/2.xml \
	modules/braille/braille-css-utils/src/test/xprocspec/test_css-cascade/1.xml \
	modules/braille/braille-css-utils/src/test/xprocspec/test_inline/test_import.xprocspec \
	modules/braille/braille-css-utils/src/test/xprocspec/test_inline/test_specificity.xprocspec \
	modules/braille/braille-css-utils/src/test/xprocspec/test_inline/test_media.xprocspec \
	modules/braille/braille-css-utils/src/test/xprocspec/test_inline/test_selectors.xprocspec \
	modules/braille/braille-css-utils/src/test/xprocspec/test_inline/test_sass.xprocspec \
	modules/braille/braille-css-utils/src/test/xprocspec/test_inline/test_bom.xprocspec \
	modules/braille/braille-css-utils/src/test/xprocspec/test_inline/test_counter-style.xprocspec \
	modules/braille/braille-css-utils/src/test/xprocspec/test_inline/test_page.xprocspec \
	modules/braille/braille-css-utils/src/test/xprocspec/test_inline/test_hyphenation-resource.xprocspec \
	modules/braille/braille-css-utils/src/test/xprocspec/test_inline/test_namespace.xprocspec \
	modules/braille/braille-css-utils/src/test/xprocspec/test_inline/test_resolver.xprocspec \
	modules/braille/braille-css-utils/src/test/xprocspec/test_inline/test_volume.xprocspec \
	modules/braille/braille-css-utils/src/test/xprocspec/test_inline/test_properties.xprocspec \
	modules/braille/braille-css-utils/src/test/xprocspec/test_inline/test_invalid.xprocspec \
	modules/braille/braille-css-utils/src/test/xprocspec/test_inline/test_inherit.xprocspec \
	modules/braille/braille-css-utils/src/test/xprocspec/test_inline/test_extension.xprocspec \
	modules/braille/braille-css-utils/src/test/xprocspec/test_inline/test_content.xprocspec \
	modules/braille/braille-css-utils/src/test/xprocspec/test_inline/test_encoding.xprocspec \
	modules/braille/braille-css-utils/src/test/xprocspec/test_inline/test_text-transform.xprocspec \
	modules/braille/braille-css-utils/src/test/xprocspec/test_inline/test_context.xprocspec \
	modules/braille/braille-css-utils/src/test/xprocspec/test_inline/test_user-stylesheet.xprocspec
.make/mk/modules/braille/braille-css-utils/sources.mk : \
	modules/braille/braille-css-utils/src \
	modules/braille/braille-css-utils/src/test \
	modules/braille/braille-css-utils/src/test/xspec \
	modules/braille/braille-css-utils/src/test/resources \
	modules/braille/braille-css-utils/src/test/resources/dir\ with\ spaces \
	modules/braille/braille-css-utils/src/test/resources/css \
	modules/braille/braille-css-utils/src/test/resources/META-INF \
	modules/braille/braille-css-utils/src/test/resources/sass \
	modules/braille/braille-css-utils/src/test/resources/css-module \
	modules/braille/braille-css-utils/src/test/resources/css-module/css \
	modules/braille/braille-css-utils/src/test/resources/css-module/sass \
	modules/braille/braille-css-utils/src/test/java \
	modules/braille/braille-css-utils/src/test/xprocspec \
	modules/braille/braille-css-utils/src/test/xprocspec/test_css-cascade \
	modules/braille/braille-css-utils/src/test/xprocspec/test_inline \
	modules/braille/braille-css-utils/src/main \
	modules/braille/braille-css-utils/src/main/resources \
	modules/braille/braille-css-utils/src/main/resources/META-INF \
	modules/braille/braille-css-utils/src/main/resources/xml \
	modules/braille/braille-css-utils/src/main/java \
	modules/braille/braille-css-utils/src/main/java/org \
	modules/braille/braille-css-utils/src/main/java/org/daisy \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/impl \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/xpath \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/xpath/impl \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/saxon \
	modules/braille/braille-css-utils/src/main/java/org/daisy/pipeline/braille/css/saxon/impl
