modules/daisy202-to-epub3/.test modules/daisy202-to-epub3/.install modules/daisy202-to-epub3/.install-doc $(TARGET_DIR)/state/modules/daisy202-to-epub3/modified-since-release_ : \
	modules/daisy202-to-epub3/src/main/resources/META-INF/catalog.xml \
	modules/daisy202-to-epub3/src/main/resources/xml/daisy202-to-epub3.xpl \
	modules/daisy202-to-epub3/src/main/resources/xml/convert/resources.xpl \
	modules/daisy202-to-epub3/src/main/resources/xml/convert/navigation.xpl \
	modules/daisy202-to-epub3/src/main/resources/xml/convert/ncc-to-nav-page-list.xpl \
	modules/daisy202-to-epub3/src/main/resources/xml/convert/ncc-to-nav-page-list.xsl \
	modules/daisy202-to-epub3/src/main/resources/xml/convert/convert.xpl \
	modules/daisy202-to-epub3/src/main/resources/xml/convert/ncc-to-opf-metadata.xpl \
	modules/daisy202-to-epub3/src/main/resources/xml/convert/package.xpl \
	modules/daisy202-to-epub3/src/main/resources/xml/convert/resolve-links.create-mapping.xpl \
	modules/daisy202-to-epub3/src/main/resources/xml/convert/media-overlay.xpl \
	modules/daisy202-to-epub3/src/main/resources/xml/convert/ncc-navigation.xpl \
	modules/daisy202-to-epub3/src/main/resources/xml/convert/resolve-links.xpl \
	modules/daisy202-to-epub3/src/main/resources/xml/convert/daisy202-content-to-epub3-content.xsl \
	modules/daisy202-to-epub3/src/main/resources/xml/convert/content.annotate-pagebreaks.xsl \
	modules/daisy202-to-epub3/src/main/resources/xml/convert/package.manifest-to-fileset.xsl \
	modules/daisy202-to-epub3/src/main/resources/xml/convert/resolve-links.xsl \
	modules/daisy202-to-epub3/src/main/resources/xml/convert/ncc-to-nav-toc.xsl \
	modules/daisy202-to-epub3/src/main/resources/xml/convert/ncc-to-nav-toc.xpl \
	modules/daisy202-to-epub3/src/main/resources/xml/convert/ncc-navigation.make-new-hrefs.xsl \
	modules/daisy202-to-epub3/src/main/resources/xml/convert/content.xpl \
	modules/daisy202-to-epub3/src/main/resources/xml/convert/ncc-to-nav-landmarks.xpl \
	modules/daisy202-to-epub3/src/main/resources/xml/convert/ncc-to-content.xsl \
	modules/daisy202-to-epub3/src/main/resources/xml/convert/ncc-to-nav-landmarks.xsl \
	modules/daisy202-to-epub3/src/main/resources/xml/convert/ncc-metadata-to-opf-metadata.xsl
modules/daisy202-to-epub3/.test modules/daisy202-to-epub3/.install-doc : \
	modules/daisy202-to-epub3/src/test/resources/logback.xml \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario2/output/F00000\ -\ Don't\ Worry,\ Be\ Happy\ Lyrics.epub \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario2/temp-dir/epub/META-INF/container.xml \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario2/temp-dir/epub/mimetype \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario2/temp-dir/epub/EPUB/Content/content.xhtml \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario2/temp-dir/epub/EPUB/Content/default.css \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario2/temp-dir/epub/EPUB/Content/ncc.xhtml \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario2/temp-dir/epub/EPUB/package.opf \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario1/output/F00000\ -\ Don't\ Worry,\ Be\ Happy\ Lyrics.epub \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario1/temp-dir/epub/META-INF/container.xml \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario1/temp-dir/epub/mimetype \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario1/temp-dir/epub/EPUB/Content/content.xhtml \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario1/temp-dir/epub/EPUB/Content/ncx.xml \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario1/temp-dir/epub/EPUB/Content/speechgen0003.mp3 \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario1/temp-dir/epub/EPUB/Content/speechgen0002.mp3 \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario1/temp-dir/epub/EPUB/Content/content.smil \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario1/temp-dir/epub/EPUB/Content/speechgen0001.mp3 \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario1/temp-dir/epub/EPUB/Content/default.css \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario1/temp-dir/epub/EPUB/Content/speechgen0005.mp3 \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario1/temp-dir/epub/EPUB/Content/speechgen0004.mp3 \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario1/temp-dir/epub/EPUB/Content/speechgen0006.mp3 \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario1/temp-dir/epub/EPUB/Content/speechgen0007.mp3 \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario1/temp-dir/epub/EPUB/Content/ncc.xhtml \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario1/temp-dir/epub/EPUB/package.opf \
	modules/daisy202-to-epub3/src/test/resources/input/book1/speechgen0001.smil \
	modules/daisy202-to-epub3/src/test/resources/input/book1/speechgen0006.smil \
	modules/daisy202-to-epub3/src/test/resources/input/book1/speechgen0007.smil \
	modules/daisy202-to-epub3/src/test/resources/input/book1/speechgen0004.smil \
	modules/daisy202-to-epub3/src/test/resources/input/book1/speechgen0003.mp3 \
	modules/daisy202-to-epub3/src/test/resources/input/book1/speechgen0002.mp3 \
	modules/daisy202-to-epub3/src/test/resources/input/book1/speechgen0001.mp3 \
	modules/daisy202-to-epub3/src/test/resources/input/book1/default.css \
	modules/daisy202-to-epub3/src/test/resources/input/book1/speechgen0005.mp3 \
	modules/daisy202-to-epub3/src/test/resources/input/book1/speechgen0004.mp3 \
	modules/daisy202-to-epub3/src/test/resources/input/book1/tpbnarrator_res.mp3 \
	modules/daisy202-to-epub3/src/test/resources/input/book1/speechgen0006.mp3 \
	modules/daisy202-to-epub3/src/test/resources/input/book1/speechgen0007.mp3 \
	modules/daisy202-to-epub3/src/test/resources/input/book1/speechgen0005.smil \
	modules/daisy202-to-epub3/src/test/resources/input/book1/speechgen0002.smil \
	modules/daisy202-to-epub3/src/test/resources/input/book1/speechgen0003.smil \
	modules/daisy202-to-epub3/src/test/resources/input/book1/content.html \
	modules/daisy202-to-epub3/src/test/resources/input/book1/ncc.html \
	modules/daisy202-to-epub3/src/test/resources/input/minimal/speechgen0001.smil \
	modules/daisy202-to-epub3/src/test/resources/input/minimal/speechgen0001.mp3 \
	modules/daisy202-to-epub3/src/test/resources/input/minimal/content.html \
	modules/daisy202-to-epub3/src/test/resources/input/minimal/ncc.html \
	modules/daisy202-to-epub3/src/test/java/XProcSpecTest.java \
	modules/daisy202-to-epub3/src/test/xprocspec/test_resolve-links.xprocspec \
	modules/daisy202-to-epub3/src/test/xprocspec/test_daisy202-to-epub3.xprocspec \
	modules/daisy202-to-epub3/src/test/xprocspec/test_daisy202-to-epub3.script.xprocspec
modules/daisy202-to-epub3/.install-doc : \
	modules/daisy202-to-epub3/doc/index.md
.make/mk/modules/daisy202-to-epub3/sources.mk : \
	modules/daisy202-to-epub3/src \
	modules/daisy202-to-epub3/src/test \
	modules/daisy202-to-epub3/src/test/resources \
	modules/daisy202-to-epub3/src/test/resources/expected \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario2 \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario2/output \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario2/temp-dir \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario2/temp-dir/epub \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario2/temp-dir/epub/META-INF \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario2/temp-dir/epub/EPUB \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario2/temp-dir/epub/EPUB/Content \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario1 \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario1/output \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario1/temp-dir \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario1/temp-dir/epub \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario1/temp-dir/epub/META-INF \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario1/temp-dir/epub/EPUB \
	modules/daisy202-to-epub3/src/test/resources/expected/scenario1/temp-dir/epub/EPUB/Content \
	modules/daisy202-to-epub3/src/test/resources/input \
	modules/daisy202-to-epub3/src/test/resources/input/book1 \
	modules/daisy202-to-epub3/src/test/resources/input/minimal \
	modules/daisy202-to-epub3/src/test/java \
	modules/daisy202-to-epub3/src/test/xprocspec \
	modules/daisy202-to-epub3/src/main \
	modules/daisy202-to-epub3/src/main/resources \
	modules/daisy202-to-epub3/src/main/resources/META-INF \
	modules/daisy202-to-epub3/src/main/resources/xml \
	modules/daisy202-to-epub3/src/main/resources/xml/convert \
	modules/daisy202-to-epub3/doc
