modules/braille/pef-utils/.test modules/braille/pef-utils/.install modules/braille/pef-utils/.install-doc $(TARGET_DIR)/state/modules/braille/pef-utils/modified-since-release_ : \
	modules/braille/pef-utils/src/main/resources/NotCourierSans-Bold.ttf \
	modules/braille/pef-utils/src/main/resources/odt2braille8.ttf \
	modules/braille/pef-utils/src/main/resources/META-INF/catalog.xml \
	modules/braille/pef-utils/src/main/resources/META-INF/services/org.daisy.dotify.api.embosser.EmbosserProvider \
	modules/braille/pef-utils/src/main/resources/META-INF/services/org.daisy.dotify.api.embosser.FileFormatProvider \
	modules/braille/pef-utils/src/main/resources/NotCourierSans-Bold.otf \
	modules/braille/pef-utils/src/main/resources/xml/validate.xpl \
	modules/braille/pef-utils/src/main/resources/xml/merge.xpl \
	modules/braille/pef-utils/src/main/resources/xml/compare.xpl \
	modules/braille/pef-utils/src/main/resources/xml/add-opf-metadata-to-pef.xsl \
	modules/braille/pef-utils/src/main/resources/xml/pef-preview.css \
	modules/braille/pef-utils/src/main/resources/xml/store.xpl \
	modules/braille/pef-utils/src/main/resources/xml/merge.remove-duplicate-attributes.xsl \
	modules/braille/pef-utils/src/main/resources/xml/x-compare.xpl \
	modules/braille/pef-utils/src/main/resources/xml/sheets-multiple-of-two.xsl \
	modules/braille/pef-utils/src/main/resources/xml/pef-preview.xsl \
	modules/braille/pef-utils/src/main/resources/xml/add-metadata.xpl \
	modules/braille/pef-utils/src/main/resources/xml/blank-last-page.xsl \
	modules/braille/pef-utils/src/main/resources/xml/pef-to-html.convert.xpl \
	modules/braille/pef-utils/src/main/resources/xml/pef-preview.js \
	modules/braille/pef-utils/src/main/resources/xml/merge.extract-sections.xsl \
	modules/braille/pef-utils/src/main/resources/xml/pef-padding.xsl \
	modules/braille/pef-utils/src/main/resources/xml/library.xpl \
	modules/braille/pef-utils/src/main/resources/xml/library.xsl \
	modules/braille/pef-utils/src/main/resources/schema/pef-2008-1.rng \
	modules/braille/pef-utils/src/main/resources/schema/pef-2008-1.sch \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille/pef/impl/BRFWriter.java \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille/pef/impl/FileFormatCatalog.java \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille/pef/impl/TableDatatypeService.java \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille/pef/impl/PEFFileFormat.java \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille/pef/impl/TableCatalog.java \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille/pef/impl/ConfigurableFileFormat.java \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille/pef/impl/LocaleBasedTableProvider.java \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille/pef/TableRegistry.java \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille/pef/calabash/impl/pdf/ColorFactory.java \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille/pef/calabash/impl/pdf/PEF2PDFStep.java \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille/pef/calabash/impl/ValidateStep.java \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille/pef/calabash/impl/PEF2TextStep.java \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille/pef/AbstractTableProvider.java \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille/pef/BrailleFileFormat.java \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille/pef/saxon/impl/PefMediaFunctionProvider.java \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille/pef/saxon/impl/GetTableIdDefinition.java \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille/pef/saxon/impl/DecodeDefinition.java \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille/pef/saxon/impl/EncodeDefinition.java \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille/pef/TableProvider.java \
	modules/braille/pef-utils/src/main/README.md
modules/braille/pef-utils/.test modules/braille/pef-utils/.install-doc : \
	modules/braille/pef-utils/src/test/resources/logback.xml \
	modules/braille/pef-utils/src/test/resources/pef_4.pef \
	modules/braille/pef-utils/src/test/resources/merged_sections.pef \
	modules/braille/pef-utils/src/test/resources/pef_3.pef \
	modules/braille/pef-utils/src/test/resources/pef_2.pef \
	modules/braille/pef-utils/src/test/resources/pef_1.pef \
	modules/braille/pef-utils/src/test/resources/merged_volumes.pef \
	modules/braille/pef-utils/src/test/resources/pef_3_1.brf \
	modules/braille/pef-utils/src/test/resources/pef_3_2.brf \
	modules/braille/pef-utils/src/test/resources/.gitattributes \
	modules/braille/pef-utils/src/test/resources/test_store_06.brf \
	modules/braille/pef-utils/src/test/resources/test_store_07.brf \
	modules/braille/pef-utils/src/test/resources/test_store_05.brf \
	modules/braille/pef-utils/src/test/java/XProcSpecTest.java \
	modules/braille/pef-utils/src/test/java/org/daisy/pipeline/braille/pef/impl/TableCatalogTest.java \
	modules/braille/pef-utils/src/test/java/PefCoreTest.java \
	modules/braille/pef-utils/src/test/xprocspec/test_padding.xprocspec \
	modules/braille/pef-utils/src/test/xprocspec/test_merge.xprocspec \
	modules/braille/pef-utils/src/test/xprocspec/test_store.xprocspec
.make/mk/modules/braille/pef-utils/sources.mk : \
	modules/braille/pef-utils/src \
	modules/braille/pef-utils/src/test \
	modules/braille/pef-utils/src/test/resources \
	modules/braille/pef-utils/src/test/java \
	modules/braille/pef-utils/src/test/java/org \
	modules/braille/pef-utils/src/test/java/org/daisy \
	modules/braille/pef-utils/src/test/java/org/daisy/pipeline \
	modules/braille/pef-utils/src/test/java/org/daisy/pipeline/braille \
	modules/braille/pef-utils/src/test/java/org/daisy/pipeline/braille/pef \
	modules/braille/pef-utils/src/test/java/org/daisy/pipeline/braille/pef/impl \
	modules/braille/pef-utils/src/test/xprocspec \
	modules/braille/pef-utils/src/main \
	modules/braille/pef-utils/src/main/resources \
	modules/braille/pef-utils/src/main/resources/META-INF \
	modules/braille/pef-utils/src/main/resources/META-INF/services \
	modules/braille/pef-utils/src/main/resources/xml \
	modules/braille/pef-utils/src/main/resources/schema \
	modules/braille/pef-utils/src/main/java \
	modules/braille/pef-utils/src/main/java/org \
	modules/braille/pef-utils/src/main/java/org/daisy \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille/pef \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille/pef/impl \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille/pef/calabash \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille/pef/calabash/impl \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille/pef/calabash/impl/pdf \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille/pef/saxon \
	modules/braille/pef-utils/src/main/java/org/daisy/pipeline/braille/pef/saxon/impl
