namespace onecorenative
{
    [default_interface]
    runtimeclass SpeechResult
    {
        SpeechResult(UInt8[] speech, String[] marksNames,Int64[] marksPositions, UInt8 errorFlag);
        UInt8[] getSpeech();
        String[] getMarksNames();
        Int64[] getMarksPositions();
        UInt8 getErrorFlag();
        void setErrorFlag(UInt8 error);
    }

    [default_interface]
    runtimeclass Connection
    {
        Connection();
        Windows.Media.SpeechSynthesis.VoiceInformation[] voices();
        Windows.Media.SpeechSynthesis.VoiceInformation defaultVoice();
        SpeechResult speak(String ssml, String voiceName);

    }
}
