/* DO NOT EDIT THIS FILE - it is machine generated */

/* Header for class org_daisy_pipeline_tts_onecore_OnecoreLib */

#ifndef _Included_org_daisy_pipeline_tts_onecore_OnecoreLib
#define _Included_org_daisy_pipeline_tts_onecore_OnecoreLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_daisy_pipeline_tts_onecore_OnecoreLib
 * Method:    openConnection
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_daisy_pipeline_tts_onecore_OnecoreLib_openConnection
  (JNIEnv *, jclass);

/*
 * Class:     org_daisy_pipeline_tts_onecore_OnecoreLib
 * Method:    closeConnection
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_daisy_pipeline_tts_onecore_OnecoreLib_closeConnection
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_daisy_pipeline_tts_onecore_OnecoreLib
 * Method:    speak
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_daisy_pipeline_tts_onecore_OnecoreLib_speak
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring);

/*
 * Class:     org_daisy_pipeline_tts_onecore_OnecoreLib
 * Method:    getStreamSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_daisy_pipeline_tts_onecore_OnecoreLib_getStreamSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_daisy_pipeline_tts_onecore_OnecoreLib
 * Method:    readStream
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_org_daisy_pipeline_tts_onecore_OnecoreLib_readStream
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     org_daisy_pipeline_tts_onecore_OnecoreLib
 * Method:    getVoiceVendors
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_daisy_pipeline_tts_onecore_OnecoreLib_getVoiceVendors
  (JNIEnv *, jclass);

/*
 * Class:     org_daisy_pipeline_tts_onecore_OnecoreLib
 * Method:    getVoiceNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_daisy_pipeline_tts_onecore_OnecoreLib_getVoiceNames
  (JNIEnv *, jclass);

/*
 * Class:     org_daisy_pipeline_tts_onecore_OnecoreLib
 * Method:    getVoiceLocales
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_daisy_pipeline_tts_onecore_OnecoreLib_getVoiceLocales
  (JNIEnv *, jclass);

/*
 * Class:     org_daisy_pipeline_tts_onecore_OnecoreLib
 * Method:    getVoiceGenders
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_daisy_pipeline_tts_onecore_OnecoreLib_getVoiceGenders
  (JNIEnv *, jclass);

/*
 * Class:     org_daisy_pipeline_tts_onecore_OnecoreLib
 * Method:    getVoiceAges
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_daisy_pipeline_tts_onecore_OnecoreLib_getVoiceAges
  (JNIEnv *, jclass);

/*
 * Class:     org_daisy_pipeline_tts_onecore_OnecoreLib
 * Method:    getBookmarkNames
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_daisy_pipeline_tts_onecore_OnecoreLib_getBookmarkNames
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_daisy_pipeline_tts_onecore_OnecoreLib
 * Method:    getBookmarkPositions
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_daisy_pipeline_tts_onecore_OnecoreLib_getBookmarkPositions
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_daisy_pipeline_tts_onecore_OnecoreLib
 * Method:    initialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_daisy_pipeline_tts_onecore_OnecoreLib_initialize
  (JNIEnv *, jclass);

/*
 * Class:     org_daisy_pipeline_tts_onecore_OnecoreLib
 * Method:    dispose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_daisy_pipeline_tts_onecore_OnecoreLib_dispose
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
