/* DO NOT EDIT THIS FILE - it is machine generated */

/* Header for class org_daisy_pipeline_tts_onecore_Onecore */

#ifndef _Included_org_daisy_pipeline_tts_onecore_Onecore
#define _Included_org_daisy_pipeline_tts_onecore_Onecore
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_daisy_pipeline_tts_onecore_Onecore
 * Method:    getVoices
 * Signature: ()[Lorg/daisy/pipeline/tts/Voice;
 */
JNIEXPORT jobjectArray JNICALL Java_org_daisy_pipeline_tts_onecore_Onecore_getVoices
	(JNIEnv*, jclass);

/*
 * Class:     org_daisy_pipeline_tts_onecore_Onecore
 * Method:    speak
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lorg/daisy/pipeline/tts/onecore/NativeSynthesisResult
 */
JNIEXPORT jobject JNICALL Java_org_daisy_pipeline_tts_onecore_Onecore_speak
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     org_daisy_pipeline_tts_onecore_Onecore
 * Method:    initialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_daisy_pipeline_tts_onecore_Onecore_initialize
  (JNIEnv *, jclass);

/*
 * Class:     org_daisy_pipeline_tts_onecore_Onecore
 * Method:    dispose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_daisy_pipeline_tts_onecore_Onecore_dispose
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
