modules/daisy202-to-daisy3/.test modules/daisy202-to-daisy3/.install modules/daisy202-to-daisy3/.install-doc $(TARGET_DIR)/state/modules/daisy202-to-daisy3/modified-since-release_ : \
	modules/daisy202-to-daisy3/src/main/resources/META-INF/catalog.xml \
	modules/daisy202-to-daisy3/src/main/resources/xml/d202ncc_Z2005ncx.xsl \
	modules/daisy202-to-daisy3/src/main/resources/xml/daisy202-to-daisy3.script.xpl \
	modules/daisy202-to-daisy3/src/main/resources/xml/daisy202-to-daisy3.xpl \
	modules/daisy202-to-daisy3/src/main/resources/xml/text.res \
	modules/daisy202-to-daisy3/src/main/resources/xml/ncc-to-oebps-metadata.xpl \
	modules/daisy202-to-daisy3/src/main/resources/xml/ncc-to-oebps-metadata.xsl \
	modules/daisy202-to-daisy3/src/main/resources/xml/d202smil_Z2005smil.xsl
modules/daisy202-to-daisy3/.test modules/daisy202-to-daisy3/.install-doc : \
	modules/daisy202-to-daisy3/src/test/resources/logback.xml \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy-nccOnly/speechgen0001.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy-nccOnly/speechgen0006.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy-nccOnly/speechgen0007.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy-nccOnly/speechgen0004.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy-nccOnly/speechgen0003.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy-nccOnly/speechgen0002.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy-nccOnly/speechgen0001.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy-nccOnly/default.css \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy-nccOnly/speechgen0005.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy-nccOnly/speechgen0004.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy-nccOnly/speechgen0006.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy-nccOnly/speechgen0007.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy-nccOnly/speechgen0005.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy-nccOnly/speechgen0002.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy-nccOnly/speechgen0003.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy-nccOnly/ncc.html \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy/speechgen0001.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy/speechgen0006.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy/speechgen0007.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy/speechgen0004.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy/speechgen0003.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy/speechgen0002.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy/speechgen0001.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy/default.css \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy/speechgen0005.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy/speechgen0004.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy/tpbnarrator_res.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy/speechgen0006.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy/speechgen0007.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy/speechgen0005.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy/speechgen0002.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy/speechgen0003.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy/content.html \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy/ncc.html \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy-nccOnly/speechgen0001.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy-nccOnly/speechgen0006.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy-nccOnly/speechgen0007.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy-nccOnly/speechgen0004.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy-nccOnly/speechgen0003.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy-nccOnly/speechgen0002.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy-nccOnly/speechgen0001.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy-nccOnly/text.res \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy-nccOnly/speechgen0005.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy-nccOnly/navigation.ncx \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy-nccOnly/speechgen0004.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy-nccOnly/speechgen0006.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy-nccOnly/speechgen0007.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy-nccOnly/speechgen0005.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy-nccOnly/speechgen0002.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy-nccOnly/speechgen0003.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy-nccOnly/package.opf \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy/dtbook.2005.basic.css \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy/speechgen0001.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy/speechgen0006.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy/content.xml \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy/speechgen0007.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy/speechgen0004.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy/speechgen0003.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy/speechgen0002.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy/speechgen0001.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy/text.res \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy/speechgen0005.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy/navigation.ncx \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy/speechgen0004.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy/speechgen0006.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy/speechgen0007.mp3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy/speechgen0005.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy/speechgen0002.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy/speechgen0003.smil \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy/package.opf \
	modules/daisy202-to-daisy3/src/test/java/XProcSpecTest.java \
	modules/daisy202-to-daisy3/src/test/xprocspec/test_daisy202-to-daisy3.xprocspec \
	modules/daisy202-to-daisy3/src/test/xprocspec/test_daisy202-to-daisy3.script.xprocspec
modules/daisy202-to-daisy3/.install-doc : \
	modules/daisy202-to-daisy3/doc/index.md
.make/mk/modules/daisy202-to-daisy3/sources.mk : \
	modules/daisy202-to-daisy3/src \
	modules/daisy202-to-daisy3/src/test \
	modules/daisy202-to-daisy3/src/test/resources \
	modules/daisy202-to-daisy3/src/test/resources/daisy202 \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy-nccOnly \
	modules/daisy202-to-daisy3/src/test/resources/daisy202/dontworrybehappy \
	modules/daisy202-to-daisy3/src/test/resources/daisy3 \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy-nccOnly \
	modules/daisy202-to-daisy3/src/test/resources/daisy3/dontworrybehappy \
	modules/daisy202-to-daisy3/src/test/java \
	modules/daisy202-to-daisy3/src/test/xprocspec \
	modules/daisy202-to-daisy3/src/main \
	modules/daisy202-to-daisy3/src/main/resources \
	modules/daisy202-to-daisy3/src/main/resources/META-INF \
	modules/daisy202-to-daisy3/src/main/resources/xml \
	modules/daisy202-to-daisy3/doc
