framework/framework-core/.test framework/framework-core/.install framework/framework-core/.install-doc $(TARGET_DIR)/state/framework/framework-core/modified-since-release_ : \
	framework/framework-core/src/main/resources/org/daisy/pipeline/datatypes/resources/data-type.rng \
	framework/framework-core/src/main/resources/org/daisy/pipeline/datatypes/resources/data-type.normalize-space.xsl \
	framework/framework-core/src/main/resources/org/daisy/pipeline/datatypes/resources/data-type.rnc \
	framework/framework-core/src/main/java/org/daisy/pipeline/clients/Client.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/clients/JobConfigurationStorage.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/clients/WebserviceStorage.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/clients/RequestLog.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/clients/RequestLogEntry.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/clients/ClientStorage.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/datatypes/DatatypeRegistry.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/datatypes/ValidationResult.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/datatypes/UrlBasedDatatypeService.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/datatypes/DatatypeService.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/datatypes/XMLBasedDatatypeService.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/script/ScriptRegistry.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/script/impl/StaxXProcScriptParser.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/script/impl/DynamicResultProvider.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/script/impl/XProcDecorator.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/script/impl/StaxXProcPipelineInfoParser.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/script/impl/StatusResultProvider.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/script/impl/XProcScriptConstants.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/script/impl/package-info.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/script/XProcOptionMetadata.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/script/BoundScript.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/script/ScriptInput.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/script/ScriptServiceProvider.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/script/ScriptService.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/script/XProcScript.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/script/XProcScriptService.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/script/XProcPortMetadata.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/script/ScriptOption.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/script/Script.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/script/ScriptPort.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/script/package-info.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/impl/DefaultJobExecutionService.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/impl/FilteredJobQueue.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/impl/VolatileJob.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/impl/IOHelper.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/impl/fuzzy/FuzzyJobFactory.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/impl/fuzzy/FuzzyPriorityCalculator.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/impl/VolatileJobStorage.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/impl/JobExecutionService.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/impl/JobURIUtils.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/impl/DefaultJobBuilder.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/impl/DefaultJobManager.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/impl/DefaultJobQueue.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/impl/JobMessageAccessorFromStorage.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/JobResourcesDir.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/JobResources.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/JobIdGenerator.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/JobMonitorFactory.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/Job.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/JobQueue.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/JobResult.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/JobMonitor.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/AbstractJobContext.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/JobResultSet.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/AbstractJob.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/ZippedJobResources.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/JobURIUtils.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/JobStorage.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/JobUUIDGenerator.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/JobManager.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/JobSize.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/JobId.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/JobBatchId.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/JobFactory.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/StatusNotifier.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/JobIdFactory.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/JobManagerFactory.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/package-info.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/event/impl/VolatileMessageStorage.java \
	framework/framework-core/src/main/java/org/daisy/pipeline/event/MessageStorage.java
framework/framework-core/.test framework/framework-core/.install-doc : \
	framework/framework-core/src/test/resources/logback.xml \
	framework/framework-core/src/test/resources/script.xpl \
	framework/framework-core/src/test/resources/test/folder/3.txt \
	framework/framework-core/src/test/resources/test/folder/2.txt \
	framework/framework-core/src/test/resources/test/1.txt \
	framework/framework-core/src/test/resources/META-INF/catalog.xml \
	framework/framework-core/src/test/resources/test.zip \
	framework/framework-core/src/test/resources/OSGI-INF/script.xml \
	framework/framework-core/src/test/resources/OSGI-INF/xproc-engine.xml \
	framework/framework-core/src/test/resources/OSGI-INF/datatype.xml \
	framework/framework-core/src/test/resources/datatype.xml \
	framework/framework-core/src/test/java/MockXProcEngine.java \
	framework/framework-core/src/test/java/org/daisy/pipeline/datatypes/ValidationResultTest.java \
	framework/framework-core/src/test/java/org/daisy/pipeline/script/impl/XProcPipelineInfoParserTest.java \
	framework/framework-core/src/test/java/org/daisy/pipeline/script/impl/DynamicResultProviderPartsTest.java \
	framework/framework-core/src/test/java/org/daisy/pipeline/script/impl/DynamicResultProviderTest.java \
	framework/framework-core/src/test/java/org/daisy/pipeline/script/impl/XProcDecoratorTest.java \
	framework/framework-core/src/test/java/org/daisy/pipeline/script/impl/XProcScriptParserTest.java \
	framework/framework-core/src/test/java/org/daisy/pipeline/script/StatusPortTest.java \
	framework/framework-core/src/test/java/org/daisy/pipeline/script/JobResultSetBuilderTest.java \
	framework/framework-core/src/test/java/org/daisy/pipeline/job/impl/DefaultJobExecutionServiceTest.java \
	framework/framework-core/src/test/java/org/daisy/pipeline/job/impl/VolatileClient.java \
	framework/framework-core/src/test/java/org/daisy/pipeline/job/impl/VolatileJobStorageTest.java \
	framework/framework-core/src/test/java/org/daisy/pipeline/job/impl/fuzzy/FuzzyPriorityCalculatorTest.java \
	framework/framework-core/src/test/java/org/daisy/pipeline/job/impl/fuzzy/FuzzyJobFactoryTest.java \
	framework/framework-core/src/test/java/org/daisy/pipeline/job/impl/DefaultExecutionQueueTest.java \
	framework/framework-core/src/test/java/org/daisy/pipeline/job/impl/JobURIUtilsTest.java \
	framework/framework-core/src/test/java/org/daisy/pipeline/job/impl/ZipResourceContextTest.java \
	framework/framework-core/src/test/java/org/daisy/pipeline/job/impl/Mock.java \
	framework/framework-core/src/test/java/org/daisy/pipeline/job/JobSizeTest.java \
	framework/framework-core/src/test/java/org/daisy/pipeline/job/JobResultTest.java \
	framework/framework-core/src/test/java/org/daisy/pipeline/job/JobResultSetTest.java \
	framework/framework-core/src/test/java/org/daisy/pipeline/event/impl/VolatileMessageAccessorTest.java \
	framework/framework-core/src/test/java/org/daisy/pipeline/event/impl/VolatileMessageStorageTest.java \
	framework/framework-core/src/test/java/FrameworkCoreTest.java
.make/mk/framework/framework-core/sources.mk : \
	framework/framework-core/src \
	framework/framework-core/src/test \
	framework/framework-core/src/test/resources \
	framework/framework-core/src/test/resources/test \
	framework/framework-core/src/test/resources/test/folder \
	framework/framework-core/src/test/resources/META-INF \
	framework/framework-core/src/test/resources/OSGI-INF \
	framework/framework-core/src/test/java \
	framework/framework-core/src/test/java/org \
	framework/framework-core/src/test/java/org/daisy \
	framework/framework-core/src/test/java/org/daisy/pipeline \
	framework/framework-core/src/test/java/org/daisy/pipeline/datatypes \
	framework/framework-core/src/test/java/org/daisy/pipeline/script \
	framework/framework-core/src/test/java/org/daisy/pipeline/script/impl \
	framework/framework-core/src/test/java/org/daisy/pipeline/job \
	framework/framework-core/src/test/java/org/daisy/pipeline/job/impl \
	framework/framework-core/src/test/java/org/daisy/pipeline/job/impl/fuzzy \
	framework/framework-core/src/test/java/org/daisy/pipeline/event \
	framework/framework-core/src/test/java/org/daisy/pipeline/event/impl \
	framework/framework-core/src/main \
	framework/framework-core/src/main/resources \
	framework/framework-core/src/main/resources/org \
	framework/framework-core/src/main/resources/org/daisy \
	framework/framework-core/src/main/resources/org/daisy/pipeline \
	framework/framework-core/src/main/resources/org/daisy/pipeline/datatypes \
	framework/framework-core/src/main/resources/org/daisy/pipeline/datatypes/resources \
	framework/framework-core/src/main/java \
	framework/framework-core/src/main/java/org \
	framework/framework-core/src/main/java/org/daisy \
	framework/framework-core/src/main/java/org/daisy/pipeline \
	framework/framework-core/src/main/java/org/daisy/pipeline/clients \
	framework/framework-core/src/main/java/org/daisy/pipeline/datatypes \
	framework/framework-core/src/main/java/org/daisy/pipeline/script \
	framework/framework-core/src/main/java/org/daisy/pipeline/script/impl \
	framework/framework-core/src/main/java/org/daisy/pipeline/job \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/impl \
	framework/framework-core/src/main/java/org/daisy/pipeline/job/impl/fuzzy \
	framework/framework-core/src/main/java/org/daisy/pipeline/event \
	framework/framework-core/src/main/java/org/daisy/pipeline/event/impl
