framework/common-utils/.test framework/common-utils/.install framework/common-utils/.install-doc $(TARGET_DIR)/state/framework/common-utils/modified-since-release_ : \
	framework/common-utils/src/main/resources/org/daisy/pipeline/logging/jul-to-slf4j.xml \
	framework/common-utils/src/main/java/org/daisy/common/stax/DelegatingXMLStreamReader.java \
	framework/common-utils/src/main/java/org/daisy/common/stax/DelegatingXMLStreamWriter.java \
	framework/common-utils/src/main/java/org/daisy/common/stax/StaxEventHelper.java \
	framework/common-utils/src/main/java/org/daisy/common/stax/DelegatingBaseURIAwareXMLStreamReader.java \
	framework/common-utils/src/main/java/org/daisy/common/stax/DelegatingBaseURIAwareXMLStreamWriter.java \
	framework/common-utils/src/main/java/org/daisy/common/stax/XMLStreamWriterHelper.java \
	framework/common-utils/src/main/java/org/daisy/common/stax/BaseURIAwareXMLStreamWriter.java \
	framework/common-utils/src/main/java/org/daisy/common/stax/EventProcessor.java \
	framework/common-utils/src/main/java/org/daisy/common/stax/BaseURIAwareXMLStreamReader.java \
	framework/common-utils/src/main/java/org/daisy/common/stax/package-info.java \
	framework/common-utils/src/main/java/org/daisy/common/file/URLs.java \
	framework/common-utils/src/main/java/org/daisy/common/file/Resource.java \
	framework/common-utils/src/main/java/org/daisy/common/file/Files.java \
	framework/common-utils/src/main/java/org/daisy/common/slf4j/AbstractLogger.java \
	framework/common-utils/src/main/java/org/daisy/common/shell/CommandRunner.java \
	framework/common-utils/src/main/java/org/daisy/common/shell/BinaryFinder.java \
	framework/common-utils/src/main/java/org/daisy/common/fuzzy/FuzzySet.java \
	framework/common-utils/src/main/java/org/daisy/common/fuzzy/MembershipFunctions.java \
	framework/common-utils/src/main/java/org/daisy/common/fuzzy/FuzzyVariable.java \
	framework/common-utils/src/main/java/org/daisy/common/fuzzy/package-info.java \
	framework/common-utils/src/main/java/org/daisy/common/fuzzy/InferenceEngine.java \
	framework/common-utils/src/main/java/org/daisy/common/java/JarIsolatedClassLoader.java \
	framework/common-utils/src/main/java/org/daisy/common/xml/DocumentBuilder.java \
	framework/common-utils/src/main/java/org/daisy/common/zip/ZipUtils.java \
	framework/common-utils/src/main/java/org/daisy/common/properties/Properties.java \
	framework/common-utils/src/main/java/org/daisy/common/priority/UpdatablePriorityBlockingQueue.java \
	framework/common-utils/src/main/java/org/daisy/common/priority/PriorityThreadPoolExecutor.java \
	framework/common-utils/src/main/java/org/daisy/common/priority/Prioritizable.java \
	framework/common-utils/src/main/java/org/daisy/common/priority/ForwardingPrioritableRunnable.java \
	framework/common-utils/src/main/java/org/daisy/common/priority/PriorityCalculator.java \
	framework/common-utils/src/main/java/org/daisy/common/priority/timetracking/LinearTimeNormalizer.java \
	framework/common-utils/src/main/java/org/daisy/common/priority/timetracking/TimeFunctionFactory.java \
	framework/common-utils/src/main/java/org/daisy/common/priority/timetracking/TimeTrackerFactory.java \
	framework/common-utils/src/main/java/org/daisy/common/priority/timetracking/TimeFunctions.java \
	framework/common-utils/src/main/java/org/daisy/common/priority/timetracking/TimeTracker.java \
	framework/common-utils/src/main/java/org/daisy/common/priority/timetracking/TimeStats.java \
	framework/common-utils/src/main/java/org/daisy/common/priority/timetracking/package-info.java \
	framework/common-utils/src/main/java/org/daisy/common/priority/WrappingPriorityQueue.java \
	framework/common-utils/src/main/java/org/daisy/common/priority/package-info.java \
	framework/common-utils/src/main/java/org/daisy/common/priority/PrioritizableRunnable.java \
	framework/common-utils/src/main/java/org/daisy/common/priority/Priority.java \
	framework/common-utils/src/main/java/org/daisy/common/priority/PrioritizableComparator.java \
	framework/common-utils/src/main/java/org/daisy/common/messaging/Message.java \
	framework/common-utils/src/main/java/org/daisy/common/messaging/ProgressMessage.java \
	framework/common-utils/src/main/java/org/daisy/common/messaging/AbstractLogger.java \
	framework/common-utils/src/main/java/org/daisy/common/messaging/AbstractMessageAccessor.java \
	framework/common-utils/src/main/java/org/daisy/common/messaging/MessageBus.java \
	framework/common-utils/src/main/java/org/daisy/common/messaging/MessageImpl.java \
	framework/common-utils/src/main/java/org/daisy/common/messaging/MessageBuilder.java \
	framework/common-utils/src/main/java/org/daisy/common/messaging/MessageFilterImpl.java \
	framework/common-utils/src/main/java/org/daisy/common/messaging/MessageAppender.java \
	framework/common-utils/src/main/java/org/daisy/common/messaging/MessageAccessor.java \
	framework/common-utils/src/main/java/org/daisy/common/transform/LazySaxResultProvider.java \
	framework/common-utils/src/main/java/org/daisy/common/transform/LazySaxSourceProvider.java \
	framework/common-utils/src/main/java/org/daisy/common/transform/Mult.java \
	framework/common-utils/src/main/java/org/daisy/common/transform/InputValue.java \
	framework/common-utils/src/main/java/org/daisy/common/transform/XMLTransformer.java \
	framework/common-utils/src/main/java/org/daisy/common/transform/XMLInputValue.java \
	framework/common-utils/src/main/java/org/daisy/common/transform/StringWithNamespaceContext.java \
	framework/common-utils/src/main/java/org/daisy/common/transform/SingleInSingleOutXMLTransformer.java \
	framework/common-utils/src/main/java/org/daisy/common/transform/Buffer.java \
	framework/common-utils/src/main/java/org/daisy/common/transform/OutputValue.java \
	framework/common-utils/src/main/java/org/daisy/common/transform/XMLOutputValue.java \
	framework/common-utils/src/main/java/org/daisy/common/transform/TransformerException.java \
	framework/common-utils/src/main/java/org/daisy/common/logging/impl/JulToSlf4jBridgeSetup.java
framework/common-utils/.test framework/common-utils/.install-doc : \
	framework/common-utils/src/test/resources/logback.xml \
	framework/common-utils/src/test/resources/dir/subdir/file3 \
	framework/common-utils/src/test/resources/dir/file\ 2 \
	framework/common-utils/src/test/resources/dir/file1 \
	framework/common-utils/src/test/java/org/daisy/common/file/URLsTest.java \
	framework/common-utils/src/test/java/org/daisy/common/file/MockFile.java \
	framework/common-utils/src/test/java/org/daisy/common/shell/BinaryFinderTest.java \
	framework/common-utils/src/test/java/org/daisy/common/fuzzy/InferenceEngineTest.java \
	framework/common-utils/src/test/java/org/daisy/common/fuzzy/FuzzySetTest.java \
	framework/common-utils/src/test/java/org/daisy/common/fuzzy/InferenceEngineBenchmarksTest.java \
	framework/common-utils/src/test/java/org/daisy/common/fuzzy/MembershipFunctionsTest.java \
	framework/common-utils/src/test/java/org/daisy/common/fuzzy/FuzzyVariableTest.java \
	framework/common-utils/src/test/java/org/daisy/common/zip/ZipUtilsTest.java \
	framework/common-utils/src/test/java/org/daisy/common/priority/PriorityTest.java \
	framework/common-utils/src/test/java/org/daisy/common/priority/PrioritizableRunnableTest.java \
	framework/common-utils/src/test/java/org/daisy/common/priority/PrioritizableComparatorTest.java \
	framework/common-utils/src/test/java/org/daisy/common/priority/UpdatablePriorityBlockingQueueTest.java \
	framework/common-utils/src/test/java/org/daisy/common/priority/timetracking/LinearTimeNormalizerTest.java \
	framework/common-utils/src/test/java/org/daisy/common/priority/timetracking/TimeTrackerTest.java \
	framework/common-utils/src/test/java/org/daisy/common/priority/timetracking/TimeTrackingTest.java \
	framework/common-utils/src/test/java/org/daisy/common/priority/timetracking/TimeStatsTest.java \
	framework/common-utils/src/test/java/URLsTest.java \
	framework/common-utils/src/test/java/PatternMatcher.java
.make/mk/framework/common-utils/sources.mk : \
	framework/common-utils/src \
	framework/common-utils/src/test \
	framework/common-utils/src/test/resources \
	framework/common-utils/src/test/resources/dir \
	framework/common-utils/src/test/resources/dir/subdir \
	framework/common-utils/src/test/java \
	framework/common-utils/src/test/java/org \
	framework/common-utils/src/test/java/org/daisy \
	framework/common-utils/src/test/java/org/daisy/common \
	framework/common-utils/src/test/java/org/daisy/common/file \
	framework/common-utils/src/test/java/org/daisy/common/shell \
	framework/common-utils/src/test/java/org/daisy/common/fuzzy \
	framework/common-utils/src/test/java/org/daisy/common/zip \
	framework/common-utils/src/test/java/org/daisy/common/priority \
	framework/common-utils/src/test/java/org/daisy/common/priority/timetracking \
	framework/common-utils/src/main \
	framework/common-utils/src/main/resources \
	framework/common-utils/src/main/resources/org \
	framework/common-utils/src/main/resources/org/daisy \
	framework/common-utils/src/main/resources/org/daisy/pipeline \
	framework/common-utils/src/main/resources/org/daisy/pipeline/logging \
	framework/common-utils/src/main/java \
	framework/common-utils/src/main/java/org \
	framework/common-utils/src/main/java/org/daisy \
	framework/common-utils/src/main/java/org/daisy/common \
	framework/common-utils/src/main/java/org/daisy/common/stax \
	framework/common-utils/src/main/java/org/daisy/common/file \
	framework/common-utils/src/main/java/org/daisy/common/slf4j \
	framework/common-utils/src/main/java/org/daisy/common/shell \
	framework/common-utils/src/main/java/org/daisy/common/fuzzy \
	framework/common-utils/src/main/java/org/daisy/common/java \
	framework/common-utils/src/main/java/org/daisy/common/xml \
	framework/common-utils/src/main/java/org/daisy/common/zip \
	framework/common-utils/src/main/java/org/daisy/common/properties \
	framework/common-utils/src/main/java/org/daisy/common/priority \
	framework/common-utils/src/main/java/org/daisy/common/priority/timetracking \
	framework/common-utils/src/main/java/org/daisy/common/messaging \
	framework/common-utils/src/main/java/org/daisy/common/transform \
	framework/common-utils/src/main/java/org/daisy/common/logging \
	framework/common-utils/src/main/java/org/daisy/common/logging/impl
