name: compile for all platforms
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.21.3'
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build
        run: mvn --batch-mode clean verify
      - name: Upload the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "cli"
          path: target/*.zip
