MVN_LOCAL_REPOSITORY := .maven-workspace
export MVN_LOCAL_REPOSITORY
MAVEN_AGGREGATORS += .
MAVEN_AGGREGATORS += utils/build-utils
MAVEN_AGGREGATORS += utils/build-utils/ds-to-spi
MAVEN_AGGREGATORS += utils/build-utils/archetypes
MAVEN_AGGREGATORS += utils/xspec-maven-plugin
MAVEN_AGGREGATORS += utils/xproc-maven-plugin
MAVEN_AGGREGATORS += libs/osgi-libs
MAVEN_AGGREGATORS += framework
MAVEN_AGGREGATORS += modules
MAVEN_AGGREGATORS += clientlib/java
MAVEN_MODULES += framework/bom
MAVEN_MODULES += modules/bom
MAVEN_MODULES += utils/daisy-parent/daisy-parent
MAVEN_MODULES += utils/build-utils/modules-build-helper
MAVEN_MODULES += utils/build-utils/modules-test-helper
MAVEN_MODULES += utils/build-utils/ds-to-spi/ds-to-spi-annotations
MAVEN_MODULES += utils/build-utils/ds-to-spi/ds-to-spi-annotations-processor
MAVEN_MODULES += utils/build-utils/ds-to-spi/ds-to-spi-runtime
MAVEN_MODULES += utils/build-utils/ds-to-spi/ds-to-spi-maven-plugin
MAVEN_MODULES += utils/build-utils/archetypes/basic-module
MAVEN_MODULES += utils/xspec-maven-plugin/xspec-runner
MAVEN_MODULES += utils/xspec-maven-plugin/xspec-maven-plugin
MAVEN_MODULES += utils/xprocspec
MAVEN_MODULES += utils/xproc-maven-plugin/xproc-engine-api
MAVEN_MODULES += utils/xproc-maven-plugin/xproc-engine-calabash
MAVEN_MODULES += utils/xproc-maven-plugin/xprocspec-runner
MAVEN_MODULES += utils/xproc-maven-plugin/xproc-maven-plugin
MAVEN_MODULES += libs/jstyleparser
MAVEN_MODULES += libs/braille-css
MAVEN_MODULES += libs/osgi-libs/jing
MAVEN_MODULES += libs/osgi-libs/jnaerator
MAVEN_MODULES += libs/osgi-libs/parboiled
MAVEN_MODULES += libs/osgi-libs/pegdown
MAVEN_MODULES += libs/osgi-libs/saxon
MAVEN_MODULES += libs/osgi-libs/servlet-api
MAVEN_MODULES += framework/parent
MAVEN_MODULES += framework/utils/clientlib-java-jaxb
MAVEN_MODULES += framework/utils/xproc-engine-daisy-pipeline
MAVEN_MODULES += framework/utils/xproc-engine-daisy-pipeline-logging
MAVEN_MODULES += framework/saxon-adapter
MAVEN_MODULES += framework/calabash-adapter
MAVEN_MODULES += framework/common-utils
MAVEN_MODULES += framework/framework-core
MAVEN_MODULES += framework/framework-persistence
MAVEN_MODULES += framework/logging-appender
MAVEN_MODULES += framework/modules-registry
MAVEN_MODULES += framework/persistence-derby
MAVEN_MODULES += framework/webservice
MAVEN_MODULES += framework/xproc-api
MAVEN_MODULES += framework/pipeline1-adapter
MAVEN_MODULES += modules/parent
MAVEN_MODULES += modules/common/common-utils
MAVEN_MODULES += modules/common/file-utils
MAVEN_MODULES += modules/common/fileset-utils
MAVEN_MODULES += modules/common/image-utils
MAVEN_MODULES += modules/common/mediatype-utils
MAVEN_MODULES += modules/common/validation-utils
MAVEN_MODULES += modules/common/zip-utils
MAVEN_MODULES += modules/scripts-utils/ace-adapter
MAVEN_MODULES += modules/scripts-utils/asciimath-utils
MAVEN_MODULES += modules/scripts-utils/css-utils
MAVEN_MODULES += modules/scripts-utils/html-utils
MAVEN_MODULES += modules/scripts-utils/daisy202-utils
MAVEN_MODULES += modules/scripts-utils/daisy3-utils
MAVEN_MODULES += modules/scripts-utils/dtbook-utils
MAVEN_MODULES += modules/scripts-utils/epub-utils
MAVEN_MODULES += modules/scripts-utils/epubcheck-adapter
MAVEN_MODULES += modules/scripts-utils/epub3-to-html
MAVEN_MODULES += modules/scripts-utils/mathml-utils
MAVEN_MODULES += modules/scripts-utils/mathcat-adapter
MAVEN_MODULES += modules/scripts-utils/smil-utils
MAVEN_MODULES += modules/scripts-utils/metadata-utils
MAVEN_MODULES += modules/scripts-utils/ocr-utils
MAVEN_MODULES += modules/scripts-utils/odf-utils
MAVEN_MODULES += modules/scripts-utils/pandoc-adapter
MAVEN_MODULES += modules/scripts-utils/zedai-utils
MAVEN_MODULES += modules/nlp/nlp-common
MAVEN_MODULES += modules/nlp/lexers/ruled-lexer
MAVEN_MODULES += modules/nlp/lexers/light-lexer
MAVEN_MODULES += modules/nlp/lexers/omnilang-lexer
MAVEN_MODULES += modules/audio/audio-common
MAVEN_MODULES += modules/audio/audio-encoder-lame
MAVEN_MODULES += modules/tts/tts-common
MAVEN_MODULES += modules/tts/tts-adapter-espeak
MAVEN_MODULES += modules/tts/tts-adapter-acapela
MAVEN_MODULES += modules/tts/tts-adapter-osx
MAVEN_MODULES += modules/tts/tts-adapter-sapinative
MAVEN_MODULES += modules/tts/tts-adapter-qfrency
MAVEN_MODULES += modules/tts/tts-adapter-google
MAVEN_MODULES += modules/tts/tts-adapter-cereproc
MAVEN_MODULES += modules/tts/tts-adapter-azure
MAVEN_MODULES += modules/tts/tts-adapter-aws
MAVEN_MODULES += modules/tts/tts-mocks
MAVEN_MODULES += modules/braille/braille-common
MAVEN_MODULES += modules/braille/braille-css-utils
MAVEN_MODULES += modules/braille/pef-utils
MAVEN_MODULES += modules/braille/obfl-utils
MAVEN_MODULES += modules/braille/liblouis-utils
MAVEN_MODULES += modules/braille/dotify-utils
MAVEN_MODULES += modules/braille/libhyphen-utils
MAVEN_MODULES += modules/braille/texhyph-utils
MAVEN_MODULES += modules/scripts/daisy202-to-epub3
MAVEN_MODULES += modules/scripts/daisy202-validator
MAVEN_MODULES += modules/scripts/daisy202-to-daisy3
MAVEN_MODULES += modules/scripts/daisy202-to-mp3
MAVEN_MODULES += modules/scripts/daisy3-to-daisy202
MAVEN_MODULES += modules/scripts/daisy3-to-epub3
MAVEN_MODULES += modules/scripts/daisy3-to-mp3
MAVEN_MODULES += modules/scripts/dtbook-to-daisy3
MAVEN_MODULES += modules/scripts/dtbook-to-ebraille
MAVEN_MODULES += modules/scripts/dtbook-to-epub3
MAVEN_MODULES += modules/scripts/dtbook-to-html
MAVEN_MODULES += modules/scripts/dtbook-to-odt
MAVEN_MODULES += modules/scripts/dtbook-to-pef
MAVEN_MODULES += modules/scripts/dtbook-to-rtf
MAVEN_MODULES += modules/scripts/dtbook-to-zedai
MAVEN_MODULES += modules/scripts/dtbook-validator
MAVEN_MODULES += modules/scripts/epub-to-daisy
MAVEN_MODULES += modules/scripts/epub2-to-epub3
MAVEN_MODULES += modules/scripts/epub3-to-daisy202
MAVEN_MODULES += modules/scripts/epub3-to-daisy3
MAVEN_MODULES += modules/scripts/epub3-to-epub3
MAVEN_MODULES += modules/scripts/epub3-to-pef
MAVEN_MODULES += modules/scripts/epub3-validator
MAVEN_MODULES += modules/scripts/html-to-dtbook
MAVEN_MODULES += modules/scripts/html-to-epub3
MAVEN_MODULES += modules/scripts/html-to-pef
MAVEN_MODULES += modules/scripts/nimas-fileset-validator
MAVEN_MODULES += modules/scripts/word-to-dtbook
MAVEN_MODULES += modules/scripts/zedai-to-epub3
MAVEN_MODULES += modules/scripts/zedai-to-html
MAVEN_MODULES += modules/scripts/zedai-to-pef
MAVEN_MODULES += cli
MAVEN_MODULES += assembly
MAVEN_MODULES += website/target/maven
MAVEN_MODULES += clientlib/java/clientlib-java
MAVEN_MODULES += clientlib/java/clientlib-java-httpclient
ifndef FIXED_BUILD
poms : $(TARGET_DIR)/optimized/./pom.xml
poms : $(TARGET_DIR)/optimized/utils/build-utils/pom.xml
poms : $(TARGET_DIR)/optimized/utils/build-utils/ds-to-spi/pom.xml
poms : $(TARGET_DIR)/optimized/utils/build-utils/archetypes/pom.xml
poms : $(TARGET_DIR)/optimized/utils/xspec-maven-plugin/pom.xml
poms : $(TARGET_DIR)/optimized/utils/xproc-maven-plugin/pom.xml
poms : $(TARGET_DIR)/optimized/libs/osgi-libs/pom.xml
poms : $(TARGET_DIR)/optimized/framework/pom.xml
poms : $(TARGET_DIR)/optimized/modules/pom.xml
poms : $(TARGET_DIR)/optimized/clientlib/java/pom.xml
poms : $(TARGET_DIR)/optimized/framework/bom/pom.xml
poms : $(TARGET_DIR)/optimized/modules/bom/pom.xml
poms : utils/daisy-parent/daisy-parent/pom.xml
poms : utils/build-utils/modules-build-helper/pom.xml
poms : utils/build-utils/modules-test-helper/pom.xml
poms : utils/build-utils/ds-to-spi/ds-to-spi-annotations/pom.xml
poms : utils/build-utils/ds-to-spi/ds-to-spi-annotations-processor/pom.xml
poms : utils/build-utils/ds-to-spi/ds-to-spi-runtime/pom.xml
poms : utils/build-utils/ds-to-spi/ds-to-spi-maven-plugin/pom.xml
poms : utils/build-utils/archetypes/basic-module/pom.xml
poms : utils/xspec-maven-plugin/xspec-runner/pom.xml
poms : utils/xspec-maven-plugin/xspec-maven-plugin/pom.xml
poms : utils/xprocspec/pom.xml
poms : utils/xproc-maven-plugin/xproc-engine-api/pom.xml
poms : utils/xproc-maven-plugin/xproc-engine-calabash/pom.xml
poms : utils/xproc-maven-plugin/xprocspec-runner/pom.xml
poms : utils/xproc-maven-plugin/xproc-maven-plugin/pom.xml
poms : libs/jstyleparser/pom.xml
poms : libs/braille-css/pom.xml
poms : libs/osgi-libs/jing/pom.xml
poms : libs/osgi-libs/jnaerator/pom.xml
poms : libs/osgi-libs/parboiled/pom.xml
poms : libs/osgi-libs/pegdown/pom.xml
poms : libs/osgi-libs/saxon/pom.xml
poms : libs/osgi-libs/servlet-api/pom.xml
poms : framework/parent/pom.xml
poms : framework/utils/clientlib-java-jaxb/pom.xml
poms : framework/utils/xproc-engine-daisy-pipeline/pom.xml
poms : framework/utils/xproc-engine-daisy-pipeline-logging/pom.xml
poms : framework/saxon-adapter/pom.xml
poms : framework/calabash-adapter/pom.xml
poms : framework/common-utils/pom.xml
poms : framework/framework-core/pom.xml
poms : framework/framework-persistence/pom.xml
poms : framework/logging-appender/pom.xml
poms : framework/modules-registry/pom.xml
poms : framework/persistence-derby/pom.xml
poms : framework/webservice/pom.xml
poms : framework/xproc-api/pom.xml
poms : framework/pipeline1-adapter/pom.xml
poms : modules/parent/pom.xml
poms : modules/common/common-utils/pom.xml
poms : modules/common/file-utils/pom.xml
poms : modules/common/fileset-utils/pom.xml
poms : modules/common/image-utils/pom.xml
poms : modules/common/mediatype-utils/pom.xml
poms : modules/common/validation-utils/pom.xml
poms : modules/common/zip-utils/pom.xml
poms : modules/scripts-utils/ace-adapter/pom.xml
poms : modules/scripts-utils/asciimath-utils/pom.xml
poms : modules/scripts-utils/css-utils/pom.xml
poms : modules/scripts-utils/html-utils/pom.xml
poms : modules/scripts-utils/daisy202-utils/pom.xml
poms : modules/scripts-utils/daisy3-utils/pom.xml
poms : modules/scripts-utils/dtbook-utils/pom.xml
poms : modules/scripts-utils/epub-utils/pom.xml
poms : modules/scripts-utils/epubcheck-adapter/pom.xml
poms : modules/scripts-utils/epub3-to-html/pom.xml
poms : modules/scripts-utils/mathml-utils/pom.xml
poms : modules/scripts-utils/mathcat-adapter/pom.xml
poms : modules/scripts-utils/smil-utils/pom.xml
poms : modules/scripts-utils/metadata-utils/pom.xml
poms : modules/scripts-utils/ocr-utils/pom.xml
poms : modules/scripts-utils/odf-utils/pom.xml
poms : modules/scripts-utils/pandoc-adapter/pom.xml
poms : modules/scripts-utils/zedai-utils/pom.xml
poms : modules/nlp/nlp-common/pom.xml
poms : modules/nlp/lexers/ruled-lexer/pom.xml
poms : modules/nlp/lexers/light-lexer/pom.xml
poms : modules/nlp/lexers/omnilang-lexer/pom.xml
poms : modules/audio/audio-common/pom.xml
poms : modules/audio/audio-encoder-lame/pom.xml
poms : modules/tts/tts-common/pom.xml
poms : modules/tts/tts-adapter-espeak/pom.xml
poms : modules/tts/tts-adapter-acapela/pom.xml
poms : modules/tts/tts-adapter-osx/pom.xml
poms : modules/tts/tts-adapter-sapinative/pom.xml
poms : modules/tts/tts-adapter-qfrency/pom.xml
poms : modules/tts/tts-adapter-google/pom.xml
poms : modules/tts/tts-adapter-cereproc/pom.xml
poms : modules/tts/tts-adapter-azure/pom.xml
poms : modules/tts/tts-adapter-aws/pom.xml
poms : modules/tts/tts-mocks/pom.xml
poms : modules/braille/braille-common/pom.xml
poms : modules/braille/braille-css-utils/pom.xml
poms : modules/braille/pef-utils/pom.xml
poms : modules/braille/obfl-utils/pom.xml
poms : modules/braille/liblouis-utils/pom.xml
poms : modules/braille/dotify-utils/pom.xml
poms : modules/braille/libhyphen-utils/pom.xml
poms : modules/braille/texhyph-utils/pom.xml
poms : modules/scripts/daisy202-to-epub3/pom.xml
poms : modules/scripts/daisy202-validator/pom.xml
poms : modules/scripts/daisy202-to-daisy3/pom.xml
poms : modules/scripts/daisy202-to-mp3/pom.xml
poms : modules/scripts/daisy3-to-daisy202/pom.xml
poms : modules/scripts/daisy3-to-epub3/pom.xml
poms : modules/scripts/daisy3-to-mp3/pom.xml
poms : modules/scripts/dtbook-to-daisy3/pom.xml
poms : modules/scripts/dtbook-to-ebraille/pom.xml
poms : modules/scripts/dtbook-to-epub3/pom.xml
poms : modules/scripts/dtbook-to-html/pom.xml
poms : modules/scripts/dtbook-to-odt/pom.xml
poms : modules/scripts/dtbook-to-pef/pom.xml
poms : modules/scripts/dtbook-to-rtf/pom.xml
poms : modules/scripts/dtbook-to-zedai/pom.xml
poms : modules/scripts/dtbook-validator/pom.xml
poms : modules/scripts/epub-to-daisy/pom.xml
poms : modules/scripts/epub2-to-epub3/pom.xml
poms : modules/scripts/epub3-to-daisy202/pom.xml
poms : modules/scripts/epub3-to-daisy3/pom.xml
poms : modules/scripts/epub3-to-epub3/pom.xml
poms : modules/scripts/epub3-to-pef/pom.xml
poms : modules/scripts/epub3-validator/pom.xml
poms : modules/scripts/html-to-dtbook/pom.xml
poms : modules/scripts/html-to-epub3/pom.xml
poms : modules/scripts/html-to-pef/pom.xml
poms : modules/scripts/nimas-fileset-validator/pom.xml
poms : modules/scripts/word-to-dtbook/pom.xml
poms : modules/scripts/zedai-to-epub3/pom.xml
poms : modules/scripts/zedai-to-html/pom.xml
poms : modules/scripts/zedai-to-pef/pom.xml
poms : cli/pom.xml
poms : assembly/pom.xml
poms : website/target/maven/pom.xml
poms : clientlib/java/clientlib-java/pom.xml
poms : clientlib/java/clientlib-java-httpclient/pom.xml
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/parent/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/utils/clientlib-java-jaxb/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/utils/xproc-engine-daisy-pipeline/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/utils/xproc-engine-daisy-pipeline-logging/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/saxon-adapter/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/calabash-adapter/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/common-utils/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/framework-core/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/framework-persistence/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/logging-appender/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/modules-registry/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/persistence-derby/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/webservice/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/xproc-api/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/pipeline1-adapter/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/parent/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/common/common-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/common/file-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/common/fileset-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/common/image-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/common/mediatype-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/common/validation-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/common/zip-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts-utils/ace-adapter/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts-utils/asciimath-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts-utils/css-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts-utils/html-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts-utils/daisy202-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts-utils/daisy3-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts-utils/dtbook-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts-utils/epub-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts-utils/epubcheck-adapter/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts-utils/epub3-to-html/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts-utils/mathml-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts-utils/mathcat-adapter/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts-utils/smil-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts-utils/metadata-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts-utils/ocr-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts-utils/odf-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts-utils/pandoc-adapter/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts-utils/zedai-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/nlp/nlp-common/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/nlp/lexers/ruled-lexer/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/nlp/lexers/light-lexer/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/nlp/lexers/omnilang-lexer/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/audio/audio-common/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/audio/audio-encoder-lame/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/tts/tts-common/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/tts/tts-adapter-espeak/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/tts/tts-adapter-acapela/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/tts/tts-adapter-osx/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/tts/tts-adapter-sapinative/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/tts/tts-adapter-qfrency/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/tts/tts-adapter-google/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/tts/tts-adapter-cereproc/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/tts/tts-adapter-azure/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/tts/tts-adapter-aws/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/tts/tts-mocks/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/braille/braille-common/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/braille/braille-css-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/braille/pef-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/braille/obfl-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/braille/liblouis-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/braille/dotify-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/braille/libhyphen-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/braille/texhyph-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/daisy202-to-epub3/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/daisy202-validator/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/daisy202-to-daisy3/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/daisy202-to-mp3/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/daisy3-to-daisy202/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/daisy3-to-epub3/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/daisy3-to-mp3/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/dtbook-to-daisy3/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/dtbook-to-ebraille/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/dtbook-to-epub3/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/dtbook-to-html/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/dtbook-to-odt/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/dtbook-to-pef/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/dtbook-to-rtf/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/dtbook-to-zedai/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/dtbook-validator/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/epub-to-daisy/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/epub2-to-epub3/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/epub3-to-daisy202/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/epub3-to-daisy3/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/epub3-to-epub3/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/epub3-to-pef/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/epub3-validator/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/html-to-dtbook/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/html-to-epub3/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/html-to-pef/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/nimas-fileset-validator/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/word-to-dtbook/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/zedai-to-epub3/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/zedai-to-html/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/scripts/zedai-to-pef/modified-since-release
$(MY_DIR)/mk/maven.mk : ./pom.xml
$(MY_DIR)/mk/maven.mk : utils/build-utils/pom.xml
$(MY_DIR)/mk/maven.mk : utils/build-utils/ds-to-spi/pom.xml
$(MY_DIR)/mk/maven.mk : utils/build-utils/archetypes/pom.xml
$(MY_DIR)/mk/maven.mk : utils/xspec-maven-plugin/pom.xml
$(MY_DIR)/mk/maven.mk : utils/xproc-maven-plugin/pom.xml
$(MY_DIR)/mk/maven.mk : libs/osgi-libs/pom.xml
$(MY_DIR)/mk/maven.mk : framework/pom.xml
$(MY_DIR)/mk/maven.mk : modules/pom.xml
$(MY_DIR)/mk/maven.mk : clientlib/java/pom.xml
$(MY_DIR)/mk/maven.mk : utils/daisy-parent/daisy-parent/pom.xml
$(MY_DIR)/mk/maven.mk : utils/build-utils/modules-build-helper/pom.xml
$(MY_DIR)/mk/maven.mk : utils/build-utils/modules-test-helper/pom.xml
$(MY_DIR)/mk/maven.mk : utils/build-utils/ds-to-spi/ds-to-spi-annotations/pom.xml
$(MY_DIR)/mk/maven.mk : utils/build-utils/ds-to-spi/ds-to-spi-annotations-processor/pom.xml
$(MY_DIR)/mk/maven.mk : utils/build-utils/ds-to-spi/ds-to-spi-runtime/pom.xml
$(MY_DIR)/mk/maven.mk : utils/build-utils/ds-to-spi/ds-to-spi-maven-plugin/pom.xml
$(MY_DIR)/mk/maven.mk : utils/build-utils/archetypes/basic-module/pom.xml
$(MY_DIR)/mk/maven.mk : utils/xspec-maven-plugin/xspec-runner/pom.xml
$(MY_DIR)/mk/maven.mk : utils/xspec-maven-plugin/xspec-maven-plugin/pom.xml
$(MY_DIR)/mk/maven.mk : utils/xprocspec/pom.xml
$(MY_DIR)/mk/maven.mk : utils/xproc-maven-plugin/xproc-engine-api/pom.xml
$(MY_DIR)/mk/maven.mk : utils/xproc-maven-plugin/xproc-engine-calabash/pom.xml
$(MY_DIR)/mk/maven.mk : utils/xproc-maven-plugin/xprocspec-runner/pom.xml
$(MY_DIR)/mk/maven.mk : utils/xproc-maven-plugin/xproc-maven-plugin/pom.xml
$(MY_DIR)/mk/maven.mk : libs/jstyleparser/pom.xml
$(MY_DIR)/mk/maven.mk : libs/braille-css/pom.xml
$(MY_DIR)/mk/maven.mk : libs/osgi-libs/jing/pom.xml
$(MY_DIR)/mk/maven.mk : libs/osgi-libs/jnaerator/pom.xml
$(MY_DIR)/mk/maven.mk : libs/osgi-libs/parboiled/pom.xml
$(MY_DIR)/mk/maven.mk : libs/osgi-libs/pegdown/pom.xml
$(MY_DIR)/mk/maven.mk : libs/osgi-libs/saxon/pom.xml
$(MY_DIR)/mk/maven.mk : libs/osgi-libs/servlet-api/pom.xml
$(MY_DIR)/mk/maven.mk : framework/parent/pom.xml
$(MY_DIR)/mk/maven.mk : framework/utils/clientlib-java-jaxb/pom.xml
$(MY_DIR)/mk/maven.mk : framework/utils/xproc-engine-daisy-pipeline/pom.xml
$(MY_DIR)/mk/maven.mk : framework/utils/xproc-engine-daisy-pipeline-logging/pom.xml
$(MY_DIR)/mk/maven.mk : framework/saxon-adapter/pom.xml
$(MY_DIR)/mk/maven.mk : framework/calabash-adapter/pom.xml
$(MY_DIR)/mk/maven.mk : framework/common-utils/pom.xml
$(MY_DIR)/mk/maven.mk : framework/framework-core/pom.xml
$(MY_DIR)/mk/maven.mk : framework/framework-persistence/pom.xml
$(MY_DIR)/mk/maven.mk : framework/logging-appender/pom.xml
$(MY_DIR)/mk/maven.mk : framework/modules-registry/pom.xml
$(MY_DIR)/mk/maven.mk : framework/persistence-derby/pom.xml
$(MY_DIR)/mk/maven.mk : framework/webservice/pom.xml
$(MY_DIR)/mk/maven.mk : framework/xproc-api/pom.xml
$(MY_DIR)/mk/maven.mk : framework/pipeline1-adapter/pom.xml
$(MY_DIR)/mk/maven.mk : modules/parent/pom.xml
$(MY_DIR)/mk/maven.mk : modules/common/common-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/common/file-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/common/fileset-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/common/image-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/common/mediatype-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/common/validation-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/common/zip-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts-utils/ace-adapter/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts-utils/asciimath-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts-utils/css-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts-utils/html-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts-utils/daisy202-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts-utils/daisy3-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts-utils/dtbook-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts-utils/epub-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts-utils/epubcheck-adapter/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts-utils/epub3-to-html/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts-utils/mathml-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts-utils/mathcat-adapter/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts-utils/smil-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts-utils/metadata-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts-utils/ocr-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts-utils/odf-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts-utils/pandoc-adapter/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts-utils/zedai-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/nlp/nlp-common/pom.xml
$(MY_DIR)/mk/maven.mk : modules/nlp/lexers/ruled-lexer/pom.xml
$(MY_DIR)/mk/maven.mk : modules/nlp/lexers/light-lexer/pom.xml
$(MY_DIR)/mk/maven.mk : modules/nlp/lexers/omnilang-lexer/pom.xml
$(MY_DIR)/mk/maven.mk : modules/audio/audio-common/pom.xml
$(MY_DIR)/mk/maven.mk : modules/audio/audio-encoder-lame/pom.xml
$(MY_DIR)/mk/maven.mk : modules/tts/tts-common/pom.xml
$(MY_DIR)/mk/maven.mk : modules/tts/tts-adapter-espeak/pom.xml
$(MY_DIR)/mk/maven.mk : modules/tts/tts-adapter-acapela/pom.xml
$(MY_DIR)/mk/maven.mk : modules/tts/tts-adapter-osx/pom.xml
$(MY_DIR)/mk/maven.mk : modules/tts/tts-adapter-sapinative/pom.xml
$(MY_DIR)/mk/maven.mk : modules/tts/tts-adapter-qfrency/pom.xml
$(MY_DIR)/mk/maven.mk : modules/tts/tts-adapter-google/pom.xml
$(MY_DIR)/mk/maven.mk : modules/tts/tts-adapter-cereproc/pom.xml
$(MY_DIR)/mk/maven.mk : modules/tts/tts-adapter-azure/pom.xml
$(MY_DIR)/mk/maven.mk : modules/tts/tts-adapter-aws/pom.xml
$(MY_DIR)/mk/maven.mk : modules/tts/tts-mocks/pom.xml
$(MY_DIR)/mk/maven.mk : modules/braille/braille-common/pom.xml
$(MY_DIR)/mk/maven.mk : modules/braille/braille-css-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/braille/pef-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/braille/obfl-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/braille/liblouis-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/braille/dotify-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/braille/libhyphen-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/braille/texhyph-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/daisy202-to-epub3/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/daisy202-validator/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/daisy202-to-daisy3/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/daisy202-to-mp3/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/daisy3-to-daisy202/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/daisy3-to-epub3/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/daisy3-to-mp3/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/dtbook-to-daisy3/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/dtbook-to-ebraille/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/dtbook-to-epub3/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/dtbook-to-html/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/dtbook-to-odt/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/dtbook-to-pef/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/dtbook-to-rtf/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/dtbook-to-zedai/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/dtbook-validator/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/epub-to-daisy/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/epub2-to-epub3/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/epub3-to-daisy202/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/epub3-to-daisy3/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/epub3-to-epub3/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/epub3-to-pef/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/epub3-validator/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/html-to-dtbook/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/html-to-epub3/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/html-to-pef/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/nimas-fileset-validator/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/word-to-dtbook/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/zedai-to-epub3/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/zedai-to-html/pom.xml
$(MY_DIR)/mk/maven.mk : modules/scripts/zedai-to-pef/pom.xml
$(MY_DIR)/mk/maven.mk : cli/pom.xml
$(MY_DIR)/mk/maven.mk : assembly/pom.xml
$(MY_DIR)/mk/maven.mk : website/target/maven/pom.xml
$(MY_DIR)/mk/maven.mk : clientlib/java/clientlib-java/pom.xml
$(MY_DIR)/mk/maven.mk : clientlib/java/clientlib-java-httpclient/pom.xml
$(MY_DIR)/mk/maven.mk : framework/bom/pom.xml
$(MY_DIR)/mk/maven.mk : modules/bom/pom.xml
endif
