MVN_LOCAL_REPOSITORY := .maven-workspace
export MVN_LOCAL_REPOSITORY
MAVEN_AGGREGATORS += .
MAVEN_AGGREGATORS += utils/build-utils
MAVEN_AGGREGATORS += utils/build-utils/ds-to-spi
MAVEN_AGGREGATORS += utils/build-utils/archetypes
MAVEN_AGGREGATORS += utils/xspec-maven-plugin
MAVEN_AGGREGATORS += utils/xproc-maven-plugin
MAVEN_AGGREGATORS += libs/osgi-libs
MAVEN_AGGREGATORS += framework
MAVEN_AGGREGATORS += modules
MAVEN_AGGREGATORS += clientlib/java
MAVEN_MODULES += framework/bom
MAVEN_MODULES += modules/bom
MAVEN_MODULES += utils/daisy-parent/daisy-parent
MAVEN_MODULES += utils/build-utils/modules-build-helper
MAVEN_MODULES += utils/build-utils/modules-test-helper
MAVEN_MODULES += utils/build-utils/ds-to-spi/ds-to-spi-annotations
MAVEN_MODULES += utils/build-utils/ds-to-spi/ds-to-spi-annotations-processor
MAVEN_MODULES += utils/build-utils/ds-to-spi/ds-to-spi-runtime
MAVEN_MODULES += utils/build-utils/ds-to-spi/ds-to-spi-maven-plugin
MAVEN_MODULES += utils/build-utils/archetypes/basic-module
MAVEN_MODULES += utils/xspec-maven-plugin/xspec-runner
MAVEN_MODULES += utils/xspec-maven-plugin/xspec-maven-plugin
MAVEN_MODULES += utils/xprocspec
MAVEN_MODULES += utils/xproc-maven-plugin/xproc-engine-api
MAVEN_MODULES += utils/xproc-maven-plugin/xproc-engine-calabash
MAVEN_MODULES += utils/xproc-maven-plugin/xprocspec-runner
MAVEN_MODULES += utils/xproc-maven-plugin/xproc-maven-plugin
MAVEN_MODULES += libs/jstyleparser
MAVEN_MODULES += libs/braille-css
MAVEN_MODULES += libs/osgi-libs/jing
MAVEN_MODULES += libs/osgi-libs/jnaerator
MAVEN_MODULES += libs/osgi-libs/parboiled
MAVEN_MODULES += libs/osgi-libs/pegdown
MAVEN_MODULES += libs/osgi-libs/saxon
MAVEN_MODULES += libs/osgi-libs/servlet-api
MAVEN_MODULES += framework/parent
MAVEN_MODULES += framework/utils/clientlib-java-jaxb
MAVEN_MODULES += framework/utils/xproc-engine-daisy-pipeline
MAVEN_MODULES += framework/utils/xproc-engine-daisy-pipeline-logging
MAVEN_MODULES += framework/saxon-adapter
MAVEN_MODULES += framework/calabash-adapter
MAVEN_MODULES += framework/common-utils
MAVEN_MODULES += framework/framework-core
MAVEN_MODULES += framework/framework-persistence
MAVEN_MODULES += framework/logging-appender
MAVEN_MODULES += framework/modules-registry
MAVEN_MODULES += framework/persistence-derby
MAVEN_MODULES += framework/webservice
MAVEN_MODULES += framework/xproc-api
MAVEN_MODULES += framework/pipeline1-adapter
MAVEN_MODULES += modules/parent
MAVEN_MODULES += modules/ace-adapter
MAVEN_MODULES += modules/asciimath-utils
MAVEN_MODULES += modules/audio-common
MAVEN_MODULES += modules/audio-encoder-lame
MAVEN_MODULES += modules/braille-common
MAVEN_MODULES += modules/braille-css-utils
MAVEN_MODULES += modules/common-utils
MAVEN_MODULES += modules/css-utils
MAVEN_MODULES += modules/daisy202-to-daisy3
MAVEN_MODULES += modules/daisy202-to-epub3
MAVEN_MODULES += modules/daisy202-to-mp3
MAVEN_MODULES += modules/daisy202-utils
MAVEN_MODULES += modules/daisy3-to-daisy202
MAVEN_MODULES += modules/daisy3-to-epub3
MAVEN_MODULES += modules/daisy3-to-mp3
MAVEN_MODULES += modules/daisy3-utils
MAVEN_MODULES += modules/dotify-utils
MAVEN_MODULES += modules/dtbook-to-daisy3
MAVEN_MODULES += modules/dtbook-to-ebraille
MAVEN_MODULES += modules/dtbook-to-epub3
MAVEN_MODULES += modules/dtbook-to-html
MAVEN_MODULES += modules/dtbook-to-odt
MAVEN_MODULES += modules/dtbook-to-pef
MAVEN_MODULES += modules/dtbook-to-rtf
MAVEN_MODULES += modules/dtbook-to-zedai
MAVEN_MODULES += modules/dtbook-utils
MAVEN_MODULES += modules/epub-to-daisy
MAVEN_MODULES += modules/epub-utils
MAVEN_MODULES += modules/epub3-to-daisy202
MAVEN_MODULES += modules/epub3-to-daisy3
MAVEN_MODULES += modules/epub3-to-html
MAVEN_MODULES += modules/epub3-to-pef
MAVEN_MODULES += modules/epubcheck-adapter
MAVEN_MODULES += modules/file-utils
MAVEN_MODULES += modules/fileset-utils
MAVEN_MODULES += modules/html-to-dtbook
MAVEN_MODULES += modules/html-to-epub3
MAVEN_MODULES += modules/html-to-pef
MAVEN_MODULES += modules/html-utils
MAVEN_MODULES += modules/image-utils
MAVEN_MODULES += modules/libhyphen-utils
MAVEN_MODULES += modules/liblouis-utils
MAVEN_MODULES += modules/mathcat-adapter
MAVEN_MODULES += modules/mathml-utils
MAVEN_MODULES += modules/mediatype-utils
MAVEN_MODULES += modules/metadata-utils
MAVEN_MODULES += modules/nlp-common
MAVEN_MODULES += modules/obfl-utils
MAVEN_MODULES += modules/ocr-utils
MAVEN_MODULES += modules/odf-utils
MAVEN_MODULES += modules/pandoc-adapter
MAVEN_MODULES += modules/pef-utils
MAVEN_MODULES += modules/smil-utils
MAVEN_MODULES += modules/tts-adapter-acapela
MAVEN_MODULES += modules/tts-adapter-aws
MAVEN_MODULES += modules/tts-adapter-azure
MAVEN_MODULES += modules/tts-adapter-cereproc
MAVEN_MODULES += modules/tts-adapter-espeak
MAVEN_MODULES += modules/tts-adapter-google
MAVEN_MODULES += modules/tts-adapter-osx
MAVEN_MODULES += modules/tts-adapter-qfrency
MAVEN_MODULES += modules/tts-adapter-sapinative
MAVEN_MODULES += modules/tts-common
MAVEN_MODULES += modules/tts-mocks
MAVEN_MODULES += modules/validation-utils
MAVEN_MODULES += modules/word-to-dtbook
MAVEN_MODULES += modules/zedai-to-epub3
MAVEN_MODULES += modules/zedai-to-html
MAVEN_MODULES += modules/zedai-to-pef
MAVEN_MODULES += modules/zedai-utils
MAVEN_MODULES += modules/zip-utils
MAVEN_MODULES += cli
MAVEN_MODULES += assembly
MAVEN_MODULES += website/target/maven
MAVEN_MODULES += clientlib/java/clientlib-java
MAVEN_MODULES += clientlib/java/clientlib-java-httpclient
ifndef FIXED_BUILD
poms : $(TARGET_DIR)/optimized/./pom.xml
poms : $(TARGET_DIR)/optimized/utils/build-utils/pom.xml
poms : $(TARGET_DIR)/optimized/utils/build-utils/ds-to-spi/pom.xml
poms : $(TARGET_DIR)/optimized/utils/build-utils/archetypes/pom.xml
poms : $(TARGET_DIR)/optimized/utils/xspec-maven-plugin/pom.xml
poms : $(TARGET_DIR)/optimized/utils/xproc-maven-plugin/pom.xml
poms : $(TARGET_DIR)/optimized/libs/osgi-libs/pom.xml
poms : $(TARGET_DIR)/optimized/framework/pom.xml
poms : $(TARGET_DIR)/optimized/modules/pom.xml
poms : $(TARGET_DIR)/optimized/clientlib/java/pom.xml
poms : $(TARGET_DIR)/optimized/framework/bom/pom.xml
poms : $(TARGET_DIR)/optimized/modules/bom/pom.xml
poms : utils/daisy-parent/daisy-parent/pom.xml
poms : utils/build-utils/modules-build-helper/pom.xml
poms : utils/build-utils/modules-test-helper/pom.xml
poms : utils/build-utils/ds-to-spi/ds-to-spi-annotations/pom.xml
poms : utils/build-utils/ds-to-spi/ds-to-spi-annotations-processor/pom.xml
poms : utils/build-utils/ds-to-spi/ds-to-spi-runtime/pom.xml
poms : utils/build-utils/ds-to-spi/ds-to-spi-maven-plugin/pom.xml
poms : utils/build-utils/archetypes/basic-module/pom.xml
poms : utils/xspec-maven-plugin/xspec-runner/pom.xml
poms : utils/xspec-maven-plugin/xspec-maven-plugin/pom.xml
poms : utils/xprocspec/pom.xml
poms : utils/xproc-maven-plugin/xproc-engine-api/pom.xml
poms : utils/xproc-maven-plugin/xproc-engine-calabash/pom.xml
poms : utils/xproc-maven-plugin/xprocspec-runner/pom.xml
poms : utils/xproc-maven-plugin/xproc-maven-plugin/pom.xml
poms : libs/jstyleparser/pom.xml
poms : libs/braille-css/pom.xml
poms : libs/osgi-libs/jing/pom.xml
poms : libs/osgi-libs/jnaerator/pom.xml
poms : libs/osgi-libs/parboiled/pom.xml
poms : libs/osgi-libs/pegdown/pom.xml
poms : libs/osgi-libs/saxon/pom.xml
poms : libs/osgi-libs/servlet-api/pom.xml
poms : framework/parent/pom.xml
poms : framework/utils/clientlib-java-jaxb/pom.xml
poms : framework/utils/xproc-engine-daisy-pipeline/pom.xml
poms : framework/utils/xproc-engine-daisy-pipeline-logging/pom.xml
poms : framework/saxon-adapter/pom.xml
poms : framework/calabash-adapter/pom.xml
poms : framework/common-utils/pom.xml
poms : framework/framework-core/pom.xml
poms : framework/framework-persistence/pom.xml
poms : framework/logging-appender/pom.xml
poms : framework/modules-registry/pom.xml
poms : framework/persistence-derby/pom.xml
poms : framework/webservice/pom.xml
poms : framework/xproc-api/pom.xml
poms : framework/pipeline1-adapter/pom.xml
poms : modules/parent/pom.xml
poms : modules/ace-adapter/pom.xml
poms : modules/asciimath-utils/pom.xml
poms : modules/audio-common/pom.xml
poms : modules/audio-encoder-lame/pom.xml
poms : modules/braille-common/pom.xml
poms : modules/braille-css-utils/pom.xml
poms : modules/common-utils/pom.xml
poms : modules/css-utils/pom.xml
poms : modules/daisy202-to-daisy3/pom.xml
poms : modules/daisy202-to-epub3/pom.xml
poms : modules/daisy202-to-mp3/pom.xml
poms : modules/daisy202-utils/pom.xml
poms : modules/daisy3-to-daisy202/pom.xml
poms : modules/daisy3-to-epub3/pom.xml
poms : modules/daisy3-to-mp3/pom.xml
poms : modules/daisy3-utils/pom.xml
poms : modules/dotify-utils/pom.xml
poms : modules/dtbook-to-daisy3/pom.xml
poms : modules/dtbook-to-ebraille/pom.xml
poms : modules/dtbook-to-epub3/pom.xml
poms : modules/dtbook-to-html/pom.xml
poms : modules/dtbook-to-odt/pom.xml
poms : modules/dtbook-to-pef/pom.xml
poms : modules/dtbook-to-rtf/pom.xml
poms : modules/dtbook-to-zedai/pom.xml
poms : modules/dtbook-utils/pom.xml
poms : modules/epub-to-daisy/pom.xml
poms : modules/epub-utils/pom.xml
poms : modules/epub3-to-daisy202/pom.xml
poms : modules/epub3-to-daisy3/pom.xml
poms : modules/epub3-to-html/pom.xml
poms : modules/epub3-to-pef/pom.xml
poms : modules/epubcheck-adapter/pom.xml
poms : modules/file-utils/pom.xml
poms : modules/fileset-utils/pom.xml
poms : modules/html-to-dtbook/pom.xml
poms : modules/html-to-epub3/pom.xml
poms : modules/html-to-pef/pom.xml
poms : modules/html-utils/pom.xml
poms : modules/image-utils/pom.xml
poms : modules/libhyphen-utils/pom.xml
poms : modules/liblouis-utils/pom.xml
poms : modules/mathcat-adapter/pom.xml
poms : modules/mathml-utils/pom.xml
poms : modules/mediatype-utils/pom.xml
poms : modules/metadata-utils/pom.xml
poms : modules/nlp-common/pom.xml
poms : modules/obfl-utils/pom.xml
poms : modules/ocr-utils/pom.xml
poms : modules/odf-utils/pom.xml
poms : modules/pandoc-adapter/pom.xml
poms : modules/pef-utils/pom.xml
poms : modules/smil-utils/pom.xml
poms : modules/tts-adapter-acapela/pom.xml
poms : modules/tts-adapter-aws/pom.xml
poms : modules/tts-adapter-azure/pom.xml
poms : modules/tts-adapter-cereproc/pom.xml
poms : modules/tts-adapter-espeak/pom.xml
poms : modules/tts-adapter-google/pom.xml
poms : modules/tts-adapter-osx/pom.xml
poms : modules/tts-adapter-qfrency/pom.xml
poms : modules/tts-adapter-sapinative/pom.xml
poms : modules/tts-common/pom.xml
poms : modules/tts-mocks/pom.xml
poms : modules/validation-utils/pom.xml
poms : modules/word-to-dtbook/pom.xml
poms : modules/zedai-to-epub3/pom.xml
poms : modules/zedai-to-html/pom.xml
poms : modules/zedai-to-pef/pom.xml
poms : modules/zedai-utils/pom.xml
poms : modules/zip-utils/pom.xml
poms : cli/pom.xml
poms : assembly/pom.xml
poms : website/target/maven/pom.xml
poms : clientlib/java/clientlib-java/pom.xml
poms : clientlib/java/clientlib-java-httpclient/pom.xml
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/parent/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/utils/clientlib-java-jaxb/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/utils/xproc-engine-daisy-pipeline/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/utils/xproc-engine-daisy-pipeline-logging/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/saxon-adapter/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/calabash-adapter/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/common-utils/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/framework-core/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/framework-persistence/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/logging-appender/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/modules-registry/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/persistence-derby/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/webservice/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/xproc-api/modified-since-release
$(TARGET_DIR)/optimized/framework/bom/pom.xml : $(TARGET_DIR)/state/framework/pipeline1-adapter/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/parent/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/ace-adapter/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/asciimath-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/audio-common/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/audio-encoder-lame/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/braille-common/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/braille-css-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/common-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/css-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/daisy202-to-daisy3/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/daisy202-to-epub3/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/daisy202-to-mp3/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/daisy202-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/daisy3-to-daisy202/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/daisy3-to-epub3/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/daisy3-to-mp3/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/daisy3-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/dotify-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/dtbook-to-daisy3/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/dtbook-to-ebraille/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/dtbook-to-epub3/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/dtbook-to-html/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/dtbook-to-odt/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/dtbook-to-pef/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/dtbook-to-rtf/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/dtbook-to-zedai/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/dtbook-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/epub-to-daisy/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/epub-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/epub3-to-daisy202/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/epub3-to-daisy3/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/epub3-to-html/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/epub3-to-pef/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/epubcheck-adapter/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/file-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/fileset-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/html-to-dtbook/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/html-to-epub3/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/html-to-pef/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/html-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/image-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/libhyphen-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/liblouis-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/mathcat-adapter/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/mathml-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/mediatype-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/metadata-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/nlp-common/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/obfl-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/ocr-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/odf-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/pandoc-adapter/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/pef-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/smil-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/tts-adapter-acapela/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/tts-adapter-aws/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/tts-adapter-azure/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/tts-adapter-cereproc/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/tts-adapter-espeak/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/tts-adapter-google/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/tts-adapter-osx/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/tts-adapter-qfrency/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/tts-adapter-sapinative/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/tts-common/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/tts-mocks/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/validation-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/word-to-dtbook/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/zedai-to-epub3/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/zedai-to-html/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/zedai-to-pef/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/zedai-utils/modified-since-release
$(TARGET_DIR)/optimized/modules/bom/pom.xml : $(TARGET_DIR)/state/modules/zip-utils/modified-since-release
$(MY_DIR)/mk/maven.mk : ./pom.xml
$(MY_DIR)/mk/maven.mk : utils/build-utils/pom.xml
$(MY_DIR)/mk/maven.mk : utils/build-utils/ds-to-spi/pom.xml
$(MY_DIR)/mk/maven.mk : utils/build-utils/archetypes/pom.xml
$(MY_DIR)/mk/maven.mk : utils/xspec-maven-plugin/pom.xml
$(MY_DIR)/mk/maven.mk : utils/xproc-maven-plugin/pom.xml
$(MY_DIR)/mk/maven.mk : libs/osgi-libs/pom.xml
$(MY_DIR)/mk/maven.mk : framework/pom.xml
$(MY_DIR)/mk/maven.mk : modules/pom.xml
$(MY_DIR)/mk/maven.mk : clientlib/java/pom.xml
$(MY_DIR)/mk/maven.mk : utils/daisy-parent/daisy-parent/pom.xml
$(MY_DIR)/mk/maven.mk : utils/build-utils/modules-build-helper/pom.xml
$(MY_DIR)/mk/maven.mk : utils/build-utils/modules-test-helper/pom.xml
$(MY_DIR)/mk/maven.mk : utils/build-utils/ds-to-spi/ds-to-spi-annotations/pom.xml
$(MY_DIR)/mk/maven.mk : utils/build-utils/ds-to-spi/ds-to-spi-annotations-processor/pom.xml
$(MY_DIR)/mk/maven.mk : utils/build-utils/ds-to-spi/ds-to-spi-runtime/pom.xml
$(MY_DIR)/mk/maven.mk : utils/build-utils/ds-to-spi/ds-to-spi-maven-plugin/pom.xml
$(MY_DIR)/mk/maven.mk : utils/build-utils/archetypes/basic-module/pom.xml
$(MY_DIR)/mk/maven.mk : utils/xspec-maven-plugin/xspec-runner/pom.xml
$(MY_DIR)/mk/maven.mk : utils/xspec-maven-plugin/xspec-maven-plugin/pom.xml
$(MY_DIR)/mk/maven.mk : utils/xprocspec/pom.xml
$(MY_DIR)/mk/maven.mk : utils/xproc-maven-plugin/xproc-engine-api/pom.xml
$(MY_DIR)/mk/maven.mk : utils/xproc-maven-plugin/xproc-engine-calabash/pom.xml
$(MY_DIR)/mk/maven.mk : utils/xproc-maven-plugin/xprocspec-runner/pom.xml
$(MY_DIR)/mk/maven.mk : utils/xproc-maven-plugin/xproc-maven-plugin/pom.xml
$(MY_DIR)/mk/maven.mk : libs/jstyleparser/pom.xml
$(MY_DIR)/mk/maven.mk : libs/braille-css/pom.xml
$(MY_DIR)/mk/maven.mk : libs/osgi-libs/jing/pom.xml
$(MY_DIR)/mk/maven.mk : libs/osgi-libs/jnaerator/pom.xml
$(MY_DIR)/mk/maven.mk : libs/osgi-libs/parboiled/pom.xml
$(MY_DIR)/mk/maven.mk : libs/osgi-libs/pegdown/pom.xml
$(MY_DIR)/mk/maven.mk : libs/osgi-libs/saxon/pom.xml
$(MY_DIR)/mk/maven.mk : libs/osgi-libs/servlet-api/pom.xml
$(MY_DIR)/mk/maven.mk : framework/parent/pom.xml
$(MY_DIR)/mk/maven.mk : framework/utils/clientlib-java-jaxb/pom.xml
$(MY_DIR)/mk/maven.mk : framework/utils/xproc-engine-daisy-pipeline/pom.xml
$(MY_DIR)/mk/maven.mk : framework/utils/xproc-engine-daisy-pipeline-logging/pom.xml
$(MY_DIR)/mk/maven.mk : framework/saxon-adapter/pom.xml
$(MY_DIR)/mk/maven.mk : framework/calabash-adapter/pom.xml
$(MY_DIR)/mk/maven.mk : framework/common-utils/pom.xml
$(MY_DIR)/mk/maven.mk : framework/framework-core/pom.xml
$(MY_DIR)/mk/maven.mk : framework/framework-persistence/pom.xml
$(MY_DIR)/mk/maven.mk : framework/logging-appender/pom.xml
$(MY_DIR)/mk/maven.mk : framework/modules-registry/pom.xml
$(MY_DIR)/mk/maven.mk : framework/persistence-derby/pom.xml
$(MY_DIR)/mk/maven.mk : framework/webservice/pom.xml
$(MY_DIR)/mk/maven.mk : framework/xproc-api/pom.xml
$(MY_DIR)/mk/maven.mk : framework/pipeline1-adapter/pom.xml
$(MY_DIR)/mk/maven.mk : modules/parent/pom.xml
$(MY_DIR)/mk/maven.mk : modules/ace-adapter/pom.xml
$(MY_DIR)/mk/maven.mk : modules/asciimath-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/audio-common/pom.xml
$(MY_DIR)/mk/maven.mk : modules/audio-encoder-lame/pom.xml
$(MY_DIR)/mk/maven.mk : modules/braille-common/pom.xml
$(MY_DIR)/mk/maven.mk : modules/braille-css-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/common-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/css-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/daisy202-to-daisy3/pom.xml
$(MY_DIR)/mk/maven.mk : modules/daisy202-to-epub3/pom.xml
$(MY_DIR)/mk/maven.mk : modules/daisy202-to-mp3/pom.xml
$(MY_DIR)/mk/maven.mk : modules/daisy202-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/daisy3-to-daisy202/pom.xml
$(MY_DIR)/mk/maven.mk : modules/daisy3-to-epub3/pom.xml
$(MY_DIR)/mk/maven.mk : modules/daisy3-to-mp3/pom.xml
$(MY_DIR)/mk/maven.mk : modules/daisy3-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/dotify-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/dtbook-to-daisy3/pom.xml
$(MY_DIR)/mk/maven.mk : modules/dtbook-to-ebraille/pom.xml
$(MY_DIR)/mk/maven.mk : modules/dtbook-to-epub3/pom.xml
$(MY_DIR)/mk/maven.mk : modules/dtbook-to-html/pom.xml
$(MY_DIR)/mk/maven.mk : modules/dtbook-to-odt/pom.xml
$(MY_DIR)/mk/maven.mk : modules/dtbook-to-pef/pom.xml
$(MY_DIR)/mk/maven.mk : modules/dtbook-to-rtf/pom.xml
$(MY_DIR)/mk/maven.mk : modules/dtbook-to-zedai/pom.xml
$(MY_DIR)/mk/maven.mk : modules/dtbook-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/epub-to-daisy/pom.xml
$(MY_DIR)/mk/maven.mk : modules/epub-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/epub3-to-daisy202/pom.xml
$(MY_DIR)/mk/maven.mk : modules/epub3-to-daisy3/pom.xml
$(MY_DIR)/mk/maven.mk : modules/epub3-to-html/pom.xml
$(MY_DIR)/mk/maven.mk : modules/epub3-to-pef/pom.xml
$(MY_DIR)/mk/maven.mk : modules/epubcheck-adapter/pom.xml
$(MY_DIR)/mk/maven.mk : modules/file-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/fileset-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/html-to-dtbook/pom.xml
$(MY_DIR)/mk/maven.mk : modules/html-to-epub3/pom.xml
$(MY_DIR)/mk/maven.mk : modules/html-to-pef/pom.xml
$(MY_DIR)/mk/maven.mk : modules/html-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/image-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/libhyphen-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/liblouis-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/mathcat-adapter/pom.xml
$(MY_DIR)/mk/maven.mk : modules/mathml-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/mediatype-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/metadata-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/nlp-common/pom.xml
$(MY_DIR)/mk/maven.mk : modules/obfl-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/ocr-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/odf-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/pandoc-adapter/pom.xml
$(MY_DIR)/mk/maven.mk : modules/pef-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/smil-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/tts-adapter-acapela/pom.xml
$(MY_DIR)/mk/maven.mk : modules/tts-adapter-aws/pom.xml
$(MY_DIR)/mk/maven.mk : modules/tts-adapter-azure/pom.xml
$(MY_DIR)/mk/maven.mk : modules/tts-adapter-cereproc/pom.xml
$(MY_DIR)/mk/maven.mk : modules/tts-adapter-espeak/pom.xml
$(MY_DIR)/mk/maven.mk : modules/tts-adapter-google/pom.xml
$(MY_DIR)/mk/maven.mk : modules/tts-adapter-osx/pom.xml
$(MY_DIR)/mk/maven.mk : modules/tts-adapter-qfrency/pom.xml
$(MY_DIR)/mk/maven.mk : modules/tts-adapter-sapinative/pom.xml
$(MY_DIR)/mk/maven.mk : modules/tts-common/pom.xml
$(MY_DIR)/mk/maven.mk : modules/tts-mocks/pom.xml
$(MY_DIR)/mk/maven.mk : modules/validation-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/word-to-dtbook/pom.xml
$(MY_DIR)/mk/maven.mk : modules/zedai-to-epub3/pom.xml
$(MY_DIR)/mk/maven.mk : modules/zedai-to-html/pom.xml
$(MY_DIR)/mk/maven.mk : modules/zedai-to-pef/pom.xml
$(MY_DIR)/mk/maven.mk : modules/zedai-utils/pom.xml
$(MY_DIR)/mk/maven.mk : modules/zip-utils/pom.xml
$(MY_DIR)/mk/maven.mk : cli/pom.xml
$(MY_DIR)/mk/maven.mk : assembly/pom.xml
$(MY_DIR)/mk/maven.mk : website/target/maven/pom.xml
$(MY_DIR)/mk/maven.mk : clientlib/java/clientlib-java/pom.xml
$(MY_DIR)/mk/maven.mk : clientlib/java/clientlib-java-httpclient/pom.xml
$(MY_DIR)/mk/maven.mk : framework/bom/pom.xml
$(MY_DIR)/mk/maven.mk : modules/bom/pom.xml
endif
