modules/mathcat-adapter/.test modules/mathcat-adapter/.install modules/mathcat-adapter/.install-doc $(TARGET_DIR)/state/modules/mathcat-adapter/modified-since-release_ : \
	modules/mathcat-adapter/src/main/resources/rules/prefs.yaml \
	modules/mathcat-adapter/src/main/resources/rules/intent.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/LaTeX/unicode-full.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/LaTeX/unicode.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/LaTeX/definitions.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/LaTeX/LaTeX_Rules.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/CMU/unicode-full.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/CMU/unicode.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/CMU/definitions.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/CMU/CMU_Rules.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/definitions.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/ASCIIMath/unicode-full.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/ASCIIMath/unicode.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/ASCIIMath/ASCIIMath_Rules.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/ASCIIMath/definitions.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/Swedish/unicode-full.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/Swedish/unicode.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/Swedish/definitions.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/Swedish/Swedish_Rules.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/UEB/unicode-full.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/UEB/unicode.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/UEB/UEB_Rules.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/UEB/definitions.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/Nemeth/unicode-full.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/Nemeth/unicode.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/Nemeth/Nemeth_Rules.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/Nemeth/definitions.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/Vietnam/unicode-full.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/Vietnam/unicode.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/Vietnam/Vietnam_Rules.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/Vietnam/definitions.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/ASCIIMath-fi/unicode-full.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/ASCIIMath-fi/unicode.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/ASCIIMath-fi/ASCIIMath_Rules.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Braille/ASCIIMath-fi/definitions.yaml \
	modules/mathcat-adapter/src/main/resources/rules/README \
	modules/mathcat-adapter/src/main/resources/rules/Languages/vi/SimpleSpeak_Rules.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/vi/unicode-full.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/vi/SharedRules/geometry.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/vi/SharedRules/general.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/vi/SharedRules/linear-algebra.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/vi/SharedRules/calculus.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/vi/SharedRules/default.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/vi/navigate.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/vi/unicode.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/vi/ClearSpeak_Rules.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/vi/definitions.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/vi/overview.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/sv/SimpleSpeak_Rules.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/sv/unicode-full.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/sv/SharedRules/geometry.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/sv/SharedRules/general.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/sv/SharedRules/linear-algebra.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/sv/SharedRules/calculus.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/sv/SharedRules/default.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/sv/navigate.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/sv/unicode.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/sv/ClearSpeak_Rules.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/sv/definitions.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/sv/overview.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zh/tw/SimpleSpeak_Rules.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zh/tw/unicode-full.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zh/tw/SharedRules/geometry.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zh/tw/SharedRules/general.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zh/tw/SharedRules/linear-algebra.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zh/tw/SharedRules/calculus.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zh/tw/SharedRules/default.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zh/tw/navigate.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zh/tw/ClearSpeak_Rules.yaml.ignore \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zh/tw/unicode.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zh/tw/definitions.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zh/tw/overview.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zz/SimpleSpeak_Rules.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zz/unicode-full.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zz/navigate.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zz/unicode.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zz/ClearSpeak_Rules.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zz/definitions.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zz/overview.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zz/aa/unicode.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zz/aa/ClearSpeak_Rules.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zz/aa/definitions.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/fi/SimpleSpeak_Rules.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/fi/unicode-full.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/fi/SharedRules/geometry.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/fi/SharedRules/general.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/fi/SharedRules/linear-algebra.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/fi/SharedRules/calculus.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/fi/SharedRules/default.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/fi/navigate.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/fi/unicode.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/fi/ClearSpeak_Rules.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/fi/definitions.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/fi/overview.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/id/SimpleSpeak_Rules.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/id/unicode-full.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/id/SharedRules/geometry.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/id/SharedRules/general.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/id/SharedRules/linear-algebra.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/id/SharedRules/calculus.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/id/SharedRules/default.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/id/navigate.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/id/unicode.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/id/ClearSpeak_Rules.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/id/definitions.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/id/overview.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/es/SimpleSpeak_Rules.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/es/unicode-full.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/es/SharedRules/geometry.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/es/SharedRules/general.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/es/SharedRules/linear-algebra.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/es/SharedRules/calculus.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/es/SharedRules/default.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/es/navigate.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/es/unicode.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/es/ClearSpeak_Rules.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/es/definitions.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/es/overview.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/en/SimpleSpeak_Rules.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/en/unicode-full.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/en/SharedRules/geometry.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/en/SharedRules/general.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/en/SharedRules/linear-algebra.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/en/SharedRules/calculus.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/en/SharedRules/default.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/en/navigate.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/en/unicode.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/en/ClearSpeak_Rules.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/en/definitions.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/en/overview.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Languages/en/gb/unicode.yaml \
	modules/mathcat-adapter/src/main/resources/rules/definitions.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Intent/geometry.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Intent/general.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Intent/linear-algebra.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Intent/probability.yaml \
	modules/mathcat-adapter/src/main/resources/rules/Intent/calculus.yaml \
	modules/mathcat-adapter/src/main/java/org/daisy/pipeline/mathcat/impl/MathCAT.java
modules/mathcat-adapter/.test modules/mathcat-adapter/.install-doc : \
	modules/mathcat-adapter/src/test/xspec/test_asciimath-to-ssml.xspec \
	modules/mathcat-adapter/src/test/resources/logback.xml \
	modules/mathcat-adapter/src/test/java/XProcSpecTest.java \
	modules/mathcat-adapter/src/test/xprocspec/test_mathml-to-ssml.xprocspec
.make/mk/modules/mathcat-adapter/sources.mk : \
	modules/mathcat-adapter/src \
	modules/mathcat-adapter/src/test \
	modules/mathcat-adapter/src/test/xspec \
	modules/mathcat-adapter/src/test/resources \
	modules/mathcat-adapter/src/test/java \
	modules/mathcat-adapter/src/test/xprocspec \
	modules/mathcat-adapter/src/main \
	modules/mathcat-adapter/src/main/resources \
	modules/mathcat-adapter/src/main/resources/rules \
	modules/mathcat-adapter/src/main/resources/rules/Braille \
	modules/mathcat-adapter/src/main/resources/rules/Braille/LaTeX \
	modules/mathcat-adapter/src/main/resources/rules/Braille/CMU \
	modules/mathcat-adapter/src/main/resources/rules/Braille/ASCIIMath \
	modules/mathcat-adapter/src/main/resources/rules/Braille/Swedish \
	modules/mathcat-adapter/src/main/resources/rules/Braille/UEB \
	modules/mathcat-adapter/src/main/resources/rules/Braille/Nemeth \
	modules/mathcat-adapter/src/main/resources/rules/Braille/Vietnam \
	modules/mathcat-adapter/src/main/resources/rules/Braille/ASCIIMath-fi \
	modules/mathcat-adapter/src/main/resources/rules/Languages \
	modules/mathcat-adapter/src/main/resources/rules/Languages/vi \
	modules/mathcat-adapter/src/main/resources/rules/Languages/vi/SharedRules \
	modules/mathcat-adapter/src/main/resources/rules/Languages/sv \
	modules/mathcat-adapter/src/main/resources/rules/Languages/sv/SharedRules \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zh \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zh/tw \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zh/tw/SharedRules \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zz \
	modules/mathcat-adapter/src/main/resources/rules/Languages/zz/aa \
	modules/mathcat-adapter/src/main/resources/rules/Languages/fi \
	modules/mathcat-adapter/src/main/resources/rules/Languages/fi/SharedRules \
	modules/mathcat-adapter/src/main/resources/rules/Languages/id \
	modules/mathcat-adapter/src/main/resources/rules/Languages/id/SharedRules \
	modules/mathcat-adapter/src/main/resources/rules/Languages/es \
	modules/mathcat-adapter/src/main/resources/rules/Languages/es/SharedRules \
	modules/mathcat-adapter/src/main/resources/rules/Languages/en \
	modules/mathcat-adapter/src/main/resources/rules/Languages/en/SharedRules \
	modules/mathcat-adapter/src/main/resources/rules/Languages/en/gb \
	modules/mathcat-adapter/src/main/resources/rules/Intent \
	modules/mathcat-adapter/src/main/java \
	modules/mathcat-adapter/src/main/java/org \
	modules/mathcat-adapter/src/main/java/org/daisy \
	modules/mathcat-adapter/src/main/java/org/daisy/pipeline \
	modules/mathcat-adapter/src/main/java/org/daisy/pipeline/mathcat \
	modules/mathcat-adapter/src/main/java/org/daisy/pipeline/mathcat/impl
