libs/jstyleparser/.test libs/jstyleparser/.install libs/jstyleparser/.install-doc $(TARGET_DIR)/state/libs/jstyleparser/modified-since-release_ : \
	libs/jstyleparser/src/main/assembly/dist.xml \
	libs/jstyleparser/src/main/resources/placeholder \
	libs/jstyleparser/src/main/java/org/fit/net/DataURLConnection.java \
	libs/jstyleparser/src/main/java/org/fit/net/Base64Coder.java \
	libs/jstyleparser/src/main/java/org/fit/net/DataURLHandler.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/domassign/Traversal.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/domassign/Repeater.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/domassign/Analyzer.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/domassign/SupportedCSS3.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/domassign/DeclarationTransformer.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/domassign/Variator.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/domassign/AssignedDeclaration.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/domassign/SingleMapNodeData.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/domassign/StyleMap.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/domassign/QuadrupleMapNodeData.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/domassign/DeclarationMap.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/domassign/SupportedCSS21.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/domassign/GenericTreeWalker.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/domassign/DirectAnalyzer.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/domassign/MultiMap.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/TermInteger.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/CSSException.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/TermNumeric.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/MatchCondition.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/TermLengthOrPercent.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/TermResolution.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/FeatureCondition.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/RuleFactory.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/MediaQueryList.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/NetworkProcessor.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/RuleFontFace.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/MediaSpec.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/MediaSpecType.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/CombinedSelector.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/RuleViewport.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/RuleMedia.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/TermPercent.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/TermColor.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/MediaSpecAll.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/TermNumber.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/TermFactory.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/TermString.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/RuleSupports.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/RuleImport.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/TermTime.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/MediaQuery.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/CSSFactory.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/Declaration.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/RuleList.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/TermLength.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/StyleSheet.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/RuleMargin.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/SupportedCSS.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/MediaExpression.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/TermList.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/Selector.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/NodeData.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/SourceLocator.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/FeatureSpec.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/TermAngle.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/MediaSpecNone.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/RulePage.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/TermPair.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/TermExpression.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/TermFrequency.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/Term.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/PrettyOutput.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/TermFunction.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/TermIdent.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/RuleBlock.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/CSSProperty.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/FeatureQuery.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/Rule.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/RuleSet.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css/TermURI.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/TermTimeImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/TermNumberImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/FeatureQueryImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/StyleSheetImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/TermListImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/RulePageImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/RuleFactoryImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/antlr/CSSToken.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/antlr/Preparator.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/antlr/CSSLexerState.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/antlr/CSSTokenRecovery.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/antlr/CSSExpressionReader.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/antlr/TreeUtil.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/antlr/CSSTokenFactory.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/antlr/CSSTreeNodeRecovery.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/antlr/DefaultCSSSourceReader.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/antlr/SimplePreparator.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/antlr/CSSSource.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/antlr/SourceMap.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/antlr/CSSParserFactory.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/antlr/CSSSourceReader.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/antlr/CSSInputStream.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/ColorCard.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/RuleMediaImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/TermImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/TermURIImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/CombinedSelectorImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/ElementUtil.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/RuleFontFaceImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/RuleViewportImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/SelectorImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/AbstractRuleBlock.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/TermStringImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/TermAngleImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/MediaQueryListImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/RuleMarginImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/TermResolutionImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/TermLengthImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/MediaExpressionImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/MatchConditionOnElements.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/TermPairImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/OutputUtil.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/DeclarationImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/TermFactoryImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/TermFunctionImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/MatchConditionImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/TermColorImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/TermIdentImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/RuleXslt.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/TermPercentImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/TermFrequencyImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/MediaQueryImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/RuleArrayList.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/RuleSetImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/TermIntegerImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/RuleSupportsImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/DefaultNetworkProcessor.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/AbstractRule.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/TermNumericImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/RuleImportImpl.java \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/TermExpressionImpl.java \
	libs/jstyleparser/src/main/antlr3/CSSLexer.g \
	libs/jstyleparser/src/main/antlr3/.gitignore \
	libs/jstyleparser/src/main/antlr3/CSSParser.g \
	libs/jstyleparser/src/main/antlr3/CSSTreeParser.g
libs/jstyleparser/.test libs/jstyleparser/.install-doc : \
	libs/jstyleparser/src/test/resources/advanced/domassign.html \
	libs/jstyleparser/src/test/resources/advanced/style.html \
	libs/jstyleparser/src/test/resources/advanced/inherit.html \
	libs/jstyleparser/src/test/resources/advanced/style.css \
	libs/jstyleparser/src/test/resources/advanced/background.html \
	libs/jstyleparser/src/test/resources/w3c/style.css \
	libs/jstyleparser/src/test/resources/w3c/w3c_input_files/w3c_main.png \
	libs/jstyleparser/src/test/resources/w3c/w3c_input_files/right000.png \
	libs/jstyleparser/src/test/resources/w3c/w3c_input_files/58400000.png \
	libs/jstyleparser/src/test/resources/w3c/w3c_input_files/Logo_25w.gif \
	libs/jstyleparser/src/test/resources/w3c/w3c_input_files/workshop.jpg \
	libs/jstyleparser/src/test/resources/w3c/w3c_input_files/MWI-Pict.png \
	libs/jstyleparser/src/test/resources/w3c/w3c_input_files/valid-xh.png \
	libs/jstyleparser/src/test/resources/w3c/w3c_input_files/wcag1AA0.png \
	libs/jstyleparser/src/test/resources/w3c/w3c_input_files/valid-cs.png \
	libs/jstyleparser/src/test/resources/w3c/w3c_input.html \
	libs/jstyleparser/src/test/resources/abclinuxu/styles.css \
	libs/jstyleparser/src/test/resources/abclinuxu/temp.css \
	libs/jstyleparser/src/test/resources/abclinuxu/layout.css \
	libs/jstyleparser/src/test/resources/abclinuxu/opensuse-11.1-beta-1.html \
	libs/jstyleparser/src/test/resources/invalid/recovery2.css \
	libs/jstyleparser/src/test/resources/invalid/style.html \
	libs/jstyleparser/src/test/resources/invalid/style.css \
	libs/jstyleparser/src/test/resources/invalid/recovery2.html \
	libs/jstyleparser/src/test/resources/simple/impmedia.css \
	libs/jstyleparser/src/test/resources/simple/selectors3.css \
	libs/jstyleparser/src/test/resources/simple/selectors2.css \
	libs/jstyleparser/src/test/resources/simple/selectors.css \
	libs/jstyleparser/src/test/resources/simple/line-height.html \
	libs/jstyleparser/src/test/resources/simple/imp.css \
	libs/jstyleparser/src/test/resources/simple/data.html \
	libs/jstyleparser/src/test/resources/simple/selectors3.html \
	libs/jstyleparser/src/test/resources/simple/pseudo.html \
	libs/jstyleparser/src/test/resources/simple/h1.html \
	libs/jstyleparser/src/test/resources/simple/selectors.html \
	libs/jstyleparser/src/test/resources/simple/selectors2.html \
	libs/jstyleparser/src/test/resources/simple/data.css \
	libs/jstyleparser/src/test/resources/media/media1.html \
	libs/jstyleparser/src/test/java/test/NodeDataVariantTest.java \
	libs/jstyleparser/src/test/java/test/ElementMap.java \
	libs/jstyleparser/src/test/java/test/ImportTest1.java \
	libs/jstyleparser/src/test/java/test/DOMAssignMediaTest.java \
	libs/jstyleparser/src/test/java/test/DeclarationsUtil.java \
	libs/jstyleparser/src/test/java/test/GrammarRecovery1Test.java \
	libs/jstyleparser/src/test/java/test/MediaTest.java \
	libs/jstyleparser/src/test/java/test/FunctionsTest.java \
	libs/jstyleparser/src/test/java/test/AntlrDebug.java \
	libs/jstyleparser/src/test/java/test/SelectorTest.java \
	libs/jstyleparser/src/test/java/test/CollectionSpeedTest.java \
	libs/jstyleparser/src/test/java/test/ErrorTest.java \
	libs/jstyleparser/src/test/java/test/SimpleTest.java \
	libs/jstyleparser/src/test/java/test/DOMAssignDirectTest.java \
	libs/jstyleparser/src/test/java/test/SelectorsUtil.java \
	libs/jstyleparser/src/test/java/test/ParserDemo.java \
	libs/jstyleparser/src/test/java/test/AnalyzerTest.java \
	libs/jstyleparser/src/test/java/test/DecoderTest.java \
	libs/jstyleparser/src/test/java/test/AdvancedCSSTest.java \
	libs/jstyleparser/src/test/java/test/GrammarRecovery2Test.java \
	libs/jstyleparser/src/test/java/test/PseudoClassTest.java \
	libs/jstyleparser/src/test/java/test/DOMSource.java \
	libs/jstyleparser/src/test/java/test/UAConformancyTest.java \
	libs/jstyleparser/src/test/java/test/ProfilerEntryPoint.java \
	libs/jstyleparser/src/test/java/test/DOMAssignTest.java
libs/jstyleparser/.install-doc : \
	libs/jstyleparser/doc/manual/doc_php.xsl \
	libs/jstyleparser/doc/manual/gen \
	libs/jstyleparser/doc/manual/doc.xsl \
	libs/jstyleparser/doc/manual/manual.php \
	libs/jstyleparser/doc/manual/manual.xml \
	libs/jstyleparser/doc/manual/manual.html \
	libs/jstyleparser/doc/manual/manual.css
.make/mk/libs/jstyleparser/sources.mk : \
	libs/jstyleparser/src \
	libs/jstyleparser/src/test \
	libs/jstyleparser/src/test/resources \
	libs/jstyleparser/src/test/resources/advanced \
	libs/jstyleparser/src/test/resources/w3c \
	libs/jstyleparser/src/test/resources/w3c/w3c_input_files \
	libs/jstyleparser/src/test/resources/abclinuxu \
	libs/jstyleparser/src/test/resources/invalid \
	libs/jstyleparser/src/test/resources/simple \
	libs/jstyleparser/src/test/resources/media \
	libs/jstyleparser/src/test/java \
	libs/jstyleparser/src/test/java/test \
	libs/jstyleparser/src/main \
	libs/jstyleparser/src/main/assembly \
	libs/jstyleparser/src/main/resources \
	libs/jstyleparser/src/main/java \
	libs/jstyleparser/src/main/java/org \
	libs/jstyleparser/src/main/java/org/fit \
	libs/jstyleparser/src/main/java/org/fit/net \
	libs/jstyleparser/src/main/java/cz \
	libs/jstyleparser/src/main/java/cz/vutbr \
	libs/jstyleparser/src/main/java/cz/vutbr/web \
	libs/jstyleparser/src/main/java/cz/vutbr/web/domassign \
	libs/jstyleparser/src/main/java/cz/vutbr/web/css \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit \
	libs/jstyleparser/src/main/java/cz/vutbr/web/csskit/antlr \
	libs/jstyleparser/src/main/antlr3 \
	libs/jstyleparser/doc \
	libs/jstyleparser/doc/manual
