services:
  pipeline:
    image: daisyorg/pipeline
    environment:
      PIPELINE2_WS_HOST: "0.0.0.0"
      PIPELINE2_WS_AUTHENTICATION: "false"
    volumes:
      - "pipeline-data:/opt/daisy-pipeline2/data"
  webui:
    image: daisyorg/pipeline-webui
    environment:
      DAISY_PIPELINE2_URL: http://pipeline:8181/ws
    ports:
      - "9000:9000"
    volumes:
      - "webui-data:/opt/daisy-pipeline2-webui/data"
volumes:
  pipeline-data:
  webui-data:
