modules/braille/braille-common/.test modules/braille/braille-common/.install modules/braille/braille-common/.install-doc $(TARGET_DIR)/state/modules/braille/braille-common/modified-since-release_ : \
	modules/braille/braille-common/src/main/resources/META-INF/catalog.xml \
	modules/braille/braille-common/src/main/resources/xml/block-translator.xpl \
	modules/braille/braille-common/src/main/resources/xml/block-translator-from-text-transform.xsl \
	modules/braille/braille-common/src/main/resources/xml/collapse-pseudo-elements.xsl \
	modules/braille/braille-common/src/main/resources/xml/select-by-base.xpl \
	modules/braille/braille-common/src/main/resources/xml/select-by-position.xpl \
	modules/braille/braille-common/src/main/resources/xml/data-types/transform-query.xml \
	modules/braille/braille-common/src/main/resources/xml/abstract-block-translator.xsl \
	modules/braille/braille-common/src/main/resources/xml/expand-pseudo-elements.xsl \
	modules/braille/braille-common/src/main/resources/xml/mark-transitions.xpl \
	modules/braille/braille-common/src/main/resources/xml/xslt-for-each.xpl \
	modules/braille/braille-common/src/main/resources/xml/mark-transitions.xsl \
	modules/braille/braille-common/src/main/resources/xml/encoding-functions.xsl \
	modules/braille/braille-common/src/main/resources/xml/library.xpl \
	modules/braille/braille-common/src/main/resources/xml/library.xsl \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/BrailleTranslatorRegistry.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/impl/CSSBlockTransform.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/AbstractTransformProvider.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/BrailleTranslator.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/AbstractResourcePath.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/BundledResourcePath.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/util.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/Transform.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/HyphenatorWithExceptions.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/CompoundHyphenator.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/TransformationException.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/HyphenatorRegistry.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/Provider.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/ResourcePath.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/ResourceRegistry.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/calabash/impl/PxParseQueryStep.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/calabash/impl/PxTransformStep.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/UnityBrailleTranslator.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/AbstractHyphenator.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/BundledNativePath.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/XMLTransform.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/CompoundBrailleTranslator.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/Contextual.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/WithSideEffect.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/BrailleCode.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/saxon/impl/TextTransformDefinition.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/saxon/impl/TransformDefinition.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/saxon/impl/BrailleCodeFunctionProvider.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/AbstractTransform.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/Query.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/NativePath.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/LazyValue.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/ResourceResolver.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/StandardNativePath.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/Memoizing.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/BrailleTranslatorProvider.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/TextTransformParser.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/Hyphenator.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/TransformProvider.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/HyphenatorProvider.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/HyphenationResourceParser.java \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/AbstractBrailleTranslator.java \
	modules/braille/braille-common/src/main/README.md
modules/braille/braille-common/.test modules/braille/braille-common/.install-doc : \
	modules/braille/braille-common/src/test/xspec/test_text-transform.xspec \
	modules/braille/braille-common/src/test/resources/logback.xml \
	modules/braille/braille-common/src/test/resources/uppercase-block-translator.xsl \
	modules/braille/braille-common/src/test/resources/uppercase.xpl \
	modules/braille/braille-common/src/test/resources/META-INF/catalog.xml \
	modules/braille/braille-common/src/test/resources/foobar.cti \
	modules/braille/braille-common/src/test/java/ignore \
	modules/braille/braille-common/src/test/java/org/daisy/pipeline/braille/common/LocalesTest.java \
	modules/braille/braille-common/src/test/java/org/daisy/pipeline/braille/common/HyphenatorWithExceptionsTest.java \
	modules/braille/braille-common/src/test/java/org/daisy/pipeline/braille/common/UtilsTest.java \
	modules/braille/braille-common/src/test/java/org/daisy/pipeline/braille/common/QueryTest.java \
	modules/braille/braille-common/src/test/java/org/daisy/pipeline/braille/common/DefaultLineBreakerTest.java \
	modules/braille/braille-common/src/test/java/XSpecAndXProcSpecTest.java \
	modules/braille/braille-common/src/test/java/UppercaseTransform.java \
	modules/braille/braille-common/src/test/xprocspec/test_abstract-block-translator.xprocspec \
	modules/braille/braille-common/src/test/xprocspec/test_transform.xprocspec \
	modules/braille/braille-common/src/test/xprocspec/test_parse_query.xprocspec
modules/braille/braille-common/.install-doc : \
	modules/braille/braille-common/doc/index.md
.make/mk/modules/braille/braille-common/sources.mk : \
	modules/braille/braille-common/src \
	modules/braille/braille-common/src/test \
	modules/braille/braille-common/src/test/xspec \
	modules/braille/braille-common/src/test/resources \
	modules/braille/braille-common/src/test/resources/META-INF \
	modules/braille/braille-common/src/test/java \
	modules/braille/braille-common/src/test/java/org \
	modules/braille/braille-common/src/test/java/org/daisy \
	modules/braille/braille-common/src/test/java/org/daisy/pipeline \
	modules/braille/braille-common/src/test/java/org/daisy/pipeline/braille \
	modules/braille/braille-common/src/test/java/org/daisy/pipeline/braille/common \
	modules/braille/braille-common/src/test/xprocspec \
	modules/braille/braille-common/src/main \
	modules/braille/braille-common/src/main/resources \
	modules/braille/braille-common/src/main/resources/META-INF \
	modules/braille/braille-common/src/main/resources/xml \
	modules/braille/braille-common/src/main/resources/xml/data-types \
	modules/braille/braille-common/src/main/java \
	modules/braille/braille-common/src/main/java/org \
	modules/braille/braille-common/src/main/java/org/daisy \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/impl \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/calabash \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/calabash/impl \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/saxon \
	modules/braille/braille-common/src/main/java/org/daisy/pipeline/braille/common/saxon/impl \
	modules/braille/braille-common/doc
