modules/scripts-utils/mathml-utils/.test modules/scripts-utils/mathml-utils/.install modules/scripts-utils/mathml-utils/.install-doc $(TARGET_DIR)/state/modules/scripts-utils/mathml-utils/modified-since-release_ : \
	modules/scripts-utils/mathml-utils/src/main/resources/META-INF/catalog.xml \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml3/statistics.rng \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml3/mathml3.rng \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml3/constants.rng \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml3/mathml3-pragmatic.rng \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml3/calculus_veccalc.rng \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml3/mathml3-common.rng \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml3/mathml3-cds.rng \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml3/mathml3-deprecated.rng \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml3/sequences_series.rng \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml3/mathml3-strict.rng \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml3/mathml3-cds-pragmatic.rng \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml3/linear_algebra.rng \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml3/specfun.rng \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml3/errors.rng \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml3/sets.rng \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml3/algebra-logic.rng \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml3/relations.rng \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml3/mathml3-content.rng \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml3/basic-content-elements.rng \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml3/mathml3-presentation.rng \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml3/mathml3-strict-content.rng \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd/mathml/mmlalias.ent \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd/mathml/mmlextra.ent \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd/iso9573-13/isoamsa.ent \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd/iso9573-13/isoamsb.ent \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd/iso9573-13/isoamsc.ent \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd/iso9573-13/isotech.ent \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd/iso9573-13/isoamsr.ent \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd/iso9573-13/isomfrk.ent \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd/iso9573-13/isogrk3.ent \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd/iso9573-13/isomopf.ent \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd/iso9573-13/isoamsn.ent \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd/iso9573-13/isoamso.ent \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd/iso9573-13/isomscr.ent \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd/mathml2-qname-1.mod \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd/iso8879/isobox.ent \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd/iso8879/isonum.ent \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd/iso8879/isolat1.ent \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd/iso8879/isolat2.ent \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd/iso8879/isocyr2.ent \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd/iso8879/isocyr1.ent \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd/iso8879/isopub.ent \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd/iso8879/isodia.ent \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd/mathml2.dtd \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/rng/mathml2.rng \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/rng/mathml2-qname-1.mod.rng \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/xproc/mathml-to-ssml.impl/pres-to-ssml/pres-mathml-to-ssml.xsl \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/xproc/mathml-to-ssml.impl/pres-to-ssml/mathml-serialization.xsl \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/xproc/mathml-to-ssml.impl/pres-to-ssml/mathml-rules.xml \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/xproc/mathml-to-ssml.impl/pres-to-ssml/mathml-normalization.xsl \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/xproc/mathml-to-ssml.impl/content-to-pres/mathmlc2p.xsl \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/xproc/mathml-to-ssml.impl/mathml-to-ssml.xpl \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/xproc/mathml-to-ssml.xsl \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/xproc/library.xpl \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/xproc/mathml-to-ssml.xpl \
	modules/scripts-utils/mathml-utils/src/main/java/org/daisy/pipeline/mathml/tts/impl/FallbackMathMLProcessor.java \
	modules/scripts-utils/mathml-utils/src/main/java/org/daisy/pipeline/mathml/tts/saxon/impl/MathMLToSSMLFunctionProvider.java
modules/scripts-utils/mathml-utils/.test modules/scripts-utils/mathml-utils/.install-doc : \
	modules/scripts-utils/mathml-utils/src/test/resources/logback.xml \
	modules/scripts-utils/mathml-utils/src/test/resources/mathml3.xml \
	modules/scripts-utils/mathml-utils/src/test/resources/mathml2.xml \
	modules/scripts-utils/mathml-utils/src/test/java/XProcSpecTest.java \
	modules/scripts-utils/mathml-utils/src/test/xprocspec/validate-mathml3-with-relax-ng.xprocspec \
	modules/scripts-utils/mathml-utils/src/test/xprocspec/load-mathml2-dtd.xprocspec \
	modules/scripts-utils/mathml-utils/src/test/xprocspec/pres-math-to-ssml.xprocspec \
	modules/scripts-utils/mathml-utils/src/test/xprocspec/validate-mathml2-with-relax-ng.xprocspec
.make/mk/modules/scripts-utils/mathml-utils/sources.mk : \
	modules/scripts-utils/mathml-utils/src \
	modules/scripts-utils/mathml-utils/src/test \
	modules/scripts-utils/mathml-utils/src/test/resources \
	modules/scripts-utils/mathml-utils/src/test/java \
	modules/scripts-utils/mathml-utils/src/test/xprocspec \
	modules/scripts-utils/mathml-utils/src/main \
	modules/scripts-utils/mathml-utils/src/main/resources \
	modules/scripts-utils/mathml-utils/src/main/resources/META-INF \
	modules/scripts-utils/mathml-utils/src/main/resources/xml \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml3 \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2 \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd/mathml \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd/iso9573-13 \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/dtd/iso8879 \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/mathml2/rng \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/xproc \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/xproc/mathml-to-ssml.impl \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/xproc/mathml-to-ssml.impl/pres-to-ssml \
	modules/scripts-utils/mathml-utils/src/main/resources/xml/xproc/mathml-to-ssml.impl/content-to-pres \
	modules/scripts-utils/mathml-utils/src/main/java \
	modules/scripts-utils/mathml-utils/src/main/java/org \
	modules/scripts-utils/mathml-utils/src/main/java/org/daisy \
	modules/scripts-utils/mathml-utils/src/main/java/org/daisy/pipeline \
	modules/scripts-utils/mathml-utils/src/main/java/org/daisy/pipeline/mathml \
	modules/scripts-utils/mathml-utils/src/main/java/org/daisy/pipeline/mathml/tts \
	modules/scripts-utils/mathml-utils/src/main/java/org/daisy/pipeline/mathml/tts/impl \
	modules/scripts-utils/mathml-utils/src/main/java/org/daisy/pipeline/mathml/tts/saxon \
	modules/scripts-utils/mathml-utils/src/main/java/org/daisy/pipeline/mathml/tts/saxon/impl
