modules/dotify-utils/.test modules/dotify-utils/.install modules/dotify-utils/.install-doc $(TARGET_DIR)/state/modules/dotify-utils/modified-since-release_ : \
	modules/dotify-utils/src/main/resources/META-INF/catalog.xml \
	modules/dotify-utils/src/main/resources/META-INF/services/org.daisy.dotify.api.text.Integer2TextFactoryMakerService \
	modules/dotify-utils/src/main/resources/xml/preserve-white-space.xpl \
	modules/dotify-utils/src/main/resources/xml/preserve-white-space.xsl \
	modules/dotify-utils/src/main/resources/xml/make-table-grid.xpl \
	modules/dotify-utils/src/main/resources/xml/obfl-to-pef.script.xpl \
	modules/dotify-utils/src/main/resources/xml/make-table-grid.xsl \
	modules/dotify-utils/src/main/resources/xml/shift-string-set.xpl \
	modules/dotify-utils/src/main/resources/xml/make-pseudo-elements.xpl \
	modules/dotify-utils/src/main/resources/xml/eval-target-content.xsl \
	modules/dotify-utils/src/main/resources/xml/label-targets.xsl \
	modules/dotify-utils/src/main/resources/xml/obfl-css-definition.xpl \
	modules/dotify-utils/src/main/resources/xml/move-table-of-contents.xsl \
	modules/dotify-utils/src/main/resources/xml/make-pseudo-elements.xsl \
	modules/dotify-utils/src/main/resources/xml/eval-target-content.xpl \
	modules/dotify-utils/src/main/resources/xml/split.xpl \
	modules/dotify-utils/src/main/resources/xml/obfl-css-definition.xsl \
	modules/dotify-utils/src/main/resources/xml/label-targets.xpl \
	modules/dotify-utils/src/main/resources/xml/css-to-obfl.xpl \
	modules/dotify-utils/src/main/resources/xml/generate-obfl-layout-master.xsl \
	modules/dotify-utils/src/main/resources/xml/css-to-obfl.xsl \
	modules/dotify-utils/src/main/resources/xml/eval-counter.xpl \
	modules/dotify-utils/src/main/resources/xml/extract-obfl-pseudo-elements.xsl \
	modules/dotify-utils/src/main/resources/xml/eval-target-text.xpl \
	modules/dotify-utils/src/main/resources/xml/make-anonymous-block-boxes.xpl \
	modules/dotify-utils/src/main/resources/xml/eval-target-text.xsl \
	modules/dotify-utils/src/main/resources/xml/extract-obfl-pseudo-elements.xpl \
	modules/dotify-utils/src/main/resources/xml/make-boxes.xsl \
	modules/dotify-utils/src/main/resources/xml/obfl-normalize-space.xpl \
	modules/dotify-utils/src/main/resources/xml/make-boxes.xpl \
	modules/dotify-utils/src/main/resources/xml/propagate-page-break.xsl \
	modules/dotify-utils/src/main/resources/xml/css-to-obfl.block-boxes-with-no-line-boxes.xsl \
	modules/dotify-utils/src/main/resources/xml/padding-to-margin.xsl \
	modules/dotify-utils/src/main/resources/xml/flow-into.xsl \
	modules/dotify-utils/src/main/resources/xml/flow-from.xpl \
	modules/dotify-utils/src/main/resources/xml/make-anonymous-inline-boxes.xsl \
	modules/dotify-utils/src/main/resources/xml/marker-reference.xsl \
	modules/dotify-utils/src/main/resources/xml/make-obfl-pseudo-elements.xsl \
	modules/dotify-utils/src/main/resources/xml/shift-id.xpl \
	modules/dotify-utils/src/main/resources/xml/padding-to-margin.xpl \
	modules/dotify-utils/src/main/resources/xml/flow-into.xpl \
	modules/dotify-utils/src/main/resources/xml/propagate-page-break.xpl \
	modules/dotify-utils/src/main/resources/xml/make-anonymous-inline-boxes.xpl \
	modules/dotify-utils/src/main/resources/xml/flow-from.xsl \
	modules/dotify-utils/src/main/resources/xml/shift-obfl-marker.xpl \
	modules/dotify-utils/src/main/resources/xml/make-obfl-pseudo-elements.xpl \
	modules/dotify-utils/src/main/resources/xml/adjust-boxes.xsl \
	modules/dotify-utils/src/main/resources/xml/transform/dotify-transform.xpl \
	modules/dotify-utils/src/main/resources/xml/render-table-by.xpl \
	modules/dotify-utils/src/main/resources/xml/library.xpl \
	modules/dotify-utils/src/main/resources/xml/deep-parse-page-and-volume-stylesheets.xsl \
	modules/dotify-utils/src/main/resources/xml/render-table-by.xsl \
	modules/dotify-utils/src/main/resources/xml/obfl-to-pef.xpl \
	modules/dotify-utils/src/main/resources/xml/adjust-boxes.xpl \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/impl/OBFLExtension.java \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/impl/DotifyCSSStyledDocumentTransform.java \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/impl/DotifyTranslatorImpl.java \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/impl/DotifyCSSExtension.java \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/impl/CounterHandlingBrailleTranslator.java \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/impl/DotifyOBFLTransform.java \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/impl/OBFLProperty.java \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/impl/PreTranslatedBrailleTranslatorProvider.java \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/impl/BrailleTranslatorFactoryServiceImpl.java \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/impl/SupportedOBFLProperties.java \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/calabash/impl/OBFLToPEFStep.java \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/calabash/impl/Integer2TextFactoryMaker_SPI.java \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/calabash/impl/PEFMediaWriter.java \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/calabash/impl/TemporaryBrailleTranslatorProvider.java \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/calabash/impl/ShiftStringSetStep.java \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/calabash/impl/ShiftIdStep.java \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/calabash/impl/ShiftObflMarkerStep.java \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/calabash/impl/OBFLNormalizeSpaceStep.java \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/calabash/impl/PEFWriter.java \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/calabash/impl/OBFLWsNormalizer.java \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/calabash/impl/EvalCounterStep.java \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/saxon/impl/ObflStyle.java \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/saxon/impl/EmbossedMediumFunctions.java \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/DotifyTranslator.java \
	modules/dotify-utils/src/main/README.md
modules/dotify-utils/.test modules/dotify-utils/.install-doc : \
	modules/dotify-utils/src/test/xspec/test_volume-stylesheets-use-when.xspec \
	modules/dotify-utils/src/test/xspec/test_adjust-boxes.xspec \
	modules/dotify-utils/src/test/xspec/test_padding-to-margin.xspec \
	modules/dotify-utils/src/test/xspec/test_propagate-page-break.xspec \
	modules/dotify-utils/src/test/xspec/test_resolve-css-string.xspec \
	modules/dotify-utils/src/test/xspec/test_preserve-white-space.xspec \
	modules/dotify-utils/src/test/xspec/test_generate-obfl-layout-master.xspec \
	modules/dotify-utils/src/test/xspec/test_make-table-grid.xspec \
	modules/dotify-utils/src/test/xspec/test_make-boxes.xspec \
	modules/dotify-utils/src/test/xspec/test_make-anonymous-inline-boxes.xspec \
	modules/dotify-utils/src/test/xspec/test_make-pseudo-elements.xspec \
	modules/dotify-utils/src/test/xspec/test_round-line-height.xspec \
	modules/dotify-utils/src/test/resources/logback.xml \
	modules/dotify-utils/src/test/resources/capsphrase.utb \
	modules/dotify-utils/src/test/resources/file-to-obfl.xpl \
	modules/dotify-utils/src/test/resources/non-standard-hyph.dic \
	modules/dotify-utils/src/test/resources/foo.dic \
	modules/dotify-utils/src/test/resources/test_file-to-obfl/test_01.xml \
	modules/dotify-utils/src/test/resources/test_file-to-obfl/test_02.xml \
	modules/dotify-utils/src/test/resources/write-out-numbers.utb \
	modules/dotify-utils/src/test/resources/braille-charset.dis \
	modules/dotify-utils/src/test/java/ignore \
	modules/dotify-utils/src/test/java/XSpecAndXProcSpecTest.java \
	modules/dotify-utils/src/test/java/NumberBrailleTranslator.java \
	modules/dotify-utils/src/test/java/DotifyCoreTest.java \
	modules/dotify-utils/src/test/xprocspec/test_eval-target-content.xprocspec \
	modules/dotify-utils/src/test/xprocspec/test_flow-from.xprocspec \
	modules/dotify-utils/src/test/xprocspec/test_label-targets.xprocspec \
	modules/dotify-utils/src/test/xprocspec/test_split.xprocspec \
	modules/dotify-utils/src/test/xprocspec/test_new-definition.xprocspec \
	modules/dotify-utils/src/test/xprocspec/test_flow-into.xprocspec \
	modules/dotify-utils/src/test/xprocspec/test_shift-id.xprocspec \
	modules/dotify-utils/src/test/xprocspec/test_make-anonymous-block-boxes.xprocspec \
	modules/dotify-utils/src/test/xprocspec/test_shift-string-set.xprocspec \
	modules/dotify-utils/src/test/xprocspec/test_shift-obfl-marker.xprocspec \
	modules/dotify-utils/src/test/xprocspec/test_obfl-normalize-space.xprocspec \
	modules/dotify-utils/src/test/xprocspec/test_propagate-page-break.xprocspec \
	modules/dotify-utils/src/test/xprocspec/test_format.xprocspec \
	modules/dotify-utils/src/test/xprocspec/test_obfl-to-pef_sv-SE.xprocspec \
	modules/dotify-utils/src/test/xprocspec/test_obfl-to-pef.xprocspec \
	modules/dotify-utils/src/test/xprocspec/test_eval-counter.xprocspec
modules/dotify-utils/.install-doc : \
	modules/dotify-utils/doc/index.md \
	modules/dotify-utils/doc/obfl-to-pef.md
.make/mk/modules/dotify-utils/sources.mk : \
	modules/dotify-utils/src \
	modules/dotify-utils/src/test \
	modules/dotify-utils/src/test/xspec \
	modules/dotify-utils/src/test/resources \
	modules/dotify-utils/src/test/resources/test_file-to-obfl \
	modules/dotify-utils/src/test/java \
	modules/dotify-utils/src/test/xprocspec \
	modules/dotify-utils/src/main \
	modules/dotify-utils/src/main/resources \
	modules/dotify-utils/src/main/resources/META-INF \
	modules/dotify-utils/src/main/resources/META-INF/services \
	modules/dotify-utils/src/main/resources/xml \
	modules/dotify-utils/src/main/resources/xml/transform \
	modules/dotify-utils/src/main/java \
	modules/dotify-utils/src/main/java/org \
	modules/dotify-utils/src/main/java/org/daisy \
	modules/dotify-utils/src/main/java/org/daisy/pipeline \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/impl \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/calabash \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/calabash/impl \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/saxon \
	modules/dotify-utils/src/main/java/org/daisy/pipeline/braille/dotify/saxon/impl \
	modules/dotify-utils/doc
