# -*- mode: ruby -*-

VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.6.3"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.define "boot2docker"
  
  config.vm.box = "yungsang/boot2docker"
  config.vm.box_url = "https://vagrantcloud.com/yungsang/boxes/boot2docker/versions/26/providers/virtualbox.box"
  
  config.vm.synced_folder "../", "/home/docker/pipeline-it"
  
  config.vm.network :private_network, ip: "192.168.10.12"
  config.vm.network :forwarded_port, guest: 8081, host: 8081
  config.vm.network :forwarded_port, guest: 80, host: 8080
  
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
  
end
