modules/file-utils/.test modules/file-utils/.install modules/file-utils/.install-doc $(TARGET_DIR)/state/modules/file-utils/modified-since-release_ : \
	modules/file-utils/src/main/resources/config-calabash.xml \
	modules/file-utils/src/main/resources/META-INF/catalog.xml \
	modules/file-utils/src/main/resources/xml/xproc/data.xpl \
	modules/file-utils/src/main/resources/xml/xproc/normalize-document-base.xpl \
	modules/file-utils/src/main/resources/xml/xproc/recursive-directory-list.xpl \
	modules/file-utils/src/main/resources/xml/xproc/java-library.xpl \
	modules/file-utils/src/main/resources/xml/xproc/set-xml-declaration.xpl \
	modules/file-utils/src/main/resources/xml/xproc/peek.xpl \
	modules/file-utils/src/main/resources/xml/xproc/tempdir.xpl \
	modules/file-utils/src/main/resources/xml/xproc/load.xpl \
	modules/file-utils/src/main/resources/xml/xproc/normalize-uri.xpl \
	modules/file-utils/src/main/resources/xml/xproc/read-xml-declaration.xpl \
	modules/file-utils/src/main/resources/xml/xproc/set-base-uri.xpl \
	modules/file-utils/src/main/resources/xml/xproc/add-xml-base.xpl \
	modules/file-utils/src/main/resources/xml/xproc/set-doctype.xpl \
	modules/file-utils/src/main/resources/xml/xproc/copy-resource.xpl \
	modules/file-utils/src/main/resources/xml/xproc/xml-peek.xpl \
	modules/file-utils/src/main/resources/xml/xproc/library.xpl \
	modules/file-utils/src/main/resources/xml/xproc/read-doctype.xpl \
	modules/file-utils/src/main/resources/xml/xproc/xprocspec-assert-xml-declaration.xpl \
	modules/file-utils/src/main/resources/xml/xslt/base64-to-hex.xsl \
	modules/file-utils/src/main/resources/xml/xslt/sort-directory-list.xsl \
	modules/file-utils/src/main/resources/xml/xslt/uri-functions.xsl \
	modules/file-utils/src/main/resources/xml/xslt/xml-peek.parse.xsl \
	modules/file-utils/src/main/resources/xml/xslt/library.xsl \
	modules/file-utils/src/main/java/org/daisy/pipeline/file/FileUtils.java \
	modules/file-utils/src/main/java/org/daisy/pipeline/file/calabash/impl/SetDoctypeProvider.java \
	modules/file-utils/src/main/java/org/daisy/pipeline/file/calabash/impl/XMLPeekProvider.java \
	modules/file-utils/src/main/java/org/daisy/pipeline/file/calabash/impl/NormalizeURIProvider.java \
	modules/file-utils/src/main/java/org/daisy/pipeline/file/calabash/impl/SetXmlDeclarationProvider.java \
	modules/file-utils/src/main/java/org/daisy/pipeline/file/calabash/impl/PeekProvider.java \
	modules/file-utils/src/main/java/org/daisy/pipeline/file/calabash/impl/LoadProvider.java \
	modules/file-utils/src/main/java/org/daisy/pipeline/file/calabash/impl/CopyResourceProvider.java \
	modules/file-utils/src/main/java/org/daisy/pipeline/file/saxon/impl/FileExists.java \
	modules/file-utils/src/main/java/org/daisy/pipeline/file/saxon/impl/Expand83.java \
	modules/file-utils/src/main/java/org/daisy/pipeline/file/saxon/impl/NormalizeURI.java
modules/file-utils/.test modules/file-utils/.install-doc : \
	modules/file-utils/src/test/xspec/xml-peek.parse.xspec \
	modules/file-utils/src/test/xspec/sort-directory-list.xspec \
	modules/file-utils/src/test/xspec/base64-to-hex.xspec \
	modules/file-utils/src/test/xspec/samples/xml-peek.parse.out.xml \
	modules/file-utils/src/test/xspec/samples/lots-of-prolog.xml \
	modules/file-utils/src/test/xspec/samples/lots-of-prolog.escaped.xml \
	modules/file-utils/src/test/xspec/samples/xml-peek.strip-content.in.xml \
	modules/file-utils/src/test/xspec/samples/xml-peek.strip-content.out.xml \
	modules/file-utils/src/test/xspec/samples/xml-peek.parse.in.xml \
	modules/file-utils/src/test/xspec/uri-functions.xspec \
	modules/file-utils/src/test/resources/logback.xml \
	modules/file-utils/src/test/resources/plaintext.txt \
	modules/file-utils/src/test/java/XProcSpecTest.java \
	modules/file-utils/src/test/java/org/daisy/pipeline/file/FileUtilsTest.java \
	modules/file-utils/src/test/java/org/daisy/pipeline/file/calabash/impl/CopyResourceProviderTest.java \
	modules/file-utils/src/test/java/org/daisy/pipeline/file/calabash/impl/XMLPeekProviderTest.java \
	modules/file-utils/src/test/java/org/daisy/pipeline/file/calabash/impl/Mocks.java \
	modules/file-utils/src/test/java/org/daisy/pipeline/file/calabash/impl/SetXmlDeclarationProviderTest.java \
	modules/file-utils/src/test/java/org/daisy/pipeline/file/calabash/impl/SetDoctypeProviderTest.java \
	modules/file-utils/src/test/java/org/daisy/pipeline/file/calabash/impl/PeekProviderTest.java \
	modules/file-utils/src/test/java/org/daisy/pipeline/file/MockFile.java \
	modules/file-utils/src/test/xprocspec/foo-2.xml \
	modules/file-utils/src/test/xprocspec/set-doctype.xprocspec \
	modules/file-utils/src/test/xprocspec/set-base-uri.xprocspec \
	modules/file-utils/src/test/xprocspec/normalize-document-base.xprocspec \
	modules/file-utils/src/test/xprocspec/normalize-uri.xprocspec \
	modules/file-utils/src/test/xprocspec/uri-functions.xprocspec \
	modules/file-utils/src/test/xprocspec/read-doctype.xprocspec \
	modules/file-utils/src/test/xprocspec/samples/set-doctype.with-doctype.xml \
	modules/file-utils/src/test/xprocspec/samples/read-doctype.xml \
	modules/file-utils/src/test/xprocspec/samples/set-doctype.add-extension.xml \
	modules/file-utils/src/test/xprocspec/samples/set-doctype.without-xml-declaration.xml \
	modules/file-utils/src/test/xprocspec/samples/set-doctype.without-doctype.xml \
	modules/file-utils/src/test/xprocspec/copy-resource.xprocspec \
	modules/file-utils/src/test/xprocspec/add-xml-base.xprocspec \
	modules/file-utils/src/test/xprocspec/set-xml-declaration.xprocspec \
	modules/file-utils/src/test/xprocspec/file-peek.xprocspec \
	modules/file-utils/src/test/xprocspec/file-xml-peek.xprocspec \
	modules/file-utils/src/test/xprocspec/set-base-uri.2.xprocspec \
	modules/file-utils/src/test/xprocspec/data.xprocspec
.make/mk/modules/file-utils/sources.mk : \
	modules/file-utils/src \
	modules/file-utils/src/test \
	modules/file-utils/src/test/xspec \
	modules/file-utils/src/test/xspec/samples \
	modules/file-utils/src/test/resources \
	modules/file-utils/src/test/java \
	modules/file-utils/src/test/java/org \
	modules/file-utils/src/test/java/org/daisy \
	modules/file-utils/src/test/java/org/daisy/pipeline \
	modules/file-utils/src/test/java/org/daisy/pipeline/file \
	modules/file-utils/src/test/java/org/daisy/pipeline/file/calabash \
	modules/file-utils/src/test/java/org/daisy/pipeline/file/calabash/impl \
	modules/file-utils/src/test/xprocspec \
	modules/file-utils/src/test/xprocspec/samples \
	modules/file-utils/src/main \
	modules/file-utils/src/main/resources \
	modules/file-utils/src/main/resources/META-INF \
	modules/file-utils/src/main/resources/xml \
	modules/file-utils/src/main/resources/xml/xproc \
	modules/file-utils/src/main/resources/xml/xslt \
	modules/file-utils/src/main/java \
	modules/file-utils/src/main/java/org \
	modules/file-utils/src/main/java/org/daisy \
	modules/file-utils/src/main/java/org/daisy/pipeline \
	modules/file-utils/src/main/java/org/daisy/pipeline/file \
	modules/file-utils/src/main/java/org/daisy/pipeline/file/calabash \
	modules/file-utils/src/main/java/org/daisy/pipeline/file/calabash/impl \
	modules/file-utils/src/main/java/org/daisy/pipeline/file/saxon \
	modules/file-utils/src/main/java/org/daisy/pipeline/file/saxon/impl
