modules/fileset-utils/.test modules/fileset-utils/.install modules/fileset-utils/.install-doc $(TARGET_DIR)/state/modules/fileset-utils/modified-since-release_ : \
	modules/fileset-utils/src/main/resources/META-INF/catalog.xml \
	modules/fileset-utils/src/main/resources/xml/xproc/fileset-rebase.xpl \
	modules/fileset-utils/src/main/resources/xml/xproc/fileset-intersect.xpl \
	modules/fileset-utils/src/main/resources/xml/xproc/fileset-purge.xpl \
	modules/fileset-utils/src/main/resources/xml/xproc/fileset-create.xpl \
	modules/fileset-utils/src/main/resources/xml/xproc/fileset-filter-in-memory.xpl \
	modules/fileset-utils/src/main/resources/xml/xproc/fileset-add-entries.xpl \
	modules/fileset-utils/src/main/resources/xml/xproc/fileset-compose.xpl \
	modules/fileset-utils/src/main/resources/xml/xproc/fileset-update.xpl \
	modules/fileset-utils/src/main/resources/xml/xproc/fileset-library.xpl \
	modules/fileset-utils/src/main/resources/xml/xproc/fileset-from-dir-list.xpl \
	modules/fileset-utils/src/main/resources/xml/xproc/fileset-copy.xpl \
	modules/fileset-utils/src/main/resources/xml/xproc/fileset-from-dir.xpl \
	modules/fileset-utils/src/main/resources/xml/xproc/fileset-unzip.xpl \
	modules/fileset-utils/src/main/resources/xml/xproc/xprocspec-fileset-compare.xpl \
	modules/fileset-utils/src/main/resources/xml/xproc/fileset-join.xpl \
	modules/fileset-utils/src/main/resources/xml/xproc/fileset-load.xpl \
	modules/fileset-utils/src/main/resources/xml/xproc/fileset-add-entry.xpl \
	modules/fileset-utils/src/main/resources/xml/xproc/fileset-apply.xpl \
	modules/fileset-utils/src/main/resources/xml/xproc/fileset-invert.xpl \
	modules/fileset-utils/src/main/resources/xml/xproc/fileset-fix-original-hrefs.xpl \
	modules/fileset-utils/src/main/resources/xml/xproc/fileset-diff.xpl \
	modules/fileset-utils/src/main/resources/xml/xproc/fileset-store.xpl \
	modules/fileset-utils/src/main/resources/xml/xproc/fileset-add-ref.xpl \
	modules/fileset-utils/src/main/resources/xml/xproc/fileset-move.xpl \
	modules/fileset-utils/src/main/resources/xml/xproc/fileset-delete.xpl \
	modules/fileset-utils/src/main/resources/xml/xproc/fileset-compare.xpl \
	modules/fileset-utils/src/main/resources/xml/xproc/fileset-filter.xpl \
	modules/fileset-utils/src/main/resources/xml/schemas/fileset.rnc \
	modules/fileset-utils/src/main/resources/xml/xslt/fileset-rebase.xsl \
	modules/fileset-utils/src/main/resources/xml/xslt/fileset-intersect.xsl \
	modules/fileset-utils/src/main/resources/xml/xslt/fileset-compose.xsl \
	modules/fileset-utils/src/main/resources/xml/xslt/fileset-update.xsl \
	modules/fileset-utils/src/main/resources/xml/xslt/fileset-from-dir-list.xsl \
	modules/fileset-utils/src/main/resources/xml/xslt/fileset-join.xsl \
	modules/fileset-utils/src/main/resources/xml/xslt/fileset-to-zip-manifests.xsl \
	modules/fileset-utils/src/main/resources/xml/xslt/fileset-invert.xsl \
	modules/fileset-utils/src/main/resources/xml/xslt/fileset-fix-original-hrefs.xsl \
	modules/fileset-utils/src/main/resources/xml/xslt/fileset-flatten.xsl \
	modules/fileset-utils/src/main/java/org/daisy/pipeline/fileset/Fileset.java \
	modules/fileset-utils/src/main/java/org/daisy/pipeline/fileset/calabash/impl/AddEntriesStep.java
modules/fileset-utils/.test modules/fileset-utils/.install-doc : \
	modules/fileset-utils/src/test/xspec/catalog.xml \
	modules/fileset-utils/src/test/xspec/fileset-from-dir-list.xspec \
	modules/fileset-utils/src/test/xspec/fileset-join.xspec \
	modules/fileset-utils/src/test/mock/xproc/zip-utils.xpl \
	modules/fileset-utils/src/test/mock/xproc/common-utils.xpl \
	modules/fileset-utils/src/test/mock/xproc/file-utils.xpl \
	modules/fileset-utils/src/test/mock/xslt/uri-functions.xsl \
	modules/fileset-utils/src/test/resources/logback.xml \
	modules/fileset-utils/src/test/resources/META-INF/catalog.xml \
	modules/fileset-utils/src/test/resources/dtd/svg11-flat.dtd \
	modules/fileset-utils/src/test/resources/dtd/svg11-basic-flat.dtd \
	modules/fileset-utils/src/test/resources/dtd/svg-pattern.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-structure.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-basic-text.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-hyperlink.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-core-attrib.mod \
	modules/fileset-utils/src/test/resources/dtd/svg11.dtd \
	modules/fileset-utils/src/test/resources/dtd/svg-basic-graphics-attrib.mod \
	modules/fileset-utils/src/test/resources/dtd/svg11-tiny.dtd \
	modules/fileset-utils/src/test/resources/dtd/svg11-tiny-model.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-datatypes.mod \
	modules/fileset-utils/src/test/resources/dtd/svg11-model.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-basic-paint-attrib.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-image.mod \
	modules/fileset-utils/src/test/resources/dtd/svg11-tiny-attribs.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-viewport-attrib.mod \
	modules/fileset-utils/src/test/resources/dtd/svg11-attribs.mod \
	modules/fileset-utils/src/test/resources/dtd/svg11-basic-attribs.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-opacity-attrib.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-graphevents-attrib.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-clip.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-style.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-cursor.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-basic-structure.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-container-attrib.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-basic-font.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-conditional.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-framework.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-qname.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-xlink-attrib.mod \
	modules/fileset-utils/src/test/resources/dtd/svg11-flat-20110816.dtd \
	modules/fileset-utils/src/test/resources/dtd/svg11-tiny-flat.dtd \
	modules/fileset-utils/src/test/resources/dtd/svg-animevents-attrib.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-graphics-attrib.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-basic-clip.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-docevents-attrib.mod \
	modules/fileset-utils/src/test/resources/dtd/svg11-flat-20030114.dtd \
	modules/fileset-utils/src/test/resources/dtd/svg-basic-filter.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-view.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-paint-attrib.mod \
	modules/fileset-utils/src/test/resources/dtd/svg11-basic-model.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-marker.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-extensibility.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-font.mod \
	modules/fileset-utils/src/test/resources/dtd/templates/svg-template.mod \
	modules/fileset-utils/src/test/resources/dtd/templates/svg11-template.dtd \
	modules/fileset-utils/src/test/resources/dtd/templates/svg-template-qname.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-text.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-shape.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-script.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-profile.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-extresources-attrib.mod \
	modules/fileset-utils/src/test/resources/dtd/svg11-basic.dtd \
	modules/fileset-utils/src/test/resources/dtd/svg-gradient.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-mask.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-animation.mod \
	modules/fileset-utils/src/test/resources/dtd/svg-filter.mod \
	modules/fileset-utils/src/test/java/XProcSpecTest.java \
	modules/fileset-utils/src/test/xprocspec/fileset-load.base-uri.xprocspec \
	modules/fileset-utils/src/test/xprocspec/fileset-rebase.xprocspec \
	modules/fileset-utils/src/test/xprocspec/fileset-create.xprocspec \
	modules/fileset-utils/src/test/xprocspec/fileset-filter.xprocspec \
	modules/fileset-utils/src/test/xprocspec/fileset-update.xprocspec \
	modules/fileset-utils/src/test/xprocspec/fileset-from-dir.xprocspec \
	modules/fileset-utils/src/test/xprocspec/fileset-add-ref.xprocspec \
	modules/fileset-utils/src/test/xprocspec/fileset-move.xprocspec \
	modules/fileset-utils/src/test/xprocspec/samples/test.epub \
	modules/fileset-utils/src/test/xprocspec/samples/fileset/test.xml \
	modules/fileset-utils/src/test/xprocspec/samples/fileset/dir/file.txt \
	modules/fileset-utils/src/test/xprocspec/samples/fileset/test.txt \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/porrasturvat-1.0.3.tar.gz \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/plaintext \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/magic.mime \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/a.zip \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/mime-types.properties \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/wrong-extensions/txt.xml \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/wrong-extensions/opf.txt \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/wrong-extensions/png.xml \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/wrong-extensions/html.bin \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/f.tar.gz \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/c.gif \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/b-jpg.img \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/afpfile.afp \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/META-INF/MANIFEST.MF \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/a/MimeDetector.class \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/a/MimeDetector.java \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/a/f.tar.gz \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/a/resources/mime.cache \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/a/resources/eu/medsea/mimeutil/magic.mime \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/a/resources/eu/medsea/mimeutil/mime-types.properties \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/a/e.svg \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/a/e[xml] \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/a/c-gif.img \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/a/a.html \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/xml/ncx.xml \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/xml/container.xml \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/xml/package.xml \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/xml/XSLT.xml \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/xml/mqia0001.xml \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/xml/XProc.xml \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/xml/noFileExtension \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/xml/navigation.xml \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/epub.epub \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/e.svg \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/textfiles/western \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/textfiles/unicode \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/e[xml] \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/e-svg.img \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/test.bin \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/b.jpg \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/eu/medsea/mimeutil/MimeTypeTest.java \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/eu/medsea/mimeutil/util/EncodingGuesserTest.java \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/eu/medsea/mimeutil/MimeUtil2Test.java \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/eu/medsea/mimeutil/MimeUtilTest.java \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/eu/medsea/mimeutil/MimeTypeHashSetTest.java \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/eu/medsea/mimeutil/detector/MagicMimeMimeDetectorTest.java \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/eu/medsea/mimeutil/detector/OpendesktopMimeDetectorTest.java \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/eu/medsea/mimeutil/detector/TextMimeDetectorTest.java \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/eu/medsea/mimeutil/detector/WindowsRegistryMimeDetectorTest.java \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/d.png \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/plaintext.txt \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/d-png.img \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/c-gif.img \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/e.xml \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/epub/Publication/ncx.xml \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/epub/Publication/Content/mqia0001.xhtml \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/epub/Publication/Content/tjcs0000.jpg \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/epub/Publication/Content/mqia0001.smil \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/epub/Publication/Content/1_Jamen__Benny.mp3 \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/epub/Publication/Content/41077stor.jpg \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/epub/Publication/navigation.xhtml \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/epub/Publication/package.opf \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/epub/META-INF/container.xml \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/epub/mimetype \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/log4j.properties \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/a.html \
	modules/fileset-utils/src/test/xprocspec/samples/out/test.xml \
	modules/fileset-utils/src/test/xprocspec/samples/out/dir/file.txt \
	modules/fileset-utils/src/test/xprocspec/samples/out/test.txt \
	modules/fileset-utils/src/test/xprocspec/samples/fileset-filter.fileset.xml \
	modules/fileset-utils/src/test/xprocspec/samples/sample-tests.zip \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2.xml \
	modules/fileset-utils/src/test/xprocspec/fileset-fix-original-hrefs.xprocspec \
	modules/fileset-utils/src/test/xprocspec/fileset-unzip.xprocspec \
	modules/fileset-utils/src/test/xprocspec/fileset-load.xprocspec \
	modules/fileset-utils/src/test/xprocspec/fileset-compose.xprocspec \
	modules/fileset-utils/src/test/xprocspec/fileset-copy.xprocspec \
	modules/fileset-utils/src/test/xprocspec/fileset-to-zip-manifests.xprocspec \
	modules/fileset-utils/src/test/xprocspec/fileset-invert.xprocspec \
	modules/fileset-utils/src/test/xprocspec/fileset-diff.xprocspec \
	modules/fileset-utils/src/test/xprocspec/fileset-add-entries.xprocspec \
	modules/fileset-utils/src/test/xprocspec/fileset-compare.xprocspec \
	modules/fileset-utils/src/test/xprocspec/fileset-join.xprocspec \
	modules/fileset-utils/src/test/xprocspec/fileset-store.xprocspec \
	modules/fileset-utils/src/test/xprocspec/fileset-intersect.xprocspec \
	modules/fileset-utils/src/test/xprocspec/fileset-from-dir-list.xprocspec
modules/fileset-utils/.install-doc : \
	modules/fileset-utils/doc/fileset.rnc.html
.make/mk/modules/fileset-utils/sources.mk : \
	modules/fileset-utils/src \
	modules/fileset-utils/src/test \
	modules/fileset-utils/src/test/xspec \
	modules/fileset-utils/src/test/mock \
	modules/fileset-utils/src/test/mock/xproc \
	modules/fileset-utils/src/test/mock/xslt \
	modules/fileset-utils/src/test/resources \
	modules/fileset-utils/src/test/resources/META-INF \
	modules/fileset-utils/src/test/resources/dtd \
	modules/fileset-utils/src/test/resources/dtd/templates \
	modules/fileset-utils/src/test/java \
	modules/fileset-utils/src/test/xprocspec \
	modules/fileset-utils/src/test/xprocspec/samples \
	modules/fileset-utils/src/test/xprocspec/samples/fileset \
	modules/fileset-utils/src/test/xprocspec/samples/fileset/dir \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2 \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/wrong-extensions \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/META-INF \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/a \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/a/resources \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/a/resources/eu \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/a/resources/eu/medsea \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/a/resources/eu/medsea/mimeutil \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/xml \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/textfiles \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/eu \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/eu/medsea \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/eu/medsea/mimeutil \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/eu/medsea/mimeutil/util \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/eu/medsea/mimeutil/detector \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/epub \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/epub/Publication \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/epub/Publication/Content \
	modules/fileset-utils/src/test/xprocspec/samples/fileset2/epub/META-INF \
	modules/fileset-utils/src/test/xprocspec/samples/out \
	modules/fileset-utils/src/test/xprocspec/samples/out/dir \
	modules/fileset-utils/src/main \
	modules/fileset-utils/src/main/resources \
	modules/fileset-utils/src/main/resources/META-INF \
	modules/fileset-utils/src/main/resources/xml \
	modules/fileset-utils/src/main/resources/xml/xproc \
	modules/fileset-utils/src/main/resources/xml/schemas \
	modules/fileset-utils/src/main/resources/xml/xslt \
	modules/fileset-utils/src/main/java \
	modules/fileset-utils/src/main/java/org \
	modules/fileset-utils/src/main/java/org/daisy \
	modules/fileset-utils/src/main/java/org/daisy/pipeline \
	modules/fileset-utils/src/main/java/org/daisy/pipeline/fileset \
	modules/fileset-utils/src/main/java/org/daisy/pipeline/fileset/calabash \
	modules/fileset-utils/src/main/java/org/daisy/pipeline/fileset/calabash/impl \
	modules/fileset-utils/doc
