utils/build-utils/modules-build-helper/.test utils/build-utils/modules-build-helper/.install utils/build-utils/modules-build-helper/.install-doc $(TARGET_DIR)/state/utils/build-utils/modules-build-helper/modified-since-release_ : \
	utils/build-utils/modules-build-helper/src/main/resources/process-catalog/process-catalog.xsl \
	utils/build-utils/modules-build-helper/src/main/resources/process-catalog/process-catalog.xpl \
	utils/build-utils/modules-build-helper/src/main/resources/xprocdoc/process-sources.xpl \
	utils/build-utils/modules-build-helper/src/main/resources/xprocdoc/summary-to-xhtml.xpl \
	utils/build-utils/modules-build-helper/src/main/resources/xprocdoc/xd2html.xsl \
	utils/build-utils/modules-build-helper/src/main/resources/xprocdoc/README.md \
	utils/build-utils/modules-build-helper/src/main/resources/xprocdoc/xprocdoc.xpl \
	utils/build-utils/modules-build-helper/src/main/resources/xprocdoc/.gitrepo \
	utils/build-utils/modules-build-helper/src/main/resources/xprocdoc/catalog-to-xprocdoc.xpl \
	utils/build-utils/modules-build-helper/src/main/resources/lib/extend-script.xsl \
	utils/build-utils/modules-build-helper/src/main/resources/lib/uri-functions.xsl \
	utils/build-utils/modules-build-helper/src/main/resources/htmlize-sources/htmlize-params-file.xsl \
	utils/build-utils/modules-build-helper/src/main/resources/htmlize-sources/htmlize-catalog.xsl \
	utils/build-utils/modules-build-helper/src/main/resources/htmlize-sources/htmlize-catalog.xpl \
	utils/build-utils/modules-build-helper/src/main/resources/htmlize-sources/htmlize-xslt.xpl \
	utils/build-utils/modules-build-helper/src/main/resources/htmlize-sources/htmlize-xproc-script.xsl \
	utils/build-utils/modules-build-helper/src/main/resources/htmlize-sources/htmlize-xslt.xsl \
	utils/build-utils/modules-build-helper/src/main/resources/htmlize-sources/serialize.xsl \
	utils/build-utils/modules-build-helper/src/main/resources/htmlize-sources/htmlize-xproc.xpl \
	utils/build-utils/modules-build-helper/src/main/resources/htmlize-sources/htmlize-xproc.xsl \
	utils/build-utils/modules-build-helper/src/main/resources/htmlize-sources/htmlize-xml.xsl \
	utils/build-utils/modules-build-helper/src/main/resources/htmlize-sources/htmlize-xml.xpl \
	utils/build-utils/modules-build-helper/src/main/java/org/daisy/pipeline/maven/plugin/ProcessTestCatalogMojo.java \
	utils/build-utils/modules-build-helper/src/main/java/org/daisy/pipeline/maven/plugin/ProcessCatalogMojo.java \
	utils/build-utils/modules-build-helper/src/main/java/org/daisy/pipeline/maven/plugin/DependenciesPackageListMojo.java \
	utils/build-utils/modules-build-helper/src/main/java/org/daisy/pipeline/maven/plugin/utils.java \
	utils/build-utils/modules-build-helper/src/main/java/org/daisy/pipeline/maven/plugin/XProcDocMojo.java \
	utils/build-utils/modules-build-helper/src/main/java/org/daisy/pipeline/maven/plugin/GenerateModuleClassFunctionProvider.java \
	utils/build-utils/modules-build-helper/src/main/java/org/daisy/pipeline/maven/plugin/CalabashWithPipelineModules.java \
	utils/build-utils/modules-build-helper/src/main/java/org/daisy/pipeline/maven/plugin/HtmlizeSourcesMojo.java
utils/build-utils/modules-build-helper/.test utils/build-utils/modules-build-helper/.install-doc : \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/pom.xml \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/index.md \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/test/xspec/test_foo.xspec \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/test/resources/logback.xml \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/test/java/ServicesTest.java \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/test/xprocspec/test_foo.xprocspec \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/it/xprocspec/test.xprocspec \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/resources/css/foo-2.css \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/resources/css/foo-1.css \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/resources/css/foo.xpl \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/resources/css/bar-2.xpl \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/resources/css/foo.css \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/resources/css/foo-1.xpl \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/resources/css/foo-2.xpl \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/resources/css/bar-2.md \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/resources/data-types/type.xml \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/resources/META-INF/catalog.xml \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/resources/xml/a.xml.xsl \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/resources/xml/script-options.xpl \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/resources/xml/script.xpl \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/resources/xml/foo.xpl \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/resources/xml/script-base.xpl \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/resources/xml/foo.xsl \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/resources/xml/a.xml \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/resources/xml/library.xpl \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/resources/xml/library.xsl \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/resources/liblouis/foo.utb \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/java/impl/JavaFunction.java \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/java/impl/JavaStep.java \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/java/org/daisy/impl/FooImpl.java \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/java/org/daisy/Foo.java \
	utils/build-utils/modules-build-helper/src/it/settings.xml
.make/mk/utils/build-utils/modules-build-helper/sources.mk : \
	utils/build-utils/modules-build-helper/src \
	utils/build-utils/modules-build-helper/src/it \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/test \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/test/xspec \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/test/resources \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/test/java \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/test/xprocspec \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/it \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/it/xprocspec \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/resources \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/resources/css \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/resources/data-types \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/resources/META-INF \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/resources/xml \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/resources/liblouis \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/java \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/java/impl \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/java/org \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/java/org/daisy \
	utils/build-utils/modules-build-helper/src/it/it-pipeline-module/src/main/java/org/daisy/impl \
	utils/build-utils/modules-build-helper/src/main \
	utils/build-utils/modules-build-helper/src/main/resources \
	utils/build-utils/modules-build-helper/src/main/resources/process-catalog \
	utils/build-utils/modules-build-helper/src/main/resources/xprocdoc \
	utils/build-utils/modules-build-helper/src/main/resources/lib \
	utils/build-utils/modules-build-helper/src/main/resources/htmlize-sources \
	utils/build-utils/modules-build-helper/src/main/java \
	utils/build-utils/modules-build-helper/src/main/java/org \
	utils/build-utils/modules-build-helper/src/main/java/org/daisy \
	utils/build-utils/modules-build-helper/src/main/java/org/daisy/pipeline \
	utils/build-utils/modules-build-helper/src/main/java/org/daisy/pipeline/maven \
	utils/build-utils/modules-build-helper/src/main/java/org/daisy/pipeline/maven/plugin
