package org.daisy.pipeline.tts.acapela;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : nscube_forjna.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class NSC_EVENT_DATA_WordSynch extends Structure {
	public int uiSize;
	/** C type : void* */
	public Pointer pUserData;
	/** position in bytes of first char in text */
	public int uiWordPos;
	/** position in bytes in whole audio signal */
	public int uiByteCount;
	public NSC_EVENT_DATA_WordSynch() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("uiSize", "pUserData", "uiWordPos", "uiByteCount");
	}
	/**
	 * @param pUserData C type : void*<br>
	 * @param uiWordPos position in bytes of first char in text<br>
	 * @param uiByteCount position in bytes in whole audio signal
	 */
	public NSC_EVENT_DATA_WordSynch(int uiSize, Pointer pUserData, int uiWordPos, int uiByteCount) {
		super();
		this.uiSize = uiSize;
		this.pUserData = pUserData;
		this.uiWordPos = uiWordPos;
		this.uiByteCount = uiByteCount;
	}
	public NSC_EVENT_DATA_WordSynch(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends NSC_EVENT_DATA_WordSynch implements Structure.ByReference {
		
	};
	public static class ByValue extends NSC_EVENT_DATA_WordSynch implements Structure.ByValue {
		
	};
}
