name: docker

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install xmllint
        run: sudo apt-get update -qq && sudo apt-get install -y libxml2-utils
      - name: Install Java and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Cache .maven-workspace
        uses: actions/cache@v3
        with:
          path: .maven-workspace
          key: ${{ runner.os }}-maven-workspace-${{ hashFiles('**/pom.xml', '**/*.gradle', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-maven-workspace-
      - name: Cache .maven-cache
        uses: actions/cache@v3
        with:
          path: .maven-cache
          key: ${{ runner.os }}-maven-cache
      - name: Cache JRE
        uses: actions/cache@v3
        with:
          path: assembly/src/main/jre
          key: ${{ runner.os }}-jre-${{ hashFiles('assembly/src/main/jre/*') }}
      - name: Build Docker image
        run: make dist-docker-image
      - name: Cache newly downloaded non-snapshot Maven artifacts
        if: always()
        run: make cache
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image to Docker Hub
        run: |
          docker push daisyorg/pipeline:latest-snapshot
