name: Build and publish

on:
  workflow_dispatch:
  push:
    branches: [ website ]

jobs:
  publish:
    name: Publish website on daisy.github.io/pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache gems
        uses: actions/cache@v3
        with:
          path: gems
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      - name: Install dependencies
        run: bundle install --path gems
      - name: Build
        run: make
      - name: Publish
        if: ${{ github.event_name == 'push' && github.repository =='daisy/pipeline' && github.ref == 'refs/heads/website'}}
        env:
          GH_REMOTE: "https://${{ secrets.PUBLISH_WEBSITE_GITHUB_TOKEN }}@github.com/daisy/pipeline.git"
          GH_USER_NAME: "Github CI"
          GH_USER_EMAIL: "daisy@users.noreply.github.com"
        run: |
          make publish
          # make publish-wiki
